Repository RevenueCat/purchases-ios, pull requests merged in 2021-12, with the labels that each got.

#962 Add sk2 purchase tester
  IntegrationTests/CommonFiles/IntegrationTests.swift
  IntegrationTests/PurchaseTester/PurchaseTester/Base.lproj/Main.storyboard
  IntegrationTests/PurchaseTester/PurchaseTester/CatsViewController.swift
Labels: storekit2

#1010 V4 API updates: added some more changes
  docs/V4_API_Updates.md
Labels: in progress, swift migration, storekit2

#1024 Moved test plans to its own folder
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCat.xcodeproj/xcshareddata/xcschemes/RevenueCat.xcscheme
  TestPlans/AllTests.xctestplan
  TestPlans/Coverage.xctestplan
  TestPlans/RevenueCat.xctestplan
  TestPlans/UnitTests.xctestplan
Labels: sharpen the saw

#1039 ProductInfo / ProductInfoExtractorTests refactor
  Purchases/Misc/ISOPeriodFormatter.swift
  Purchases/Purchasing/ProductInfoExtractor.swift
  Purchases/Purchasing/PurchasesOrchestrator.swift
  PurchasesTests/Misc/ISOPeriodFormatterTests.swift
  PurchasesTests/Purchasing/ProductInfoExtractorTests.swift
Labels: enhancement, sharpen the saw

#1038 Add support for SK2 discounts
  Purchases/Public/Purchases.swift
  Purchases/Purchasing/ProductInfo.swift
  Purchases/Purchasing/ProductInfoEnums.swift
  Purchases/Purchasing/ProductInfoExtractor.swift
  Purchases/Purchasing/PromotionalOffer.swift
  Purchases/Purchasing/StoreKitAbstractions/StoreProduct.swift
  Purchases/Purchasing/StoreKitAbstractions/SubscriptionPeriod.swift
  PurchasesTests/Mocks/MockSKDiscount.swift
  PurchasesTests/Networking/BackendTests.swift
  PurchasesTests/Purchasing/ProductInfoExtensions.swift
  PurchasesTests/Purchasing/ProductInfoExtractorTests.swift
  PurchasesTests/Purchasing/ProductInfoTests.swift
  PurchasesTests/Purchasing/PurchasesTests.swift
  RevenueCat.xcodeproj/project.pbxproj
  StoreKitUnitTests/StoreProductTests.swift
  StoreKitUnitTests/UnitTestsConfiguration.storekit
Labels: storekit2

#1049 Updated `PurchaseTester` to use all V4 methods
  IntegrationTests/PurchaseTester/PurchaseTester/SwiftPaywall.swift
Labels: storekit2

#1059 Add ability to enable StoreKit 2
  Purchases/Logging/Strings/ConfigureStrings.swift
  Purchases/Public/Purchases.swift
  README.md
  docs/V4_API_Updates.md
Labels: storekit2

#1074 MagicWeatherSwiftUI: use StoreKit 2
  Examples/MagicWeatherSwiftUI/Shared/Sources/Lifecycle/MagicWeatherApp.swift
Labels: storekit2

#1080 `PurchasesOrchestrator.purchase(package:completion:)`: handled invalid product error by making it impossible
  Purchases/Purchasing/PurchasesOrchestrator.swift
Labels: enhancement

#1085 StoreKit 2 support for `simulatesAskToBuyInSandbox`
  Purchases/Public/Purchases.swift
  Purchases/Purchasing/PurchasesOrchestrator.swift
  Purchases/Purchasing/StoreKit1/StoreKitWrapper.swift
Labels: storekit2

#1083 PurchaseTester: use StoreKit 2 if available
  IntegrationTests/PurchaseTester/PurchaseTester/AppDelegate.swift
Labels: storekit2

#1084 `PurchasesOrchestrator`: wrapping `StoreKitError` in our own error
  Purchases/Error Handling/ErrorUtils.swift
  Purchases/Error Handling/StoreKitError+Extensions.swift
  Purchases/Purchasing/PurchasesOrchestrator.swift
  RevenueCat.xcodeproj/project.pbxproj
Labels: storekit2

#1092 Cleaned up `StoreProduct` abstraction
  Purchases/Public/Package.swift
  Purchases/Public/Purchases.swift
  Purchases/Purchasing/ProductsManager.swift
  Purchases/Purchasing/PromotionalOffer.swift
  Purchases/Purchasing/PurchasesOrchestrator.swift
  Purchases/Purchasing/StoreKit1/ProductsFetcherSK1.swift
  Purchases/Purchasing/StoreKitAbstractions/SK1StoreProduct.swift
  Purchases/Purchasing/StoreKitAbstractions/SK2StoreProduct.swift
  Purchases/Purchasing/StoreKitAbstractions/StoreProduct.swift
  Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift
  PurchasesTests/Caching/DeviceCacheTests.swift
  PurchasesTests/Mocks/MockProductsManager.swift
  PurchasesTests/Purchasing/OfferingsTests.swift
  PurchasesTests/Purchasing/PurchasesTests.swift
  RevenueCat.xcodeproj/project.pbxproj
  StoreKitUnitTests/Mocks/PartialMockProductsManager.swift
  StoreKitUnitTests/ProductsManagerTests.swift
  StoreKitUnitTests/StoreProductTests.swift
Labels: storekit2

#1116 HTTPClient: added `X-StoreKit2-Enabled` header
  Purchases/Networking/HTTPClient.swift
Labels: storekit2
