Repository RevenueCat/purchases-ios, pull requests merged in 2021-11, with the labels that each got.

#944 Added tests for SystemInfo.isSandbox
  Purchases/Misc/SystemInfo.swift
  Purchases/Networking/Backend.swift
  Purchases/Networking/HTTPClient.swift
  Purchases/Public/Purchases.swift
  Purchases/Purchasing/PurchasesOrchestrator.swift
  Purchases/Purchasing/ReceiptFetcher.swift
  PurchasesTests/Misc/SystemInfoTests.swift
  PurchasesTests/Mocks/MockBundle.swift
  PurchasesTests/Mocks/MockReceiptFetcher.swift
  PurchasesTests/Purchasing/PurchasesTests.swift
  PurchasesTests/Purchasing/ReceiptFetcherTests.swift
  PurchasesTests/Resources/receipts/base64encoded_sandboxReceipt.txt
  PurchasesTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
  RevenueCat.xcodeproj/project.pbxproj
Labels: test backfill

#958 Clean-up: using swiftlint:disable:next instead of manually re-enabling rules
  Purchases/Attribution/AttributionPoster.swift
  Purchases/Caching/DeviceCache.swift
  Purchases/Networking/Backend.swift
  Purchases/Networking/HTTPClient.swift
  Purchases/Public/Purchases.swift
  Purchases/Purchasing/PromotionalOffer.swift
  Purchases/SubscriberAttributes/AttributionDataMigrator.swift
Labels: enhancement

#950 Clean up: moved obsoleted methods to a separate file
  Purchases/Misc/Obsoletions.swift
  Purchases/Public/Purchases.swift
  RevenueCat.xcodeproj/project.pbxproj
Labels: enhancement

#970 `IntroEligibility.init(: Int)`: refactored to avoid hardcoding values
  Purchases/Public/IntroEligibility.swift
Labels: enhancement

#969 Replaced `try!` in tests with `throws`
  PurchasesTests/Identity/CustomerInfoManagerTests.swift
  PurchasesTests/LocalReceiptParsing/Builders/ASN1ContainerBuilderTests.swift
  PurchasesTests/LocalReceiptParsing/Builders/AppleReceiptBuilderTests.swift
  PurchasesTests/LocalReceiptParsing/Builders/InAppPurchaseBuilderTests.swift
  PurchasesTests/LocalReceiptParsing/ReceiptParserTests.swift
  PurchasesTests/LocalReceiptParsing/TestsAgainstRealReceipts/ReceiptParsing+TestsWithRealReceipts.swift
  PurchasesTests/Misc/SystemInfoTests.swift
  PurchasesTests/Networking/HTTPClientTests.swift
  PurchasesTests/Purchasing/CustomerInfoTests.swift
  PurchasesTests/Purchasing/OfferingsTests.swift
  PurchasesTests/Purchasing/PurchasesTests.swift
  PurchasesTests/Purchasing/RCIntroEligibilityTests.swift
  PurchasesTests/Purchasing/ReceiptFetcherTests.swift
  PurchasesTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
  PurchasesTests/SubscriberAttributes/SubscriberAttributesManagerTests.swift
Labels: enhancement

#977 Storekit 2: update deployment targets
  Examples/MagicWeatherSwiftUI/Magic Weather SwiftUI.xcworkspace/xcshareddata/swiftpm/Package.resolved
  IntegrationTests/CocoapodsIntegration/CocoapodsIntegration.xcodeproj/project.pbxproj
  IntegrationTests/CocoapodsIntegration/Podfile
  IntegrationTests/CocoapodsIntegration/Podfile.lock
  IntegrationTests/SPMIntegration/SPMIntegration.xcodeproj/project.pbxproj
  IntegrationTests/XcodeDirectIntegration/XcodeDirectIntegration.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.swift
  RevenueCat.podspec
  RevenueCat.xcodeproj/project.pbxproj
  docs/V4_API_Updates.md
Labels: storekit2

#981 Obsoletions: correctly marked them as obsoleted on both Swift and Objective-C
  Purchases/Misc/Obsoletions.swift
Labels: bug, swift migration

#974 Obsoleted `Purchases`.`createAlias`/`identify`/`reset` and simplified `IdentityManager` implementation
  APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
  APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
  Purchases/Identity/IdentityManager.swift
  Purchases/Misc/Obsoletions.swift
  Purchases/Public/Purchases.swift
  PurchasesTests/Identity/IdentityManagerTests.swift
  PurchasesTests/Mocks/MockIdentityManager.swift
  PurchasesTests/Purchasing/PurchasesDeprecation.swift
  PurchasesTests/Purchasing/PurchasesTests.swift
Labels: enhancement
