Repository RevenueCat/purchases-ios, pull requests merged in 2022-10, with the labels that each got.

#1959 Update fastlane plugin
  Gemfile.lock
Labels: ci

#1960 Refactored `Error.isCancelledError` into `Error+Extensions`
  Sources/FoundationExtensions/Error+Extensions.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
Labels: refactor

#1961 `StoreKit1Wrapper`: separated `SKPaymentTransactionObserver` and `SKPaymentQueueDelegate` implementations
  Sources/Purchasing/StoreKit1/StoreKit1Wrapper.swift
Labels: refactor

#1962 `PaymentQueueWrapper`: also conform to `SKPaymentTransactionObserver` to fix promoted purchases
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/StoreKit1/PaymentQueueWrapper.swift
  Tests/UnitTests/Mocks/MockPaymentQueue.swift
  Tests/UnitTests/Purchasing/PaymentQuueWrapperTests.swift
  Tests/UnitTests/Purchasing/StoreKit1WrapperTests.swift
Labels: fix

#1945 `ReceiptFetcher`: added retry mechanism
  RevenueCat.xcodeproj/project.pbxproj
  Sources/FoundationExtensions/Data+Extensions.swift
  Sources/FoundationExtensions/DispatchTimeInterval+Extensions.swift
  Sources/LocalReceiptParsing/BasicTypes/AppleReceipt.swift
  Sources/LocalReceiptParsing/BasicTypes/InAppPurchase.swift
  Sources/Logging/Strings/ReceiptStrings.swift
  Sources/Misc/DangerousSettings.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/ReceiptFetcher.swift
  Sources/Purchasing/ReceiptRefreshPolicy.swift
  Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/UnitTests/LocalReceiptParsing/AppleReceiptTests.swift
  Tests/UnitTests/Misc/SystemInfoTests.swift
  Tests/UnitTests/Mocks/MockBundle.swift
  Tests/UnitTests/Mocks/MockReceiptParser.swift
  Tests/UnitTests/Mocks/MockRequestFetcher.swift
  Tests/UnitTests/Mocks/MockSystemInfo.swift
  Tests/UnitTests/Purchasing/ReceiptFetcherTests.swift
Labels: fix

#1955 Remind about updating docs and parity spreadsheet on minor releases
  .circleci/config.yml
Labels: ci

#1963 `PaymentQueueWrapper`: also implement `shouldShowPriceConsent`
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/StoreKit1/PaymentQueueWrapper.swift
Labels: fix

#1969 `Async.call` method to convert completion-block call to `async`
  Sources/FoundationExtensions/AsyncExtensions.swift
  Sources/Purchasing/ProductsManager.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/StoreKit1/ProductsFetcherSK1.swift
  Tests/StoreKitUnitTests/OfferingsManagerStoreKitTests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK2Tests.swift
  Tests/UnitTests/FoundationExtensions/AsyncExtensionsTests.swift
Labels: refactor

#1972 Fixed iOS 12/13 test snapshots
  Tests/UnitTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/iOS12-testPostReceiptWithSubscriberAttributesPassesCustomerInfoIfStatusCodeIsSuccess.1.json
  Tests/UnitTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/iOS12-testPostReceiptWithSubscriberAttributesPassesErrorIfStatusCodeIsNotSuccess.1.json
  Tests/UnitTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/iOS12-testPostReceiptWithSubscriberAttributesReturnsBadJson.1.json
  Tests/UnitTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/iOS12-testPostReceiptWithSubscriberAttributesSendsThemCorrectly.1.json
  Tests/UnitTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/iOS12-testPostReceiptWithoutSubscriberAttributesSkipsThem.1.json
  Tests/UnitTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/iOS13-testPostReceiptWithSubscriberAttributesPassesCustomerInfoIfStatusCodeIsSuccess.1.json
  Tests/UnitTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/iOS13-testPostReceiptWithSubscriberAttributesPassesErrorIfStatusCodeIsNotSuccess.1.json
  Tests/UnitTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/iOS13-testPostReceiptWithSubscriberAttributesReturnsBadJson.1.json
  Tests/UnitTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/iOS13-testPostReceiptWithSubscriberAttributesSendsThemCorrectly.1.json
  Tests/UnitTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/iOS13-testPostReceiptWithoutSubscriberAttributesSkipsThem.1.json
Labels: test

#1970 Renamed `CallbackCache.add(callback:)`
  Sources/Networking/Caching/CallbackCache.swift
  Sources/Networking/Caching/CustomerInfoCallback.swift
  Sources/Networking/CustomerAPI.swift
  Sources/Networking/IdentityAPI.swift
  Sources/Networking/OfferingsAPI.swift
Labels: refactor

#1973 `ErrorUtils.purchasesError(withUntypedError:)` handle `PurchasesErrorConvertible`
  Sources/Error Handling/ErrorUtils.swift
  Tests/UnitTests/Purchasing/ErrorUtilsTests.swift
Labels: refactor

#1968 `PaymentQueueWrapper`: improved abstraction for active `SKPaymentQueue` wrapper
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Misc/Deprecations.swift
  Sources/Misc/Either.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/StoreKit1/PaymentQueueWrapper.swift
  Sources/Purchasing/StoreKit1/StoreKit1Wrapper.swift
  Sources/Purchasing/StoreKitAbstractions/SK1StoreTransaction.swift
  Sources/Purchasing/StoreKitAbstractions/SK2StoreTransaction.swift
  Sources/Purchasing/StoreKitAbstractions/StoreTransaction.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/UnitTests/Misc/EitherTests.swift
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesDeferredPurchasesTests.swift
  Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Labels: refactor

#1974 `ErrorUtils`: improved logging and `localizedDescription` to include underlying errors
  Sources/Error Handling/ErrorUtils.swift
  Tests/UnitTests/Networking/NetworkErrorTests.swift
  Tests/UnitTests/Purchasing/ErrorUtilsTests.swift
Labels: fix

#1975 `OfferingsManager`: added missing test for ignoring missing products
  Tests/UnitTests/Purchasing/OfferingsManagerTests.swift
Labels: test

#1976 `OfferingsManager`: added ability to fail if any product is not found
  Sources/Logging/Strings/OfferingStrings.swift
  Sources/Misc/Purchases+async.swift
  Sources/Purchasing/OfferingsManager.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/UnitTests/Mocks/MockOfferingsManager.swift
  Tests/UnitTests/Purchasing/OfferingsManagerTests.swift
Labels: refactor

#1965 Purchasing: fixed consumable purchases by fixing transaction-finishing
  Sources/Logging/Strings/PurchaseStrings.swift
  Sources/Misc/Deprecations.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/StoreKitAbstractions/SK1StoreTransaction.swift
  Sources/Purchasing/StoreKitAbstractions/SK2StoreTransaction.swift
  Sources/Purchasing/StoreKitAbstractions/StoreTransaction.swift
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
  Tests/TestingApps/PurchaseTester/RevenueCat_IntegrationPurchaseTesterConfiguration.storekit
  Tests/UnitTests/Mocks/MockStoreKit1Wrapper.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift
Labels: fix, test

#1981 Fixed `Mac Catalyst` build
  Sources/Purchasing/StoreKit1/PaymentQueueWrapper.swift
  Sources/Purchasing/StoreKit1/StoreKit1Wrapper.swift
Labels: ci

#1984 `TrialOrIntroPriceEligibilityChecker`: only use SK2 implementation if enabled
  Sources/Purchasing/TrialOrIntroPriceEligibilityChecker.swift
Labels: perf

#1982 Fixed `ErrorUtils.purchasesError(withUntypedError:)` on iOS 12
  Sources/Error Handling/ErrorUtils.swift
Labels: test

#1986 Prepare next version: 4.14.0-SNAPSHOT
  .jazzy.yaml
  .version
  RevenueCat.podspec
  Sources/Info.plist
  Sources/Misc/SystemInfo.swift
  Tests/BackendIntegrationTestApp/Info.plist
  Tests/BackendIntegrationTests/Info.plist
  Tests/UnitTests/Info.plist
  Tests/UnitTestsHostApp/Info.plist
  scripts/docs/index.html
Labels: next_release

#1971 Created `InternalAPI` for "health" request
  RevenueCat.xcodeproj/project.pbxproj
  Sources/FoundationExtensions/Result+Extensions.swift
  Sources/Networking/Backend.swift
  Sources/Networking/HTTPClient/HTTPClient.swift
  Sources/Networking/HTTPClient/HTTPRequest.swift
  Sources/Networking/InternalAPI.swift
  Tests/UnitTests/FoundationExtensions/ResultExtensionsTests.swift
  Tests/UnitTests/Mocks/MockBackend.swift
  Tests/UnitTests/Mocks/MockHTTPClient.swift
  Tests/UnitTests/Networking/Backend/BackendInternalTests.swift
  Tests/UnitTests/Networking/Backend/BaseBackendTest.swift
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendInternalTests/iOS12-testHealthRequestIsNotAuthenticated.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendInternalTests/iOS12-testHealthRequestWithFailure.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendInternalTests/iOS12-testHealthRequestWithSuccess.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendInternalTests/iOS13-testHealthRequestIsNotAuthenticated.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendInternalTests/iOS13-testHealthRequestWithFailure.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendInternalTests/iOS13-testHealthRequestWithSuccess.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendInternalTests/iOS14-testHealthRequestIsNotAuthenticated.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendInternalTests/iOS14-testHealthRequestWithFailure.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendInternalTests/iOS14-testHealthRequestWithSuccess.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendInternalTests/iOS15-testHealthRequestIsNotAuthenticated.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendInternalTests/iOS15-testHealthRequestWithFailure.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendInternalTests/iOS15-testHealthRequestWithSuccess.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendInternalTests/iOS16-testHealthRequestIsNotAuthenticated.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendInternalTests/iOS16-testHealthRequestWithFailure.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendInternalTests/iOS16-testHealthRequestWithSuccess.1.json
  Tests/UnitTests/Networking/HTTPRequestTests.swift
Labels: refactor

#1958 `Purchases.logIn`: log warning if attempting to use a static `appUserID`
  Sources/Logging/Strings/IdentityStrings.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesLogInTests.swift
Labels: docs

#1989 Update fastlane-plugin-revenuecat_internal
  Gemfile.lock
Labels: ci

#1991 `Nimble`: use a fixed version
  RevenueCat.xcodeproj/project.pbxproj
Labels: test, ci

#1993 CI: removed redundant `swiftlint` installation
  .circleci/config.yml
Labels: ci

#1994 Fixed Xcode 13.2.x / Swift 5.5 compatibility
  Sources/Identity/IdentityManager.swift
  Sources/Misc/OperationDispatcher.swift
  Sources/Networking/CustomerAPI.swift
  Sources/Purchasing/OfferingsManager.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Support/ManageSubscriptionsHelper.swift
Labels: fix

#1995 Prepare next version: 4.14.0-SNAPSHOT
  .jazzy.yaml
  .version
  RevenueCat.podspec
  Sources/Info.plist
  Sources/Misc/SystemInfo.swift
  Tests/BackendIntegrationTestApp/Info.plist
  Tests/BackendIntegrationTests/Info.plist
  Tests/UnitTests/Info.plist
  Tests/UnitTestsHostApp/Info.plist
  scripts/docs/index.html
Labels: next_release

#1990 CI: added job to test compilation with `Xcode 13.2.1` / `Swift 5.5`
  .circleci/config.yml
Labels: ci

#1997 Documentation: fixed missing docs from inherited symbols
  .circleci/config.yml
  fastlane/Fastfile
Labels: docs

#1998 Update `fastlane`
  Gemfile.lock
Labels: build

#1985 `PurchaseTesterSwiftUI`: fixed warnings and simplified code using `async` methods
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/PurchaseTesterApp.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Customer/TransactionsView.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Offerings/OfferingDetailView.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Offerings/PromoOfferDetailsView.swift
Labels: refactor

#2000 [AUTOMATIC] Release/4.13.4
  .jazzy.yaml
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  RevenueCat.podspec
  Sources/Info.plist
  Sources/Misc/SystemInfo.swift
  Tests/BackendIntegrationTestApp/Info.plist
  Tests/BackendIntegrationTests/Info.plist
  Tests/InstallationTests/CommonFiles/RevenueCat-Swift.h
  Tests/UnitTests/Info.plist
  Tests/UnitTestsHostApp/Info.plist
  scripts/docs/index.html
Labels: next_release

#1992 CI: use `Xcode 14.1`
  .circleci/config.yml
  fastlane/Fastfile
Labels: ci

#2001 Prepare next version: 4.14.0-SNAPSHOT
  .jazzy.yaml
  .version
  RevenueCat.podspec
  Sources/Info.plist
  Sources/Misc/SystemInfo.swift
  Tests/BackendIntegrationTestApp/Info.plist
  Tests/BackendIntegrationTests/Info.plist
  Tests/UnitTests/Info.plist
  Tests/UnitTestsHostApp/Info.plist
  scripts/docs/index.html
Labels: next_release

#2002 Docs: fixed `logIn` references
  Sources/DocCDocumentation/DocCDocumentation.docc/Purchases.md
  Sources/DocCDocumentation/DocCDocumentation.docc/RevenueCat.md
Labels: docs

#1977 Introduced `PurchasesDiagnostics` to help diagnose SDK configuration errors
  RevenueCat.xcodeproj/project.pbxproj
  Sources/DocCDocumentation/DocCDocumentation.docc/Purchases.md
  Sources/DocCDocumentation/DocCDocumentation.docc/RevenueCat.md
  Sources/Networking/Backend.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesType.swift
  Sources/Support/PurchasesDiagnostics.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester.xcodeproj/project.pbxproj
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesDiagnosticsAPI.h
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesDiagnosticsAPI.m
  Tests/APITesters/ObjCAPITester/ObjCAPITester/main.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester.xcodeproj/project.pbxproj
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesDiagnosticsAPI.swift
  Tests/BackendIntegrationTests/OtherIntegrationTests.swift
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
  Tests/UnitTests/Misc/PurchasesDiagnosticsTests.swift
  Tests/UnitTests/Mocks/MockPurchases.swift
Labels: feat

#2005 Less Array()
  Sources/Attribution/AttributionPoster.swift
Labels: perf

#2008 `NetworkOperation`: workaround for iOS 12 crashes
  Sources/Networking/Operations/NetworkOperation.swift
Labels: fix

#1996 `PurchaseTesterSwiftUI`: combined targets into one multi-platform and fixed `macOS`
  Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester-Info.plist
  Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.entitlements
  Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/project.pbxproj
  Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/xcshareddata/xcschemes/PurchaseTester (iOS).xcscheme
  Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/xcshareddata/xcschemes/PurchaseTester SK (iOS).xcscheme
  Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/xcshareddata/xcschemes/PurchaseTester.xcscheme
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/TextFieldAlert.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/macOS/macOS.entitlements
Labels: refactor

#2013 Added `Set + Set` and `Set += Set` operators
  Sources/FoundationExtensions/Set+Extensions.swift
  Tests/UnitTests/FoundationExtensions/SetExtensionsTests.swift
Labels: refactor

#2010 `bug_report.md`: changed SK2 wording
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: docs
