Repository RevenueCat/purchases-ios, pull requests merged in 2022-05, with the labels that each got.

#1547 Improved `EntitlementInfosTests`
  Tests/UnitTests/Purchasing/EntitlementInfosTests.swift
Labels: sharpen the saw

#1540 Simplified `EntitlementInfo` decoding using new `@DefaultValue` property wrappers
  RevenueCat.xcodeproj/project.pbxproj
  Sources/CodableExtensions/EntitlementProductData+Extensions.swift
  Sources/FoundationExtensions/JSONDecoder+Extensions.swift
  Sources/Purchasing/EntitlementInfo.swift
  Sources/Purchasing/PurchaseOwnershipType.swift
Labels: sharpen the saw

#1541 Added `@IgnoreDecodeErrors` property wrapper
  Sources/FoundationExtensions/Decoder+Extensions.swift
  Tests/UnitTests/FoundationExtensions/DecoderExtensionTests.swift
Labels: sharpen the saw

#1543 Created `@LossyArray` and `@LossyDictionary`
  RevenueCat.xcodeproj/project.pbxproj
  Sources/FoundationExtensions/JSONDecoder+Extensions.swift
  Sources/FoundationExtensions/LossyCollections.swift
  Tests/UnitTests/FoundationExtensions/DecoderExtensionTests.swift
Labels: sharpen the saw

#1586 CF-653: Add `AmazonStore` to `Store` enum
  Sources/CodableExtensions/Store+Extensions.swift
  Sources/Purchasing/EntitlementInfo.swift
  Sources/Purchasing/StoreKitAbstractions/StoreTransaction.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCEntitlementInfoAPI.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester/EntitlementInfoAPI.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/StoreKitUnitTests/StoreKit2StorefrontListenerTests.swift
  Tests/StoreKitUnitTests/StorefrontTests.swift
  Tests/UnitTests/Purchasing/EntitlementInfosTests.swift
Labels: enhancement

#1587 CF-653: Rename `AmazonStore` Store enum case to `Amazon` to match Android naming
  Sources/CodableExtensions/Store+Extensions.swift
  Sources/Purchasing/EntitlementInfo.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCEntitlementInfoAPI.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester/EntitlementInfoAPI.swift
  Tests/UnitTests/Purchasing/EntitlementInfosTests.swift
Labels: enhancement

#1496 Converted `CustomerInfo` and related types to use `Codable`
  RevenueCat.xcodeproj/project.pbxproj
  Sources/CodableExtensions/EntitlementData+Extensions.swift
  Sources/Error Handling/ErrorUtils.swift
  Sources/Identity/CustomerInfo.swift
  Sources/Identity/CustomerInfoManager.swift
  Sources/Logging/Strings/CodableStrings.swift
  Sources/Logging/Strings/CustomerInfoStrings.swift
  Sources/Misc/RawDataContainer.swift
  Sources/Networking/Responses/CustomerInfoResponse.swift
  Sources/Purchasing/EntitlementInfo.swift
  Sources/Purchasing/EntitlementInfos.swift
  Sources/Purchasing/StoreKitAbstractions/StoreTransaction.swift
  Sources/Purchasing/TransactionsFactory.swift
  Tests/UnitTests/Identity/CustomerInfoManagerTests.swift
  Tests/UnitTests/Identity/IdentityManagerTests.swift
  Tests/UnitTests/Misc/CustomerInfo+TestExtensions.swift
  Tests/UnitTests/Networking/Responses/BaseHTTPResponseTest.swift
  Tests/UnitTests/Networking/Responses/CustomerInfoDecodingTests.swift
  Tests/UnitTests/Networking/Responses/Fixtures/CustomerInfo.json
  Tests/UnitTests/Networking/Responses/__Snapshots__/CustomerInfoDecodingTests/testEncoding.1.json
  Tests/UnitTests/Purchasing/CustomerInfoTests.swift
  Tests/UnitTests/Purchasing/EntitlementInfosTests.swift
  Tests/UnitTests/Purchasing/PurchasesTests.swift
  Tests/UnitTests/Purchasing/TransactionsFactoryTests.swift
  Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Labels: sharpen the saw

#1573 `PostOfferForSigningOperation`: changed response parsing to using `Decodable`
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Logging/Strings/BackendErrorStrings.swift
  Sources/Networking/Operations/PostOfferForSigningOperation.swift
  Sources/Networking/Responses/PostOfferResponse.swift
  Tests/UnitTests/Networking/Responses/Fixtures/PostOffer.json
  Tests/UnitTests/Networking/Responses/PostOfferDecodingTests.swift
Labels: sharpen the saw

#1576 `GetIntroEligibilityOperation`: replaced response parsing with `Decodable`
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Networking/IntroEligibilityResponse.swift
  Sources/Networking/Operations/GetIntroEligibilityOperation.swift
  Sources/Networking/Responses/GetIntroEligibilityResponse.swift
  Tests/UnitTests/Networking/Responses/Fixtures/GetIntroEligibility.json
  Tests/UnitTests/Networking/Responses/GetIntroEligibilityDecodingTests.swift
Labels: sharpen the saw

#1617 Release/4.4.0
  .jazzy.yaml
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  RevenueCat.podspec
  Sources/Misc/SystemInfo.swift
  Tests/InstallationTests/CommonFiles/RevenueCat-Swift.h
  scripts/docs/index.html
Labels: next_release

#1602 `PurchasesOrchestrator.purchase(sk2Product:promotionalOffer:)`: simplified implementation with new operator
  RevenueCat.xcodeproj/project.pbxproj
  Sources/FoundationExtensions/Operators+Extensions.swift
  Sources/Purchasing/PurchasesOrchestrator.swift
  Tests/UnitTests/FoundationExtensions/OperatorExtensionsTests.swift
Labels: sharpen the saw

#1609 Split `PurchasesTests` step 1: extracted `BasePurchasesTests`
  RevenueCat.xcodeproj/project.pbxproj
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesTests.swift
Labels: sharpen the saw

#1610 Split `PurchasesTests` step 2: extracted `PurchasesConfiguringTests` and `PurchasesGetCustomerInfoTests`
  RevenueCat.xcodeproj/project.pbxproj
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesGetCustomerInfoTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesTests.swift
Labels: sharpen the saw

#1612 Split `PurchasesTests` step 4: extracted `PurchasesRestoreTests`
  RevenueCat.xcodeproj/project.pbxproj
  Tests/UnitTests/Purchasing/Purchases/PurchasesRestoreTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesTests.swift
Labels: sharpen the saw

#1613 Split `PurchasesTests` step 5: extracted `PurchasesGetOfferingsTests`
  RevenueCat.xcodeproj/project.pbxproj
  Tests/UnitTests/Purchasing/Purchases/PurchasesGetOfferingsTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesTests.swift
Labels: sharpen the saw
