Repository RevenueCat/purchases-ios, pull requests merged in 2022-09, with the labels that each got.

#1881 Added `StoreKit2Setting.shouldOnlyUseStoreKit2`
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Misc/StoreKit2Setting.swift
  Tests/StoreKitUnitTests/TestHelpers/AvailabilityChecks.swift
  Tests/UnitTests/Misc/StoreKit2SettingTests.swift
Labels: storekit2, refactor

#1872 add link to SDK reference
  README.md
Labels: docs

#1879 Introduced type-safe `PurchasesError` and fixed some incorrect returned error types
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Error Handling/BackendError.swift
  Sources/Error Handling/ErrorCode.swift
  Sources/Error Handling/ErrorUtils.swift
  Sources/Error Handling/PurchasesError.swift
  Sources/Error Handling/SKError+Extensions.swift
  Sources/Error Handling/StoreKitError+Extensions.swift
  Sources/FoundationExtensions/Error+Extensions.swift
  Sources/Identity/IdentityManager.swift
  Sources/Networking/HTTPClient/HTTPResponse.swift
  Sources/Networking/HTTPClient/NetworkError.swift
  Sources/Purchasing/OfferingsManager.swift
  Sources/Purchasing/ProductsManager.swift
  Sources/Purchasing/Purchases/Attribution.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/StoreKit1/ProductsFetcherSK1.swift
  Sources/Purchasing/StoreKit2/ProductsFetcherSK2.swift
  Sources/SubscriberAttributes/SubscriberAttributesManager.swift
  Sources/Support/ManageSubscriptionsHelper.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
  Tests/StoreKitUnitTests/ManageSubscriptionsHelperTests.swift
  Tests/StoreKitUnitTests/ProductsManagerTests.swift
  Tests/StoreKitUnitTests/StoreProductTests.swift
  Tests/UnitTests/Mocks/MockIdentityManager.swift
  Tests/UnitTests/Mocks/MockManageSubscriptionsHelper.swift
  Tests/UnitTests/Mocks/MockProductsManager.swift
  Tests/UnitTests/Mocks/MockSubscriberAttributesManager.swift
  Tests/UnitTests/Networking/BaseErrorTests.swift
  Tests/UnitTests/Purchasing/ErrorUtilsTests.swift
  Tests/UnitTests/Purchasing/OfferingsManagerTests.swift
  Tests/UnitTests/Purchasing/ProductsFetcherSK1Tests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesLogInTests.swift
  Tests/UnitTests/TestHelpers/ErrorMatcher.swift
Labels: fix, refactor

#1883 `HTTPClient`: added `X-Client-Bundle-ID` and logged on SDK initialization
  Sources/Logging/Strings/ConfigureStrings.swift
  Sources/Misc/SystemInfo.swift
  Sources/Networking/HTTPClient/HTTPClient.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
Labels: docs

#1885 `PurchasesOrchestrator`: don't log warning if `allowSharingAppStoreAccount` setting was never explicitly set
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/UnitTests/TestHelpers/TestLogHandler.swift
Labels: fix

#1882 Disable SK1's `StoreKitWrapper` if SK2 is enabled and available
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Logging/Strings/StoreKitStrings.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/StoreKit1/PaymentQueueWrapper.swift
  Sources/Purchasing/StoreKit1/StoreKitWrapper.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
  Tests/UnitTests/Purchasing/StoreKitWrapperTests.swift
  Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Labels: WIP, feat, perf, refactor

#1884 `Offering`: improved confusing log for `PackageType.custom`
  Sources/Logging/Strings/OfferingStrings.swift
  Sources/Purchasing/Offering.swift
Labels: fix

#1887 Enabled `DEAD_CODE_STRIPPING`
  RevenueCat.xcodeproj/project.pbxproj
Labels: perf

#1886 Renamed `StoreKitWrapper` to `StoreKit1Wrapper`
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Misc/Deprecations.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/StoreKit1/StoreKit1Wrapper.swift
  Sources/Purchasing/StoreKitAbstractions/SK1StoreTransaction.swift
  Sources/Purchasing/StoreKitAbstractions/SK2StoreTransaction.swift
  Sources/Purchasing/StoreKitAbstractions/StoreTransaction.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/UnitTests/Mocks/MockStoreKitWrapper.swift
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesDeferredPurchasesTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesDelegateTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesGetOfferingsTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesGetProductsTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesSyncPurchasesTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesTransactionHandlingTests.swift
  Tests/UnitTests/Purchasing/StoreKit1WrapperTests.swift
  Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Labels: refactor

#1888 `CustomerInfoManager`/`OfferingsManager`: improved display of underlying errors
  Sources/Error Handling/BackendError.swift
  Sources/Identity/CustomerInfoManager.swift
  Sources/Logging/Strings/CustomerInfoStrings.swift
  Sources/Purchasing/OfferingsManager.swift
Labels: fix

#1889 Move to SNAPSHOT version on every commit to main if needed
  .circleci/config.yml
  Gemfile.lock
Labels: ci

#1892 `InstallationTests`: fixed deprecation warning
  Tests/InstallationTests/CommonFiles/RCInstallationRunner.m
Labels: ci

#1895 `watchOS`: fixed crash when ran on single-target apps with Xcode 14 and before watchOS 9.0
  Sources/Misc/SystemInfo.swift
Labels: fix

#1896 Fixed `CarthageInstallation` tests
  Tests/InstallationTests/CarthageInstallation/CarthageInstallation.xcodeproj/project.pbxproj
  Tests/InstallationTests/CarthageInstallation/CarthageInstallation.xcodeproj/xcshareddata/xcschemes/CarthageInstallation.xcscheme
Labels: test, ci

#1890 [AUTOMATIC] Release/4.12.0
  .jazzy.yaml
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  RevenueCat.podspec
  Sources/Misc/SystemInfo.swift
  Tests/InstallationTests/CommonFiles/RevenueCat-Swift.h
  scripts/docs/index.html
Labels: next_release

#1897 Prepare next version: 4.13.0-SNAPSHOT
  .jazzy.yaml
  .version
  RevenueCat.podspec
  Sources/Info.plist
  Sources/Misc/SystemInfo.swift
  Tests/BackendIntegrationTestApp/Info.plist
  Tests/BackendIntegrationTests/Info.plist
  Tests/UnitTests/Info.plist
  Tests/UnitTestsHostApp/Info.plist
  scripts/docs/index.html
Labels: next_release

#1880 `Integration Tests`: actually verify that entitlement is active
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
Labels: do not merge, HOLD, Investigating, test

#1899 `IntegrationTests`: simplified `testExpireSubscription` to fix flaky test
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
Labels: test

#1898 `Integration Tests`: added test to verify re-subscription behavior
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
Labels: test

#1902 `Purchases`: only expose testing data on `DEBUG`
  Sources/Purchasing/Purchases/Purchases.swift
Labels: refactor

#1904 `StoreKitUnitTests`: compile on iOS 11.0+
  .circleci/config.yml
  RevenueCat.xcodeproj/project.pbxproj
  Tests/StoreKitUnitTests/LocalReceiptParserStoreKitTests.swift
  Tests/StoreKitUnitTests/OfferingsManagerStoreKitTests.swift
  Tests/StoreKitUnitTests/PriceFormatterProviderTests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/StoreKitUnitTests/StoreKitConfigTestCase.swift
  Tests/StoreKitUnitTests/StoreProductTests.swift
  Tests/StoreKitUnitTests/StoreTransactionTests.swift
  Tests/StoreKitUnitTests/StorefrontTests.swift
  Tests/StoreKitUnitTests/TestHelpers/StoreKitTestHelpers.swift
  Tests/StoreKitUnitTests/TransactionsManagerSK1Tests.swift
  Tests/StoreKitUnitTests/TransactionsManagerSK2Tests.swift
  Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK1Tests.swift
  Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK2Tests.swift
  Tests/UnitTestsHostApp/SceneDelegate.swift
Labels: test

#1903 `spm build` CI job: changed to release build
  .circleci/config.yml
Labels: ci

#1905 `Atomic`: added unit test to verify `value`'s setter
  Tests/UnitTests/Misc/AtomicTests.swift
Labels: test

#1909 `CircleCI`: changed all jobs to use Xcode 14
  .circleci/config.yml
Labels: ci

#1916 `PurchaseTesterSwiftUI`: removed unnecessary `UIApplicationDelegate`
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/PurchaseTesterApp.swift
Labels: docs

#1918 `CircleCI`: changed iOS 12/13 to use Xcode 13
  .circleci/config.yml
Labels: ci

#1915 `PurchaseTesterSwiftUI`: fixed macOS target
  Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/project.pbxproj
Labels: fix

#1914 `pre-commit` hook: also verify leftover API keys in `PurchaseTester`
  Tests/TestingApps/PurchaseTester/PurchaseTester/Constants.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Constants.swift
  scripts/pre-commit.sh
Labels: ci

#1913 `Purchases.beginRefundRequest`: ensured errors are `PublicError`
  Sources/Error Handling/ErrorUtils.swift
  Sources/Misc/Purchases+nonasync.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
Labels: fix

#1901 `PaymentQueueWrapper`: handle promotional purchase requests from App Store when SK1 is disabled
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Logging/Strings/PurchaseStrings.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/StoreKit1/PaymentQueueWrapper.swift
  Sources/Purchasing/StoreKitAbstractions/PromotionalOffer.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/StoreKitUnitTests/TestHelpers/AvailabilityChecks.swift
  Tests/UnitTests/Mocks/MockPaymentQueueWrapper.swift
  Tests/UnitTests/Mocks/MockPurchasesDelegate.swift
  Tests/UnitTests/Mocks/MockStoreKit1Wrapper.swift
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesDeferredPurchasesTests.swift
  Tests/UnitTests/Purchasing/StoreKitAbstractions/PromotionalOfferTests.swift
Labels: fix

#1911 `GetCustomerInfoAPI`: avoid making a request if there's any `PostReceiptDataOperation` in progress
  Sources/Networking/Caching/CustomerInfoCallback.swift
  Sources/Networking/CustomerAPI.swift
  Sources/Networking/Operations/GetCustomerInfoOperation.swift
  Tests/UnitTests/Networking/Backend/BackendPostReceiptDataTests.swift
Labels: perf

#1926 `OperationQueue`: log debug message when requests are found in cache and skipped
  Sources/FoundationExtensions/OperationQueue+Extensions.swift
  Sources/Logging/Strings/NetworkStrings.swift
  Tests/UnitTests/Networking/Backend/BackendGetOfferingsTests.swift
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetOfferingsTests/iOS12-testRepeatedRequestsLogDebugMessage.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetOfferingsTests/iOS13-testRepeatedRequestsLogDebugMessage.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetOfferingsTests/iOS14-testRepeatedRequestsLogDebugMessage.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetOfferingsTests/iOS15-testRepeatedRequestsLogDebugMessage.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetOfferingsTests/iOS16-testRepeatedRequestsLogDebugMessage.1.json
  Tests/UnitTests/TestHelpers/TestLogHandler.swift
Labels: test

#1929 `StoreKitIntegrationTests`: print `AppleReceipt` data whenever `verifyEntitlementWentThrough` fails
  Sources/LocalReceiptParsing/BasicTypes/AppleReceipt.swift
  Sources/LocalReceiptParsing/BasicTypes/InAppPurchase.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
Labels: test

#1924 `ErrorUtils`: added test to verify that `PublicError`s can be `catch`'d as `ErrorCode`
  Tests/UnitTests/Purchasing/ErrorUtilsTests.swift
Labels: test

#1925 `Integration Tests`: relaunch tests when retrying failures
  Tests/TestPlans/CI-BackendIntegration.xctestplan
Labels: test, ci

#1931 `SnapshotTesting`: require version 1.9.0 to keep supporting iOS 12/13 tests
  RevenueCat.xcodeproj/project.pbxproj
Labels: dependencies, test

#1922 `StoreKit 2`: enabled by default
  Sources/Logging/Strings/PurchaseStrings.swift
  Sources/Misc/Deprecations.swift
  Sources/Misc/StoreKit2Setting.swift
  Sources/Purchasing/Configuration.swift
  Tests/UnitTests/Misc/StoreKit2SettingTests.swift
Labels: feat

#1910 `StoreKit 1`: changed result of cancelled purchases to be consistent with `StoreKit 2`
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift
Labels: fix

#1928 Fixed `tvOS` tests
  .circleci/config.yml
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Logging/Strings/PurchaseStrings.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester.xcodeproj/project.pbxproj
  Tests/APITesters/SwiftAPITester/SwiftAPITester.xcodeproj/project.pbxproj
  Tests/APITesters/SwiftAPITester/SwiftAPITester/AttributionAPI.swift
  Tests/StoreKitUnitTests/BeginRefundRequestHelperTests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/UnitTests/Mocks/MockSK2BeginRefundRequestHelper.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesAttributionDataTests.swift
  Tests/UnitTests/Purchasing/StoreKitAbstractions/SubscriptionPeriodTests.swift
  Tests/UnitTestsHostApp/AppDelegate.swift
  Tests/UnitTestsHostApp/Base.lproj/LaunchScreen.storyboard
  Tests/UnitTestsHostApp/Base.lproj/Main.storyboard
  Tests/UnitTestsHostApp/Info.plist
  fastlane/Fastfile
Labels: test, ci

#1933 `AppleReceipt`: refactored declarations into nested types
  Sources/LocalReceiptParsing/BasicTypes/AppleReceipt.swift
  Sources/LocalReceiptParsing/BasicTypes/InAppPurchase.swift
  Sources/LocalReceiptParsing/Builders/AppleReceiptBuilder.swift
  Sources/LocalReceiptParsing/Builders/InAppPurchaseBuilder.swift
  Tests/UnitTests/LocalReceiptParsing/Builders/AppleReceiptBuilderTests.swift
  Tests/UnitTests/LocalReceiptParsing/Builders/InAppPurchaseBuilderTests.swift
  Tests/UnitTests/TestHelpers/ContainerFactory.swift
Labels: refactor

#1934 `Logger`: refactored default `LogLevel` definition
  Sources/Logging/Logger.swift
Labels: refactor

#1935 `BasePurchasesTests`: changed default back to SK1
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesDeferredPurchasesTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift
Labels: test

#1932 `CacheableNetworkOperation`: fixed race condition in new test
  Tests/UnitTests/Mocks/MockHTTPClient.swift
  Tests/UnitTests/Networking/Backend/BackendGetOfferingsTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
  fastlane/Fastfile
Labels: test

#1936 Fixed iOS 12 tests
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetOfferingsTests/iOS12-testRepeatedRequestsLogDebugMessage.1.json
Labels: test

#1937 Prepare next version: 4.13.0-SNAPSHOT
  .jazzy.yaml
  .version
  RevenueCat.podspec
  Sources/Info.plist
  Sources/Misc/SystemInfo.swift
  Tests/BackendIntegrationTestApp/Info.plist
  Tests/BackendIntegrationTests/Info.plist
  Tests/UnitTests/Info.plist
  Tests/UnitTestsHostApp/Info.plist
  scripts/docs/index.html
Labels: next_release

#1939 Prepare next version: 4.14.0-SNAPSHOT
  .jazzy.yaml
  .version
  RevenueCat.podspec
  Sources/Info.plist
  Sources/Misc/SystemInfo.swift
  Tests/BackendIntegrationTestApp/Info.plist
  Tests/BackendIntegrationTests/Info.plist
  Tests/UnitTests/Info.plist
  Tests/UnitTestsHostApp/Info.plist
  scripts/docs/index.html
Labels: next_release

#1940 `PostReceiptDataOperation`: print receipt data if `debug` logs are enabled
  Sources/FoundationExtensions/JSONDecoder+Extensions.swift
  Sources/LocalReceiptParsing/BasicTypes/AppleReceipt.swift
  Sources/LocalReceiptParsing/BasicTypes/InAppPurchase.swift
  Sources/LocalReceiptParsing/ReceiptParser.swift
  Sources/Logging/Strings/ReceiptStrings.swift
  Sources/Networking/Operations/NetworkOperation.swift
  Sources/Networking/Operations/PostReceiptDataOperation.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
  Tests/StoreKitUnitTests/LocalReceiptParserStoreKitTests.swift
  Tests/UnitTests/LocalReceiptParsing/TestsAgainstRealReceipts/ReceiptParsing+TestsWithRealReceipts.swift
Labels: refactor

#1942 Moved `InAppPurchase` into `AppleReceipt`
  Sources/LocalReceiptParsing/BasicTypes/InAppPurchase.swift
  Sources/LocalReceiptParsing/Builders/AppleReceiptBuilder.swift
  Sources/LocalReceiptParsing/Builders/InAppPurchaseBuilder.swift
  Tests/UnitTests/LocalReceiptParsing/Builders/AppleReceiptBuilderTests.swift
  Tests/UnitTests/LocalReceiptParsing/Builders/InAppPurchaseBuilderTests.swift
  Tests/UnitTests/LocalReceiptParsing/ReceiptParserTests.swift
  Tests/UnitTests/Purchasing/IntroEligibilityCalculatorTests.swift
Labels: refactor

#1943 Abstracted conversion from `async` to completion-block APIs
  RevenueCat.xcodeproj/project.pbxproj
  Sources/FoundationExtensions/AsyncExtensions.swift
  Sources/Misc/Purchases+nonasync.swift
  Sources/Purchasing/ProductsManager.swift
  Sources/Purchasing/TransactionsManager.swift
  Sources/Purchasing/TrialOrIntroPriceEligibilityChecker.swift
  Sources/Support/ManageSubscriptionsHelper.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/StoreProductAPI.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/StorefrontAPI.swift
  Tests/UnitTests/FoundationExtensions/AsyncExtensionsTests.swift
Labels: refactor

#1941 Refactored `ReceiptFetcher.receiptData`
  Sources/Purchasing/ReceiptFetcher.swift
Labels: refactor

#1907 Created `CachingProductsManager` to provide consistent caching logic when fetching products
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Purchasing/CachingProductsManager.swift
  Sources/Purchasing/IntroEligibilityCalculator.swift
  Sources/Purchasing/OfferingsManager.swift
  Sources/Purchasing/ProductsManager.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/TrialOrIntroPriceEligibilityChecker.swift
  Tests/StoreKitUnitTests/ProductsManagerTests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/StoreKitUnitTests/StoreKit2CachingProductsManagerTests.swift
  Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK2Tests.swift
  Tests/UnitTests/Mocks/MockProductsManager.swift
  Tests/UnitTests/Purchasing/CachingProductsManagerTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesDeferredPurchasesTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift
Labels: perf

#1908 `ProductsFetcherSK2`: removed now redundant caching logic
  Sources/Purchasing/ProductsManager.swift
  Sources/Purchasing/StoreKit2/ProductsFetcherSK2.swift
  Tests/StoreKitUnitTests/PriceFormatterProviderTests.swift
  Tests/StoreKitUnitTests/ProductsFetcherSK2Tests.swift
  Tests/StoreKitUnitTests/StoreProductTests.swift
Labels: refactor

#1950 [AUTOMATIC] Release/4.13.1
  .jazzy.yaml
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  RevenueCat.podspec
  Sources/Info.plist
  Sources/Misc/SystemInfo.swift
  Tests/BackendIntegrationTestApp/Info.plist
  Tests/BackendIntegrationTests/Info.plist
  Tests/InstallationTests/CommonFiles/RevenueCat-Swift.h
  Tests/UnitTests/Info.plist
  Tests/UnitTestsHostApp/Info.plist
  scripts/docs/index.html
Labels: next_release

#1953 Prepare next version: 4.14.0-SNAPSHOT
  .jazzy.yaml
  .version
  RevenueCat.podspec
  Sources/Info.plist
  Sources/Misc/SystemInfo.swift
  Tests/BackendIntegrationTestApp/Info.plist
  Tests/BackendIntegrationTests/Info.plist
  Tests/UnitTests/Info.plist
  Tests/UnitTestsHostApp/Info.plist
  scripts/docs/index.html
Labels: next_release

#1952 `Integration Tests`: simplified `testIneligibleForIntroAfterPurchaseExpires` to fix flakiness
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
Labels: test
