Repository RevenueCat/purchases-ios, pull requests merged in 2022-11, with the labels that each got.

#2016 Update fastlane-plugin-revenuecat_internal
  Gemfile.lock
Labels: ci

#2017 Makes hold job wait for installation tests to pass
  .circleci/config.yml
Labels: ci

#2015 Avoid posting empty receipts by making`TransactionsManager` always use `SK1` implementation
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/TransactionsManager.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/StoreKitUnitTests/TransactionsManagerSK1Tests.swift
  Tests/StoreKitUnitTests/TransactionsManagerSK2Tests.swift
  Tests/StoreKitUnitTests/TransactionsManagerTests.swift
  Tests/UnitTests/Mocks/MockTransactionsManager.swift
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Labels: fix

#1999 `PurchaseTesterSwiftUI`: allow configuring API key at runtime
  Tests/TestingApps/PurchaseTesterSwiftUI/Constants.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/project.pbxproj
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/ConfiguredPurchases.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Extensions/Extensions.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Extensions/Identifiable.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/PurchaseTesterApp.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/ConfigurationView.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/ContentView.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift
Labels: dependencies

#2022 Changed `StoreKit2Setting.default` back to `.enabledOnlyForOptimizations`
  Sources/Misc/StoreKit2Setting.swift
  Sources/Purchasing/Configuration.swift
Labels: fix

#2026 Some updates on notify-on-non-patch-release-branches:
  .circleci/config.yml
Labels: ci

#2025 Runs push-pods after make-release
  .circleci/config.yml
  fastlane/Fastfile
Labels: ci

#2019 `eligiblePromotionalOffers`: don't log error if response is ineligible
  Sources/Misc/Purchases+async.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
Labels: refactor

#2018 Documentation: Fixed references in `V4_API_Migration_guide.md`
  Sources/DocCDocumentation/DocCDocumentation.docc/V4_API_Migration_guide.md
Labels: docs

#2006 `Async.call`: added non-throwing overload
  Sources/FoundationExtensions/AsyncExtensions.swift
  Tests/UnitTests/FoundationExtensions/AsyncExtensionsTests.swift
Labels: refactor

#2030 CI: fixed `iOS 14` tests Xcode version
  .circleci/config.yml
Labels: ci

#2035 `Integration Tests`: run on iOS 16
  .circleci/config.yml
Labels: test, ci

#2031 `Integration Tests`: changed log output to `raw`
  fastlane/Fastfile
Labels: test, ci

#2027 `PurchaseTesterSwiftUI`: replaced `Purchases` dependency with `SPM`
  Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/project.pbxproj
  Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcworkspace/contents.xcworkspacedata
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/ConfiguredPurchases.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Logger.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/PurchaseTesterApp.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/LoggerView.swift
Labels: dependencies

#2033 Added `BackendErrorCode.purchasedProductMissingInAppleReceipt`
  Sources/Error Handling/BackendErrorCode.swift
Labels: refactor

#2037 `ISO8601DateFormatter.withMilliseconds`: fixed iOS 11 crash
  Sources/FoundationExtensions/DateFormatter+Extensions.swift
Labels: fix

#2014 `CachingProductsManager`: use partial cached products
  Sources/Logging/Strings/OfferingStrings.swift
  Sources/Purchasing/CachingProductsManager.swift
  Tests/StoreKitUnitTests/StoreKit2CachingProductsManagerTests.swift
  Tests/UnitTests/Purchasing/CachingProductsManagerTests.swift
Labels: perf

#2040 `Integration Tests`: fixed `testPurchaseWithAskToBuyPostsReceipt`
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
Labels: test

#2042 `Integration Tests`: changed weekly to monthly subscriptions to work around 0-second subscriptions
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
Labels: test, ci

#2041 Update Fastlane plugin
  Gemfile.lock
Labels: ci

#2038 `PostReceiptDataOperation`: log Apple error when purchase equals expiration date
  Sources/LocalReceiptParsing/BasicTypes/AppleReceipt.swift
  Sources/LocalReceiptParsing/BasicTypes/InAppPurchase.swift
  Sources/LocalReceiptParsing/Builders/InAppPurchaseBuilder.swift
  Sources/Logging/Strings/ReceiptStrings.swift
  Sources/Networking/Operations/PostReceiptDataOperation.swift
  Tests/StoreKitUnitTests/LocalReceiptParserStoreKitTests.swift
  Tests/UnitTests/LocalReceiptParsing/AppleReceiptTests.swift
  Tests/UnitTests/Purchasing/ReceiptFetcherTests.swift
Labels: test

#2045 `CI`: fixed `push-pods` job
  .circleci/config.yml
Labels: ci

#2032 `ErrorCode.unknownBackendError`: include original error code
  Sources/Error Handling/ErrorDetails.swift
  Sources/Error Handling/ErrorUtils.swift
  Sources/Networking/HTTPClient/HTTPResponse.swift
  Tests/StoreKitUnitTests/ManageSubscriptionsHelperTests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK1Tests.swift
  Tests/UnitTests/Attribution/AttributionPosterTests.swift
  Tests/UnitTests/Misc/PurchasesDiagnosticsTests.swift
  Tests/UnitTests/Networking/Backend/BackendPostOfferForSigningTests.swift
  Tests/UnitTests/Networking/BackendErrorTests.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
  Tests/UnitTests/Networking/NetworkErrorTests.swift
  Tests/UnitTests/Purchasing/ErrorUtilsTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift
  Tests/UnitTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift
  Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Labels: refactor

#2034 `ErrorResponse.asBackendError`: serialize attribute errors as `NSDictionary`
  Sources/Networking/HTTPClient/HTTPResponse.swift
Labels: test

#2048 `HTTPClient`: added log for failed requests
  Sources/Logging/Strings/NetworkStrings.swift
  Sources/Networking/HTTPClient/HTTPClient.swift
Labels: test

#2053 `StoreKit 2`: don't finish transactions in observer mode
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Logging/Strings/PurchaseStrings.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/StoreKit2/StoreKit2TransactionListener.swift
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/StoreKitUnitTests/StoreKit2TransactionListenerTests.swift
  Tests/UnitTests/Mocks/MockStoreKit2TransactionListenerDelegate.swift
  Tests/UnitTests/Mocks/MockStoreTransaction.swift
  Tests/UnitTests/TestHelpers/AsyncTestHelpers.swift
Labels: fix

#2067 `CircleCI`: added ability to create a release manually
  .circleci/config.yml
Labels: ci

#2068 `Integration Tests`: always run them in random order locally
  Tests/TestPlans/BackendIntegrationTests.xctestplan
Labels: test

#2054 `APITester`: fixed warning in `SubscriptionPeriodAPI`
  Tests/APITesters/SwiftAPITester/SwiftAPITester/SubscriptionPeriodAPI.swift
Labels: refactor

#2043 `NSData+RCExtensionsTests`: improved errors
  Tests/UnitTests/FoundationExtensions/NSData+RCExtensionsTests.swift
Labels: test

#2076 Fixed lint issues with `SwiftLint 0.5.0`
  .swiftlint.yml
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/StoreKitUnitTests/StoreKit2TransactionListenerTests.swift
  Tests/UnitTests/Mocks/MockCustomerInfoManager.swift
  Tests/UnitTests/Mocks/MockOfferingsManager.swift
  Tests/UnitTests/Mocks/MockSubscriberAttributesManager.swift
  Tests/UnitTests/Networking/NetworkErrorTests.swift
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
Labels: build

#2046 Changed default `UserDefaults` from `.standard` to our own Suite
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Caching/DeviceCache.swift
  Sources/FoundationExtensions/UserDefaults+Extensions.swift
  Sources/Logging/Strings/ConfigureStrings.swift
  Sources/Networking/HTTPClient/ETagManager.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/StoreKitUnitTests/UserDefaultsDefaultTests.swift
  Tests/UnitTests/Mocks/MockDeviceCache.swift
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
  Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Labels: fix

#2055 `StoreKit1Wrapper`: added instance address when detecting transactions
  Sources/Logging/Strings/PurchaseStrings.swift
  Sources/Purchasing/StoreKit1/StoreKit1Wrapper.swift
Labels: test

#2078 `DeviceCache`: changed `NotificationCenter` observation to be received on posting thread
  Sources/Caching/DeviceCache.swift
  Tests/UnitTests/Mocks/MockNotificationCenter.swift
Labels: perf, refactor

#2079 `DeviceCache`: removed `fatalError` for users not overriding `UserDefaults`
  Sources/Caching/DeviceCache.swift
  Tests/UnitTests/Caching/DeviceCacheTests.swift
Labels: perf

#2056 `PurchasesSubscriberAttributesTests`: simplified tests
  Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Labels: test, refactor

#2081 Updated schemes and project for Xcode 14.1
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCat.xcodeproj/xcshareddata/xcschemes/BackendIntegrationTests.xcscheme
  RevenueCat.xcodeproj/xcshareddata/xcschemes/RevenueCat.xcscheme
  Tests/APITesters/ObjCAPITester/ObjCAPITester.xcodeproj/project.pbxproj
  Tests/APITesters/ObjCAPITester/ObjCAPITester.xcodeproj/xcshareddata/xcschemes/ObjCAPITester.xcscheme
  Tests/APITesters/SwiftAPITester/SwiftAPITester.xcodeproj/xcshareddata/xcschemes/SwiftAPITester.xcscheme
Labels: build

#2064 Exposed `SystemInfo.observerMode` to simplify code
  Sources/Misc/SystemInfo.swift
  Sources/Networking/HTTPClient/HTTPClient.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Tests/UnitTests/Misc/SystemInfoTests.swift
Labels: refactor

#2052 `PurchaseTesterSwiftUI`: added observer mode setting
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/ConfiguredPurchases.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/PurchaseTesterApp.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/ConfigurationView.swift
Labels: test

#2058 `Logger`: exposed generic `log` method
  Sources/Logging/Logger.swift
Labels: refactor

#2077 `Atomic`: added new test to verify each instance gets its own `Lock`
  Tests/UnitTests/Misc/AtomicTests.swift
Labels: test

#2075 Removed unused `APITesters.xcworkspace` and created `RevenueCat.xcworkspace`
  RevenueCat.xcworkspace/contents.xcworkspacedata
  Tests/APITesters/APITesters.xcworkspace/contents.xcworkspacedata
  Tests/APITesters/APITesters.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Tests/APITesters/APITesters.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  Tests/APITesters/APITesters.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: build

#2084 `CircleCI`: lowered `no_output_timeout` to 5 minutes
  .circleci/config.yml
Labels: ci

#2066 `SKTestSession`: finish all unfinished transactions before starting each test
  RevenueCat.xcodeproj/project.pbxproj
  Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
  Tests/StoreKitUnitTests/StoreKit2TransactionListenerTests.swift
  Tests/StoreKitUnitTests/StoreKitConfigTestCase.swift
  Tests/StoreKitUnitTests/TestHelpers/StoreKitConfigTestCase+Extensions.swift
  Tests/StoreKitUnitTests/TestHelpers/StoreKitTestHelpers.swift
Labels: test

#2059 Created `TimingUtil` to measure and log methods that are too slow
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Logging/LogIntent.swift
  Sources/Misc/TimingUtil.swift
  Tests/UnitTests/Misc/TimingUtilTests.swift
  Tests/UnitTests/TestHelpers/TestLogHandler.swift
Labels: perf

#2080 Added `LogLevel.verbose`
  Sources/Logging/LogIntent.swift
  Sources/Logging/Logger.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
  Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
Labels: feat

#2061 `StoreKit`: added logs when purchasing and product requests are too slow
  Sources/Logging/Logger.swift
  Sources/Logging/Strings/PurchaseStrings.swift
  Sources/Logging/Strings/StoreKitStrings.swift
  Sources/Misc/TimingUtil.swift
  Sources/Purchasing/Configuration.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/StoreKit1/ProductsFetcherSK1.swift
  Sources/Purchasing/StoreKit2/ProductsFetcherSK2.swift
Labels: storekit2, perf

#2082 Added `verbose` logs for `Purchases` and `StoreKit1Wrapper` lifetime
  Sources/Logging/Strings/ConfigureStrings.swift
  Sources/Logging/Strings/PurchaseStrings.swift
  Sources/Logging/Strings/Strings.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/StoreKit1/StoreKit1Wrapper.swift
Labels: test

#2087 `CircleCI`: fixed `docs-deploy` git credentials
  .circleci/config.yml
Labels: ci

#2071 `Tests`: replaced `toEventually` with new `waitUntilValue` to simplify tests
  Tests/StoreKitUnitTests/ProductsManagerTests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK1Tests.swift
  Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK2Tests.swift
  Tests/UnitTests/Identity/CustomerInfoManagerTests.swift
  Tests/UnitTests/Identity/IdentityManagerTests.swift
  Tests/UnitTests/Networking/Backend/BackendGetCustomerInfoTests.swift
  Tests/UnitTests/Networking/Backend/BackendGetIntroEligibilityTests.swift
  Tests/UnitTests/Networking/Backend/BackendGetOfferingsTests.swift
  Tests/UnitTests/Networking/Backend/BackendInternalTests.swift
  Tests/UnitTests/Networking/Backend/BackendLoginTests.swift
  Tests/UnitTests/Networking/Backend/BackendPostAdServicesTokenTests.swift
  Tests/UnitTests/Networking/Backend/BackendPostAttributionDataTests.swift
  Tests/UnitTests/Networking/Backend/BackendPostOfferForSigningTests.swift
  Tests/UnitTests/Networking/Backend/BackendPostReceiptDataTests.swift
  Tests/UnitTests/Networking/Backend/BackendPostSubscriberAttributesTests.swift
  Tests/UnitTests/Purchasing/IntroEligibilityCalculatorTests.swift
  Tests/UnitTests/Purchasing/OfferingsManagerTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesGetCustomerInfoTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesGetOfferingsTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesGetProductsTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesLogInTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesRestoreTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesSyncPurchasesTests.swift
  Tests/UnitTests/SubscriberAttributes/SubscriberAttributesManagerTests.swift
  Tests/UnitTests/TestHelpers/AsyncTestHelpers.swift
Labels: test, refactor

#2090 Update `fastlane`
  Gemfile.lock
  fastlane/README.md
Labels: ci

#2088 `TimingUtil`: fixed Xcode 13.2 compilation
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
Labels: ci

#2094 Fixed `SwiftLint` installation
  .circleci/config.yml
Labels: ci, v3.x

#2102 Fixed `LogLevel` ordering and added tests
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Logging/Logger.swift
  Tests/StoreKitUnitTests/LoggerTests.swift
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/TestHelpers/TestLogHandler.swift
Labels: test, refactor

#2093 `RCProductInfo`: added `SKStoreFront.countryCode` to post `store_country` with receipts
  Purchases/Public/RCPurchases.m
  Purchases/Purchasing/RCProductInfo.h
  Purchases/Purchasing/RCProductInfo.m
  Purchases/Purchasing/RCProductInfoExtractor.h
  Purchases/Purchasing/RCProductInfoExtractor.m
  Purchases/Purchasing/RCStoreKitWrapper.h
  Purchases/Purchasing/RCStoreKitWrapper.m
  PurchasesTests/Networking/BackendTests.swift
  PurchasesTests/Purchasing/ProductInfoExtensions.swift
  PurchasesTests/Purchasing/ProductInfoExtractorTests.swift
Labels: enhancement, v3.x
