Repository RevenueCat/purchases-ios, pull requests merged in 2022-12, with the labels that each got.

#2095 Release/3.14.3
  .jazzy.yaml
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  Purchases.podspec
  Purchases/Info.plist
  Purchases/Misc/RCSystemInfo.m
  PurchasesCoreSwift.podspec
  PurchasesCoreSwift/Info.plist
  PurchasesCoreSwiftTests/Info.plist
  PurchasesTests/Info.plist
  StoreKitTestApp/Info.plist
  StoreKitTests/Info.plist
Labels: v3.x

#2112 Version 3.x: increased output timeout for `make-release`
  .circleci/config.yml
Labels: v3.x

#2113 Fix documentation typo
  Sources/Purchasing/StoreKitAbstractions/StoreProduct.swift
Labels: docs

#2110 `Configuration.with(appUserID:)`: allow passing `nil` and added new tests
  Sources/Identity/IdentityManager.swift
  Sources/Purchasing/Configuration.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCConfigurationAPI.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester/ConfigurationAPI.swift
  Tests/UnitTests/Identity/IdentityManagerTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
Labels: fix

#2119 update CONTRIBUTING.md link in bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: docs

#2115 `StoreKit1Wrapper`: process transactions in a background thread
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/StoreKit1/StoreKit1Wrapper.swift
  Tests/UnitTests/Purchasing/StoreKit1WrapperTests.swift
Labels: perf

#2101 `DeviceCache`: added verbose logs for `init`/`deinit`
  Sources/Caching/DeviceCache.swift
  Sources/Logging/Strings/PurchaseStrings.swift
Labels: test

#2070 `StoreKit2` listeners: set `Task` `priority` to `.utility`
  Sources/Purchasing/StoreKit2/StoreKit2StorefrontListener.swift
  Sources/Purchasing/StoreKit2/StoreKit2TransactionListener.swift
Labels: storekit2, perf

#2106 `Integration Tests`: verify `Purchases` does not leak across tests
  Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
Labels: test

#2098 Extracted `LoggerType`
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Logging/Logger.swift
  Sources/Logging/LoggerType.swift
Labels: refactor

#2099 `ReceiptParser.parse` always throws `ReceiptParser.Error`
  Sources/LocalReceiptParsing/Builders/ASN1ContainerBuilder.swift
  Sources/LocalReceiptParsing/Builders/AppleReceiptBuilder.swift
  Sources/LocalReceiptParsing/Builders/InAppPurchaseBuilder.swift
  Sources/LocalReceiptParsing/DataConverters/UInt8+Extensions.swift
  Sources/LocalReceiptParsing/ReceiptParser.swift
  Sources/LocalReceiptParsing/ReceiptParsingError.swift
  Tests/UnitTests/LocalReceiptParsing/ReceiptParserTests.swift
  Tests/UnitTests/Purchasing/IntroEligibilityCalculatorTests.swift
  Tests/UnitTests/Purchasing/ReceiptFetcherTests.swift
  Tests/UnitTests/TestHelpers/ContainerFactory.swift
Labels: refactor

#2104 `BasePurchasesTests`: added assertion to ensure `Purchases` does not leak
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
Labels: test

#2118 `HTTPClient`: replaced `X-StoreKit2-Setting` with `X-StoreKit2-Enabled`
  Sources/Misc/StoreKit2Setting.swift
  Sources/Networking/HTTPClient/HTTPClient.swift
  Tests/UnitTests/Misc/StoreKit2SettingTests.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
Labels: refactor

#2126 `Integration Tests`: fixed `Purchases` leak through `PurchasesDiagnostics`
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
Labels: test

#2103 `CircleCI`: cache Homebrew installation
  .circleci/config.yml
  Brewfile
  Brewfile.lock.json
Labels: ci

#2020 Fixed purchasing with `PromotionalOffer`s using `StoreKit 2`
  Sources/Error Handling/ErrorUtils.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/StoreKitAbstractions/PromotionalOffer.swift
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/UnitTests/Purchasing/StoreKitAbstractions/PromotionalOfferTests.swift
Labels: storekit2, fix

#1588 `StoreKitIntegrationTests`: added test to check applying a promotional offer during subscription
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
Labels: test

#2127 `PostReceiptDataOperation`: also print receipt data with `verbose` logs
  Sources/Networking/Operations/PostReceiptDataOperation.swift
Labels: test

#2123 `ReceiptParser`: ensure parsing never happens in the main thread
  Sources/LocalReceiptParsing/ReceiptParser.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/ReceiptFetcher.swift
Labels: perf

#2139 `NetworkOperation`: made `Atomic` references immutable
  Sources/Networking/Operations/NetworkOperation.swift
Labels: refactor

#2137 `CallbackCache`: added assertion for tests to ensure we don't leak callbacks
  Sources/Networking/Caching/CallbackCache.swift
Labels: test

#2136 `CallbackCache`: avoid exposing internal mutable cache
  Sources/Networking/Caching/CallbackCache.swift
  Sources/Networking/Caching/CustomerInfoCallback.swift
Labels: refactor

#2129 Un-deprecate `Purchases.configure(withAPIKey:appUserID:)` and `Purchases.configure(withAPIKey:appUserID:observerMode:)`
  Sources/Misc/Deprecations.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
Labels: fix

#2128 `PostReceiptDataOperation`: clarified receipt debug log
  Sources/Logging/Strings/ReceiptStrings.swift
Labels: docs

#2143 `CallbackCache`: fixed reference
  Sources/Networking/Caching/CallbackCache.swift
Labels: refactor

#2124 Added a few performance improvements for `ReceiptParser`
  Sources/LocalReceiptParsing/Builders/ASN1ContainerBuilder.swift
  Sources/LocalReceiptParsing/DataConverters/UInt8+Extensions.swift
  Sources/LocalReceiptParsing/ReceiptParser.swift
Labels: perf

#2144 `ReceiptFetcherTests`: refactored tests using `waitUntilValue`
  Tests/UnitTests/Purchasing/ReceiptFetcherTests.swift
Labels: test, refactor

#2147 `CI`: fixed `PurchaseTester` deployment
  fastlane/Fastfile
Labels: ci

#2151 `StoreKitRequestFetcher`: added log when starting/ending requests
  Sources/Logging/Strings/StoreKitStrings.swift
  Sources/Purchasing/StoreKit1/StoreKitRequestFetcher.swift
Labels: refactor

#2134 Extracted `asyncWait` to poll `async` conditions in tests
  Sources/FoundationExtensions/DispatchTimeInterval+Extensions.swift
  Tests/StoreKitUnitTests/TestHelpers/StoreKitConfigTestCase+Extensions.swift
  Tests/UnitTests/Purchasing/ProductsFetcherSK1Tests.swift
  Tests/UnitTests/TestHelpers/AsyncTestHelpers.swift
Labels: test, refactor

#2145 Created `ClockType` and `TestClock` to be able to mock time
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Misc/Clock.swift
  Tests/UnitTests/Mocks/TestClock.swift
Labels: test

#2146 `ReceiptFetcher`: throttle receipt refreshing to avoid `StoreKit` throttle errors
  Sources/FoundationExtensions/DispatchTimeInterval+Extensions.swift
  Sources/Logging/Strings/ReceiptStrings.swift
  Sources/Purchasing/ReceiptFetcher.swift
  Sources/Purchasing/ReceiptRefreshPolicy.swift
  Tests/UnitTests/Purchasing/ReceiptFetcherTests.swift
Labels: fix

#2156 Fix sending presentedOfferingIdentifier in StoreKit2
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
Labels: fix

#2069 Added integration and unit tests to verify observer mode behavior
  Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
  Tests/StoreKitUnitTests/StoreKit2TransactionListenerTests.swift
  Tests/UnitTests/Mocks/MockStoreKit2TransactionListener.swift
  Tests/UnitTests/Mocks/MockStoreKit2TransactionListenerDelegate.swift
Labels: storekit2, test

#2157 Fixed `AttributionFetcher.adServicesToken` hanging when called in simulator
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Attribution/AttributionFetcher.swift
  Sources/Logging/Strings/AttributionStrings.swift
  Tests/UnitTests/Attribution/AttributionFetcherTests.swift
Labels: test

#2161 `Fastfile`: changed `match` to `readonly`
  fastlane/Fastfile
Labels: ci

#2162 `CI`: don't make releases until `release-checks` pass
  .circleci/config.yml
Labels: ci

#2171 `Purchase Tester`: fixed `.storekit` config file reference
  Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/project.pbxproj
Labels: test

#2142 `MagicWeatherSwiftUI`: updated `README` to point to workspace
  Examples/MagicWeatherSwiftUI/README.md
Labels: docs

#2167 `DNSChecker`: added log with resolved host
  Sources/Logging/Strings/NetworkStrings.swift
  Sources/Networking/HTTPClient/DNSChecker.swift
Labels: refactor

#2173 `TrialOrIntroPriceEligibilityCheckerSK1Tests`: use `waitUntilValue`
  Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK1Tests.swift
  Tests/UnitTests/Purchasing/IntroEligibilityCalculatorTests.swift
Labels: test, refactor

#2177 `StoreKitTestHelpers`: cleaned up unnecessary log
  Tests/StoreKitUnitTests/TestHelpers/StoreKitTestHelpers.swift
Labels: test

#2117 `StoreKit1Wrapper`: added warning if receiving too many updated transactions
  Sources/Logging/Strings/StoreKitStrings.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/StoreKit1/StoreKit1Wrapper.swift
  Tests/UnitTests/Purchasing/StoreKit1WrapperTests.swift
  Tests/UnitTests/TestHelpers/TestLogHandler.swift
Labels: docs

#2176 `BundleSandboxEnvironmentDetector`: fixed logic for `macOS`
  Sources/Misc/SandboxEnvironmentDetector.swift
  Tests/UnitTests/Misc/SandboxEnvironmentDetectorTests.swift
  Tests/UnitTests/Mocks/MockBundle.swift
Labels: fix

#2182 `IntroEligibilityStatus`: added `CustomStringConvertible` implementation
  Sources/Purchasing/IntroEligibility.swift
Labels: fix

#2152 `StoreKitRequestFetcher`: removed unnecessary dispatch
  Sources/Purchasing/StoreKit1/StoreKitRequestFetcher.swift
  Tests/UnitTests/Purchasing/StoreKitRequestFetcherTests.swift
Labels: refactor

#2158 `Integration Tests`: split up tests in smaller files
  RevenueCat.xcodeproj/project.pbxproj
  Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
  Tests/BackendIntegrationTests/StoreKitObserverModeIntegrationTests.swift
Labels: test, refactor

#2168 `HTTPClientTests`: refactored to use `waitUntil`
  Tests/UnitTests/Networking/HTTPClientTests.swift
Labels: test, refactor

#2170 `Purchase Tester`: fixed scene manifest
  Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester-Info.plist
Labels: test

#2181 `IntroEligibilityCalculator`: added log including `AppleReceipt`
  Sources/Logging/Strings/CustomerInfoStrings.swift
  Sources/Purchasing/IntroEligibilityCalculator.swift
Labels: refactor

#2175 `PurchaseTester`: fixed `macOS` support
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/PurchaseTesterApp.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/ConfigurationView.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift
Labels: test

#2135 `CacheableNetworkOperation`: avoid unnecessarily creating operations for cache hits
  Sources/FoundationExtensions/OperationQueue+Extensions.swift
  Sources/Logging/Strings/NetworkStrings.swift
  Sources/Networking/BackendConfiguration.swift
  Sources/Networking/Caching/CustomerInfoCallback.swift
  Sources/Networking/CustomerAPI.swift
  Sources/Networking/IdentityAPI.swift
  Sources/Networking/InternalAPI.swift
  Sources/Networking/OfferingsAPI.swift
  Sources/Networking/Operations/GetCustomerInfoOperation.swift
  Sources/Networking/Operations/GetOfferingsOperation.swift
  Sources/Networking/Operations/LogInOperation.swift
  Sources/Networking/Operations/NetworkOperation.swift
  Sources/Networking/Operations/PostReceiptDataOperation.swift
Labels: perf

#2148 Fixed race condition finishing `SK1` transactions
  Sources/Logging/Strings/PurchaseStrings.swift
  Sources/Purchasing/StoreKit1/PaymentQueueWrapper.swift
  Sources/Purchasing/StoreKit1/StoreKit1Wrapper.swift
  Sources/Purchasing/StoreKitAbstractions/SK1StoreTransaction.swift
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
  Tests/UnitTests/Mocks/MockStoreKit1Wrapper.swift
  Tests/UnitTests/Purchasing/StoreKit1WrapperTests.swift
Labels: fix

#2179 `Purchase Tester`: added button to clear messages on logger view
  Tests/TestingApps/PurchaseTesterSwiftUI/Core/Logger.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/project.pbxproj
  Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/xcshareddata/xcschemes/PurchaseTesterWatchOS.xcscheme
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/LoggerView.swift
Labels: test

#2166 `DNSChecker`: simplified `NetworkError` initialization
  Sources/Networking/HTTPClient/DNSChecker.swift
  Sources/Networking/HTTPClient/HTTPClient.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
Labels: refactor

#2172 `Purchase Tester`: added ability to purchase products directly with `StoreKit`
  Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/project.pbxproj
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Helpers/ObserverModeManager.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Helpers/ProductFetcherSK1.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Helpers/ProductFetcherSK2.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Helpers/PurchasesOrchestrator.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/ContentView.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Offerings/OfferingDetailView.swift
Labels: test

#2165 `ErrorUtils.purchasesError(withUntypedError:)`: handle `PublicError`s
  Sources/Error Handling/ErrorUtils.swift
  Tests/UnitTests/Purchasing/ErrorUtilsTests.swift
Labels: fix

#2185 `Purchase Tester`: fixed `SubscriptionPeriod`
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Offerings/OfferingDetailView.swift
Labels: test

#2184 `Purchase Tester`: display specific `IntroEligibilityStatus`
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Offerings/OfferingDetailView.swift
Labels: test

#2153 Exposed `PurchasesReceiptParser` and `AppleReceipt`
  RevenueCat.xcodeproj/project.pbxproj
  Sources/DocCDocumentation/DocCDocumentation.docc/Purchases.md
  Sources/DocCDocumentation/DocCDocumentation.docc/RevenueCat.md
  Sources/FoundationExtensions/JSONDecoder+Extensions.swift
  Sources/LocalReceiptParsing/BasicTypes/AppleReceipt.swift
  Sources/LocalReceiptParsing/BasicTypes/InAppPurchase.swift
  Sources/LocalReceiptParsing/Builders/ASN1ContainerBuilder.swift
  Sources/LocalReceiptParsing/Builders/AppleReceiptBuilder.swift
  Sources/LocalReceiptParsing/Builders/InAppPurchaseBuilder.swift
  Sources/LocalReceiptParsing/DataConverters/Codable+Extensions.swift
  Sources/LocalReceiptParsing/DataConverters/DateFormatter+Extensions.swift
  Sources/LocalReceiptParsing/Helpers/LoggerType.swift
  Sources/LocalReceiptParsing/Helpers/ReceiptParserLogger.swift
  Sources/LocalReceiptParsing/Helpers/ReceiptStrings.swift
  Sources/LocalReceiptParsing/PurchasesReceiptParser.swift
  Sources/LocalReceiptParsing/ReceiptParsingError.swift
  Sources/Logging/Logger.swift
  Sources/Networking/Operations/PostReceiptDataOperation.swift
  Sources/Purchasing/IntroEligibilityCalculator.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/ReceiptFetcher.swift
  Sources/Purchasing/TransactionsManager.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester.xcodeproj/project.pbxproj
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesReceiptParserAPI.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/main.swift
  Tests/StoreKitUnitTests/LocalReceiptParserStoreKitTests.swift
  Tests/UnitTests/LocalReceiptParsing/ReceiptParserTests.swift
  Tests/UnitTests/LocalReceiptParsing/TestsAgainstRealReceipts/ReceiptParsing+TestsWithRealReceipts.swift
  Tests/UnitTests/Mocks/MockASN1ContainerBuilder.swift
  Tests/UnitTests/Mocks/MockAppleReceiptBuilder.swift
  Tests/UnitTests/Mocks/MockReceiptParser.swift
  Tests/UnitTests/Purchasing/IntroEligibilityCalculatorTests.swift
  Tests/UnitTests/Purchasing/ReceiptFetcherTests.swift
Labels: feat

#2188 `Purchase Tester`: fixed `TestFlight` deployment
  Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/project.pbxproj
Labels: ci

#2189 `ReceiptParser`: a few documentation improvements
  Sources/LocalReceiptParsing/BasicTypes/AppleReceipt.swift
  Sources/LocalReceiptParsing/PurchasesReceiptParser.swift
Labels: docs

#2187 `CircleCI`: use Xcode 14.2.0
  .circleci/config.yml
Labels: ci

#2155 Created `ReceiptParser` SPM
  .circleci/config.yml
  LocalReceiptParsing
  Package.swift
  RevenueCat.podspec
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCat.xcodeproj/xcshareddata/xcschemes/ReceiptParser.xcscheme
  RevenueCat.xcodeproj/xcshareddata/xcschemes/RevenueCat.xcscheme
  Sources/LocalReceiptParsing/ReceiptParser-only-files/PurchasesReceiptParser+Extensions.swift
  Tests/APITesters/ReceiptParserAPITester/ReceiptParserAPITester.xcodeproj/project.pbxproj
  Tests/APITesters/ReceiptParserAPITester/ReceiptParserAPITester.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Tests/APITesters/ReceiptParserAPITester/ReceiptParserAPITester.xcodeproj/xcshareddata/xcschemes/ReceiptParserAPITester.xcscheme
  Tests/APITesters/ReceiptParserAPITester/ReceiptParserAPITester/AppleReceiptAPI.swift
  Tests/APITesters/ReceiptParserAPITester/ReceiptParserAPITester/PurchasesReceiptParserAPI.swift
  Tests/APITesters/ReceiptParserAPITester/ReceiptParserAPITester/main.swift
  Tests/InstallationTests/ReceiptParserInstallation/ReceiptParserInstallation.xcodeproj/project.pbxproj
  Tests/InstallationTests/ReceiptParserInstallation/ReceiptParserInstallation.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Tests/InstallationTests/ReceiptParserInstallation/ReceiptParserInstallation.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Tests/InstallationTests/ReceiptParserInstallation/ReceiptParserInstallation.xcodeproj/xcshareddata/xcschemes/ReceiptParserIntegration.xcscheme
  Tests/InstallationTests/ReceiptParserInstallation/ReceiptParserIntegration/Assets.xcassets/AccentColor.colorset/Contents.json
  Tests/InstallationTests/ReceiptParserInstallation/ReceiptParserIntegration/Assets.xcassets/AppIcon.appiconset/Contents.json
  Tests/InstallationTests/ReceiptParserInstallation/ReceiptParserIntegration/Assets.xcassets/Contents.json
  Tests/InstallationTests/ReceiptParserInstallation/ReceiptParserIntegration/ReceiptParserIntegration.entitlements
  Tests/InstallationTests/ReceiptParserInstallation/ReceiptParserIntegration/ReceiptParserIntegrationApp.swift
  Tests/InstallationTests/ReceiptParserInstallation/ReceiptParserIntegrationTests/ReceiptParserIntegrationTests.swift
  Tests/InstallationTests/ReceiptParserInstallation/fastlane/Fastfile
  Tests/InstallationTests/ReceiptParserInstallation/fastlane/Matchfile
  Tests/InstallationTests/ReceiptParserInstallation/fastlane/README.md
  fastlane/Fastfile
Labels: feat

#2190 Added `Dictionary.merge`
  Sources/FoundationExtensions/Dictionary+Extensions.swift
  Tests/UnitTests/FoundationExtensions/DictionaryExtensionsTests.swift
Labels: refactor

#2178 `Restore purchases`: post product data when posting receipts
  Sources/LocalReceiptParsing/BasicTypes/AppleReceipt.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/StoreKit1/PaymentQueueWrapper.swift
  Sources/Purchasing/StoreKit1/StoreKit1Wrapper.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/UnitTests/LocalReceiptParsing/AppleReceiptTests.swift
  Tests/UnitTests/Mocks/MockReceiptFetcher.swift
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesRestoreTests.swift
  Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Labels: fix

#2194 Update fastlane-plugin-revenuecat_internal to latest version
  Gemfile.lock
Labels: ci
