Repository RevenueCat/purchases-ios, pull requests merged in 2022-08, with the labels that each got.

#1782 Release/4.9.1
  .jazzy.yaml
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  RevenueCat.podspec
  Sources/Info.plist
  Sources/Misc/SystemInfo.swift
  Tests/BackendIntegrationTestApp/Info.plist
  Tests/BackendIntegrationTests/Info.plist
  Tests/InstallationTests/CommonFiles/RevenueCat-Swift.h
  Tests/UnitTests/Info.plist
  Tests/UnitTestsHostApp/Info.plist
  scripts/docs/index.html
Labels: next_release

#1792 `OfferingsManager`: expose underlying error when `ProductsManager` returns an error
  Sources/Error Handling/ErrorUtils.swift
  Sources/Logging/Strings/OfferingStrings.swift
  Sources/Purchasing/OfferingsManager.swift
  Tests/StoreKitUnitTests/OfferingsManagerStoreKitTests.swift
  Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK1Tests.swift
  Tests/UnitTests/Mocks/MockProductsManager.swift
  Tests/UnitTests/Purchasing/IntroEligibilityCalculatorTests.swift
  Tests/UnitTests/Purchasing/OfferingsManagerTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesTransactionHandlingTests.swift
Labels: storekit2, iOS 16, fix

#1761 Configure Danger, enforce labels
  .circleci/config.yml
  Dangerfile
  Gemfile
  Gemfile.lock
Labels: ci

#1796 Pass CircleCI branch to prepare_next_version job
  .circleci/config.yml
Labels: ci

#1798 Invalidates gem caches and separates danger and macOS caches
  .circleci/config.yml
Labels: ci

#1797 AdServices: Fix failing tests on main in iOS 12 and 13 - IOSAttributionPosterTests
  Tests/UnitTests/Attribution/AttributionPosterTests.swift
Labels: test

#1803 Replace usages of replace_in with replace_text_in_files action
  fastlane/Fastfile
Labels: ci

#1791 Update gems
  Gemfile.lock
Labels: build

#1809 `SwiftLint`: fixed deprecation warning
  scripts/pre-commit.sh
Labels: refactor

#1794 `SK2StoreProduct`: conditionally removed `@available` workaround
  Sources/Purchasing/StoreKitAbstractions/SK2StoreProduct.swift
Labels: refactor

#1811 `StoreKitConfigTestCase.changeStorefront`: re-enabled on iOS 16
  Tests/StoreKitUnitTests/PriceFormatterProviderTests.swift
  Tests/StoreKitUnitTests/StoreProductTests.swift
  Tests/StoreKitUnitTests/TestHelpers/StoreKitTestHelpers.swift
Labels: iOS 16, fix

#1812 Clean up: moved `BackendIntegrationTests.xctestplan` to `TestPlans` folder
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCat.xcodeproj/xcshareddata/xcschemes/BackendIntegrationTests.xcscheme
  Tests/TestPlans/BackendIntegrationTests.xctestplan
Labels: test, refactor

#1814 PurchaseTester- Update Podfile.lock
  Tests/TestingApps/PurchaseTester/Podfile.lock
Labels: build

#1810 `Dangerfile`: added "next_release" as supported label
  Dangerfile
Labels: ci

#1817 Update documentation for presentCodeRedemptionSheet
  Sources/Purchasing/Purchases/Purchases.swift
Labels: docs

#1808 Moved `AttributionFetcherError` inside `AttributionFetcher`
  Sources/Attribution/AttributionFetcher.swift
Labels: refactor

#1816 Fixed warnings for unnecessary `try`
  Tests/StoreKitUnitTests/OfferingsManagerStoreKitTests.swift
  Tests/StoreKitUnitTests/ProductsManagerTests.swift
Labels: refactor

#1805 `PurchasesAttributionDataTests`: fixed potential race condition in flaky test
  Tests/UnitTests/Purchasing/Purchases/PurchasesAttributionDataTests.swift
Labels: refactor

#1804 `Atomic: ExpressibleByNilLiteral`
  Sources/FoundationExtensions/Optional+Extensions.swift
  Sources/Misc/Atomic.swift
  Tests/UnitTests/Mocks/MockDNSChecker.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
Labels: refactor

#1818 `PriceFormatterProvider: Sendable` conformance and fixed thread-safety
  Sources/Misc/Atomic.swift
  Sources/Misc/Lock.swift
  Sources/Misc/PriceFormatterProvider.swift
  Tests/StoreKitUnitTests/PriceFormatterProviderTests.swift
Labels: fix

#1813 `Purchases.shared` and `Purchases.isConfigured` are now thread-safe
  Sources/Purchasing/Purchases/Purchases.swift
Labels: fix, refactor

#1807 `SystemInfo.finishTransactions`: made thread-safe
  Sources/Misc/SystemInfo.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
Labels: fix

#1828 Directly send delegate customer info when delegate is set (always sends cached CustomerInfo value)
  Sources/Purchasing/Purchases/Purchases.swift
Labels: refactor

#1815 Adds an approval job that will tag the release
  .circleci/config.yml
  Contributing/RELEASING.md
  fastlane/Fastfile
  fastlane/README.md
Labels: ci

#1820 `SwiftLint`: fixed build warning
  RevenueCat.xcodeproj/project.pbxproj
Labels: build

#1822 `Atomic: ExpressibleByBooleanLiteral`
  Sources/Misc/Atomic.swift
  Sources/Networking/Operations/NetworkOperation.swift
  Tests/UnitTests/Mocks/MockDNSChecker.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
Labels: refactor

#1823 `DeviceCache`: `Sendable` conformance and fixed thread-safety
  Sources/Caching/DeviceCache.swift
  Sources/Misc/SynchronizedUserDefaults.swift
Labels: fix

#1831 link to sdk reference
  README.md
Labels: docs

#1821 `SwiftLint`: cleaned up output
  scripts/swiftlint.sh
Labels: sharpen the saw, build

#1832 Created `PurchasesLoginTests`
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Networking/IdentityAPI.swift
  Tests/UnitTests/Mocks/MockIdentityManager.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesLogInTests.swift
Labels: test

#1833 `PurchasesLogInTests`: added test to verify `logIn` updates offerings cache
  Tests/UnitTests/Purchasing/Purchases/PurchasesLogInTests.swift
Labels: test

#1834 `CallbackCache`: simplified implementation using `Atomic`
  Sources/Networking/BackendConfiguration.swift
  Sources/Networking/Caching/CallbackCache.swift
  Sources/Networking/CustomerAPI.swift
  Sources/Networking/IdentityAPI.swift
  Sources/Networking/OfferingsAPI.swift
  Sources/Networking/Operations/GetCustomerInfoOperation.swift
Labels: perf, refactor

#1835 `CallbackCache: Sendable` conformance
  Sources/Networking/Caching/CallbackCache.swift
Labels: refactor

#1830 `PurchasesDelegate`: added test for latest cached customer info always being sent
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
Labels: test

#1836 Update migration doc from didReceiveUpdatedCustomerInfo to receivedUpdatedCustomerInfo
  Sources/DocCDocumentation/DocCDocumentation.docc/V4_API_Migration_guide.md
  Sources/Logging/Strings/ConfigureStrings.swift
Labels: docs

#1838 Update fastlane plugin
  Contributing/RELEASING.md
  Gemfile.lock
  fastlane/Fastfile
Labels: ci

#1827 `Backend`: fixed potential race conditions introduced by `OperationDispatcher.dispatchOnWorkerThread(withRandomDelay:)`
  Sources/Identity/CustomerInfoManager.swift
  Sources/Networking/Backend.swift
  Sources/Networking/BackendConfiguration.swift
  Sources/Networking/CustomerAPI.swift
  Sources/Networking/OfferingsAPI.swift
  Sources/Purchasing/OfferingsManager.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/UnitTests/Identity/CustomerInfoManagerTests.swift
  Tests/UnitTests/Mocks/MockBackend.swift
  Tests/UnitTests/Mocks/MockIdentityAPI.swift
  Tests/UnitTests/Mocks/MockOfferingsAPI.swift
  Tests/UnitTests/Networking/Backend/BackendGetCustomerInfoTests.swift
  Tests/UnitTests/Networking/Backend/BackendGetOfferingsTests.swift
  Tests/UnitTests/Networking/Backend/BackendPostReceiptDataTests.swift
  Tests/UnitTests/Networking/Backend/BaseBackendTest.swift
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetOfferingsTests/iOS12-testGetOfferingsCallsHTTPMethodWithRandomDelay.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetOfferingsTests/iOS13-testGetOfferingsCallsHTTPMethodWithRandomDelay.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetOfferingsTests/iOS14-testGetOfferingsCallsHTTPMethodWithRandomDelay.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetOfferingsTests/iOS15-testGetOfferingsCallsHTTPMethodWithRandomDelay.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetOfferingsTests/iOS16-testGetOfferingsCallsHTTPMethodWithRandomDelay.1.json
  Tests/UnitTests/Purchasing/OfferingsManagerTests.swift
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift
Labels: fix, perf

#1840 StoreKit 2: `PurchasesOrchestrator`: don't log "purchased product" if it was cancelled
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
Labels: fix

#1837 Adds hotfixes section to RELEASING doc
  Contributing/RELEASING.md
Labels: docs

#1842 Release train
  .circleci/config.yml
  Gemfile.lock
  fastlane/Fastfile
  fastlane/README.md
Labels: ci

#1841 Purchase cancellations: unify behavior between SK1 and SK2
  Sources/Misc/Purchases+async.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
Labels: fix

#1843 `MagicWeatherSwiftUI`: updated to use `async` APIs
  Examples/MagicWeatherSwiftUI/Shared/Sources/ViewModels/UserViewModel.swift
  Examples/MagicWeatherSwiftUI/Shared/Sources/Views/PaywallView.swift
  Examples/MagicWeatherSwiftUI/Shared/Sources/Views/UserView.swift
  Examples/MagicWeatherSwiftUI/Shared/Sources/Views/WeatherView.swift
Labels: refactor

#1844 `ErrorResponse`: don't add attribute errors to message if empty
  Sources/Error Handling/ErrorUtils.swift
  Sources/Networking/HTTPClient/HTTPResponse.swift
  Tests/UnitTests/Networking/BaseErrorTests.swift
  Tests/UnitTests/Networking/NetworkErrorTests.swift
  Tests/UnitTests/Purchasing/ErrorUtilsTests.swift
Labels: fix

#1847 `release-train`: set `github_rate_limit` to deal with rate limiting
  .circleci/config.yml
Labels: ci

#1851 Add 4.10.1 changelog
  CHANGELOG.md
Labels: docs

#1850 Update hotfixes instruction to include updating changelog in main
  Contributing/RELEASING.md
Labels: docs

#1846 `Fastfile`: `test_tvos` lane had duplicate parameter
  fastlane/Fastfile
Labels: ci

#1852 Build fix- Update package requirements for MagicWeather
  Examples/MagicWeather/MagicWeather.xcodeproj/project.pbxproj
  Examples/MagicWeather/MagicWeather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Examples/MagicWeather/README.md
Labels: build

#1845 `Configuration.with(usesStoreKit2IfAvailable:)`: removed "experimental" warning
  Sources/Purchasing/Configuration.swift
Labels: docs

#1848 Release/4.10.2
  .jazzy.yaml
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  RevenueCat.podspec
  Sources/Info.plist
  Sources/Misc/SystemInfo.swift
  Tests/BackendIntegrationTestApp/Info.plist
  Tests/BackendIntegrationTests/Info.plist
  Tests/UnitTests/Info.plist
  Tests/UnitTestsHostApp/Info.plist
  scripts/docs/index.html
Labels: next_release

#1854 Prepare next version: 4.11.0-SNAPSHOT
  .jazzy.yaml
  .version
  RevenueCat.podspec
  Sources/Info.plist
  Sources/Misc/SystemInfo.swift
  Tests/BackendIntegrationTestApp/Info.plist
  Tests/BackendIntegrationTests/Info.plist
  Tests/UnitTests/Info.plist
  Tests/UnitTestsHostApp/Info.plist
  scripts/docs/index.html
Labels: next_release

#1849 `watchOS`: fixed crash on single-target apps
  Sources/Misc/SystemInfo.swift
Labels: iOS 16, fix

#1855 `IntegrationTests`: actually fail test if tests aren't configured
  Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
Labels: test

#1856 README updates
  Examples/MagicWeather/README.md
  README.md
Labels: docs

#1857 Added `Collection.onlyElement`
  Sources/FoundationExtensions/Array+Extensions.swift
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
  Tests/BackendIntegrationTests/SubscriberAttributesManagerIntegrationTests.swift
  Tests/StoreKitUnitTests/LocalReceiptParserStoreKitTests.swift
  Tests/StoreKitUnitTests/ProductsManagerTests.swift
  Tests/StoreKitUnitTests/StoreProductTests.swift
  Tests/UnitTests/FoundationExtensions/ArrayExtensionsTests.swift
  Tests/UnitTests/Networking/Responses/PostOfferDecodingTests.swift
  Tests/UnitTests/Purchasing/ErrorUtilsTests.swift
Labels: test, refactor

#1824 `CustomerInfo: Sendable` conformance
  Sources/Identity/CustomerInfo.swift
  Sources/Purchasing/EntitlementInfo.swift
  Sources/Purchasing/EntitlementInfos.swift
  Sources/Purchasing/NonSubscriptionTransaction.swift
  Sources/Purchasing/PurchaseOwnershipType.swift
Labels: refactor

#1825 `ReceiptParser: Sendable` conformance
  Sources/LocalReceiptParsing/Builders/ASN1ContainerBuilder.swift
  Sources/LocalReceiptParsing/Builders/ASN1ObjectIdentifierBuilder.swift
  Sources/LocalReceiptParsing/Builders/AppleReceiptBuilder.swift
  Sources/LocalReceiptParsing/Builders/InAppPurchaseBuilder.swift
  Sources/LocalReceiptParsing/ReceiptParser.swift
  Tests/StoreKitUnitTests/LocalReceiptParserStoreKitTests.swift
  Tests/UnitTests/LocalReceiptParsing/Builders/ASN1ObjectIdentifierBuilderTests.swift
  Tests/UnitTests/LocalReceiptParsing/ReceiptParserTests.swift
  Tests/UnitTests/Mocks/MockReceiptParser.swift
Labels: refactor

#1826 `Offering`/`StoreProductType`: `Sendable` conformance
  Sources/Purchasing/Offering.swift
  Sources/Purchasing/Package.swift
  Sources/Purchasing/PackageType.swift
  Sources/Purchasing/StoreKitAbstractions/SK1StoreProduct.swift
  Sources/Purchasing/StoreKitAbstractions/SK1StoreProductDiscount.swift
  Sources/Purchasing/StoreKitAbstractions/SK2StoreProduct.swift
  Sources/Purchasing/StoreKitAbstractions/SK2StoreProductDiscount.swift
  Sources/Purchasing/StoreKitAbstractions/StoreProduct.swift
  Sources/Purchasing/StoreKitAbstractions/StoreProductDiscount.swift
  Sources/Purchasing/StoreKitAbstractions/SubscriptionPeriod.swift
Labels: refactor

#1819 `Lock`: changed default implementation to use `NSLock`
  Contributing/ThreadSafety.md
  Sources/Misc/Atomic.swift
  Sources/Misc/Lock.swift
  Tests/UnitTests/Misc/LockTests.swift
Labels: perf

#1859 `TrialOrIntroPriceEligibilityChecker`: return `.noIntroOfferExists` if the product has no introductory offer
  Sources/Purchasing/TrialOrIntroPriceEligibilityChecker.swift
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
Labels: fix

#1860 `CircleCI`: added job for building SDK with `SPM`
  .circleci/config.yml
Labels: test, ci

#1864 Use Dangerfile repository
  Dangerfile
Labels: ci

#1863 fix typo in comment
  Sources/Purchasing/StoreKitAbstractions/SK1StoreTransaction.swift
Labels: docs

#1866 Update fastlane-plugin-revenuecat_internal and fix release-train job
  .circleci/config.yml
  Gemfile.lock
Labels: ci

#1867 Release/4.10.3
  .jazzy.yaml
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  RevenueCat.podspec
  Sources/Info.plist
  Sources/Misc/SystemInfo.swift
  Tests/BackendIntegrationTestApp/Info.plist
  Tests/BackendIntegrationTests/Info.plist
  Tests/InstallationTests/CommonFiles/RevenueCat-Swift.h
  Tests/UnitTests/Info.plist
  Tests/UnitTestsHostApp/Info.plist
  scripts/docs/index.html
Labels: next_release

#1861 Added `beginRefundRequest` overload with completion block
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Misc/Purchases+nonasync.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
Labels: feat

#1869 Fixed crash on `async` SK1 cancelled purchase
  Sources/Misc/Purchases+async.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift
Labels: fix

#1870 Skip release if needed and adds automatic release to PR title and body
  fastlane/Fastfile
Labels: ci

#1871 `ErrorUtils`: added test to verify that returned errors can be converted to `ErrorCode`
  Tests/UnitTests/Purchasing/ErrorUtilsTests.swift
Labels: test

#1875 `Integration Tests`: added test for purchasing `StoreProduct` instead of `Package`
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
Labels: test

#1858 Introduced `TestLogHandler` to simplify how we test logged messages
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Logging/Logger.swift
  Tests/UnitTests/Mocks/MockStoreKit2TransactionListener.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
  Tests/UnitTests/Purchasing/ErrorUtilsTests.swift
  Tests/UnitTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift
  Tests/UnitTests/TestHelpers/Box.swift
  Tests/UnitTests/TestHelpers/TestLogHandler.swift
Labels: test, refactor

#1874 Prepare next version: 4.12.0-SNAPSHOT
  .jazzy.yaml
  .version
  RevenueCat.podspec
  Sources/Info.plist
  Sources/Misc/SystemInfo.swift
  Tests/BackendIntegrationTestApp/Info.plist
  Tests/BackendIntegrationTests/Info.plist
  Tests/UnitTests/Info.plist
  Tests/UnitTestsHostApp/Info.plist
  scripts/docs/index.html
Labels: next_release
