Repository RevenueCat/purchases-ios, pull requests merged in 2023-11, with the labels that each got.

#3354 Add `StoreProduct.pricePerWeek`
  Sources/Purchasing/StoreKitAbstractions/StoreProduct.swift
  Sources/Purchasing/StoreKitAbstractions/SubscriptionPeriod.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCStoreProductAPI.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester/StoreProductAPI.swift
  Tests/UnitTests/Purchasing/StoreKitAbstractions/SubscriptionPeriodTests.swift
Labels: feat

#3367 `Paywalls`: improve period abbreviations in Japanese
  RevenueCatUI/Data/Localization.swift
  Tests/RevenueCatUITests/LocalizationTests.swift
Labels: RevenueCatUI

#3370 `Paywalls`: `.presentPaywallIfNeeded` allows overriding `Offering`
  RevenueCatUI/PaywallView.swift
  RevenueCatUI/View+PresentPaywall.swift
  Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewAPI.swift
Labels: RevenueCatUI

#3373 `Offering`: new `getMetadataValue` with `Decodable` type
  Sources/Purchasing/Offering.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/OfferingAPI.swift
  Tests/UnitTests/Purchasing/OfferingsTests.swift
Labels: feat

#3371 Fix deprecation warning
  RevenueCatUI/Data/Localization.swift
Labels: refactor

#3379 `Paywalls`: optimize `background.jpg` image
  RevenueCatUI/Resources/background.jpg
Labels: perf

#3378 `RevenueCatUI`: lowered CocoaPods deployment target to 11.0
  RevenueCatUI.podspec
Labels: build

#3381 `Paywalls`: fix template 4 layout bug on iOS 16
  RevenueCatUI/Modifiers/FooterHidingModifier.swift
  RevenueCatUI/Modifiers/ViewExtensions.swift
  RevenueCatUI/Templates/Template4View.swift
Labels: fix, RevenueCatUI

#3384 `CircleCI`: fix `visionOS` job
  .circleci/config.yml
Labels: ci

#3385 `Paywalls`: fix Turkish discount string
  RevenueCatUI/Resources/tr.lproj/Localizable.strings
Labels: fix, RevenueCatUI

#3388 `Paywalls`: fix Turkish translation
  RevenueCatUI/Resources/tr.lproj/Localizable.strings
Labels: RevenueCatUI

#3389 `Paywalls`: fix Turkish translation
  RevenueCatUI/Resources/tr.lproj/Localizable.strings
Labels: RevenueCatUI

#3392 `RevenueCatUI`: added support to other deployment targets
  RevenueCatUI.podspec
  RevenueCatUI/Data/Constants.swift
  RevenueCatUI/Data/IntroEligibility/IntroEligibilityViewModel.swift
  RevenueCatUI/Data/ProcessedLocalizedConfiguration.swift
  RevenueCatUI/Data/TemplateViewConfiguration+Images.swift
  RevenueCatUI/Data/TemplateViewConfiguration.swift
  RevenueCatUI/Data/TestData.swift
  RevenueCatUI/Data/UserInterfaceIdiom.swift
  RevenueCatUI/Data/Variables.swift
  RevenueCatUI/Helpers/ColorInformation+MultiScheme.swift
  RevenueCatUI/Helpers/PaywallData+Default.swift
  RevenueCatUI/Helpers/PreviewHelpers.swift
  RevenueCatUI/Modifiers/ConsistentPackageContentView.swift
  RevenueCatUI/Modifiers/FooterHidingModifier.swift
  RevenueCatUI/Modifiers/ViewExtensions.swift
  RevenueCatUI/PaywallFontProvider.swift
  RevenueCatUI/PaywallView.swift
  RevenueCatUI/Purchasing/MockPurchases.swift
  RevenueCatUI/Purchasing/PaywallPurchasesType.swift
  RevenueCatUI/Purchasing/PurchaseHandler+TestData.swift
  RevenueCatUI/Purchasing/PurchaseHandler.swift
  RevenueCatUI/Templates/Template1View.swift
  RevenueCatUI/Templates/Template2View.swift
  RevenueCatUI/Templates/Template3View.swift
  RevenueCatUI/Templates/Template4View.swift
  RevenueCatUI/Templates/Template5View.swift
  RevenueCatUI/Templates/TemplateViewType.swift
  RevenueCatUI/UIKit/PaywallViewController.swift
  RevenueCatUI/View+PresentPaywall.swift
  RevenueCatUI/View+PresentPaywallFooter.swift
  RevenueCatUI/View+PurchaseRestoreCompleted.swift
  RevenueCatUI/Views/AsyncButton.swift
  RevenueCatUI/Views/DebugErrorView.swift
  RevenueCatUI/Views/ErrorDisplay.swift
  RevenueCatUI/Views/FooterView.swift
  RevenueCatUI/Views/IconView.swift
  RevenueCatUI/Views/IntroEligibilityStateView.swift
  RevenueCatUI/Views/LoadingPaywallView.swift
  RevenueCatUI/Views/PackageButtonStyle.swift
  RevenueCatUI/Views/PurchaseButton.swift
  RevenueCatUI/Views/RemoteImage.swift
  RevenueCatUI/Views/TemplateBackgroundImageView.swift
  Sources/Paywalls/PaywallColor.swift
  Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewAPI.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PaywallAPI.swift
  fastlane/Fastfile
Labels: build

#3391 `Paywalls`: add `displayCloseButton` to `PaywallViewController`
  RevenueCatUI/UIKit/PaywallViewController.swift
  Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewControllerAPI.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Views/AppContentView.swift
Labels: RevenueCatUI

#3396 `HTTPClient`: add `X-Is-Sandbox`
  .swiftlint.yml
  Purchases/Networking/RCHTTPClient.m
  PurchasesTests/Networking/HTTPClientTests.swift
Labels: refactor

#3397 `RCSystemInfo.isSandbox`: improve implementation
  Purchases/Misc/RCSystemInfo.h
  Purchases/Misc/RCSystemInfo.m
  PurchasesTests/Misc/SystemInfoTests.swift
Labels: refactor

#3398 Version 3.14.4
  .jazzy.yaml
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  Purchases.podspec
  Purchases/Info.plist
  Purchases/Misc/RCSystemInfo.m
  PurchasesCoreSwift.podspec
  PurchasesCoreSwift/Info.plist
  PurchasesCoreSwiftTests/Info.plist
  PurchasesTests/Info.plist
  StoreKitTestApp/Info.plist
  StoreKitTests/Info.plist
Labels: next_release

#3401 `Integration Tests`: fix potential crash on `tearDown`
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
Labels: test

#3406 `Integration Tests`: verify that `SKTestSession` purchases do not grant production entitlements
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Misc/SandboxEnvironmentDetector.swift
  Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
  Tests/UnitTests/Mocks/MockSandboxEnvironmentDetector.swift
Labels: test

#3408 `CircleCI`: upgrade to Xcode 15.1
  .circleci/config.yml
  Tests/purchases-ios-snapshots-commit
Labels: ci

#3409 `visionOS`: fix support for `Xcode 15.1 beta 3`
  Package.swift
  RevenueCatUI/PaywallFontProvider.swift
  RevenueCatUI/Templates/Template4View.swift
  RevenueCatUI/Views/FooterView.swift
  Sources/FoundationExtensions/Locale+Extensions.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Helpers/AdaptiveStack.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Helpers/ObserverModeManager.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Helpers/PurchasesOrchestrator.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Offerings/OfferingDetailView.swift
Labels: fix, xrOS

#3405 Adds `X-Storefront` request header for App Store Storefront
  Sources/Misc/SystemInfo.swift
  Sources/Networking/HTTPClient/HTTPClient.swift
  Sources/Purchasing/StoreKitAbstractions/Storefront.swift
  Tests/UnitTests/Misc/SystemInfoTests.swift
  Tests/UnitTests/Mocks/MockSystemInfo.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
Labels: refactor

#3411 `SystemInfo`: fix flaky `Storefront` test
  Tests/StoreKitUnitTests/StorefrontTests.swift
  Tests/UnitTests/Misc/SystemInfoTests.swift
Labels: test

#3418 Enable explicit_init lint rule and fix issues
  .swiftlint.yml
  Sources/Error Handling/ErrorUtils.swift
  Sources/Misc/Codable/IgnoreHashable.swift
  Sources/Purchasing/StoreKitAbstractions/SK1StoreProductDiscount.swift
  Sources/Purchasing/StoreKitAbstractions/SK2StoreProductDiscount.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PaywallAPI.swift
  Tests/UnitTests/Networking/Backend/BackendGetIntroEligibilityTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift
  Tests/UnitTests/Purchasing/StoreKit1WrapperTests.swift
Labels: style

#3417 Remove `MockStoreMessagesHelper` from SDK
  RevenueCat.xcodeproj/project.pbxproj
  Tests/UnitTests/Mocks/MockStoreMessagesHelper.swift
Labels: test

#3431 `CircleCI`: fix snapshot generation for iOS 14
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCat.xcodeproj/xcshareddata/xcschemes/RevenueCat.xcscheme
  Tests/TestPlans/CI-RevenueCat-Snapshots.xctestplan
  fastlane/Fastfile
Labels: ci

#3444 Some `APITester` fixes
  Tests/APITesters/SwiftAPITester/SwiftAPITester/StoreProductAPI.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/StoreProductDiscountAPI.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/TestStoreProductAPI.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/VerificationResultAPI.swift
Labels: test

#3470 `Paywalls`: simplified `PaywallViewMode` logic
  RevenueCatUI/Data/PaywallViewMode+Extensions.swift
  RevenueCatUI/Templates/Template1View.swift
  RevenueCatUI/Templates/Template2View.swift
  RevenueCatUI/Templates/Template3View.swift
  RevenueCatUI/Templates/Template4View.swift
  RevenueCatUI/Templates/Template5View.swift
Labels: refactor

#3468 `Paywalls`: tests for `PurchaseButton` layout logic
  RevenueCatUI/Data/TemplateViewConfiguration+Extensions.swift
  RevenueCatUI/Views/PurchaseButton.swift
  Tests/RevenueCatUITests/Data/TemplateViewConfigurationTests.swift
Labels: test

#3469 `Paywalls`: remove empty space when template 4 has no offer details
  RevenueCatUI/Data/TemplateViewConfiguration+Extensions.swift
  RevenueCatUI/Templates/Template4View.swift
  Tests/RevenueCatUITests/Data/TemplateViewConfigurationTests.swift
Labels: RevenueCatUI

#3403 `CircleCI`: upgrade to Xcode 15.1
  .circleci/config.yml
Labels: blocked, ci
