Repository RevenueCat/purchases-ios, pull requests merged in 2023-04, with the labels that each got.

#2392 `PurchaseTester`: fix memory leaks
  Tests/TestingApps/PurchaseTester/PurchaseTester/CatsViewController.swift
Labels: test

#2379 Added new `VerificationResult.verifiedOnDevice`
  Sources/Security/VerificationResult.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCVerificationResultAPI.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester/VerificationResultAPI.swift
  Tests/UnitTests/Security/SigningTests.swift
Labels: refactor

#2394 Fix iOS 12 compilation
  Sources/Logging/Strings/OfflineEntitlementsStrings.swift
  Sources/OfflineEntitlements/PurchasedProductsFetcher.swift
Labels: test

#2397 `DispatchTimeInterval`: fixed Xcode 14.3 compilation
  Sources/FoundationExtensions/DispatchTimeInterval+Extensions.swift
Labels: fix

#2399 `Xcode 14.3`: fixed compilation errors
  Tests/StoreKitUnitTests/BeginRefundRequestHelperTests.swift
  Tests/StoreKitUnitTests/ManageSubscriptionsHelperTests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/StoreKitUnitTests/StoreKit2TransactionListenerTests.swift
  Tests/StoreKitUnitTests/TestHelpers/StoreKitConfigTestCase+Extensions.swift
  Tests/UnitTests/FoundationExtensions/ArrayExtensionsTests.swift
  Tests/UnitTests/FoundationExtensions/DictionaryExtensionsTests.swift
  Tests/UnitTests/Identity/CustomerInfoManagerTests.swift
  Tests/UnitTests/Identity/IdentityManagerTests.swift
  Tests/UnitTests/Misc/AnyEncodableTests.swift
  Tests/UnitTests/Misc/CustomerInfo+TestExtensions.swift
  Tests/UnitTests/Misc/PurchasesDiagnosticsTests.swift
  Tests/UnitTests/Networking/Backend/BackendGetCustomerInfoTests.swift
  Tests/UnitTests/Networking/Backend/BackendGetOfferingsTests.swift
  Tests/UnitTests/Networking/Backend/BackendLoginTests.swift
  Tests/UnitTests/Networking/Backend/BackendOfflineEntitlementsTests.swift
  Tests/UnitTests/Networking/Backend/BackendPostOfferForSigningTests.swift
  Tests/UnitTests/Networking/Backend/BackendPostReceiptDataTests.swift
  Tests/UnitTests/Networking/Backend/BaseBackendTest.swift
  Tests/UnitTests/Purchasing/CustomerInfoTests.swift
  Tests/UnitTests/Purchasing/EntitlementInfosTests.swift
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesGetCustomerInfoTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesLogInTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesRestoreTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesSyncPurchasesTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesTransactionHandlingTests.swift
  Tests/UnitTests/Purchasing/TransactionsFactoryTests.swift
  Tests/UnitTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift
  Tests/UnitTests/SubscriberAttributes/DeviceCacheSubscriberAttributesTests.swift
  Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Labels: fix

#2398 `CircleCI`: use `Xcode 14.3.0`
  .circleci/config.yml
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCat.xcodeproj/xcshareddata/xcschemes/BackendIntegrationTests.xcscheme
  RevenueCat.xcodeproj/xcshareddata/xcschemes/ReceiptParser.xcscheme
  RevenueCat.xcodeproj/xcshareddata/xcschemes/RevenueCat.xcscheme
  Tests/APITesters/ObjCAPITester/ObjCAPITester.xcodeproj/project.pbxproj
  Tests/APITesters/ObjCAPITester/ObjCAPITester.xcodeproj/xcshareddata/xcschemes/ObjCAPITester.xcscheme
  Tests/APITesters/ReceiptParserAPITester/ReceiptParserAPITester.xcodeproj/project.pbxproj
  Tests/APITesters/ReceiptParserAPITester/ReceiptParserAPITester.xcodeproj/xcshareddata/xcschemes/ReceiptParserAPITester.xcscheme
  Tests/APITesters/SwiftAPITester/SwiftAPITester.xcodeproj/project.pbxproj
  Tests/APITesters/SwiftAPITester/SwiftAPITester.xcodeproj/xcshareddata/xcschemes/SwiftAPITester.xcscheme
  Tests/v3LoadShedderIntegration/v3LoadShedderIntegration.xcodeproj/xcshareddata/xcschemes/v3LoadShedderIntegration.xcscheme
Labels: ci

#2402 clean up v3 load shedder integration tests
  .swiftlint.yml
  Tests/v3LoadShedderIntegration/v3LoadShedderIntegrationTests/V3LoadShedderIntegrationTests.swift
Labels: test

#2407 Fix deadlock when sending notification center in customerInfoListener
  Sources/Caching/DeviceCache.swift
  Sources/Logging/Strings/PurchaseStrings.swift
  Tests/UnitTests/Caching/DeviceCacheTests.swift
Labels: fix

#2373 `ETagManager`/`HTTPClient`: sending new `X-RC-Last-Refresh-Time` header
  Sources/Networking/HTTPClient/ETagManager.swift
  Sources/Networking/HTTPClient/HTTPClient.swift
  Tests/UnitTests/Mocks/MockETagManager.swift
  Tests/UnitTests/Networking/ETagManagerTests.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
Labels: refactor

#2412 `CustomerInfoManager`: fixed deadlock caused by reading `CustomerInfo` inside of observer
  Sources/Identity/CustomerInfoManager.swift
  Sources/Misc/Concurrency/OperationDispatcher.swift
  Tests/UnitTests/Identity/CustomerInfoManagerTests.swift
  Tests/UnitTests/Mocks/MockOperationDispatcher.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesDelegateTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesLogInTests.swift
Labels: fix

#2417 `PurchaseTester`: fixed compilation for `internal` entitlement verification
  Tests/TestingApps/PurchaseTesterSwiftUI/Core/ConfiguredPurchases.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Extensions/Extensions.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/PurchaseTesterApp.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/ConfigurationView.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Customer/CustomerInfoView.swift
Labels: test

#2420 `Integration Tests`: fixed flaky errors when loading offerings
  Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
Labels: test

#2418 `StoreKit1Wrapper`: added debug log when transaction is removed but no callbacks to notify
  Sources/Logging/Strings/PurchaseStrings.swift
  Sources/Purchasing/StoreKit1/StoreKit1Wrapper.swift
Labels: refactor

#2423 `StoreKit1Wrapper`: added log when adding payment to queue
  Sources/Logging/Strings/PurchaseStrings.swift
  Sources/Purchasing/StoreKit1/StoreKit1Wrapper.swift
Labels: test

#2427 `customEntitlementComputation`: new `X-Custom-Entitlement-Computation` header
  Sources/Networking/HTTPClient/HTTPClient.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
Labels: test

#2426 `BackendPostReceiptDataTests`: increased timeout to fix flaky test
  Tests/UnitTests/Networking/Backend/BackendPostReceiptDataTests.swift
Labels: test

#2435 remove unnecessary line break
  Sources/Purchasing/Purchases/Purchases.swift
Labels: refactor

#2434 clarify reasoning for disfavoredOverload in logIn
  Sources/Purchasing/Purchases/Purchases.swift
Labels: docs

#2428 `customEntitlementComputation` part 3: tests
  Sources/Logging/Strings/ConfigureStrings.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
Labels: test

#2429 customEntitlementsComputation part 4: create convenience configuration method
  Sources/DocCDocumentation/DocCDocumentation.docc/Purchases.md
  Sources/DocCDocumentation/DocCDocumentation.docc/RevenueCat.md
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
Labels: feat

#2431 customEntitlementsMode: Sample app
  Examples/testCustomEntitlementsComputation/README.md
  Examples/testCustomEntitlementsComputation/Sample screenshot.png
  Examples/testCustomEntitlementsComputation/testCustomEntitlementsComputation.xcodeproj/project.pbxproj
  Examples/testCustomEntitlementsComputation/testCustomEntitlementsComputation.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Examples/testCustomEntitlementsComputation/testCustomEntitlementsComputation.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Examples/testCustomEntitlementsComputation/testCustomEntitlementsComputation/Assets.xcassets/AccentColor.colorset/Contents.json
  Examples/testCustomEntitlementsComputation/testCustomEntitlementsComputation/Assets.xcassets/AppIcon.appiconset/Contents.json
  Examples/testCustomEntitlementsComputation/testCustomEntitlementsComputation/Assets.xcassets/Contents.json
  Examples/testCustomEntitlementsComputation/testCustomEntitlementsComputation/Constants.swift
  Examples/testCustomEntitlementsComputation/testCustomEntitlementsComputation/ContentView.swift
  Examples/testCustomEntitlementsComputation/testCustomEntitlementsComputation/Preview Content/Preview Assets.xcassets/Contents.json
  Examples/testCustomEntitlementsComputation/testCustomEntitlementsComputation/testCustomEntitlementsComputationApp.swift
Labels: test

#2430 `PurchaseOrchestrator`: fix incorrect `InitiationSource` for SK1 queue transactions
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesTransactionHandlingTests.swift
Labels: fix

#2437 `customEntitlementsComputation`: new method to switch users
  Examples/testCustomEntitlementsComputation/testCustomEntitlementsComputation/ContentView.swift
  Sources/Identity/IdentityManager.swift
  Sources/Logging/Strings/ConfigureStrings.swift
  Sources/Logging/Strings/IdentityStrings.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
  Tests/UnitTests/Identity/IdentityManagerTests.swift
  Tests/UnitTests/Mocks/MockBackend.swift
  Tests/UnitTests/Mocks/MockIdentityManager.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesLogInTests.swift
Labels: feat

#2436 `customEntitlementsComputation`: disable automatic sync of `attConsentStatus`
  Sources/Networking/Backend.swift
  Sources/Networking/BackendConfiguration.swift
  Sources/Networking/CustomerAPI.swift
  Sources/SubscriberAttributes/SubscriberAttribute.swift
  Tests/UnitTests/Mocks/MockBackend.swift
  Tests/UnitTests/Mocks/MockIdentityAPI.swift
  Tests/UnitTests/Networking/Backend/BackendPostReceiptDataTests.swift
  Tests/UnitTests/Networking/Backend/BaseBackendTest.swift
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS12-testDoesNotPostConsentStatus.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS13-testDoesNotPostConsentStatus.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS14-testDoesNotPostConsentStatus.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS15-testDoesNotPostConsentStatus.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS16-testDoesNotPostConsentStatus.1.json
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift
Labels: perf

#2440 Create separate `SPM` library to enable custom entitlement computation
  .circleci/config.yml
  CustomEntitlementComputation
  Examples/testCustomEntitlementsComputation/testCustomEntitlementsComputation.xcodeproj/project.pbxproj
  Examples/testCustomEntitlementsComputation/testCustomEntitlementsComputation/ContentView.swift
  Package.swift
  RevenueCat.xcodeproj/project.pbxproj
  Sources/DocCDocumentation/DocCDocumentation.docc/Purchases.md
  Sources/DocCDocumentation/DocCDocumentation.docc/RevenueCat.md
  Sources/Logging/Logger.swift
  Sources/Misc/Concurrency/Purchases+async.swift
  Sources/Misc/DangerousSettings.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/StoreKit2/SK2BeginRefundRequestHelper.swift
  Sources/Support/FrameworkDisambiguation.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester/ConfigurationAPI.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
  Tests/InstallationTests/SPMCustomEntitlementComputationInstallation/Info.plist
  Tests/InstallationTests/SPMCustomEntitlementComputationInstallation/InstallationTests.swift
  Tests/InstallationTests/SPMCustomEntitlementComputationInstallation/SPMInstallation.entitlements
  Tests/InstallationTests/SPMCustomEntitlementComputationInstallation/SPMInstallation.xcodeproj/project.pbxproj
  Tests/InstallationTests/SPMCustomEntitlementComputationInstallation/SPMInstallation.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Tests/InstallationTests/SPMCustomEntitlementComputationInstallation/SPMInstallation.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Tests/InstallationTests/SPMCustomEntitlementComputationInstallation/SPMInstallation.xcodeproj/xcshareddata/xcschemes/SPMIntegration.xcscheme
  Tests/InstallationTests/SPMCustomEntitlementComputationInstallation/fastlane/Fastfile
  Tests/InstallationTests/SPMCustomEntitlementComputationInstallation/fastlane/Matchfile
  Tests/InstallationTests/SPMCustomEntitlementComputationInstallation/fastlane/README.md
  Tests/InstallationTests/SPMCustomEntitlementComputationInstallation/fastlane/Scanfile
  Tests/UnitTests/Purchasing/Purchases/PurchasesLogInTests.swift
  fastlane/Fastfile
Labels: feat

#2432 Fixed docs
  Sources/Purchasing/Purchases/PurchasesType.swift
Labels: docs

#2443 `customEntitlementsComputation`: update the copy in the sample app to explain the new usage
  Examples/testCustomEntitlementsComputation/README.md
  Examples/testCustomEntitlementsComputation/testCustomEntitlementsComputation/ContentView.swift
Labels: docs

#2448 Hide promotional offers APIs in custom entitlements computation package
  Sources/Misc/Concurrency/Purchases+async.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesType.swift
Labels: refactor

#2449 Custom Entitlement Computation: avoid `getCustomerInfo` requests for cancelled purchases
  Examples/testCustomEntitlementsComputation/testCustomEntitlementsComputation/ContentView.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift
Labels: perf

#2446 CustomEntitlementsComputation sample app: fix resubscribes to customerInfoStream
  Examples/testCustomEntitlementsComputation/testCustomEntitlementsComputation/ContentView.swift
Labels: test

#2442 Custom Entitlement Computation: disabled unnecessary APIs
  Examples/testCustomEntitlementsComputation/testCustomEntitlementsComputation/ContentView.swift
  Sources/Logging/Strings/ConfigureStrings.swift
  Sources/Misc/Concurrency/Purchases+async.swift
  Sources/Misc/Deprecations.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesType.swift
  Sources/Purchasing/StoreKitAbstractions/StoreProduct.swift
  Sources/Support/PurchasesDiagnostics.swift
  Tests/InstallationTests/SPMCustomEntitlementComputationInstallation/InstallationTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesLogInTests.swift
Labels: refactor

#2451 Custom Entitlement Computation: re-enable `syncPurchases`/`restorePurchases`
  Sources/Misc/Concurrency/Purchases+async.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesType.swift
Labels: refactor

#2455 Update offerings cache when switchUser(to:) is called
  Sources/Identity/IdentityManager.swift
  Sources/Logging/Strings/IdentityStrings.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesLogInTests.swift
Labels: perf
