Repository RevenueCat/purchases-ios, pull requests merged in 2023-05, with the labels that each got.

#2460 Clean up: moved `ReceiptParserTests-Info.plist` out of root
  RevenueCat.xcodeproj/project.pbxproj
  Tests/ReceiptParserTests/ReceiptParserTests-Info.plist
Labels: refactor

#2464 `Integration Tests`: removed `@preconcurrency import`
  Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift
Labels: test, refactor

#2458 Add message indicating tag doesn't exist
  fastlane/Fastfile
Labels: ci

#2462 Add `StoreProduct.pricePerYear`
  Sources/Purchasing/StoreKitAbstractions/StoreProduct.swift
  Sources/Purchasing/StoreKitAbstractions/SubscriptionPeriod.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCStoreProductAPI.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester/StoreProductAPI.swift
  Tests/UnitTests/Purchasing/StoreKitAbstractions/SubscriptionPeriodTests.swift
Labels: feat

#2463 `Integration Tests`: add `MainThreadMonitor` to ensure main thread is not blocked
  RevenueCat.xcodeproj/project.pbxproj
  Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
  Tests/BackendIntegrationTests/MainThreadMonitor.swift
Labels: test

#2472 Generate snapshots on CI
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCat.xcodeproj/xcshareddata/xcschemes/RevenueCat.xcscheme
  Tests/TestPlans/CI-Snapshots.xctestplan
  Tests/UnitTests/Misc/TestCase.swift
  fastlane/Fastfile
  fastlane/README.md
Labels: ci

#2488 `CarthageInstallation`: removed workaround
  .circleci/config.yml
  Tests/InstallationTests/CarthageInstallation/carthage.sh
Labels: ci

#2487 `HTTPClient`: log actual response status code
  Sources/Networking/HTTPClient/HTTPClient.swift
  Sources/Networking/HTTPClient/HTTPStatusCode.swift
Labels: test

#2489 `CocoapodsInstallation`: fixed `Xcode 14.3.0` issue
  .circleci/config.yml
  Tests/InstallationTests/CocoapodsInstallation/Gemfile
  Tests/InstallationTests/CocoapodsInstallation/Gemfile.lock
Labels: ci

#2494 `DeviceCache`: refactored cache keys
  Sources/Caching/DeviceCache.swift
Labels: refactor

#2490 `ETagManager`: don't send validation time if not present
  Sources/Networking/HTTPClient/ETagManager.swift
  Tests/UnitTests/Networking/ETagManagerTests.swift
Labels: fix

#2497 Tests: grouped all `Matcher`s into one file
  RevenueCat.xcodeproj/project.pbxproj
  Tests/StoreKitUnitTests/LocalReceiptParserStoreKitTests.swift
  Tests/StoreKitUnitTests/OfflineEntitlements/CustomerInfoOfflineEntitlementsStoreKitTest.swift
  Tests/UnitTests/Caching/DeviceCacheTests.swift
  Tests/UnitTests/FoundationExtensions/DecoderExtensionTests.swift
  Tests/UnitTests/Networking/ETagManagerTests.swift
  Tests/UnitTests/TestHelpers/Matchers.swift
Labels: test

#2378 `CustomerInfoManager`: don't cache offline `CustomerInfo`
  Sources/Identity/CustomerInfoManager.swift
  Sources/Logging/Strings/CustomerInfoStrings.swift
  Sources/OfflineEntitlements/CustomerInfo+OfflineEntitlements.swift
  Tests/StoreKitUnitTests/OfflineEntitlements/CustomerInfoOfflineEntitlementsStoreKitTest.swift
  Tests/UnitTests/Identity/CustomerInfoManagerTests.swift
Labels: refactor

#2495 `OfferingsManager`: return `Offerings` from new disk cache when server is down
  Sources/Caching/DeviceCache.swift
  Sources/Logging/Strings/OfferingStrings.swift
  Sources/Networking/Responses/OfferingsResponse.swift
  Sources/Purchasing/Offerings.swift
  Sources/Purchasing/OfferingsFactory.swift
  Sources/Purchasing/OfferingsManager.swift
  Tests/UnitTests/Caching/DeviceCacheTests.swift
  Tests/UnitTests/Misc/PurchasesDiagnosticsTests.swift
  Tests/UnitTests/Mocks/MockDeviceCache.swift
  Tests/UnitTests/Mocks/MockOfferingsFactory.swift
  Tests/UnitTests/Mocks/MockProductsManager.swift
  Tests/UnitTests/Networking/NetworkErrorTests.swift
  Tests/UnitTests/Networking/Responses/OfferingsDecodingTests.swift
  Tests/UnitTests/Purchasing/OfferingsManagerTests.swift
Labels: fix

#2499 `Integration Tests`: added snapshot test for `OfferingsResponse`
  RevenueCat.xcodeproj/project.pbxproj
  Tests/BackendIntegrationTests/LoadShedderIntegrationTests.swift
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
  Tests/BackendIntegrationTests/__Snapshots__/LoadShedderIntegrationTests/testCanGetOfferings.1.json
  Tests/BackendIntegrationTests/__Snapshots__/StoreKitIntegrationTests/testCanGetOfferings.1.json
Labels: test

#2505 `Xcode`: fixed `.storekit` file references in schemes
  RevenueCat.xcodeproj/xcshareddata/xcschemes/BackendIntegrationTests.xcscheme
  Tests/v3LoadShedderIntegration/v3LoadShedderIntegration.xcodeproj/xcshareddata/xcschemes/v3LoadShedderIntegration.xcscheme
Labels: build

#2368 `Offline Entitlements`: use offline-computed `CustomerInfo` when server is down
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Caching/DeviceCache.swift
  Sources/Error Handling/BackendError.swift
  Sources/Identity/CustomerInfoManager.swift
  Sources/Logging/Strings/CustomerInfoStrings.swift
  Sources/Logging/Strings/OfflineEntitlementsStrings.swift
  Sources/Logging/Strings/Strings.swift
  Sources/Networking/Backend.swift
  Sources/Networking/BackendConfiguration.swift
  Sources/Networking/CustomerAPI.swift
  Sources/Networking/Operations/GetCustomerInfoOperation.swift
  Sources/Networking/Operations/Handling/CustomerInfoResponseHandler.swift
  Sources/Networking/Operations/PostReceiptDataOperation.swift
  Sources/OfflineEntitlements/CustomerInfo+OfflineEntitlements.swift
  Sources/OfflineEntitlements/OfflineCustomerInfoCreator.swift
  Sources/OfflineEntitlements/OfflineEntitlementsManager.swift
  Sources/OfflineEntitlements/ProductEntitlementMappingFetcher.swift
  Sources/OfflineEntitlements/PurchasedProductsFetcher.swift
  Sources/OfflineEntitlements/PurchasedSK2Product.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Tests/StoreKitUnitTests/BeginRefundRequestHelperTests.swift
  Tests/StoreKitUnitTests/ManageSubscriptionsHelperTests.swift
  Tests/StoreKitUnitTests/OfflineEntitlements/CustomerInfoOfflineEntitlementsStoreKitTest.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/UnitTests/Identity/CustomerInfoManagerTests.swift
  Tests/UnitTests/Identity/IdentityManagerTests.swift
  Tests/UnitTests/Mocks/MockBackend.swift
  Tests/UnitTests/Mocks/MockBackendConfiguration.swift
  Tests/UnitTests/Mocks/MockDeviceCache.swift
  Tests/UnitTests/Mocks/MockIdentityAPI.swift
  Tests/UnitTests/Mocks/MockIdentityManager.swift
  Tests/UnitTests/Mocks/MockOfflineCustomerInfoCreator.swift
  Tests/UnitTests/Mocks/MockOfflineEntitlementsAPI.swift
  Tests/UnitTests/Mocks/MockOfflineEntitlementsManager.swift
  Tests/UnitTests/Mocks/MockProductEntitlementMappingFetcher.swift
  Tests/UnitTests/Mocks/MockPurchasedProductsFetcher.swift
  Tests/UnitTests/Networking/Backend/BaseBackendTest.swift
  Tests/UnitTests/OfflineEntitlements/CustomerInfoResponseHandlerTests.swift
  Tests/UnitTests/OfflineEntitlements/OfflineEntitlementsManagerTests.swift
  Tests/UnitTests/Purchasing/CustomerInfoTests.swift
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift
  Tests/UnitTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift
  Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Labels: fix

#2511 Update fastlane-plugin-revenuecat_internal
  Gemfile.lock
Labels: ci

#2501 `Offline Entitlements`: integration tests
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Logging/Strings/NetworkStrings.swift
  Sources/Misc/DangerousSettings.swift
  Sources/Misc/SystemInfo.swift
  Sources/Networking/HTTPClient/HTTPClient.swift
  Sources/Purchasing/StoreKit1/StoreKit1Wrapper.swift
  Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
  Tests/BackendIntegrationTests/OfflineStoreKitIntegrationTests.swift
  Tests/BackendIntegrationTests/StoreKitObserverModeIntegrationTests.swift
  Tests/StoreKitUnitTests/OfferingsManagerStoreKitTests.swift
  Tests/StoreKitUnitTests/PriceFormatterProviderTests.swift
  Tests/StoreKitUnitTests/ProductsManagerTests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/StoreKitUnitTests/StoreProductTests.swift
  Tests/StoreKitUnitTests/TestHelpers/StoreKitConfigTestCase+Extensions.swift
  Tests/UnitTests/Mocks/MockOfflineEntitlementsManager.swift
  Tests/UnitTests/Mocks/MockSystemInfo.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
  Tests/UnitTests/TestHelpers/AsyncTestHelpers.swift
  Tests/UnitTests/TestHelpers/TestLogHandler.swift
Labels: test

#2504 `Offline Entitlements`: allow creating offline `CustomerInfo` with empty `ProductEntitlementMapping`
  Sources/OfflineEntitlements/OfflineCustomerInfoCreator.swift
  Tests/StoreKitUnitTests/OfflineEntitlements/CustomerInfoOfflineEntitlementsStoreKitTest.swift
  Tests/UnitTests/OfflineEntitlements/CustomerInfoResponseHandlerTests.swift
Labels: refactor

#2506 `PurchasedProductsFetcher`: don't throw errors if purchased products were found
  Sources/OfflineEntitlements/PurchasedProductsFetcher.swift
  Tests/StoreKitUnitTests/OfflineEntitlements/PurchasedProductsFetcherTests.swift
Labels: refactor

#2496 Performance: new check to ensure serialization / deserialization is done from background thread
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Error Handling/Assertions.swift
  Sources/Networking/HTTPClient/HTTPClient.swift
  Sources/Networking/Operations/NetworkOperation.swift
Labels: perf

#2514 `Offline Entitlements`: fixed iOS 12 tests
  Tests/UnitTests/Purchasing/CustomerInfoTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift
Labels: test

#2509 `Offline Entitlements`: disable for custom entitlements mode
  Sources/Logging/Strings/OfflineEntitlementsStrings.swift
  Sources/OfflineEntitlements/OfflineEntitlementsManager.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/UnitTests/Mocks/MockOfflineEntitlementsManager.swift
  Tests/UnitTests/Mocks/MockSystemInfo.swift
  Tests/UnitTests/OfflineEntitlements/OfflineEntitlementsManagerTests.swift
Labels: refactor

#2517 `MainThreadMonitor`: fixed flakiness in CI
  Tests/BackendIntegrationTests/MainThreadMonitor.swift
Labels: test

#2507 `PurchasedProductsFetcher`: cache current entitlements
  Sources/FoundationExtensions/DispatchTimeInterval+Extensions.swift
  Sources/Logging/Strings/OfflineEntitlementsStrings.swift
  Sources/OfflineEntitlements/OfflineCustomerInfoCreator.swift
  Sources/OfflineEntitlements/PurchasedProductsFetcher.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/StoreKitUnitTests/OfflineEntitlements/PurchasedProductsFetcherTests.swift
  Tests/UnitTests/FoundationExtensions/DispatchTimeIntervalExtensionsTests.swift
  Tests/UnitTests/Mocks/MockPurchasedProductsFetcher.swift
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesLogInTests.swift
  Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Labels: perf

#2516 `PurchaseTesterSwiftUI`: fixed macOS UI
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift
Labels: test

#2519 `PurchaseTesterSwiftUI`: added visual feedback for purchase success/failure
  Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/project.pbxproj
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Helpers/LocalizedAlertError.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Offerings/OfferingDetailView.swift
Labels: test

#2518 `PurchaseTesterSwiftUI`: added new window on Mac to manage proxy
  Tests/TestingApps/PurchaseTesterSwiftUI/Core/ConfiguredPurchases.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/project.pbxproj
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Proxy/ProxyManager.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Proxy/ProxyView.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Proxy/ProxyViewModel.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/PurchaseTesterApp.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Windows.swift
Labels: test

#2521 `PurchasedProductsFetcher`: removed `AppStore.sync` call
  Sources/OfflineEntitlements/PurchasedProductsFetcher.swift
  Tests/StoreKitUnitTests/OfflineEntitlements/PurchasedProductsFetcherTests.swift
Labels: refactor

#2485 `SK2StoreProduct`: simplify `currencyCode` extraction
  Sources/Purchasing/StoreKitAbstractions/SK1StoreProduct.swift
  Sources/Purchasing/StoreKitAbstractions/SK2StoreProduct.swift
Labels: refactor

#2530 `CircleCI`: save test archive on `loadshedder-integration-tests`
  .circleci/config.yml
Labels: ci

#2531 `PurchaseTesterSwiftUI`: added `ProxyView` to `iOS`
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Proxy/ProxyManager.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Proxy/ProxyView.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Proxy/ProxyViewModel.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/PurchaseTesterApp.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift
Labels: test

#2534 `BasePurchasesTests`: fixed leak detection
  Sources/Logging/Strings/PurchaseStrings.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
Labels: test

#2529 `HTTPClient`: don't assume error responses are JSON
  Sources/Networking/HTTPClient/HTTPClient.swift
  Sources/Networking/HTTPClient/HTTPResponse.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
  Tests/UnitTests/TestHelpers/TestLogHandler.swift
Labels: fix

#2498 `Offering` metadata
  Sources/Networking/Responses/OfferingsResponse.swift
  Sources/Purchasing/Offering.swift
  Sources/Purchasing/OfferingsFactory.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCOfferingAPI.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester/OfferingAPI.swift
  Tests/BackendIntegrationTests/__Snapshots__/LoadShedderIntegrationTests/testCanGetOfferings.1.json
  Tests/BackendIntegrationTests/__Snapshots__/StoreKitIntegrationTests/testCanGetOfferings.1.json
  Tests/UnitTests/Mocks/MockOfferingsFactory.swift
  Tests/UnitTests/Networking/Responses/Fixtures/Offerings.json
  Tests/UnitTests/Networking/Responses/OfferingsDecodingTests.swift
  Tests/UnitTests/Purchasing/OfferingsManagerTests.swift
  Tests/UnitTests/Purchasing/OfferingsTests.swift
Labels: feat

#2520 `OfflineEntitlementsManager`: disable offline `CustomerInfo` in observer mode
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Logging/Strings/OfflineEntitlementsStrings.swift
  Sources/Networking/Backend.swift
  Sources/OfflineEntitlements/OfflineCustomerInfoCreator.swift
  Sources/OfflineEntitlements/OfflineEntitlementsManager.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/UnitTests/OfflineEntitlements/OfflineCustomerInfoCreatorTests.swift
  Tests/UnitTests/OfflineEntitlements/OfflineEntitlementsManagerTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
Labels: refactor

#2522 `Offline Entitlements`: don't compute offline `CustomerInfo` when purchasing a consumable products
  Sources/Logging/Strings/OfflineEntitlementsStrings.swift
  Sources/OfflineEntitlements/PurchasedProductsFetcher.swift
  Tests/BackendIntegrationTests/OfflineStoreKitIntegrationTests.swift
  Tests/UnitTests/Mocks/MockOfflineCustomerInfoCreator.swift
  Tests/UnitTests/Networking/Backend/BackendPostReceiptDataTests.swift
  Tests/UnitTests/Networking/Backend/BaseBackendTest.swift
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS12-testPostingReceiptCreatesACustomerInfoObject.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS13-testPostingReceiptCreatesACustomerInfoObject.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS14-testPostingReceiptCreatesACustomerInfoObject.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS15-testPostingReceiptCreatesACustomerInfoObject.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS15-testPostingReceiptForSubscriptionAndServerErrorComputesOfflineUser.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS15-testPostingReceiptWithNoProductDataAndServerErrorComputesOfflineUser.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS16-testPostingReceiptCreatesACustomerInfoObject.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS16-testPostingReceiptForSubscriptionAndServerErrorComputesOfflineUser.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS16-testPostingReceiptWithNoProductDataAndServerErrorComputesOfflineUser.1.json
Labels: refactor

#2538 Extracted and tested `AsyncSequence.extractValues`
  Sources/FoundationExtensions/AsyncExtensions.swift
  Tests/UnitTests/FoundationExtensions/AsyncExtensionsTests.swift
  Tests/UnitTests/Mocks/MockAsyncSequence.swift
  Tests/UnitTests/TestHelpers/AsyncTestHelpers.swift
Labels: test

#2545 Fix doc on getMetadataValue
  Sources/Purchasing/Offering.swift
Labels: docs

#2546 Fix load shedder integration tests
  Tests/BackendIntegrationTests/__Snapshots__/LoadShedderIntegrationTests/testCanGetOfferings.1.json
Labels: test

#2539 Created `StoreKit2TransactionFetcher`
  RevenueCat.xcodeproj/project.pbxproj
  Sources/OfflineEntitlements/PurchasedProductsFetcher.swift
  Sources/Purchasing/StoreKit2/StoreKit2TransactionFetcher.swift
  Tests/StoreKitUnitTests/StoreKit2/StoreKit2CachingProductsManagerTests.swift
  Tests/StoreKitUnitTests/StoreKit2/StoreKit2StorefrontListenerTests.swift
  Tests/StoreKitUnitTests/StoreKit2/StoreKit2TransactionFetcherTests.swift
  Tests/StoreKitUnitTests/StoreKit2/StoreKit2TransactionListenerTests.swift
  Tests/StoreKitUnitTests/TestHelpers/StoreKitConfigTestCase+Extensions.swift
  Tests/StoreKitUnitTests/TestHelpers/StoreKitTestHelpers.swift
Labels: refactor

#2547 `CircleCI`: specify device to run `backend_integration_tests`
  .circleci/config.yml
Labels: ci

#2528 `DefaultDecodable`: moved to `Misc/Codable/DefaultDecodable.swift`
  RevenueCat.xcodeproj/project.pbxproj
  Sources/FoundationExtensions/Decoder+Extensions.swift
  Sources/FoundationExtensions/JSONDecoder+Extensions.swift
  Sources/Misc/Codable/DefaultDecodable.swift
Labels: refactor

#2549 `PostReceiptOperation`: added ability to also post `AdServices` token
  Sources/Attribution/AttributionPoster.swift
  Sources/Logging/Strings/AttributionStrings.swift
  Sources/Networking/Backend.swift
  Sources/Networking/CustomerAPI.swift
  Sources/Networking/Operations/PostReceiptDataOperation.swift
  Sources/Purchasing/Purchases/Attribution.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Tests/APITesters/CustomEntitlementComputationSwiftAPITester/CustomEntitlementComputationSwiftAPITester.xcodeproj/project.pbxproj
  Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/AttributionAPI.swift
  Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/PurchasesAPI.swift
  Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/main.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/StoreKitUnitTests/TestHelpers/AvailabilityChecks.swift
  Tests/UnitTests/Attribution/AttributionPosterTests.swift
  Tests/UnitTests/Mocks/MockBackend.swift
  Tests/UnitTests/Mocks/MockSystemInfo.swift
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift
  Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
  Tests/UnitTests/SubscriberAttributes/SubscriberAttributesManagerTests.swift
  Tests/UnitTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/iOS16-testPostReceiptWithAdServicesToken.1.json
Labels: refactor

#2548 `AttributionPoster`: replaced hardcoded strings with constants
  Sources/Attribution/AttributionPoster.swift
Labels: refactor

#2551 `enableAdServicesAttributionTokenCollection`: added integration test
  Sources/Attribution/AttributionFetcher.swift
  Sources/FoundationExtensions/ProcessInfo+Extensions.swift
  Sources/Logging/Strings/AttributionStrings.swift
  Tests/BackendIntegrationTests/OtherIntegrationTests.swift
  Tests/TestPlans/BackendIntegrationTests.xctestplan
  Tests/TestPlans/CI-BackendIntegration.xctestplan
Labels: test

#2540 Extracted `TransactionPoster` from `PurchasesOrchestrator`
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Misc/Concurrency/OperationDispatcher.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/Purchases/TransactionPoster.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Labels: refactor

#2541 `Backend.ResponseHandler` is now `@Sendable`
  Sources/Networking/Backend.swift
  Tests/UnitTests/Networking/Backend/BackendGetCustomerInfoTests.swift
  Tests/UnitTests/Networking/Backend/BackendGetOfferingsTests.swift
  Tests/UnitTests/Networking/Backend/BackendPostReceiptDataTests.swift
  Tests/UnitTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift
  Tests/UnitTests/TestHelpers/AsyncTestHelpers.swift
Labels: refactor

#2554 Release notes for `4.19.1`
  CHANGELOG.md
Labels: docs

#2556 `StoreTransaction`: implemented `description`
  Sources/Purchasing/StoreKitAbstractions/StoreTransaction.swift
Labels: refactor

#2533 `GetCustomerInfo` posts receipts if there are pending transactions
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Identity/CustomerInfoManager.swift
  Sources/Logging/Strings/CustomerInfoStrings.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/StoreKit2/StoreKit2TransactionFetcher.swift
  Tests/BackendIntegrationTests/OfflineStoreKitIntegrationTests.swift
  Tests/StoreKitUnitTests/BeginRefundRequestHelperTests.swift
  Tests/StoreKitUnitTests/ManageSubscriptionsHelperTests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/UnitTests/Identity/CustomerInfoManagerPostReceiptTests.swift
  Tests/UnitTests/Identity/CustomerInfoManagerTests.swift
  Tests/UnitTests/Identity/IdentityManagerTests.swift
  Tests/UnitTests/Mocks/MockIdentityManager.swift
  Tests/UnitTests/Mocks/MockStoreKit2TransactionFetcher.swift
  Tests/UnitTests/Mocks/MockTransactionPoster.swift
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesDeferredPurchasesTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesGetCustomerInfoTests.swift
  Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
  Tests/UnitTests/TestHelpers/TestLogHandler.swift
Labels: fix

#2565 `SK2StoreProduct`: fix crash on iOS 12
  Sources/Misc/Box.swift
  Sources/Purchasing/StoreKitAbstractions/SK2StoreProduct.swift
Labels: fix

#2557 Added `TransactionPoster` tests
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Purchasing/Purchases/TransactionPoster.swift
  Tests/UnitTests/Identity/CustomerInfoManagerPostReceiptTests.swift
  Tests/UnitTests/Mocks/MockTransactionPoster.swift
  Tests/UnitTests/Purchasing/Purchases/TransactionPosterTests.swift
Labels: test

#2562 `Offline Entitlements`: improved computation log
  Sources/Logging/Strings/CustomerInfoStrings.swift
Labels: refactor

#2564 `AppleReceipt.debugDescription`: don't pretty-print JSON
  Sources/LocalReceiptParsing/BasicTypes/AppleReceipt.swift
  Sources/LocalReceiptParsing/DataConverters/Codable+Extensions.swift
  Sources/Networking/HTTPClient/HTTPClient.swift
  Tests/UnitTests/Caching/DeviceCacheTests.swift
  Tests/UnitTests/Identity/CustomerInfoManagerTests.swift
  Tests/UnitTests/Misc/CustomerInfo+TestExtensions.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
  Tests/UnitTests/Networking/SignatureVerificationHTTPClientTests.swift
  Tests/UnitTests/Purchasing/OfferingsManagerTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesGetCustomerInfoTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesRestoreTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesSyncPurchasesTests.swift
Labels: fix

#2566 `PostReceiptOperation`: added ability to also post `AdServices` token
  Sources/Attribution/AttributionPoster.swift
  Sources/Logging/Strings/AttributionStrings.swift
  Sources/Networking/Operations/PostReceiptDataOperation.swift
  Sources/Purchasing/Purchases/Attribution.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/Purchases/TransactionPoster.swift
  Tests/APITesters/CustomEntitlementComputationSwiftAPITester/CustomEntitlementComputationSwiftAPITester.xcodeproj/project.pbxproj
  Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/AttributionAPI.swift
  Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/PurchasesAPI.swift
  Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/main.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/StoreKitUnitTests/TestHelpers/AvailabilityChecks.swift
  Tests/UnitTests/Attribution/AttributionPosterTests.swift
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift
  Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
  Tests/UnitTests/SubscriberAttributes/SubscriberAttributesManagerTests.swift
  Tests/UnitTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/iOS16-testPostReceiptWithAdServicesToken.1.json
Labels: refactor

#2563 `CustomerInfoManager`: post all unfinished transactions
  Sources/Identity/CustomerInfoManager.swift
  Sources/Logging/Strings/CustomerInfoStrings.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/Purchases/TransactionPoster.swift
  Tests/BackendIntegrationTests/OfflineStoreKitIntegrationTests.swift
  Tests/UnitTests/Identity/CustomerInfoManagerPostReceiptTests.swift
  Tests/UnitTests/Mocks/MockTransactionPoster.swift
Labels: refactor
