Repository RevenueCat/purchases-ios, pull requests merged in 2023-03, with the labels that each got.

#2310 Update `CustomerInfo.requestDate` from 304 responses
  Sources/FoundationExtensions/Date+Extensions.swift
  Sources/Identity/CustomerInfo.swift
  Sources/Logging/Strings/CustomerInfoStrings.swift
  Sources/Logging/Strings/SigningStrings.swift
  Sources/Misc/Signing+ResponseVerification.swift
  Sources/Misc/Signing.swift
  Sources/Networking/HTTPClient/ETagManager.swift
  Sources/Networking/HTTPClient/HTTPClient.swift
  Sources/Networking/HTTPClient/HTTPResponse.swift
  Sources/Networking/HTTPClient/HTTPResponseBody.swift
  Sources/Networking/Operations/Handling/CustomerInfoResponseHandler.swift
  Sources/Purchasing/VerificationResult.swift
  Tests/UnitTests/FoundationExtensions/NSDate+RCExtensionsTests.swift
  Tests/UnitTests/Identity/CustomerInfoManagerTests.swift
  Tests/UnitTests/Misc/CustomerInfo+TestExtensions.swift
  Tests/UnitTests/Misc/SigningTests.swift
  Tests/UnitTests/Mocks/MockHTTPClient.swift
  Tests/UnitTests/Networking/Backend/BackendGetCustomerInfoTests.swift
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerInfoTests/iOS12-testUpdatesRequestDateFromResponseHeader.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerInfoTests/iOS13-testUpdatesRequestDateFromResponseHeader.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerInfoTests/iOS14-testUpdatesRequestDateFromResponseHeader.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerInfoTests/iOS15-testUpdatesRequestDateFromResponseHeader.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerInfoTests/iOS16-testUpdatesRequestDateFromResponseHeader.1.json
  Tests/UnitTests/Networking/ETagManagerTests.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
  Tests/UnitTests/Networking/HTTPResponseTests.swift
  Tests/UnitTests/Purchasing/CustomerInfoTests.swift
  Tests/UnitTests/Purchasing/EntitlementInfosTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesGetCustomerInfoTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesRestoreTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesSyncPurchasesTests.swift
Labels: refactor

#2288 `EntitlementInfo`: add a grace period limit to outdated entitlements
  Sources/FoundationExtensions/DispatchTimeInterval+Extensions.swift
  Sources/LocalReceiptParsing/DataConverters/DateFormatter+Extensions.swift
  Sources/Logging/Strings/PurchaseStrings.swift
  Sources/Purchasing/EntitlementInfo.swift
  Tests/UnitTests/Purchasing/CustomerInfoTests.swift
  Tests/UnitTests/Purchasing/EntitlementInfosTests.swift
Labels: refactor

#2321 Renamed `VerificationResult.notVerified` to `.notRequested`
  Sources/Identity/CustomerInfo.swift
  Sources/Misc/Signing+ResponseVerification.swift
  Sources/Purchasing/VerificationResult.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCVerificationResultAPI.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester/VerificationResultAPI.swift
  Tests/UnitTests/Misc/SigningTests.swift
  Tests/UnitTests/Networking/Backend/BackendGetCustomerInfoTests.swift
  Tests/UnitTests/Networking/ETagManagerTests.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
  Tests/UnitTests/Networking/HTTPResponseTests.swift
  Tests/UnitTests/Networking/Responses/CustomerInfoDecodingTests.swift
  Tests/UnitTests/Purchasing/CustomerInfoTests.swift
Labels: refactor

#2320 `CustomerInfo`: removed `entitlementVerification`
  Sources/Identity/CustomerInfo.swift
  Sources/Purchasing/VerificationResult.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCCustomerInfoAPI.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester/CustomerInfoAPI.swift
  Tests/UnitTests/Networking/Backend/BackendGetCustomerInfoTests.swift
  Tests/UnitTests/Networking/Backend/BackendPostReceiptDataTests.swift
  Tests/UnitTests/Networking/Responses/CustomerInfoDecodingTests.swift
  Tests/UnitTests/Purchasing/CustomerInfoTests.swift
Labels: refactor

#2323 replace `iff` with `if and only if`
  Sources/FoundationExtensions/Array+Extensions.swift
  Sources/Misc/StoreKit2Setting.swift
Labels: docs

#2324 Add additional logging on init
  Sources/Logging/Strings/ConfigureStrings.swift
  Sources/Purchasing/Purchases/Purchases.swift
Labels: docs

#2325 `EntitlementInfo`: request date is not optional
  Sources/Purchasing/EntitlementInfo.swift
  Sources/Purchasing/EntitlementInfos.swift
Labels: refactor

#2328 `PurchaseTester`: fixed compilation from verification API changes
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Extensions/Extensions.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Customer/CustomerInfoView.swift
Labels: test

#2322 `HTTPClient`: don't verify 4xx/5xx responses
  Sources/Misc/Signing+ResponseVerification.swift
  Sources/Networking/HTTPClient/HTTPStatusCode.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
  Tests/UnitTests/Networking/HTTPStatusCodeTests.swift
Labels: refactor

#2327 `CustomerInfo`: use same grace period logic for active subscriptions
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Identity/CustomerInfo+ActiveDates.swift
  Sources/Identity/CustomerInfo.swift
  Sources/Purchasing/EntitlementInfo.swift
  Tests/UnitTests/Purchasing/CustomerInfoTests.swift
  Tests/UnitTests/Purchasing/EntitlementInfosTests.swift
Labels: refactor

#2326 Refactor: reorganized files in new Security and Misc folders
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Misc/Codable/AnyDecodable.swift
  Sources/Misc/Codable/AnyEncodable.swift
  Sources/Misc/Codable/IgnoreHashable.swift
  Sources/Misc/Codable/RawDataContainer.swift
  Sources/Misc/Concurrency/Atomic.swift
  Sources/Misc/Concurrency/Lock.swift
  Sources/Misc/Concurrency/OperationDispatcher.swift
  Sources/Misc/Concurrency/Purchases+async.swift
  Sources/Misc/Concurrency/Purchases+nonasync.swift
  Sources/Misc/Concurrency/SynchronizedUserDefaults.swift
  Sources/Misc/DateAndTime/Clock.swift
  Sources/Misc/DateAndTime/DateExtensions.swift
  Sources/Misc/DateAndTime/DateProvider.swift
  Sources/Misc/DateAndTime/ISOPeriodFormatter.swift
  Sources/Misc/DateAndTime/TimingUtil.swift
  Sources/Networking/Caching/CacheFetchPolicy.swift
  Sources/Security/Signing+ResponseVerification.swift
  Sources/Security/Signing.swift
  Sources/Security/VerificationResult.swift
  Tests/UnitTests/Security/SigningTests.swift
Labels: refactor

#2329 Made `Configuration.EntitlementVerificationMode.enforced` unavailable
  Sources/Networking/InternalAPI.swift
  Sources/Purchasing/Configuration.swift
  Sources/Security/Signing.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/ConfigurationAPI.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Extensions/Extensions.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
  Tests/UnitTests/Networking/HTTPRequestTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
Labels: refactor

#2330 `IdentityManager`: clear `ETagManager` and `DeviceCache` if verification is enabled but cached `CustomerInfo` is not
  Sources/Identity/IdentityManager.swift
  Sources/Logging/Strings/IdentityStrings.swift
  Sources/Networking/Backend.swift
  Sources/Networking/HTTPClient/HTTPClient.swift
  Tests/UnitTests/Identity/IdentityManagerTests.swift
  Tests/UnitTests/Mocks/MockBackend.swift
  Tests/UnitTests/Mocks/MockCustomerInfoManager.swift
Labels: refactor

#2331 `ETagManager`: don't ignore failed etags with `Signing.VerificationMode.informational`
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Networking/HTTPClient/ETagManager.swift
  Sources/Networking/HTTPClient/HTTPClient.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Security/Signing.swift
  Tests/UnitTests/Mocks/MockETagManager.swift
  Tests/UnitTests/Networking/Backend/BaseBackendTest.swift
  Tests/UnitTests/Networking/ETagManagerTests.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
  Tests/UnitTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift
Labels: refactor

#2332 `AppleReceipt.mostRecentActiveSubscription`: performance optimization
  Sources/LocalReceiptParsing/BasicTypes/AppleReceipt.swift
Labels: perf

#2334 `Configuration.Builder.with(entitlementVerificationMode:)`: improved documentation
  Sources/Purchasing/Configuration.swift
Labels: docs

#2333 Finished signature verification `HTTPClient` tests
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Security/VerificationResult.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
  Tests/UnitTests/Networking/SignatureVerificationHTTPClientTests.swift
  Tests/UnitTests/Security/SigningTests.swift
Labels: test

#2336 `RELEASING.md`: added GitHub rate limiting parameter
  Contributing/RELEASING.md
Labels: docs

#2337 `VerificationResult.notRequested`: removed caching reference
  Sources/Security/VerificationResult.swift
Labels: docs

#2340 `CI`: also run tests on `watchOS`
  .circleci/config.yml
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCat.xcodeproj/xcshareddata/xcschemes/RevenueCat.xcscheme
  Sources/Purchasing/StoreKitAbstractions/SK1StoreProduct.swift
  Sources/Purchasing/StoreKitAbstractions/StoreProduct.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester/AttributionAPI.swift
  Tests/StoreKitUnitTests/LocalReceiptParserStoreKitTests.swift
  Tests/StoreKitUnitTests/OfferingsManagerStoreKitTests.swift
  Tests/StoreKitUnitTests/PriceFormatterProviderTests.swift
  Tests/StoreKitUnitTests/ProductsManagerTests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/StoreKitUnitTests/StoreKitConfigTestCase.swift
  Tests/StoreKitUnitTests/StoreProductTests.swift
  Tests/StoreKitUnitTests/StoreTransactionTests.swift
  Tests/StoreKitUnitTests/StorefrontTests.swift
  Tests/StoreKitUnitTests/TestHelpers/StoreKitConfigTestCase+Extensions.swift
  Tests/StoreKitUnitTests/TransactionsManagerTests.swift
  Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK1Tests.swift
  Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK2Tests.swift
  Tests/TestPlans/CI-RevenueCat.xctestplan
  Tests/UnitTests/Attribution/AttributionPosterTests.swift
  Tests/UnitTests/Mocks/MockAttributionTypeFactory.swift
  Tests/UnitTests/Mocks/MockStoreKit2TransactionListener.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesAttributionDataTests.swift
  Tests/UnitTests/Purchasing/StoreKit1WrapperTests.swift
  Tests/UnitTests/Purchasing/StoreKitAbstractions/StoreKitWorkaroundsTests.swift
  Tests/UnitTests/StoreKitExtensions/StoreKitErrorTests.swift
  Tests/UnitTests/TestHelpers/OSVersionEquivalent.swift
  Tests/UnitTestsHostApp/AppDelegate.swift
  Tests/UnitTestsHostApp/ViewController.swift
  fastlane/Fastfile
Labels: ci

#2347 `ETagManager`: don't use ETags if response verification failed
  Sources/Networking/HTTPClient/ETagManager.swift
  Sources/Security/VerificationResult.swift
  Tests/UnitTests/Networking/ETagManagerTests.swift
  Tests/UnitTests/Networking/SignatureVerificationHTTPClientTests.swift
Labels: fix

#2348 Version 4.17.9 release notes
  CHANGELOG.latest.md
  CHANGELOG.md
Labels: docs

#2350 `Trusted Entitlements`: changed all APIs to `internal`
  Sources/Purchasing/Configuration.swift
  Sources/Purchasing/EntitlementInfo.swift
  Sources/Purchasing/EntitlementInfos.swift
  Sources/Security/VerificationResult.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCEntitlementInfosAPI.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester/ConfigurationAPI.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/EntitlementInfoAPI.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/EntitlementInfosAPI.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/VerificationResultAPI.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/main.swift
Labels: refactor

#2354 `DeviceCache`: simplified constructor
  Sources/Caching/DeviceCache.swift
  Sources/Caching/InMemoryCachedObject.swift
  Tests/UnitTests/Caching/DeviceCacheTests.swift
  Tests/UnitTests/Caching/InMemoryCachedObjectTests.swift
  Tests/UnitTests/Mocks/MockInMemoryCachedOfferings.swift
Labels: refactor

#2349 `ETagManagerTests`: fixed tests on iOS 12
  Tests/UnitTests/Networking/ETagManagerTests.swift
Labels: test

#2346 `Purchases.deinit`: don't reset `Purchases.proxyURL`
  Sources/Purchasing/Purchases/Purchases.swift
Labels: fix

#2344 `ConfigureStrings`: fixed double-space typo
  Sources/Logging/Strings/ConfigureStrings.swift
Labels: refactor

#2345 `PurchaseTesterSwiftUI` improvements
  Tests/TestingApps/PurchaseTesterSwiftUI/Core/ConfiguredPurchases.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/PurchaseTesterApp.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/ConfigurationView.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/ContentView.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Customer/CustomerView.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift
Labels: test

#2361 `HTTPClient`: added test for 2xx response for request with etag
  Tests/UnitTests/Networking/HTTPClientTests.swift
Labels: test

#2351 `Offline Entitlements`: created `ProductEntitlementMappingResponse`
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Networking/Responses/ProductEntitlementMappingResponse.swift
  Tests/UnitTests/Networking/Responses/Fixtures/ProductsEntitlements.json
  Tests/UnitTests/Networking/Responses/ProductEntitlementMappingDecodingTests.swift
Labels: refactor

#2357 `TestLogHandler`: increased default capacity
  Tests/UnitTests/Purchasing/StoreKit1WrapperTests.swift
  Tests/UnitTests/TestHelpers/TestLogHandler.swift
Labels: test

#2360 `ETagManager`: added test for 304 responses with no etag
  Sources/Networking/HTTPClient/ETagManager.swift
  Tests/UnitTests/Networking/ETagManagerTests.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
Labels: test

#2367 Implemented `NetworkError.isServerDown`
  Sources/Networking/HTTPClient/NetworkError.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
  Tests/UnitTests/Networking/NetworkErrorTests.swift
Labels: refactor

#2353 `Offline Entitlements`: added support for fetching `ProductEntitlementMappingResponse` in `OfflineEntitlementsAPI`
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Networking/Backend.swift
  Sources/Networking/BackendConfiguration.swift
  Sources/Networking/Caching/ProductEntitlementMappingCallback.swift
  Sources/Networking/CustomerAPI.swift
  Sources/Networking/HTTPClient/HTTPRequest.swift
  Sources/Networking/OfferingsAPI.swift
  Sources/Networking/OfflineEntitlementsAPI.swift
  Sources/Networking/Operations/GetProductEntitlementMappingOperation.swift
  Tests/UnitTests/Mocks/MockBackend.swift
  Tests/UnitTests/Mocks/MockOfflineEntitlementsAPI.swift
  Tests/UnitTests/Networking/Backend/BackendGetOfferingsTests.swift
  Tests/UnitTests/Networking/Backend/BackendOfflineEntitlementsTests.swift
  Tests/UnitTests/Networking/Backend/BaseBackendTest.swift
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendOfflineEntitlementsTests/iOS12-testGetProductEntitlementMapping.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendOfflineEntitlementsTests/iOS12-testGetProductEntitlementMappingCachesForSameUserID.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendOfflineEntitlementsTests/iOS13-testGetProductEntitlementMapping.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendOfflineEntitlementsTests/iOS13-testGetProductEntitlementMappingCachesForSameUserID.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendOfflineEntitlementsTests/iOS14-testGetProductEntitlementMapping.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendOfflineEntitlementsTests/iOS14-testGetProductEntitlementMappingCachesForSameUserID.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendOfflineEntitlementsTests/iOS15-testGetProductEntitlementMapping.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendOfflineEntitlementsTests/iOS15-testGetProductEntitlementMappingCachesForSameUserID.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendOfflineEntitlementsTests/iOS16-testGetProductEntitlementMapping.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendOfflineEntitlementsTests/iOS16-testGetProductEntitlementMappingCachesForSameUserID.1.json
  Tests/UnitTests/Networking/HTTPRequestTests.swift
Labels: refactor

#2369 `OfferingsManager`: fixed Xcode 13.x build
  Sources/Purchasing/OfferingsManager.swift
Labels: test

#2370 `HTTPClient`: new flag to force server errors
  Sources/Misc/DangerousSettings.swift
  Sources/Networking/HTTPClient/HTTPClient.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
Labels: test

#2371 `HTTPClient`: debug log when performing redirects
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Logging/Strings/NetworkStrings.swift
  Sources/Networking/HTTPClient/HTTPClient.swift
  Sources/Networking/HTTPClient/HTTPStatusCode.swift
  Sources/Networking/HTTPClient/RedirectLoggerTaskDelegate.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
  Tests/UnitTests/Networking/HTTPStatusCodeTests.swift
Labels: refactor

#2372 Added `@DefaultDecodable.Now`
  Sources/FoundationExtensions/Decoder+Extensions.swift
  Tests/UnitTests/FoundationExtensions/DecoderExtensionTests.swift
Labels: refactor

#2358 `Offline Entitlements`: create `CustomerInfo` from offline entitlements
  RevenueCat.xcodeproj/project.pbxproj
  Sources/FoundationExtensions/JSONDecoder+Extensions.swift
  Sources/Logging/Strings/OfflineEntitlementsStrings.swift
  Sources/Networking/Responses/CustomerInfoResponse.swift
  Sources/OfflineEntitlements/CustomerInfo+OfflineEntitlements.swift
  Sources/OfflineEntitlements/PurchasedProductsFetcher.swift
  Sources/OfflineEntitlements/PurchasedSK2Product.swift
  Tests/StoreKitUnitTests/OfflineEntitlements/CustomerInfoOfflineEntitlementsStoreKitTest.swift
  Tests/StoreKitUnitTests/OfflineEntitlements/PurchasedProductsFetcherTests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/StoreKitUnitTests/StoreKit2TransactionListenerTests.swift
  Tests/StoreKitUnitTests/TestHelpers/StoreKitConfigTestCase+Extensions.swift
  Tests/StoreKitUnitTests/UnitTestsConfiguration.storekit
Labels: refactor

#2380 `SubscriberAttributesManagerIntegrationTests`: fixed potential race condition
  Tests/BackendIntegrationTests/SubscriberAttributesManagerIntegrationTests.swift
Labels: test

#2376 `PurchaseTesterSwiftUI`: fixed iOS compilation
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/PurchaseTesterApp.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift
Labels: test

#2374 `@DefaultDecodable.Now`: fixed flaky test
  Tests/UnitTests/FoundationExtensions/DecoderExtensionTests.swift
Labels: test

#2377 `PostReceiptDataOperation` / `GetCustomerInfoOperation`: only invoke response handlers once
  Sources/Networking/Operations/GetCustomerInfoOperation.swift
  Sources/Networking/Operations/PostReceiptDataOperation.swift
Labels: perf

#2375 `DeviceCache`: workaround for potential deadlock
  Sources/Caching/DeviceCache.swift
  Sources/Identity/IdentityManager.swift
  Tests/UnitTests/Caching/DeviceCacheTests.swift
Labels: fix

#2383 Fix migration guide link
  README.md
Labels: docs

#2384 redirect to latest version of migration guide
  README.md
  fastlane/Fastfile
  scripts/docs/v4_api_migration_guide.html
Labels: docs

#2381 `SubscriberAttributesManagerIntegrationTests`: fixed flaky failures
  Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
  Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift
Labels: test

#2362 `Offline Entitlements`: created `LoadShedderIntegrationTests`
  RevenueCat.xcodeproj/project.pbxproj
  Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
  Tests/BackendIntegrationTests/Constants.swift
  Tests/BackendIntegrationTests/LoadShedderIntegrationTests.swift
  Tests/TestingApps/PurchaseTester/RevenueCat_IntegrationPurchaseTesterConfiguration.storekit
  fastlane/Fastfile
Labels: test

#2387 iOS v3 load shedder integration tests
  RevenueCat.xcodeproj/project.pbxproj
  Tests/v3LoadShedderIntegration/v3LoadShedderIntegration.xcodeproj/project.pbxproj
  Tests/v3LoadShedderIntegration/v3LoadShedderIntegration.xcodeproj/xcshareddata/xcschemes/v3LoadShedderIntegration.xcscheme
  Tests/v3LoadShedderIntegration/v3LoadShedderIntegration/AppDelegate.swift
  Tests/v3LoadShedderIntegration/v3LoadShedderIntegration/Assets.xcassets/AccentColor.colorset/Contents.json
  Tests/v3LoadShedderIntegration/v3LoadShedderIntegration/Assets.xcassets/AppIcon.appiconset/Contents.json
  Tests/v3LoadShedderIntegration/v3LoadShedderIntegration/Assets.xcassets/Contents.json
  Tests/v3LoadShedderIntegration/v3LoadShedderIntegration/Base.lproj/LaunchScreen.storyboard
  Tests/v3LoadShedderIntegration/v3LoadShedderIntegration/Base.lproj/Main.storyboard
  Tests/v3LoadShedderIntegration/v3LoadShedderIntegration/Info.plist
  Tests/v3LoadShedderIntegration/v3LoadShedderIntegration/SceneDelegate.swift
  Tests/v3LoadShedderIntegration/v3LoadShedderIntegration/ViewController.swift
  Tests/v3LoadShedderIntegration/v3LoadShedderIntegrationTests/V3LoadShedderIntegrationTests.swift
  Tests/v3LoadShedderIntegration/v3LoadShedderIntegrationTests/V3LoadShedderIntegrationTestsConfiguration.storekit
Labels: test

#2388 Add lane for running iOS v3 load shedder integration tests
  Tests/v3LoadShedderIntegration/v3LoadShedderIntegrationTests/V3LoadShedderIntegrationTests.swift
  fastlane/Fastfile
  fastlane/README.md
Labels: test
