Repository RevenueCat/purchases-ios, pull requests merged in 2023-01, with the labels that each got.

#2196 remove stalebot in favor of SLAs in Zendesk
  .github/stale.yml
Labels: ci

#2205 Update Gemfile.lock
  Gemfile.lock
Labels: ci

#2007 Created `CachingTrialOrIntroPriceEligibilityChecker`
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Logging/Strings/EligibilityStrings.swift
  Sources/Logging/Strings/PurchaseStrings.swift
  Sources/Logging/Strings/Strings.swift
  Sources/Misc/Purchases+async.swift
  Sources/Purchasing/CachingTrialOrIntroPriceEligibilityChecker.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/TrialOrIntroPriceEligibilityChecker.swift
  Tests/UnitTests/Mocks/MockCachingTrialOrIntroPriceEligibilityChecker.swift
  Tests/UnitTests/Mocks/MockTrialOrIntroPriceEligibilityChecker.swift
  Tests/UnitTests/Purchasing/CachingTrialOrIntroPriceEligibilityCheckerTests.swift
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesGetProductsTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesLogInTests.swift
Labels: perf

#2197 `PurchasesReceiptParser`: improved documentation to reference `default`
  Sources/LocalReceiptParsing/PurchasesReceiptParser.swift
Labels: docs

#2210 `PurchaseTester`: small refactor to simplify `Date` formatting
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Extensions/Package+Extensions.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Customer/CustomerInfoView.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Customer/CustomerView.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Customer/EntitlementsView.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Customer/TransactionsView.swift
Labels: refactor

#2199 `PostReceiptDataOperation`: replaced receipt `base64` with `hash` for cache key
  Sources/FoundationExtensions/Data+Extensions.swift
  Sources/Networking/Operations/PostReceiptDataOperation.swift
  Tests/UnitTests/FoundationExtensions/NSData+RCExtensionsTests.swift
Labels: perf

#2202 `ReceiptFetcher`: refactored implementation to log error when failing to fetch receipt
  RevenueCat.xcodeproj/project.pbxproj
  Sources/FoundationExtensions/Data+Extensions.swift
  Sources/FoundationExtensions/Optional+Extensions.swift
  Sources/LocalReceiptParsing/Helpers/ReceiptStrings.swift
  Sources/Purchasing/ReceiptFetcher.swift
  Tests/UnitTests/FoundationExtensions/OptionalExtensionsTests.swift
  Tests/UnitTests/Mocks/MockBundle.swift
Labels: refactor

#2011 Deploy `PurchaseTester` for `macOS`
  Tests/TestingApps/PurchaseTesterSwiftUI/AppIcon.xcassets/AppIcon.appiconset/App_store_1024_1x.png
  Tests/TestingApps/PurchaseTesterSwiftUI/AppIcon.xcassets/AppIcon.appiconset/App_store_512.png
  Tests/TestingApps/PurchaseTesterSwiftUI/AppIcon.xcassets/AppIcon.appiconset/Contents.json
  Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/project.pbxproj
  fastlane/Fastfile
Labels: ci

#2203 Added `ReceiptParserTests`
  .swiftlint.yml
  Package.swift
  ReceiptParserTests-Info.plist
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCat.xcodeproj/xcshareddata/xcschemes/ReceiptParser.xcscheme
  Tests/ReceiptParserTests/ReceiptParserFetchingTests.swift
  Tests/TestPlans/AllTests.xctestplan
  Tests/TestPlans/CI-AllTests.xctestplan
Labels: test

#2212 `JSONDecoder`: added decoding type when logging `DecodingError.keyNotFound`
  Sources/FoundationExtensions/JSONDecoder+Extensions.swift
  Sources/Logging/Strings/CodableStrings.swift
Labels: refactor

#2213 `CustomerInfo`: support parsing schema version 2 to restore SDK `v3.x` compatibility
  Sources/Identity/CustomerInfo.swift
  Sources/Identity/CustomerInfoManager.swift
  Tests/UnitTests/Identity/CustomerInfoManagerTests.swift
  Tests/UnitTests/Networking/Responses/CustomerInfoDecodingTests.swift
  Tests/UnitTests/Networking/Responses/Fixtures/CustomerInfo-v2.json
Labels: fix

#2204 Added new `ReceiptParser.fetchAndParseLocalReceipt`
  RevenueCat.xcodeproj/project.pbxproj
  Sources/FoundationExtensions/Data+Extensions.swift
  Sources/LocalReceiptParsing/Helpers/FileReader.swift
  Sources/LocalReceiptParsing/ReceiptParser-only-files/PurchasesReceiptParser+Fetching.swift
  Sources/LocalReceiptParsing/ReceiptParsingError.swift
  Tests/APITesters/ReceiptParserAPITester/ReceiptParserAPITester/PurchasesReceiptParserAPI.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesReceiptParserAPI.swift
  Tests/ReceiptParserTests/Helpers/MockBundle.swift
  Tests/ReceiptParserTests/ReceiptParserFetchingTests.swift
  Tests/UnitTests/Mocks/MockFileReader.swift
Labels: feat

#2211 `PurchaseTester`: added section to visualize `AppleReceipt`
  Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/project.pbxproj
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/LocalReceiptView.swift
Labels: test

#2217 `SPM`: added `APPLICATION_EXTENSION_API_ONLY` flag to `RevenueCat` and `ReceiptParser`
  Package.swift
Labels: build

#2222 Produce a compilation error when using an old `Xcode` version
  Contributing/UpdatingRequirements.md
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Support/SwiftVersionCheck.swift
Labels: build, docs

#2218 set flag to extract objc info for swift symbols
  RevenueCat.xcodeproj/project.pbxproj
Labels: docs

#2225 Revert "`SPM`: added `APPLICATION_EXTENSION_API_ONLY` flag to `RevenueCat` and `ReceiptParser` (#2217)"
  Package.swift
Labels: build

#2232 `PurchaseTester`: setting `changelog` when submitting to `TestFlight`
  fastlane/Fastfile
Labels: ci

#2229 `PurchaseTester`: fixed `isPurchasing` state when purchasing fails
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Offerings/OfferingDetailView.swift
Labels: test

#2228 `PurchaseTester`: ignore errors when restoring purchases
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/LocalReceiptView.swift
Labels: test

#2231 `Purchases`: avoid potential crash when initializing in the background
  Sources/Purchasing/Purchases/Purchases.swift
Labels: fix

#2230 `SystemInfo.isApplicationBackgrounded`: added overload for `@MainActor`
  Sources/Misc/SystemInfo.swift
  Tests/BackendIntegrationTests/SubscriberAttributesManagerIntegrationTests.swift
Labels: refactor

#2233 `PurchaseTester`: added contents of `CHANGELOG.latest.md` to `TestFlight` changelog
  fastlane/Fastfile
Labels: ci

#2236 Simplified `OperationDispatcher.dispatchOnMainActor`
  Sources/Misc/OperationDispatcher.swift
Labels: refactor

#2239 Update `fastlane-plugin-revenuecat_internal`
  Gemfile.lock
Labels: ci

#2240 Improve logging for custom package durations
  Sources/Logging/Strings/OfferingStrings.swift
Labels: docs

#2242 Code coverage
  .circleci/config.yml
  Tests/TestPlans/CI-AllTests.xctestplan
Labels: test, ci

#2241 `Purchases`: fixed documentation warnings
  Sources/Purchasing/Purchases/PurchasesType.swift
Labels: docs

#2174 `IntroEligibilityCalculator`: fixed logic for subscriptions in same group
  Sources/LocalReceiptParsing/BasicTypes/AppleReceipt.swift
  Sources/LocalReceiptParsing/BasicTypes/InAppPurchase.swift
  Sources/Purchasing/IntroEligibilityCalculator.swift
  Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
  Tests/TestingApps/PurchaseTester/RevenueCat_IntegrationPurchaseTesterConfiguration.storekit
  Tests/UnitTests/Purchasing/IntroEligibilityCalculatorTests.swift
Labels: fix

#2245 `PurchasesOrchestrator`: changed `ReceiptRefreshPolicy.always` to `.onlyIfEmpty` after a purchase
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift
Labels: refactor

#2244 `StoreKitIntegrationTests`: replaced `XCTSkipIf` with `XCTExpectFailure`
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
Labels: test

#2224 `CustomerInfoManager`: improved thread-safety
  Sources/Identity/CustomerInfoManager.swift
Labels: fix
