Repository RevenueCat/purchases-ios, pull requests merged in 2023-06, with the labels that each got.

#2573 `Package.swift` fix warning for unrecognized `Info.plist`
  Package.swift
Labels: build

#2570 `Integration Tests`: avoid crashes when printing receipt
  Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift
Labels: test

#2578 Fixed typo in file name
  RevenueCat.xcodeproj/project.pbxproj
  Tests/UnitTests/Purchasing/PaymentQueueWrapperTests.swift
Labels: refactor

#2575 `ProductsManager`: improved display of underlying errors
  Sources/Logging/Strings/StoreKitStrings.swift
  Sources/Purchasing/ProductsManager.swift
  Sources/Purchasing/StoreKit1/ProductsFetcherSK1.swift
  Sources/Purchasing/StoreKit1/StoreKitRequestFetcher.swift
Labels: refactor

#2568 `Custom Entitlements Computation`: added Integration Tests
  .circleci/config.yml
  RevenueCat.xcodeproj/project.pbxproj
  Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
  Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift
  Tests/BackendIntegrationTests/CustomEntitlementsComputationIntegrationTests.swift
  Tests/BackendIntegrationTests/OtherIntegrationTests.swift
  Tests/StoreKitUnitTests/LoggerTests.swift
  Tests/TestPlans/BackendIntegrationTests.xctestplan
  Tests/TestPlans/CI-BackendIntegration.xctestplan
  Tests/UnitTests/Misc/XCTestCase+Extensions.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesLogInTests.swift
  Tests/UnitTests/Purchasing/Purchases/TransactionPosterTests.swift
  Tests/UnitTests/TestHelpers/TestLogHandler.swift
  fastlane/Fastfile
Labels: test

#2579 `Custom Entitlement Computation`: added missing scheme to project
  Examples/testCustomEntitlementsComputation/testCustomEntitlementsComputation.xcodeproj/xcshareddata/xcschemes/testCustomEntitlementsComputation.xcscheme
Labels: test

#2582 `Dictionary.MergeStrategy`: fixed Xcode 15 compilation
  Sources/FoundationExtensions/Dictionary+Extensions.swift
Labels: fix, iOS 17

#2583 `Configuration.Builder`: fixed doc reference
  Sources/Purchasing/Configuration.swift
Labels: docs

#2587 `Dictionary.MergeStrategy`: simplify implementation
  Sources/FoundationExtensions/Dictionary+Extensions.swift
Labels: refactor

#2589 `StoreKitObserverModeIntegrationTests`: fixed and disabled SK2 `testPurchaseInDevicePostsReceipt`
  Tests/BackendIntegrationTests/StoreKitObserverModeIntegrationTests.swift
Labels: test

#2567 Introduced `debugRevenueCatOverlay()`: new SwiftUI debug overlay
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Misc/SystemInfo.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Support/DebugUI/DebugContentViews.swift
  Sources/Support/DebugUI/DebugView.swift
  Sources/Support/DebugUI/DebugViewModel.swift
  Sources/Support/DebugUI/DebugViewSheetPresentation.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester.xcodeproj/project.pbxproj
  Tests/APITesters/SwiftAPITester/SwiftAPITester/OtherAPI.swift
Labels: feat

#2596 `Xcode 15`: fixed all documentation warnings
  Sources/DocCDocumentation/DocCDocumentation.docc/V4_API_Migration_guide.md
  Sources/Purchasing/Configuration.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesType.swift
  Sources/Purchasing/StoreKitAbstractions/PromotionalOffer.swift
Labels: docs, iOS 17

#2594 `debugRevenueCatOverlay` improvements
  Sources/Support/DebugUI/DebugContentViews.swift
  Sources/Support/DebugUI/DebugViewModel.swift
Labels: refactor

#2604 `StoreProductDiscount`: added `description`
  Sources/Purchasing/StoreKitAbstractions/StoreProductDiscount.swift
Labels: refactor

#2602 Fixed test compilation with `Xcode 15`
  Tests/UnitTests/Networking/NetworkErrorTests.swift
  Tests/UnitTests/Purchasing/Purchases/TransactionPosterTests.swift
  Tests/UnitTests/TestHelpers/Matchers.swift
Labels: refactor, iOS 17

#2601 Removed unnecessary `Strings.trimmedOrError`
  Sources/FoundationExtensions/String+Extensions.swift
  Sources/Networking/Operations/LogInOperation.swift
Labels: refactor

#2605 Changed tests to work around `URL` decoding differences in `iOS 17`
  Tests/UnitTests/FoundationExtensions/DecoderExtensionTests.swift
  Tests/UnitTests/Purchasing/CustomerInfoTests.swift
Labels: test, iOS 17

#2600 Refactor: extracted all log strings
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Logging/Strings/ConfigureStrings.swift
  Sources/Logging/Strings/DiagnosticsStrings.swift
  Sources/Logging/Strings/NetworkStrings.swift
  Sources/Logging/Strings/OfferingStrings.swift
  Sources/Logging/Strings/PurchaseStrings.swift
  Sources/Logging/Strings/RestoreStrings.swift
  Sources/Logging/Strings/StoreKitStrings.swift
  Sources/Logging/Strings/Strings.swift
  Sources/Misc/DateAndTime/TimingUtil.swift
  Sources/Networking/Operations/NetworkOperation.swift
  Sources/Purchasing/Configuration.swift
  Sources/Purchasing/Offering.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/StoreKit1/StoreKit1Wrapper.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
Labels: refactor

#2595 `debugRevenueCatOverlay`: added ability to display new `SubscriptionStoreView`
  Sources/Support/DebugUI/DebugContentViews.swift
Labels: refactor, iOS 17

#2607 `Encodable.jsonEncodedData`: fixed tests on iOS 17 due to inconsistent key ordering
  Sources/LocalReceiptParsing/DataConverters/Codable+Extensions.swift
  Tests/UnitTests/Caching/DeviceCacheTests.swift
Labels: test, iOS 17

#2591 `CI`: added `iOS 17` job
  .circleci/config.yml
Labels: ci, iOS 17

#2613 `PaywallExtensions`: fixed compilation
  Sources/Support/PaywallExtensions.swift
Labels: refactor

#2617 `StoreKitConfigTestCase`: set `continueAfterFailure` to `false`
  Tests/StoreKitUnitTests/StoreKitConfigTestCase.swift
Labels: test

#2615 Improved `finishAllUnfinishedTransactions`
  Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
  Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift
  Tests/StoreKitUnitTests/StoreKitConfigTestCase.swift
  Tests/StoreKitUnitTests/TestHelpers/StoreKitTestHelpers.swift
Labels: test

#2622 `PurchaseTester`: make CI job always point to current version
  .circleci/config.yml
  Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/project.pbxproj
  fastlane/Fastfile
Labels: ci

#2610 `ErrorCode.networkError`: improved description
  Sources/Error Handling/ErrorCode.swift
Labels: refactor

#2611 `StoreTransaction`: read `Storefront` from `StoreKit.Transaction`
  Sources/Misc/Deprecations.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/StoreKitAbstractions/SK1StoreTransaction.swift
  Sources/Purchasing/StoreKitAbstractions/SK2StoreTransaction.swift
  Sources/Purchasing/StoreKitAbstractions/StoreTransaction.swift
  Tests/StoreKitUnitTests/StoreTransactionTests.swift
  Tests/UnitTests/Mocks/MockStoreTransaction.swift
Labels: refactor, iOS 17

#2623 Removed `preventPurchasePopupCallFromTriggeringCacheRefresh`, update caches on `willEnterForeground`
  Sources/Caching/DeviceCache.swift
  Sources/Logging/Strings/ConfigureStrings.swift
  Sources/Logging/Strings/PurchaseStrings.swift
  Sources/Misc/SystemInfo.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Tests/UnitTests/Caching/DeviceCacheTests.swift
  Tests/UnitTests/Mocks/MockDeviceCache.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesDelegateTests.swift
  Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Labels: fix

#2627 `CI`: disable iOS 17 for now
  .circleci/config.yml
Labels: ci

#2629 `PurchasesOrchestrator`: also get `Storefront` from SK1
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
Labels: refactor

#2628 `PostReceiptDataOperation`: clean up cache key
  Sources/Networking/Operations/PostReceiptDataOperation.swift
Labels: refactor

#2625 `verifyNoUnfinishedTransactions`/`verifyUnfinishedTransaction`: added missing `#file` parameter
  Tests/StoreKitUnitTests/TestHelpers/StoreKitTestHelpers.swift
Labels: test

#2630 `DebugView`: added snapshot tests
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Support/DebugUI/DebugContentViews.swift
  Sources/Support/DebugUI/DebugViewModel.swift
  Tests/StoreKitUnitTests/TestHelpers/AvailabilityChecks.swift
  Tests/UnitTests/Support/DebugViewSwiftUITests.swift
  Tests/UnitTests/Support/__Snapshots__/DebugViewSwiftUITests/testDebugView.1.png
  Tests/UnitTests/Support/__Snapshots__/DebugViewSwiftUITests/testLoadingState.1.png
  Tests/UnitTests/TestHelpers/ImageSnapshot.swift
Labels: test

#2631 New `DebugViewController`: UIKit counterpart for SwiftUI's `debugRevenueCatOverlay`
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Support/DebugUI/DebugContentViews.swift
  Sources/Support/DebugUI/DebugView.swift
  Sources/Support/DebugUI/DebugViewController.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester.xcodeproj/project.pbxproj
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCOtherAPI.h
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCOtherAPI.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester/OtherAPI.swift
  Tests/TestingApps/PurchaseTester/PurchaseTester/InitialViewController.swift
Labels: feat

#2638 `Signing`: removed API for loading key from a file
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Security/Signing.swift
  Tests/UnitTests/Resources/public_keys/invalid_certificate.cer
  Tests/UnitTests/Security/SigningTests.swift
Labels: refactor

#2636 `IntegrationTests`: explicit `StoreKit 1` mode
  Tests/BackendIntegrationTests/OfflineStoreKitIntegrationTests.swift
  Tests/BackendIntegrationTests/StoreKitObserverModeIntegrationTests.swift
Labels: test

#2635 Add `InternalDangerousSettings.forceSignatureFailures`
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Logging/Strings/NetworkStrings.swift
  Sources/Misc/DangerousSettings.swift
  Sources/Networking/HTTPClient/HTTPClient.swift
  Sources/Security/FakeSigning.swift
  Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
  Tests/UnitTests/Networking/SignatureVerificationHTTPClientTests.swift
Labels: test

#2643 `HTTPResponseTests`: fixed disabled test
  Tests/UnitTests/Networking/HTTPResponseTests.swift
Labels: test

#2639 `copy(with: VerificationResult)`: optimization to avoid copies
  Sources/Identity/CustomerInfo.swift
  Sources/Networking/HTTPClient/HTTPResponse.swift
  Tests/UnitTests/Networking/HTTPResponseTests.swift
  Tests/UnitTests/Purchasing/CustomerInfoTests.swift
Labels: perf

#2641 `debugRevenueCatOverlay`: simplified title
  Sources/Support/DebugUI/DebugContentViews.swift
  Tests/UnitTests/Support/__Snapshots__/DebugViewSwiftUITests/testDebugView.1.png
  Tests/UnitTests/Support/__Snapshots__/DebugViewSwiftUITests/testLoadingState.1.png
Labels: refactor

#2647 `Trusted Entitlements`: added debug log with `ResponseVerificationMode`
  Sources/Logging/Strings/ConfigureStrings.swift
  Sources/Purchasing/Purchases/Purchases.swift
Labels: refactor

#2619 Added `.xcprivacy` for Xcode 15
  Examples/MagicWeatherSwiftUI/Magic Weather SwiftUI.xcodeproj/project.pbxproj
  Examples/MagicWeatherSwiftUI/Shared/PrivacyInfo.xcprivacy
  Package.swift
  RevenueCat.xcodeproj/project.pbxproj
  Sources/PrivacyInfo.xcprivacy
  Tests/TestingApps/PurchaseTesterSwiftUI/PrivacyInfo.xcprivacy
  Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/project.pbxproj
Labels: docs, iOS 17

#2650 `ErrorUtils.missingReceiptFileError`: added receipt URL `userInfo` context
  Sources/Error Handling/BackendError.swift
  Sources/Error Handling/ErrorUtils.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/Purchases/TransactionPoster.swift
  Sources/Purchasing/ReceiptFetcher.swift
  Sources/Purchasing/TrialOrIntroPriceEligibilityChecker.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/UnitTests/Misc/PurchasesDiagnosticsTests.swift
  Tests/UnitTests/Mocks/MockReceiptFetcher.swift
  Tests/UnitTests/Networking/BackendErrorTests.swift
  Tests/UnitTests/Purchasing/ErrorUtilsTests.swift
  Tests/UnitTests/Purchasing/Purchases/TransactionPosterTests.swift
  Tests/UnitTests/Purchasing/ReceiptFetcherTests.swift
Labels: refactor

#2612 Always initialize `StoreKit2TransactionListener` even on SK1 mode
  Sources/Logging/Strings/PurchaseStrings.swift
  Sources/Logging/Strings/StoreKitStrings.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/StoreKit1/PaymentQueueWrapper.swift
  Sources/Purchasing/StoreKit2/StoreKit2TransactionListener.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/StoreKitUnitTests/StoreKit2/StoreKit2TransactionListenerTests.swift
  Tests/UnitTests/Mocks/MockStoreKit2TransactionListenerDelegate.swift
Labels: storekit2, refactor

#2590 `StoreKitObserverModeIntegrationTests`: added test for posting renewals
  Sources/Logging/Strings/PurchaseStrings.swift
  Sources/Purchasing/Purchases/TransactionPoster.swift
  Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift
  Tests/BackendIntegrationTests/StoreKitObserverModeIntegrationTests.swift
Labels: test

#2651 `ImageSnapshot`: fixed Xcode 15 compilation
  Tests/UnitTests/TestHelpers/ImageSnapshot.swift
Labels: test

#2655 `LoadShedderIntegrationTests`: enable signature verification
  Tests/BackendIntegrationTests/LoadShedderIntegrationTests.swift
Labels: test

#2648 `debugRevenueCatOverlay`: added support for `macOS`
  Sources/Support/DebugUI/DebugContentViews.swift
  Sources/Support/DebugUI/DebugView.swift
  Sources/Support/DebugUI/DebugViewModel.swift
  Sources/Support/DebugUI/DebugViewSheetPresentation.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/OtherAPI.swift
Labels: refactor

#2652 `debugRevenueCatOverlay`: display `receiptURL`
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Support/DebugUI/DebugContentViews.swift
  Sources/Support/DebugUI/DebugViewModel.swift
  Tests/UnitTests/Support/DebugViewSwiftUITests.swift
  Tests/UnitTests/Support/__Snapshots__/DebugViewSwiftUITests/testDebugView.1.png
Labels: refactor

#2662 `MainThreadMonitor`: increased threshold
  Tests/BackendIntegrationTests/MainThreadMonitor.swift
Labels: test

#2608 Changed `Logger` to use `os_log`
  RevenueCat.xcodeproj/project.pbxproj
  Sources/LocalReceiptParsing/Helpers/LoggerType.swift
  Sources/LocalReceiptParsing/Helpers/ReceiptParserLogger.swift
  Sources/LocalReceiptParsing/Helpers/ReceiptStrings.swift
  Sources/Logging/Logger.swift
  Sources/Logging/Strings/AttributionStrings.swift
  Sources/Logging/Strings/BackendErrorStrings.swift
  Sources/Logging/Strings/CodableStrings.swift
  Sources/Logging/Strings/ConfigureStrings.swift
  Sources/Logging/Strings/CustomerInfoStrings.swift
  Sources/Logging/Strings/DiagnosticsStrings.swift
  Sources/Logging/Strings/EligibilityStrings.swift
  Sources/Logging/Strings/IdentityStrings.swift
  Sources/Logging/Strings/ManageSubscriptionsStrings.swift
  Sources/Logging/Strings/NetworkStrings.swift
  Sources/Logging/Strings/OfferingStrings.swift
  Sources/Logging/Strings/OfflineEntitlementsStrings.swift
  Sources/Logging/Strings/PurchaseStrings.swift
  Sources/Logging/Strings/SigningStrings.swift
  Sources/Logging/Strings/StoreKitStrings.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
  Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift
  Tests/BackendIntegrationTests/Helpers/TestMessage.swift
  Tests/BackendIntegrationTests/MainThreadMonitor.swift
  Tests/StoreKitUnitTests/LoggerTests.swift
  Tests/StoreKitUnitTests/StoreKitConfigTestCase.swift
  Tests/StoreKitUnitTests/TestHelpers/StoreKitTestHelpers.swift
  Tests/UnitTests/Mocks/MockProductsManager.swift
  Tests/UnitTests/TestHelpers/TestLogHandler.swift
Labels: refactor

#2654 Support `product_plan_identifier` for purchased subscriptions from `Google Play`
  Sources/Identity/CustomerInfo+ActiveDates.swift
  Sources/Networking/Responses/CustomerInfoResponse.swift
  Sources/Purchasing/EntitlementInfo.swift
  Tests/UnitTests/Purchasing/CustomerInfoTests.swift
  Tests/UnitTests/Purchasing/EntitlementInfosTests.swift
Labels: fix

#2645 `PaywallExtensions`: post purchases with `Offering` identifier
  Sources/Logging/Strings/PurchaseStrings.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/Purchases/TransactionPoster.swift
  Sources/Support/DebugUI/DebugContentViews.swift
  Sources/Support/PaywallExtensions.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/OtherAPI.swift
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
Labels: fix

#2664 Fixed `HTTPResponse.description`
  Sources/Networking/HTTPClient/HTTPResponse.swift
Labels: refactor

#2658 `Signature Verification`: added test-only log for debugging invalid signatures
  Sources/Logging/Strings/SigningStrings.swift
  Sources/Security/Signing+ResponseVerification.swift
Labels: refactor

#2656 `ETagManager`: added new verbose logs
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Logging/Strings/ETagStrings.swift
  Sources/Logging/Strings/NetworkStrings.swift
  Sources/Logging/Strings/Strings.swift
  Sources/Networking/HTTPClient/ETagManager.swift
  Tests/UnitTests/Purchasing/ErrorUtilsTests.swift
Labels: refactor

#2669 `HTTPClient`: improved log for failed requests
  Sources/Logging/Strings/NetworkStrings.swift
  Sources/Networking/HTTPClient/HTTPClient.swift
Labels: refactor

#2657 `NetworkError.signatureVerificationFailed`: added status code to error `userInfo`
  Sources/Error Handling/ErrorUtils.swift
  Sources/Networking/HTTPClient/NetworkError.swift
  Sources/Security/Signing+ResponseVerification.swift
  Tests/UnitTests/Misc/PurchasesDiagnosticsTests.swift
  Tests/UnitTests/Networking/Backend/BackendSignatureVerificationTests.swift
  Tests/UnitTests/Networking/NetworkErrorTests.swift
  Tests/UnitTests/Networking/SignatureVerificationHTTPClientTests.swift
Labels: refactor

#2661 Documented `HTTPStatusCode.isSuccessfullySynced`
  Sources/Networking/HTTPClient/HTTPStatusCode.swift
  Tests/UnitTests/Networking/HTTPStatusCodeTests.swift
  Tests/UnitTests/Networking/NetworkErrorTests.swift
Labels: docs

#2660 `ErrorResponse`: drastically improved error messages, no more "unknown error"s
  Sources/Logging/Strings/NetworkStrings.swift
  Sources/Networking/HTTPClient/HTTPClient.swift
  Sources/Networking/HTTPClient/HTTPResponse.swift
  Sources/Networking/HTTPClient/NetworkError.swift
  Tests/UnitTests/Networking/BaseErrorTests.swift
  Tests/UnitTests/Networking/NetworkErrorTests.swift
Labels: fix

#2668 `HTTPClient`: disable `URLSession` cache
  Sources/Networking/HTTPClient/HTTPClient.swift
Labels: refactor

#2666 `ETagManager.httpResultFromCacheOrBackend`: return response headers
  Sources/Networking/HTTPClient/ETagManager.swift
  Tests/UnitTests/Networking/ETagManagerTests.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
Labels: refactor

#2677 `TimingUtil`: removed slow purchase logs
  Sources/Logging/Strings/PurchaseStrings.swift
  Sources/Purchasing/Configuration.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
Labels: refactor

#2676 `PurchasesOrchestrator`: update `CustomerInfoManager` cache after processing transactions
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Tests/BackendIntegrationTests/StoreKitObserverModeIntegrationTests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
Labels: storekit2, fix

#2678 `getPromotionalOffer`: return `ErrorCode.ineligibleError` if receipt is not found
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
Labels: refactor

#2671 `ETagManager`: refactored e-tag creation and tests
  Sources/Networking/HTTPClient/ETagManager.swift
  Sources/Networking/HTTPClient/HTTPClient.swift
  Tests/UnitTests/Networking/ETagManagerTests.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
Labels: refactor

#2680 `Xcode 15`: handle `Locale.currencyCode` deprecation
  RevenueCat.xcodeproj/project.pbxproj
  Sources/FoundationExtensions/Locale+Extensions.swift
  Sources/Purchasing/StoreKitAbstractions/SK1StoreProduct.swift
  Sources/Purchasing/StoreKitAbstractions/SK1StoreProductDiscount.swift
  Tests/UnitTests/FoundationExtensions/LocaleExtensionsTests.swift
Labels: fix, iOS 17, xrOS

#2642 `Signature Verification`: new `Integration Tests`
  RevenueCat.xcodeproj/project.pbxproj
  Tests/BackendIntegrationTests/SignatureVerificationIntegrationTests.swift
Labels: test

#2683 `xrOS`: added support for new `purchase(confirmIn:options:)` method
  Sources/FoundationExtensions/UIApplication+RCExtensions.swift
  Sources/Logging/Strings/ManageSubscriptionsStrings.swift
  Sources/Misc/SystemInfo.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Support/BeginRefundRequestHelper.swift
  Sources/Support/ManageSubscriptionsHelper.swift
Labels: fix, xrOS

#2685 `xrOS`: added support to `PurchaseTester`
  Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/project.pbxproj
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Helpers/AdaptiveStack.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Helpers/ObserverModeManager.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Helpers/PurchasesOrchestrator.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Offerings/OfferingDetailView.swift
Labels: test, xrOS

#2691 `xrOS`: fixed runtime warning
  Sources/FoundationExtensions/UIApplication+RCExtensions.swift
  Sources/Misc/SystemInfo.swift
Labels: refactor, xrOS

#2681 `xrOS`: fixed compilation by disabling debug overlay
  Sources/Support/DebugUI/DebugContentViews.swift
  Sources/Support/DebugUI/DebugView.swift
  Sources/Support/DebugUI/DebugViewController.swift
  Sources/Support/DebugUI/DebugViewModel.swift
  Sources/Support/DebugUI/DebugViewSheetPresentation.swift
  Sources/Support/PaywallExtensions.swift
Labels: fix, xrOS

#2689 `PurchaseTester`: fixed release compilation
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift
Labels: test

#2673 `Diagnostics`: new `FileHandler` for abstracting file operations
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Diagnostics/FileHandler.swift
  Sources/FoundationExtensions/String+Extensions.swift
  Tests/UnitTests/Diagnostics/FileHandlerTests.swift
  Tests/UnitTests/FoundationExtensions/StringExtensionsTests.swift
Labels: refactor

#2695 Refactored `Data.asString` implementation
  RevenueCat.xcodeproj/project.pbxproj
  Sources/FoundationExtensions/Data+Extensions.swift
  Tests/UnitTests/FoundationExtensions/DataExtensionsTests.swift
  Tests/UnitTests/LocalReceiptParsing/TestsAgainstRealReceipts/ReceiptParsing+TestsWithRealReceipts.swift
  Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
  Tests/UnitTests/SubscriberAttributes/SubscriberAttributesManagerTests.swift
Labels: refactor

#2694 Add `Sequence<AdditiveArithmetic>.sum()`
  Sources/FoundationExtensions/Array+Extensions.swift
  Tests/UnitTests/FoundationExtensions/ArrayExtensionsTests.swift
Labels: refactor

#2697 Refactor: extract `ErrorResponse` into its own file
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Networking/HTTPClient/ErrorResponse.swift
  Sources/Networking/HTTPClient/HTTPResponse.swift
Labels: refactor

#2696 Add `Data.sha1`
  Sources/FoundationExtensions/Data+Extensions.swift
  Tests/UnitTests/FoundationExtensions/DataExtensionsTests.swift
Labels: refactor

#2701 `PurchaseTester`: fixed `watchOS` build and ASC deployment
  Tests/TestingApps/PurchaseTesterSwiftUI/AppIcon.xcassets/AppIcon.appiconset/App_store_1024_1x 1.png
  Tests/TestingApps/PurchaseTesterSwiftUI/AppIcon.xcassets/AppIcon.appiconset/Contents.json
  Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/project.pbxproj
  Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/xcshareddata/xcschemes/PurchaseTester.xcscheme
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/PurchaseTesterApp.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/ReceiptInspector.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/ConfigurationView.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/LocalReceiptView.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/LoggerView.swift
Labels: test

#2703 Fix google play purchases missing purchase date
  Sources/Identity/CustomerInfo+ActiveDates.swift
  Sources/Networking/Responses/CustomerInfoResponse.swift
  Tests/UnitTests/Purchasing/CustomerInfoTests.swift
Labels: fix

#2705 Remove alpha from purchase tester icon to upload to testflight
  Tests/TestingApps/PurchaseTesterSwiftUI/AppIcon.xcassets/AppIcon.appiconset/App_store_1024_1x 1.png
Labels: build

#2699 `Purchases.restoreLogHandler`
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/StoreKitUnitTests/LoggerTests.swift
  Tests/UnitTests/TestHelpers/TestLogHandler.swift
Labels: test

#2702 `xrOS`: add support for `debugRevenueCatOverlay`
  Sources/Support/DebugUI/DebugContentViews.swift
  Sources/Support/DebugUI/DebugView.swift
  Sources/Support/DebugUI/DebugViewModel.swift
  Sources/Support/DebugUI/DebugViewSheetPresentation.swift
Labels: refactor, xrOS

#2712 `PriceFormatterProvider.priceFormatterForSK2`: enable on all versions
  Sources/Misc/PriceFormatterProvider.swift
  Tests/StoreKitUnitTests/PriceFormatterProviderTests.swift
Labels: refactor

#2710 `CI`: removed `carthage_archive` from `release` lane
  fastlane/Fastfile
Labels: ci

#2709 `XCFramework`: sign archive for `Xcode 15`
  fastlane/Fastfile
Labels: refactor

#2716 `TimingUtil`: added synchronous API
  Sources/Misc/DateAndTime/TimingUtil.swift
  Tests/UnitTests/Misc/TimingUtilTests.swift
Labels: refactor

#2713 Add `UInt32(littleEndian32Bits:)` and `UInt32.littleEndianData`
  RevenueCat.xcodeproj/project.pbxproj
  Sources/FoundationExtensions/Integer+Extensions.swift
  Tests/UnitTests/FoundationExtensions/IntegerExtensionsTests.swift
Labels: refactor

#2714 Remove unused `Signing.loadPublicKey(with:)`
  Sources/Logging/Strings/ConfigureStrings.swift
  Sources/Security/Signing.swift
  Tests/UnitTests/Security/SigningTests.swift
Labels: refactor

#2719 `Integration Tests`: fix clearing `UserDefaults` before each test
  Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
Labels: test

#2720 `Tests`: disabled `iOS 11.x` tests to fix `Xcode 15` tests
  RevenueCat.xcodeproj/project.pbxproj
  Tests/APITesters/ObjCAPITester/ObjCAPITester.xcodeproj/project.pbxproj
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCConfigurationAPI.m
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCEntitlementInfoAPI.m
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesDiagnosticsAPI.m
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCStoreProductAPI.m
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCStorefrontAPI.m
  Tests/APITesters/ReceiptParserAPITester/ReceiptParserAPITester.xcodeproj/project.pbxproj
  Tests/APITesters/SwiftAPITester/SwiftAPITester.xcodeproj/project.pbxproj
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
Labels: test, iOS 17

#2732 `SystemInfo.identifierForVendor`: add tests
  Sources/Misc/SystemInfo.swift
  Tests/UnitTests/Misc/SystemInfoTests.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
Labels: test

#2730 `Trusted Entitlements`: add integration tests to verify `CustomerInfo` cache invalidation
  Tests/BackendIntegrationTests/SignatureVerificationIntegrationTests.swift
Labels: test

#2731 Refactor: simplified `PurchasesOrchestrator.syncPurchases`
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
Labels: refactor

#2739 `VerificationResult: CustomDebugStringConvertible`
  Sources/Security/VerificationResult.swift
Labels: refactor

#2711 New `TestStoreProduct` for creating mock `StoreProduct`s and `Offering`s
  Examples/MagicWeatherSwiftUI/Shared/Sources/Views/PaywallView.swift
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Purchasing/Offering.swift
  Sources/Purchasing/Package.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/StoreKitAbstractions/ProductType.swift
  Sources/Purchasing/StoreKitAbstractions/StoreProduct.swift
  Sources/Purchasing/StoreKitAbstractions/Test Data/TestStoreProduct.swift
  Sources/Purchasing/StoreKitAbstractions/Test Data/TestStoreProductDiscount.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester.xcodeproj/project.pbxproj
  Tests/APITesters/SwiftAPITester/SwiftAPITester/OfferingAPI.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PackageAPI.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/TestStoreProductAPI.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/TestStoreProductDiscountAPI.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/main.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/StoreKitUnitTests/StoreProductTests.swift
  Tests/UnitTests/Mocks/MockOfferingsFactory.swift
Labels: feat

#2741 `Integration Tests`: avoid crashes when stopping tests early
  Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift
Labels: test

#2679 `Trusted Entitlements`: new Signature format
  Sources/Logging/Strings/SigningStrings.swift
  Sources/Networking/HTTPClient/HTTPResponse.swift
  Sources/Security/Signing+ResponseVerification.swift
  Sources/Security/Signing.swift
  Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
  Tests/BackendIntegrationTests/CustomEntitlementsComputationIntegrationTests.swift
  Tests/BackendIntegrationTests/LoadShedderIntegrationTests.swift
  Tests/BackendIntegrationTests/OtherIntegrationTests.swift
  Tests/BackendIntegrationTests/SignatureVerificationIntegrationTests.swift
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
  Tests/UnitTests/Networking/SignatureVerificationHTTPClientTests.swift
  Tests/UnitTests/Security/SigningTests.swift
Labels: refactor

#2698 `Trusted Entitlements`: update handling of 304 responses
  Sources/Logging/Strings/ETagStrings.swift
  Sources/Logging/Strings/SigningStrings.swift
  Sources/Networking/HTTPClient/ETagManager.swift
  Sources/Networking/HTTPClient/HTTPClient.swift
  Sources/Networking/HTTPClient/HTTPResponse.swift
  Sources/Networking/InternalAPI.swift
  Sources/Networking/Operations/GetCustomerInfoOperation.swift
  Sources/Networking/Operations/GetIntroEligibilityOperation.swift
  Sources/Networking/Operations/GetOfferingsOperation.swift
  Sources/Networking/Operations/GetProductEntitlementMappingOperation.swift
  Sources/Networking/Operations/Handling/CustomerInfoResponseHandler.swift
  Sources/Networking/Operations/LogInOperation.swift
  Sources/Networking/Operations/PostAdServicesTokenOperation.swift
  Sources/Networking/Operations/PostAttributionDataOperation.swift
  Sources/Networking/Operations/PostOfferForSigningOperation.swift
  Sources/Networking/Operations/PostReceiptDataOperation.swift
  Sources/Networking/Operations/PostSubscriberAttributesOperation.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Security/Signing+ResponseVerification.swift
  Sources/Security/Signing.swift
  Sources/Security/VerificationResult.swift
  Tests/UnitTests/Mocks/MockETagManager.swift
  Tests/UnitTests/Mocks/MockHTTPClient.swift
  Tests/UnitTests/Networking/ETagManagerTests.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
  Tests/UnitTests/Networking/HTTPResponseTests.swift
  Tests/UnitTests/Networking/SignatureVerificationHTTPClientTests.swift
  Tests/UnitTests/OfflineEntitlements/CustomerInfoResponseHandlerTests.swift
  Tests/UnitTests/Security/SigningTests.swift
Labels: refactor

#2715 `Signing`: extract and verify intermediate key
  Sources/Logging/Strings/SigningStrings.swift
  Sources/Security/Signing.swift
  Tests/UnitTests/Security/SigningTests.swift
Labels: refactor
