Repository RevenueCat/purchases-ios, pull requests merged in 2023-10, with the labels that each got.

#3247 `debugRevenueCatOverlay`: added list of active entitlements
  Sources/Support/DebugUI/DebugContentViews.swift
Labels: refactor

#3248 `Paywalls`: added previews for `IntroEligibilityStateView`
  RevenueCatUI/Views/IntroEligibilityStateView.swift
Labels: refactor

#3249 `Paywalls`: polished template 4 layout math
  RevenueCatUI/Helpers/PreviewHelpers.swift
  RevenueCatUI/Templates/Template4View.swift
  Tests/purchases-ios-snapshots-commit
Labels: RevenueCatUI

#3261 `Paywalls`: small PaywallsTester refactor
  Tests/TestingApps/PaywallsTester/PaywallsTester/Views/OfferingsList.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Views/PaywallViewMode+Extensions.swift
Labels: refactor

#3264 Refactored `StoreMessagesHelper`
  Sources/Misc/Concurrency/Purchases+nonasync.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/Purchases/PurchasesType.swift
  Sources/Support/StoreMessageType.swift
  Sources/Support/StoreMessagesHelper.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/StoreKitUnitTests/StoreMessagesHelperTests.swift
  Tests/StoreKitUnitTests/TestHelpers/AvailabilityChecks.swift
  Tests/UnitTests/Mocks/MockPurchases.swift
  Tests/UnitTests/Mocks/MockStoreMessagesHelper.swift
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Labels: refactor

#3259 PaywallsTester: add a new tab that calls presentPaywallIfNeeded
  Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/project.pbxproj
  Tests/TestingApps/PaywallsTester/PaywallsTester/Views/AppContentView.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Views/UpsellView.swift
Labels: test

#3252 StoreKit In App messages support
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Logging/Strings/StoreKitStrings.swift
  Sources/Misc/Concurrency/Purchases+nonasync.swift
  Sources/Misc/Deprecations.swift
  Sources/Purchasing/Configuration.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/Purchases/PurchasesType.swift
  Sources/Support/StoreMessageType.swift
  Sources/Support/StoreMessagesHelper.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
  Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/StoreKitUnitTests/StoreMessagesHelperTests.swift
  Tests/UnitTests/Mocks/MockPurchases.swift
  Tests/UnitTests/Mocks/MockStoreMessagesHelper.swift
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
  Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Labels: feat

#3268 Add `Attribution.setOnesignalUserID`
  Sources/Purchasing/Purchases/Attribution.swift
  Sources/SubscriberAttributes/ReservedSubscriberAttributes.swift
  Sources/SubscriberAttributes/SubscriberAttributesManager.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCAttributionAPI.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester/AttributionAPI.swift
  Tests/UnitTests/Mocks/MockSubscriberAttributesManager.swift
  Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
  Tests/UnitTests/SubscriberAttributes/SubscriberAttributesManagerTests.swift
Labels: feat

#3269 Remove ObjC showStoreMessages API
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Misc/Concurrency/Purchases+nonasync.swift
  Sources/Purchasing/Configuration.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesType.swift
  Sources/Support/StoreMessageType.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
  Tests/StoreKitUnitTests/StoreMessageTypeTests.swift
  Tests/StoreKitUnitTests/StoreMessagesHelperTests.swift
  Tests/UnitTests/Mocks/MockPurchases.swift
Labels: refactor

#3265 `Paywalls`: simplified `LoadingPaywallView`
  RevenueCatUI/Views/LoadingPaywallView.swift
  RevenueCatUI/Views/PurchaseButton.swift
Labels: refactor

#3272 `Paywalls`: fixed `macOS` compilation
  RevenueCatUI/Modifiers/ViewExtensions.swift
Labels: fix

#3260 PaywallsTester: allow for configuration for demos
  Tests/TestingApps/PaywallsTester/PaywallsTester/Configuration.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/SimpleApp.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Views/AppContentView.swift
  Tests/TestingApps/PaywallsTester/ci_scripts/ci_pre_xcodebuild.sh
Labels: test

#3273 Update `SwiftLint`
  Brewfile.lock.json
  Tests/RevenueCatUITests/BaseSnapshotTest.swift
  Tests/RevenueCatUITests/Helpers/TestCase.swift
  Tests/v3LoadShedderIntegration/v3LoadShedderIntegration/ViewController.swift
Labels: test

#3276 `Paywalls Tester`: group live paywalls by template
  Tests/TestingApps/PaywallsTester/PaywallsTester/Views/OfferingsList.swift
Labels: test

#3278 `SK2StoreProduct.priceFormatter`: use locale from `StoreKit.Product`
  Sources/Purchasing/StoreKitAbstractions/SK2StoreProduct.swift
  Tests/StoreKitUnitTests/StoreProductTests.swift
Labels: fix

#3281 `AAAttribution.attributionToken`: avoid using on main thread
  Sources/Attribution/AttributionFetcher.swift
  Sources/Attribution/AttributionPoster.swift
  Sources/Purchasing/Purchases/Attribution.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Tests/UnitTests/Attribution/AttributionFetcherTests.swift
  Tests/UnitTests/Attribution/AttributionPosterTests.swift
  Tests/UnitTests/Mocks/MockAttributionFetcher.swift
Labels: perf

#3279 `Paywalls`: improved purchase-in-progress UI
  RevenueCatUI/Data/Constants.swift
  RevenueCatUI/Helpers/PreviewHelpers.swift
  RevenueCatUI/PaywallView.swift
  RevenueCatUI/Templates/Template2View.swift
  RevenueCatUI/Templates/Template4View.swift
  RevenueCatUI/Templates/Template5View.swift
  RevenueCatUI/Views/PackageButtonStyle.swift
  Tests/purchases-ios-snapshots-commit
Labels: RevenueCatUI

#3282 `Tests`: improved flaky test
  Tests/UnitTests/Paywalls/Events/PaywallEventsManagerTests.swift
Labels: test

#3290 Expose `productPlanIdentifier` in `EntitlementInfo`
  Sources/Purchasing/EntitlementInfo.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCEntitlementInfoAPI.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester/EntitlementInfoAPI.swift
Labels: feat

#3274 `Purchases`: new `cachedCustomerInfo` and `cachedOfferings`
  Sources/Purchasing/OfferingsManager.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesType.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
  Tests/UnitTests/Mocks/MockOfferingsManager.swift
  Tests/UnitTests/Mocks/MockPurchases.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesGetCustomerInfoTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesGetOfferingsTests.swift
Labels: feat

#3289 `PaywallEventStore`: changed container to use `URL.applicationSupportDirectory`
  Sources/Paywalls/Events/PaywallEventStore.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
  Tests/UnitTests/Paywalls/Events/PaywallEventStoreTests.swift
Labels: fix

#3283 `Paywalls`: avoid flickering when displaying paywalls with available cache
  RevenueCatUI/PaywallView.swift
Labels: RevenueCatUI

#3292 `Paywalls`: extracted common `TemplateViewType` method for previews
  RevenueCatUI/Helpers/PreviewHelpers.swift
  RevenueCatUI/Templates/TemplateViewType.swift
Labels: refactor

#3294 `CI`: change `visionOS` build to environment with `xrOS` SDK
  .circleci/config.yml
Labels: ci

#3246 `Paywalls`: created `ConsistentPackageContentView` to improve package change transitions
  RevenueCatUI/Data/IntroEligibility/IntroEligibilityViewModel.swift
  RevenueCatUI/Modifiers/ConsistentPackageContentView.swift
  RevenueCatUI/Templates/Template1View.swift
  RevenueCatUI/Templates/Template2View.swift
  RevenueCatUI/Templates/Template3View.swift
  RevenueCatUI/Templates/Template4View.swift
  RevenueCatUI/Templates/Template5View.swift
  RevenueCatUI/Views/PurchaseButton.swift
Labels: RevenueCatUI

#3295 `Paywalls`: localize default template
  RevenueCatUI/Data/PaywallData+Validation.swift
  RevenueCatUI/Helpers/PaywallData+Default.swift
  RevenueCatUI/PaywallView.swift
  RevenueCatUI/Resources/ar.lproj/Localizable.strings
  RevenueCatUI/Resources/bg.lproj/Localizable.strings
  RevenueCatUI/Resources/ca.lproj/Localizable.strings
  RevenueCatUI/Resources/cs.lproj/Localizable.strings
  RevenueCatUI/Resources/da.lproj/Localizable.strings
  RevenueCatUI/Resources/de.lproj/Localizable.strings
  RevenueCatUI/Resources/el.lproj/Localizable.strings
  RevenueCatUI/Resources/en.lproj/Localizable.strings
  RevenueCatUI/Resources/en_AU.lproj/Localizable.strings
  RevenueCatUI/Resources/en_CA.lproj/Localizable.strings
  RevenueCatUI/Resources/en_GB.lproj/Localizable.strings
  RevenueCatUI/Resources/en_US.lproj/Localizable.strings
  RevenueCatUI/Resources/es_419.lproj/Localizable.strings
  RevenueCatUI/Resources/es_ES.lproj/Localizable.strings
  RevenueCatUI/Resources/fi.lproj/Localizable.strings
  RevenueCatUI/Resources/fr_CA.lproj/Localizable.strings
  RevenueCatUI/Resources/he.lproj/Localizable.strings
  RevenueCatUI/Resources/hi.lproj/Localizable.strings
  RevenueCatUI/Resources/hr.lproj/Localizable.strings
  RevenueCatUI/Resources/hu.lproj/Localizable.strings
  RevenueCatUI/Resources/id.lproj/Localizable.strings
  RevenueCatUI/Resources/it.lproj/Localizable.strings
  RevenueCatUI/Resources/ja.lproj/Localizable.strings
  RevenueCatUI/Resources/kk.lproj/Localizable.strings
  RevenueCatUI/Resources/ko.lproj/Localizable.strings
  RevenueCatUI/Resources/ms.lproj/Localizable.strings
  RevenueCatUI/Resources/nl.lproj/Localizable.strings
  RevenueCatUI/Resources/no.lproj/Localizable.strings
  RevenueCatUI/Resources/pl.lproj/Localizable.strings
  RevenueCatUI/Resources/pt_BR.lproj/Localizable.strings
  RevenueCatUI/Resources/pt_PT.lproj/Localizable.strings
  RevenueCatUI/Resources/ro.lproj/Localizable.strings
  RevenueCatUI/Resources/ru.lproj/Localizable.strings
  RevenueCatUI/Resources/sk.lproj/Localizable.strings
  RevenueCatUI/Resources/sv.lproj/Localizable.strings
  RevenueCatUI/Resources/th.lproj/Localizable.strings
  RevenueCatUI/Resources/tr.lproj/Localizable.strings
  RevenueCatUI/Resources/uk.lproj/Localizable.strings
  RevenueCatUI/Resources/vi.lproj/Localizable.strings
  RevenueCatUI/Resources/zh-Hans.lproj/Localizable.strings
  RevenueCatUI/Resources/zh_HK.lproj/Localizable.strings
  RevenueCatUI/Resources/zh_TW.lproj/Localizable.strings
  RevenueCatUI/Views/LoadingPaywallView.swift
  Tests/RevenueCatUITests/Data/PaywallDataValidationTests.swift
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateMissingPaywallWithSpanishLocalization.1.json
  Tests/RevenueCatUITests/Templates/OtherPaywallViewTests.swift
  Tests/purchases-ios-snapshots-commit
Labels: RevenueCatUI

#3303 `Debug View`: display receipt status
  Sources/Support/DebugUI/DebugContentViews.swift
  Sources/Support/DebugUI/DebugViewModel.swift
  Tests/StoreKitUnitTests/Support/__Snapshots__/DebugViewSwiftUITests/iOS16-testDebugView.1.png
Labels: refactor

#3300 `StoreKit 1`: improved debug log for `finishTransactions` invoked outside the SDK
  Sources/Logging/Strings/PurchaseStrings.swift
Labels: refactor

#3311 `CircleCI`: update simulators for Xcode 15.0.1
  .circleci/config.yml
Labels: ci

#3227 `StoreKit 2`: Optionally send JWS tokens instead of receipts to the backend
  RevenueCat.xcodeproj/project.pbxproj
  Sources/LocalReceiptParsing/Helpers/ReceiptStrings.swift
  Sources/Misc/DangerousSettings.swift
  Sources/Misc/Deprecations.swift
  Sources/Networking/Backend.swift
  Sources/Networking/CustomerAPI.swift
  Sources/Networking/OfferingsAPI.swift
  Sources/Networking/Operations/PostOfferForSigningOperation.swift
  Sources/Networking/Operations/PostReceiptDataOperation.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/Purchases/TransactionPoster.swift
  Sources/Purchasing/StoreKit2/StoreKit2TransactionFetcher.swift
  Sources/Purchasing/StoreKit2/StoreKit2TransactionListener.swift
  Sources/Purchasing/StoreKitAbstractions/EncodedAppleReceipt.swift
  Sources/Purchasing/StoreKitAbstractions/SK1StoreTransaction.swift
  Sources/Purchasing/StoreKitAbstractions/SK2StoreTransaction.swift
  Sources/Purchasing/StoreKitAbstractions/StoreTransaction.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCConfigurationAPI.m
  Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/StoreKitUnitTests/StoreKit2/StoreKit2TransactionFetcherTests.swift
  Tests/StoreKitUnitTests/StoreKit2/StoreKit2TransactionListenerTests.swift
  Tests/StoreKitUnitTests/StoreTransactionTests.swift
  Tests/StoreKitUnitTests/TestHelpers/StoreKitConfigTestCase+Extensions.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Core/ConfiguredPurchases.swift
  Tests/UnitTests/Mocks/MockBackend.swift
  Tests/UnitTests/Mocks/MockOfferingsAPI.swift
  Tests/UnitTests/Mocks/MockStoreKit2TransactionFetcher.swift
  Tests/UnitTests/Mocks/MockStoreKit2TransactionListener.swift
  Tests/UnitTests/Mocks/MockStoreTransaction.swift
  Tests/UnitTests/Mocks/MockSystemInfo.swift
  Tests/UnitTests/Networking/Backend/BackendPostOfferForSigningTests.swift
  Tests/UnitTests/Networking/Backend/BackendPostReceiptDataTests.swift
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS12-testPostsJWSTokenWithProductDataCorrectly.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS13-testPostsJWSTokenWithProductDataCorrectly.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS14-testPostsJWSTokenWithProductDataCorrectly.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS15-testPostsJWSTokenWithProductDataCorrectly.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS16-testPostsJWSTokenWithProductDataCorrectly.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS17-testPostsJWSTokenWithProductDataCorrectly.1.json
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesRestoreTests.swift
  Tests/UnitTests/Purchasing/Purchases/TransactionPosterTests.swift
  Tests/UnitTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift
  Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Labels: refactor

#3312 `CI`: run all iOS 17 tests
  .circleci/config.yml
  Tests/StoreKitUnitTests/Support/__Snapshots__/DebugViewSwiftUITests/iOS17-testDebugView.1.png
Labels: ci

#3317 `PaywallEventStore`: also remove legacy `revenuecat` documents directory
  Sources/Paywalls/Events/PaywallEventStore.swift
Labels: fix

#2857 `CI`: added workaround for Snapshots in `Xcode Cloud`
  .circleci/config.yml
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCat.xcodeproj/xcshareddata/xcschemes/RevenueCat.xcscheme
  Sources/LocalReceiptParsing/Helpers/ProcessInfo+Extensions.swift
  Tests/StoreKitUnitTests/Support/DebugViewSwiftUITests.swift
  Tests/TestPlans/XC-AllTests.xctestplan
  Tests/UnitTests/Misc/AnyEncodableTests.swift
  Tests/UnitTests/Purchasing/ProductRequestDataTests.swift
  Tests/UnitTests/TestHelpers/SnapshotTesting+Extensions.swift
  ci_scripts/Tests
Labels: blocked, ci

#3323 `Paywalls`: new `.onPurchaseCompleted` overload with `StoreTransaction`
  RevenueCatUI/PaywallView.swift
  RevenueCatUI/Purchasing/PurchaseHandler+TestData.swift
  RevenueCatUI/Purchasing/PurchaseHandler.swift
  RevenueCatUI/UIKit/PaywallViewController.swift
  RevenueCatUI/View+PurchaseRestoreCompleted.swift
  Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewAPI.swift
  Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewControllerAPI.swift
  Tests/RevenueCatUITests/PurchaseCompletedHandlerTests.swift
  Tests/RevenueCatUITests/Purchasing/PurchaseHandlerTests.swift
Labels: feat, RevenueCatUI

#3321 `Paywalls Tester`: fix release build
  Tests/TestingApps/PaywallsTester/PaywallsTester/Views/AppContentView.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Views/OfferingsList.swift
Labels: test

#3324 `Paywalls`: disable shimmering on footer loading view
  RevenueCatUI/Views/LoadingPaywallView.swift
  RevenueCatUI/Views/TemplateBackgroundImageView.swift
  Tests/purchases-ios-snapshots-commit
Labels: RevenueCatUI

#3322 `CircleCI`: change iOS 17 job to use M1 Large resource
  .circleci/config.yml
Labels: ci

#3328 `Integration Tests`: new logs for troubleshooting flaky tests
  Sources/Logging/Strings/OfflineEntitlementsStrings.swift
  Sources/OfflineEntitlements/PurchasedProductsFetcher.swift
  Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift
  Tests/BackendIntegrationTests/Helpers/TestMessage.swift
Labels: test

#3338 `CI`: replace Carthage build jobs with `xcodebuild`
  fastlane/Fastfile
Labels: ci

#3330 `Paywalls`: create new event session when paywall appears
  RevenueCatUI/PaywallView.swift
  RevenueCatUI/Purchasing/PurchaseHandler.swift
  Tests/RevenueCatUITests/Purchasing/PurchaseHandlerTests.swift
Labels: fix, RevenueCatUI

#3339 `Paywall Tester`: fixed paywall presentation
  Tests/TestingApps/PaywallsTester/PaywallsTester/Views/OfferingsList.swift
Labels: test

#3327 `ProductFetcherSK1`: enable `TimingUtil` log
  Sources/Purchasing/ProductsManager.swift
  Sources/Purchasing/StoreKit1/ProductsFetcherSK1.swift
  Tests/UnitTests/Purchasing/ProductsFetcherSK1Tests.swift
Labels: refactor

#3332 `Paywalls`: add identifier to events
  RevenueCatUI/Purchasing/PurchaseHandler.swift
  Sources/Networking/Operations/PostReceiptDataOperation.swift
  Sources/Paywalls/Events/Networking/PaywallEventsRequest.swift
  Sources/Paywalls/Events/PaywallEvent.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/Purchases/TransactionPoster.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PaywallAPI.swift
  Tests/BackendIntegrationTests/PaywallEventsIntegrationTests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/UnitTests/Networking/Backend/BackendPostReceiptDataTests.swift
  Tests/UnitTests/Paywalls/Events/PaywallEventSerializerTests.swift
  Tests/UnitTests/Paywalls/Events/PaywallEventStoreTests.swift
  Tests/UnitTests/Paywalls/Events/PaywallEventsBackendTests.swift
  Tests/UnitTests/Paywalls/Events/PaywallEventsManagerTests.swift
  Tests/UnitTests/Paywalls/Events/PaywallEventsRequestTests.swift
  Tests/UnitTests/Paywalls/Events/__Snapshots__/PaywallEventsBackendTests/iOS15-testPostPaywallEventsWithMultipleEvents.1.json
  Tests/UnitTests/Paywalls/Events/__Snapshots__/PaywallEventsBackendTests/iOS15-testPostPaywallEventsWithOneEvent.1.json
  Tests/UnitTests/Paywalls/Events/__Snapshots__/PaywallEventsBackendTests/iOS16-testPostPaywallEventsWithMultipleEvents.1.json
  Tests/UnitTests/Paywalls/Events/__Snapshots__/PaywallEventsBackendTests/iOS16-testPostPaywallEventsWithOneEvent.1.json
  Tests/UnitTests/Paywalls/Events/__Snapshots__/PaywallEventsBackendTests/iOS17-testPostPaywallEventsWithMultipleEvents.1.json
  Tests/UnitTests/Paywalls/Events/__Snapshots__/PaywallEventsBackendTests/iOS17-testPostPaywallEventsWithOneEvent.1.json
  Tests/UnitTests/Paywalls/Events/__Snapshots__/PaywallEventsRequestTests/testCancelEvent.1.json
  Tests/UnitTests/Paywalls/Events/__Snapshots__/PaywallEventsRequestTests/testCloseEvent.1.json
  Tests/UnitTests/Paywalls/Events/__Snapshots__/PaywallEventsRequestTests/testImpressionEvent.1.json
Labels: refactor, RevenueCatUI

#3320 `HTTPClient`: verbose logs for request IDs
  Sources/FoundationExtensions/OperationQueue+Extensions.swift
  Sources/Logging/Logger.swift
  Sources/Logging/Strings/NetworkStrings.swift
  Sources/Networking/HTTPClient/ETagManager.swift
  Sources/Networking/HTTPClient/HTTPClient.swift
  Sources/Networking/HTTPClient/HTTPResponse.swift
  Sources/Networking/HTTPClient/HTTPStatusCode.swift
  Sources/Networking/Operations/Handling/CustomerInfoResponseHandler.swift
  Sources/Networking/Operations/LogInOperation.swift
  Sources/Networking/Operations/PostOfferForSigningOperation.swift
  Sources/Security/Signing+ResponseVerification.swift
  Tests/BackendIntegrationTests/OtherIntegrationTests.swift
  Tests/UnitTests/Mocks/MockHTTPClient.swift
  Tests/UnitTests/Networking/ETagManagerTests.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
  Tests/UnitTests/Networking/HTTPResponseTests.swift
  Tests/UnitTests/Networking/SignatureVerificationHTTPClientTests.swift
  Tests/UnitTests/OfflineEntitlements/CustomerInfoResponseHandlerTests.swift
  Tests/UnitTests/Security/SigningTests.swift
Labels: refactor

#3345 `PaywallColor`: change visibility of `Color.init(light:dark:)` to `private`
  Sources/Paywalls/PaywallColor.swift
Labels: feat

#3346 `ErrorUtils.purchasesError(withSKError:)`: handle `URLError`s
  Sources/Error Handling/ErrorUtils.swift
  Sources/Networking/HTTPClient/HTTPClient.swift
  Sources/Networking/HTTPClient/NetworkError.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
  Tests/UnitTests/Networking/NetworkErrorTests.swift
  Tests/UnitTests/Paywalls/Events/PaywallEventsManagerTests.swift
  Tests/UnitTests/Purchasing/ErrorUtilsTests.swift
Labels: fix

#3342 `Paywalls`: new `onDismiss` parameter for `presentPaywallIfNeeded`
  RevenueCatUI/View+PresentPaywall.swift
  Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewAPI.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Views/UpsellView.swift
Labels: RevenueCatUI

#3340 `Paywalls`: finished template 5
  RevenueCatUI/Data/PaywallTemplate.swift
  RevenueCatUI/Data/TestData.swift
  RevenueCatUI/Helpers/ColorInformation+MultiScheme.swift
  RevenueCatUI/Templates/Template5View.swift
  Sources/Paywalls/PaywallData.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PaywallAPI.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/SamplePaywalls.swift
  Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-Sample1.json
  Tests/UnitTests/Paywalls/PaywallDataTests.swift
  Tests/purchases-ios-snapshots-commit
Labels: RevenueCatUI

#3349 `Paywalls`: improve `FooterView` accessibility
  RevenueCatUI/Views/FooterView.swift
Labels: RevenueCatUI

#3352 `Paywalls`: move size configuration to `TemplateViewType`
  RevenueCatUI/PaywallView.swift
  RevenueCatUI/Templates/TemplateViewType.swift
Labels: refactor

#3348 `Paywalls Tester`: improve `.paywallFooter` presentation
  Tests/TestingApps/PaywallsTester/PaywallsTester/Views/CustomPaywall.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Views/CustomPaywallContent.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Views/OfferingsList.swift
Labels: test

#3357 `Paywalls`: improve conversion from `Color`/`UIColor` to `PaywallColor`
  RevenueCatUI/Data/TestData.swift
  Sources/Paywalls/PaywallColor.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PaywallAPI.swift
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedIconsGeneratesDefaultPaywall.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedTemplateNameGeneratesDefaultPaywall.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedVariableGeneratesDefaultPaywall.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedVariableInFeaturesGeneratesDefaultPaywall.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateMissingPaywall.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateMissingPaywallWithSpanishLocalization.1.json
  Tests/RevenueCatUITests/Helpers/DataExtensions.swift
  Tests/UnitTests/Paywalls/PaywallColorTests.swift
  Tests/purchases-ios-snapshots-commit
Labels: refactor

#3359 `Paywalls`: new optional `displayCloseButton` parameter
  RevenueCatUI/PaywallView.swift
  RevenueCatUI/View+PresentPaywall.swift
  RevenueCatUI/Views/LoadingPaywallView.swift
  Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewAPI.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Views/AppContentView.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Views/OfferingsList.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Views/SamplePaywallsList.swift
Labels: feat, RevenueCatUI

#3360 `Paywalls`: refactored `IntroEligibilityStateView`
  RevenueCatUI/Templates/Template1View.swift
  RevenueCatUI/Templates/Template2View.swift
  RevenueCatUI/Templates/Template3View.swift
  RevenueCatUI/Templates/Template4View.swift
  RevenueCatUI/Templates/Template5View.swift
  RevenueCatUI/Views/IntroEligibilityStateView.swift
  RevenueCatUI/Views/PurchaseButton.swift
Labels: refactor

#3363 `Paywalls`: fix template 2 top padding inside navigation view
  RevenueCatUI/Templates/Template2View.swift
Labels: RevenueCatUI

#3362 `Paywalls`: simplify `PurchaseButton`
  RevenueCatUI/Views/IntroEligibilityStateView.swift
  RevenueCatUI/Views/PurchaseButton.swift
Labels: refactor

#3364 `Paywalls`: improve Japanese localization
  RevenueCatUI/Resources/ja.lproj/Localizable.strings
Labels: RevenueCatUI

#3366 `Paywalls`: log warning when attempting to purchase already-subscribed product
  RevenueCatUI/Data/Strings.swift
  RevenueCatUI/Views/PurchaseButton.swift
Labels: RevenueCatUI
