Repository RevenueCat/purchases-ios, pull requests merged in 2023-02, with the labels that each got.

#2254 Update `Gemfile.lock`
  Gemfile.lock
Labels: dependencies

#2247 `IntroEligibilityCalculator`: changed logic to handle products with no subscription group
  Sources/Purchasing/IntroEligibilityCalculator.swift
  Tests/UnitTests/Purchasing/IntroEligibilityCalculatorTests.swift
Labels: refactor

#2258 `StoreKit1WrapperTests`: avoid using `Bool.random` to fix flaky code coverage
  Tests/UnitTests/Purchasing/StoreKit1WrapperTests.swift
Labels: test

#2259 Adds dependabot
  .github/dependabot.yml
  Gemfile
Labels: ci

#2249 PurchaseTester: Add Receipt Inspector UI
  Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/project.pbxproj
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/PurchaseTesterApp.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/ReceiptInspector.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/ReceiptVerifier.swift
Labels: test

#2257 `HTTPClientTests`: refactored tests to use `waitUntil`
  Tests/UnitTests/Networking/HTTPClientTests.swift
Labels: test

#2262 `HTTPClientTests`: fixed failing test with missing assertions
  Tests/UnitTests/Networking/HTTPClientTests.swift
Labels: test

#2250 Replaced `Any` uses for workaround with `Box`
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Misc/Box.swift
  Sources/Purchasing/StoreKitAbstractions/SK2StoreProduct.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/UnitTests/Mocks/MockNotificationCenter.swift
  Tests/UnitTests/Mocks/MockSK2BeginRefundRequestHelper.swift
Labels: refactor

#2215 `Configuration`: added (`internal` for now) API to load public key
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Logging/Strings/ConfigureStrings.swift
  Sources/Misc/Deprecations.swift
  Sources/Misc/Signing.swift
  Sources/Misc/SystemInfo.swift
  Sources/Purchasing/Configuration.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Support/public_key.der
  Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
  Tests/UnitTests/Misc/SigningTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
  Tests/UnitTests/Resources/public_keys/invalid_certificate.cer
Labels: refactor

#2216 Created `Signing.verify(message:hasValidSignature:with:)`
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Logging/Strings/SigningStrings.swift
  Sources/Logging/Strings/Strings.swift
  Sources/Misc/Signing.swift
  Tests/UnitTests/Misc/SigningTests.swift
Labels: refactor

#2263 `NetworkError`: added underlying error to description
  Sources/Error Handling/ErrorUtils.swift
  Tests/UnitTests/Purchasing/ErrorUtilsTests.swift
Labels: refactor

#2265 `StoreKit2StorefrontListener`: added tests to fix flaky code coverage
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/StoreKit2/StoreKit2StorefrontListener.swift
  Sources/Purchasing/StoreKitAbstractions/Storefront.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/StoreKitUnitTests/StoreKit2StorefrontListenerTests.swift
  Tests/UnitTests/Mocks/MockAsyncSequence.swift
Labels: test

#2276 `BundleSandboxEnvironmentDetector`: always return `true` when running on simulator
  Sources/Misc/SandboxEnvironmentDetector.swift
  Sources/Misc/SystemInfo.swift
  Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
  Tests/UnitTests/Misc/SandboxEnvironmentDetectorTests.swift
  Tests/UnitTests/Misc/SystemInfoTests.swift
Labels: fix

#2279 `EntitlementInfos.all`: fixed docstring
  Sources/Purchasing/EntitlementInfos.swift
Labels: docs

#2282 Updated targets and schemes for Xcode 14.2
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCat.xcodeproj/xcshareddata/xcschemes/BackendIntegrationTests.xcscheme
  RevenueCat.xcodeproj/xcshareddata/xcschemes/ReceiptParser.xcscheme
  RevenueCat.xcodeproj/xcshareddata/xcschemes/RevenueCat.xcscheme
  Tests/APITesters/ObjCAPITester/ObjCAPITester.xcodeproj/project.pbxproj
  Tests/APITesters/ObjCAPITester/ObjCAPITester.xcodeproj/xcshareddata/xcschemes/ObjCAPITester.xcscheme
  Tests/APITesters/ReceiptParserAPITester/ReceiptParserAPITester.xcodeproj/project.pbxproj
  Tests/APITesters/ReceiptParserAPITester/ReceiptParserAPITester.xcodeproj/xcshareddata/xcschemes/ReceiptParserAPITester.xcscheme
  Tests/APITesters/SwiftAPITester/SwiftAPITester.xcodeproj/project.pbxproj
  Tests/APITesters/SwiftAPITester/SwiftAPITester.xcodeproj/xcshareddata/xcschemes/SwiftAPITester.xcscheme
Labels: build

#2285 `BaseBackendTest`: improved test failure message
  Tests/UnitTests/Networking/Backend/BaseBackendTest.swift
Labels: test

#2284 `UserDefaultsDefaultTests`: fixed flaky failures
  Tests/StoreKitUnitTests/UserDefaultsDefaultTests.swift
  Tests/UnitTests/Misc/XCTestCase+Extensions.swift
Labels: test

#2280 `PurchaseOrchestrator`: always refresh receipt purchasing in sandbox
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift
Labels: fix

#2272 `HTTPClient`: added signature validation and introduced `ErrorCode.signatureVerificationFailed`
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Error Handling/ErrorCode.swift
  Sources/Error Handling/ErrorUtils.swift
  Sources/Logging/Strings/SigningStrings.swift
  Sources/Misc/Signing+ResponseValidation.swift
  Sources/Misc/Signing.swift
  Sources/Networking/HTTPClient/ETagManager.swift
  Sources/Networking/HTTPClient/HTTPClient.swift
  Sources/Networking/HTTPClient/HTTPRequest.swift
  Sources/Networking/HTTPClient/HTTPResponse.swift
  Sources/Networking/HTTPClient/NetworkError.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesErrorCodeAPI.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester/ErrorCodesAPI.swift
  Tests/UnitTests/Misc/SigningTests.swift
  Tests/UnitTests/Mocks/MockETagManager.swift
  Tests/UnitTests/Mocks/MockHTTPClient.swift
  Tests/UnitTests/Mocks/MockSigning.swift
  Tests/UnitTests/Networking/ETagManagerTests.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
  Tests/UnitTests/Networking/HTTPResponseTests.swift
  Tests/UnitTests/Purchasing/ErrorCodeTests.swift
Labels: feat

#2274 `Signing`: updated to use production public key
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Logging/Strings/SigningStrings.swift
  Sources/Misc/Signing.swift
  Sources/Purchasing/Configuration.swift
  Sources/Support/public_key.der
  Tests/UnitTests/Misc/SigningTests.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
Labels: refactor

#2267 `PurchasesDiagnostics`: added step to verify signature verification
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Error Handling/ErrorUtils.swift
  Sources/Networking/Backend.swift
  Sources/Networking/HTTPClient/HTTPClient.swift
  Sources/Networking/HTTPClient/HTTPRequest.swift
  Sources/Networking/InternalAPI.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesType.swift
  Sources/Support/PurchasesDiagnostics.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesDiagnosticsAPI.swift
  Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
  Tests/BackendIntegrationTests/OtherIntegrationTests.swift
  Tests/UnitTests/Misc/PurchasesDiagnosticsTests.swift
  Tests/UnitTests/Mocks/MockHTTPClient.swift
  Tests/UnitTests/Mocks/MockPurchases.swift
  Tests/UnitTests/Networking/Backend/BackendInternalTests.swift
  Tests/UnitTests/Networking/Backend/BackendSignatureVerificationTests.swift
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendSignatureVerificationTests/iOS12-testRequestContainsSignatureHeader.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendSignatureVerificationTests/iOS12-testRequestFailsIfSignatureVerificationFails.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendSignatureVerificationTests/iOS13-testRequestContainsSignatureHeader.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendSignatureVerificationTests/iOS13-testRequestFailsIfSignatureVerificationFails.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendSignatureVerificationTests/iOS14-testRequestContainsSignatureHeader.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendSignatureVerificationTests/iOS14-testRequestFailsIfSignatureVerificationFails.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendSignatureVerificationTests/iOS15-testRequestContainsSignatureHeader.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendSignatureVerificationTests/iOS15-testRequestFailsIfSignatureVerificationFails.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendSignatureVerificationTests/iOS16-testRequestContainsSignatureHeader.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendSignatureVerificationTests/iOS16-testRequestFailsIfSignatureVerificationFails.1.json
Labels: feat, test

#2292 Fixed `PurchasesOrchestrator` compilation error on Xcode 14.3 beta 1
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
Labels: fix

#2294 clarifies error messages for storekit 1 bugs
  Sources/Logging/Strings/PurchaseStrings.swift
  Sources/Purchasing/StoreKitAbstractions/SK1StoreTransaction.swift
  Sources/Purchasing/StoreKitAbstractions/StoreKitWorkarounds.swift
Labels: docs

#2295 SK2-config deprecation: fixed tests
  Sources/Misc/Deprecations.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
Labels: test

#2293 Deprecate `usesStoreKit2IfAvailable`
  Sources/Misc/Deprecations.swift
  Sources/Purchasing/Configuration.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/ConfigurationAPI.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
Labels: docs

#2307 Release 4.17.7 changelog
  CHANGELOG.latest.md
  CHANGELOG.md
Labels: next_release

#2290 `PurchaseTester`: added ability to set `Configuration.EntitlementVerificationMode`
  Tests/TestingApps/PurchaseTesterSwiftUI/Core/ConfiguredPurchases.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Extensions/Extensions.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/PurchaseTesterApp.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/ConfigurationView.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Customer/CustomerInfoView.swift
Labels: test

#2281 Fix issue where underlying error information for product fetch errors was not printed in log.
  Sources/Purchasing/StoreKit2/ProductsFetcherSK2.swift
Labels: refactor

#2311 `PurchaseTester`: fixed leak when reconfiguring `Purchases`
  Tests/TestingApps/PurchaseTesterSwiftUI/Core/ConfiguredPurchases.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/ContentView.swift
Labels: test

#2304 `RELEASING.md`: fixed hotfix instructions
  Contributing/RELEASING.md
Labels: docs

#2312 `PurchaseTester`: added ability to reload `CustomerInfo` with a custom `CacheFetchPolicy`
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Extensions/Extensions.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift
Labels: test

#2286 `HTTPClient`: automatically add `nonce` based on `HTTPRequest.Path`
  Sources/Misc/Signing.swift
  Sources/Networking/HTTPClient/HTTPClient.swift
  Sources/Networking/HTTPClient/HTTPRequest.swift
  Sources/Networking/InternalAPI.swift
  Tests/UnitTests/Mocks/MockHTTPClient.swift
  Tests/UnitTests/Networking/Backend/BackendGetCustomerInfoTests.swift
  Tests/UnitTests/Networking/Backend/BackendSignatureVerificationTests.swift
  Tests/UnitTests/Networking/Backend/BaseBackendTest.swift
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerInfoTests/iOS12-testSendsNonceWhenEnabled.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerInfoTests/iOS13-testSendsNonceWhenEnabled.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerInfoTests/iOS14-testSendsNonceWhenEnabled.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerInfoTests/iOS15-testSendsNonceWhenEnabled.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerInfoTests/iOS16-testSendsNonceWhenEnabled.1.json
  Tests/UnitTests/Networking/HTTPClientTests.swift
  Tests/UnitTests/Networking/HTTPRequestTests.swift
Labels: refactor

#2308 `HTTPClient`: changed header search to be case-insensitive
  Sources/Misc/Signing+ResponseVerification.swift
  Sources/Networking/HTTPClient/ETagManager.swift
  Sources/Networking/HTTPClient/HTTPClient.swift
  Sources/Networking/HTTPClient/HTTPRequest.swift
  Sources/Networking/HTTPClient/HTTPResponse.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
  Tests/UnitTests/Networking/HTTPResponseTests.swift
Labels: refactor

#2313 Fix issue with missing subscriber attributes if set after login but before login callback
  Sources/Caching/DeviceCache.swift
  Sources/Identity/IdentityManager.swift
  Sources/Logging/Strings/AttributionStrings.swift
  Sources/Logging/Strings/IdentityStrings.swift
  Tests/UnitTests/Caching/DeviceCacheTests.swift
  Tests/UnitTests/Identity/IdentityManagerTests.swift
  Tests/UnitTests/Mocks/MockDeviceCache.swift
Labels: fix

#2309 `Signing`: added request time & eTag to signature verification
  Sources/FoundationExtensions/Date+Extensions.swift
  Sources/Logging/Strings/SigningStrings.swift
  Sources/Misc/Signing+ResponseVerification.swift
  Sources/Misc/Signing.swift
  Sources/Networking/HTTPClient/ETagManager.swift
  Sources/Networking/HTTPClient/HTTPClient.swift
  Tests/UnitTests/Misc/SigningTests.swift
  Tests/UnitTests/Mocks/MockETagManager.swift
  Tests/UnitTests/Mocks/MockSigning.swift
  Tests/UnitTests/Networking/ETagManagerTests.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
Labels: refactor

#2315 Remove Logging Typo
  Sources/Logging/Strings/StoreKitStrings.swift
Labels: refactor
