Repository RevenueCat/purchases-ios, pull requests merged in 2024-06, with the labels that each got.

#3935 Revert docs-deploy to xcode 14
  .circleci/config.yml
  fastlane/Fastfile
Labels: ci

#3931 Diagnostics: Make setting public
  Sources/Purchasing/Configuration.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCConfigurationAPI.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester/ConfigurationAPI.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Core/ConfiguredPurchases.swift
Labels: feat

#3939 Fix prepare next version job
  .circleci/config.yml
Labels: ci

#3946 Drop xcode 14 support in v5
  .circleci/config.yml
  README.md
Labels: breaking, ci

#3951 Remove Original Application Version Section from Migration Guide
  Sources/DocCDocumentation/DocCDocumentation.docc/V5_API_Migration_guide.md
Labels: docs

#3958 Switch tests for iOS 12 and 13 to M1
  .circleci/config.yml
Labels: ci

#3956 Deprecate observer mode in 5.0 branch
  .circleci/config.yml
  Examples/MagicWeather/MagicWeather/Sources/Lifecycle/AppDelegate.swift
  Examples/MagicWeatherSwiftUI/Shared/Sources/Lifecycle/MagicWeatherApp.swift
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/Purchasing/MockPurchases.swift
  RevenueCatUI/Purchasing/PurchaseHandler+TestData.swift
  Sources/DocCDocumentation/DocCDocumentation.docc/RevenueCat.md
  Sources/DocCDocumentation/DocCDocumentation.docc/V5_API_Migration_guide.md
  Sources/Logging/Strings/ConfigureStrings.swift
  Sources/Logging/Strings/PurchaseStrings.swift
  Sources/Misc/Deprecations.swift
  Sources/Misc/Obsoletions.swift
  Sources/Purchasing/Configuration.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesAreCompletedBy.swift
  Sources/Purchasing/Purchases/PurchasesType.swift
  Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/ConfigurationAPI.swift
  Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/PurchasesAPI.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCConfigurationAPI.m
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester/ConfigurationAPI.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
  Tests/BackendIntegrationTests/StoreKitObserverModeIntegrationTests.swift
  Tests/RevenueCatUITests/PurchaseCompletedHandlerTests.swift
  Tests/UnitTests/Mocks/MockPurchases.swift
  Tests/UnitTests/Purchasing/ConfigurationTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift
Labels: refactor

#3947 finishTransactions/ObserverMode -> PurchasesAreCompletedBy
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/Purchasing/MockPurchases.swift
  RevenueCatUI/Purchasing/PurchaseHandler+TestData.swift
  Sources/Purchasing/Configuration.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesAreCompletedBy.swift
  Sources/Purchasing/Purchases/PurchasesType.swift
  Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/ConfigurationAPI.swift
  Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/PurchasesAPI.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCConfigurationAPI.m
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester/ConfigurationAPI.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
  Tests/RevenueCatUITests/PurchaseCompletedHandlerTests.swift
  Tests/UnitTests/Mocks/MockPurchases.swift
  Tests/UnitTests/Purchasing/ConfigurationTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift
Labels: refactor

#3960 Xcode project with RevenueCatUI + Tests
  .swiftpm/xcode/xcshareddata/xcschemes/RevenueCatUITests.xcscheme
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCat.xcodeproj/xcshareddata/xcschemes/RevenueCatUIDev.xcscheme
  RevenueCat.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  RevenueCatUI/Data/Localization.swift
  RevenueCatUI/Data/PaywallViewMode+Extensions.swift
  RevenueCatUI/Helpers/Bundle+Extensions.swift
  RevenueCatUI/RevenueCatUIDev.xctestplan
  RevenueCatUIDev/RevenueCatUIDev.h
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/SamplePaywallsList.swift
Labels: build

#3961 Run offline backend integration tests on M1 machines
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift
  Tests/BackendIntegrationTests/OfflineStoreKitIntegrationTests.swift
  Tests/BackendIntegrationTests/PaywallEventsIntegrationTests.swift
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
  Tests/BackendIntegrationTests/StoreKitObserverModeIntegrationTests.swift
  Tests/StoreKitUnitTests/StoreKit2/StoreKit2TransactionListenerTests.swift
  Tests/StoreKitUnitTests/TestHelpers/StoreKitTestHelpers.swift
  Tests/TestingApps/PurchaseTester/RevenueCat_IntegrationPurchaseTesterConfiguration.storekit
  fastlane/Fastfile
  fastlane/README.md
  fastlane/actions/retry_scan_save_failed_tests.rb
Labels: ci

#3974 Revert "Run offline backend integration tests on M1 machines (#3961)"
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift
  Tests/BackendIntegrationTests/OfflineStoreKitIntegrationTests.swift
  Tests/BackendIntegrationTests/PaywallEventsIntegrationTests.swift
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
  Tests/BackendIntegrationTests/StoreKitObserverModeIntegrationTests.swift
  Tests/StoreKitUnitTests/StoreKit2/StoreKit2TransactionListenerTests.swift
  Tests/StoreKitUnitTests/TestHelpers/StoreKitTestHelpers.swift
  Tests/TestingApps/PurchaseTester/RevenueCat_IntegrationPurchaseTesterConfiguration.storekit
  fastlane/Fastfile
  fastlane/README.md
  fastlane/actions/retry_scan_save_failed_tests.rb
Labels: test

#3978 Fix Carthage
  Tests/InstallationTests/CarthageInstallation/fastlane/Fastfile
Labels: build

#3976 Bring back offline integration tests on M1
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift
  Tests/BackendIntegrationTests/OfflineStoreKitIntegrationTests.swift
  Tests/BackendIntegrationTests/PaywallEventsIntegrationTests.swift
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
  Tests/BackendIntegrationTests/StoreKitObserverModeIntegrationTests.swift
  Tests/StoreKitUnitTests/StoreKit2/StoreKit2TransactionListenerTests.swift
  Tests/StoreKitUnitTests/TestHelpers/StoreKitTestHelpers.swift
  Tests/TestingApps/PurchaseTester/RevenueCat_IntegrationPurchaseTesterConfiguration.storekit
  fastlane/Fastfile
  fastlane/README.md
  fastlane/actions/retry_scan_save_failed_tests.rb
Labels: ci

#3927 Remove carthage from CI and update release jobs to use xcode 15 and M1
  .circleci/config.yml
  fastlane/Fastfile
  scripts/carthage.sh
Labels: ci

#3981 Fix cocoapods installation tests
  Tests/InstallationTests/CocoapodsInstallation/Gemfile
Labels: test

#3953 AppTransaction Integration Tests
  Sources/Networking/HTTPClient/HTTPRequestBody.swift
  Sources/Networking/Operations/LogInOperation.swift
  Sources/Networking/Operations/PostReceiptDataOperation.swift
  Sources/Security/HTTPRequestBody+Signing.swift
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS13-testGetsEntitlementsWithFailedVerification.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS13-testGetsEntitlementsWithVerifiedResponse.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS14-testGetsEntitlementsWithFailedVerification.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS14-testGetsEntitlementsWithVerifiedResponse.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS15-testGetsEntitlementsWithFailedVerification.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS15-testGetsEntitlementsWithVerifiedResponse.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS16-testGetsEntitlementsWithFailedVerification.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS16-testGetsEntitlementsWithVerifiedResponse.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS17-testGetsEntitlementsWithFailedVerification.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS17-testGetsEntitlementsWithVerifiedResponse.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/macOS-testGetsEntitlementsWithFailedVerification.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/macOS-testGetsEntitlementsWithVerifiedResponse.1.json
  Tests/UnitTests/Networking/HTTPClientTests.swift
Labels: test

#3992 Fix OS versions in migration guide
  Sources/DocCDocumentation/DocCDocumentation.docc/V5_API_Migration_guide.md
Labels: docs

#3993 Remove AdClient framework related code
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Attribution/AfficheClientProxy.swift
  Sources/Attribution/AttributionFetcher.swift
  Sources/Attribution/AttributionPoster.swift
  Sources/Attribution/AttributionTypeFactory.swift
  Sources/Logging/Strings/AttributionStrings.swift
  Sources/Misc/Deprecations.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/UnitTests/Attribution/AttributionPosterTests.swift
  Tests/UnitTests/Mocks/MockAttributionTypeFactory.swift
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesAttributionDataTests.swift
  Tests/UnitTests/Purchasing/PurchasesDeprecation.swift
  Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Labels: fix

#3994 Remove AdClient framework related code (on v5)
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Attribution/AfficheClientProxy.swift
  Sources/Attribution/AttributionFetcher.swift
  Sources/Attribution/AttributionPoster.swift
  Sources/Attribution/AttributionTypeFactory.swift
  Sources/Logging/Strings/AttributionStrings.swift
  Sources/Misc/Deprecations.swift
  Sources/Misc/Obsoletions.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
  Tests/UnitTests/Attribution/AttributionPosterTests.swift
  Tests/UnitTests/Mocks/MockAttributionTypeFactory.swift
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesAttributionDataTests.swift
  Tests/UnitTests/Purchasing/PurchasesDeprecation.swift
  Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Labels: fix

#3997 Fix observer mode obsoletion messages
  Sources/Misc/Obsoletions.swift
Labels: fix, docs
