Repository RevenueCat/purchases-ios, pull requests merged in 2024-05, with the labels that each got.

#3849 Paywalls Tester Refresh Data
  Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/project.pbxproj
  Tests/TestingApps/PaywallsTester/PaywallsTester/Data/ApplicationData.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Networking/HTTPClient.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Networking/HTTPEndpoint.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Networking/HTTPMethod.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Networking/HTTPRequest.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Responses/DeveloperResponse.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Responses/OfferingsResponse.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Responses/PaywallsResponse.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/AppList.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/Login/LoginWall.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingsList.swift
Labels: feat

#3868 Paywalls Tester 0.1
  Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/project.pbxproj
  Tests/TestingApps/PaywallsTester/PaywallsTester/Assets.xcassets/AccentColor.colorset/Contents.json
  Tests/TestingApps/PaywallsTester/PaywallsTester/Assets.xcassets/logo.imageset/Contents.json
  Tests/TestingApps/PaywallsTester/PaywallsTester/Assets.xcassets/logo.imageset/logo46 1.png
  Tests/TestingApps/PaywallsTester/PaywallsTester/Assets.xcassets/logo.imageset/logo46.png
  Tests/TestingApps/PaywallsTester/PaywallsTester/Assets.xcassets/logo.imageset/logo69.png
  Tests/TestingApps/PaywallsTester/PaywallsTester/Configuration.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Data/ApplicationData.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Data/ApplicationManager.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Data/AuthenticationActor.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Data/OfferingsPaywallsViewModel.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Data/TemplateInfo.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Extensions/ArrayExtensions.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Extensions/JSONExtensions.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Extensions/StringExtensions.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Extensions/UserDefaultsExtensions.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Logging/Logging.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Mocks/MockData.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Networking/HTTPClient.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Networking/HTTPEndpoint.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Networking/HTTPMethod.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Networking/HTTPRequest.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Networking/HTTPStatusCode.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/PaywallsPreview.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/PaywallsTester.entitlements
  Tests/TestingApps/PaywallsTester/PaywallsTester/Responses/DeveloperResponse.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Responses/ErrorResponse.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Responses/LoginResponse.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Responses/OfferingsResponse.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Responses/PaywallsResponse.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/SamplePaywalls.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/SimpleApp.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Utility Views/AsyncButton.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Utility Views/ErrorDisplay.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/AppContentView.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/AppList.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/CustomPaywall.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/CustomPaywallContent.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/DebugView.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/Login/LoginScreen.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/Login/LoginWall.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingList/ManagePaywallButton.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingList/OfferingButton.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingList/OfferingsList.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/PaywallForID.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/PaywallPresenter.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/PaywallViewMode+Extensions.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/SamplePaywallsList.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/UpsellView.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Views/OfferingsList.swift
Labels: test

#3878 Cleanup: Remove test storekit configuration files when importing through SPM
  Tests/Package.swift
Labels: ci

#3869 Paywalls Tester: Use key defined in CI
  Tests/TestingApps/PaywallsTester/PaywallsTester/Configuration.swift
  Tests/TestingApps/PaywallsTester/ci_scripts/ci_pre_xcodebuild.sh
Labels: test

#3880 Preprocessor to make select constructs public
  RevenueCatUI/Data/IntroEligibility/TrialOrIntroEligibilityChecker+TestData.swift
  RevenueCatUI/Data/IntroEligibility/TrialOrIntroEligibilityChecker.swift
  RevenueCatUI/Data/PaywallViewConfiguration.swift
  RevenueCatUI/Modifiers/ViewExtensions.swift
  RevenueCatUI/PaywallView.swift
  RevenueCatUI/Purchasing/PurchaseHandler.swift
  RevenueCatUI/View+PresentPaywallFooter.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/project.pbxproj
  Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/xcshareddata/xcschemes/PaywallsTester - Live Config.xcscheme
  Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/xcshareddata/xcschemes/PaywallsTester - SK config.xcscheme
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/CustomPaywallContent.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingList/OfferingsList.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/PaywallPresenter.swift
  Tests/TestingApps/PaywallsTester/Postprocessor.sh
  Tests/TestingApps/PaywallsTester/Preprocessor.sh
Labels: build

#3853 Seamless SK2 Observer Mode
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Caching/DeviceCache.swift
  Sources/Misc/SystemInfo.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/StoreKit2/Observer Mode/StoreKit2ObserverModePurchaseDetector.swift
  Sources/Purchasing/StoreKit2/StoreKit2TransactionListener.swift
  Tests/BackendIntegrationTests/OtherIntegrationTests.swift
  Tests/BackendIntegrationTests/StoreKitObserverModeIntegrationTests.swift
  Tests/InstallationTests/CommonFiles/RevenueCat-Swift.h
  Tests/StoreKitUnitTests/BasePurchasesOrchestratorTests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorSK1Tests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorSK2Tests.swift
  Tests/StoreKitUnitTests/StoreKit2/StoreKit2ObserverModePurchaseDetectorTests.swift
  Tests/UnitTests/Mocks/MockAllTransactionsProvider.swift
  Tests/UnitTests/Mocks/MockDeviceCache.swift
  Tests/UnitTests/Mocks/MockStoreKit2ObserverModePurchaseDetector.swift
  Tests/UnitTests/Mocks/MockStoreKit2TransactionListener.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesDelegateTests.swift
Labels: enhancement, perf

#3883 Improved Error Handling
  Sources/Misc/Codable/EnsureNonEmptyCollectionDecodable.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Data/OfferingsPaywallsViewModel.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Networking/HTTPClient.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Utility Views/AsyncButton.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Utility Views/ErrorDisplay.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/Login/LoginWall.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingList/ManagePaywallButton.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingList/OfferingsList.swift
Labels: test

#3884 PaywallsTester: Remove unused code
  Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/project.pbxproj
  Tests/TestingApps/PaywallsTester/PaywallsTester/Configuration.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/AppContentView.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/CustomPaywallContent.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/UpsellView.swift
Labels: test

#3894 Use Ruby 3.2 on CircleCI
  .circleci/config.yml
  Gemfile
  Gemfile.lock
Labels: ci

#3896 Use Ruby 3.2 on CircleCI
  .circleci/config.yml
  Gemfile
  Gemfile.lock
Labels: ci

#3889 Paywalls Tester: App Store Prep
  Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/project.pbxproj
  Tests/TestingApps/PaywallsTester/PaywallsTester/Assets.xcassets/AppIcon.appiconset/Contents.json
  Tests/TestingApps/PaywallsTester/PaywallsTester/Assets.xcassets/AppIcon.appiconset/Red icon 1.png
  Tests/TestingApps/PaywallsTester/PaywallsTester/Assets.xcassets/AppIcon.appiconset/Red icon.png
  Tests/TestingApps/PaywallsTester/PaywallsTester/Assets.xcassets/AppIcon.appiconset/appstore1024 1.png
  Tests/TestingApps/PaywallsTester/PaywallsTester/Assets.xcassets/AppIcon.appiconset/appstore1024.png
  Tests/TestingApps/PaywallsTester/PaywallsTester/Config/ConfigItem.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Config/Configuration.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Config/LocalConfigItems.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Config/SamplePaywalls.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/CustomPaywall.swift
  Tests/TestingApps/PaywallsTester/ci_scripts/ci_pre_xcodebuild.sh
  scripts/pre-commit.sh
Labels: test

#3897 Add `http_request_performed` diagnostics event
  Sources/Diagnostics/DiagnosticsEvent.swift
  Sources/Diagnostics/DiagnosticsTracker.swift
  Sources/Diagnostics/Networking/DiagnosticsEventsRequest.swift
  Sources/Identity/CustomerInfoManager.swift
  Sources/Networking/Backend.swift
  Sources/Networking/HTTPClient/HTTPClient.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/UnitTests/Diagnostics/DiagnosticsTrackerTests.swift
  Tests/UnitTests/Mocks/MockBackendConfiguration.swift
  Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
  Tests/UnitTests/Mocks/MockHTTPClient.swift
  Tests/UnitTests/Networking/Backend/BaseBackendTest.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift
Labels: refactor

#3901 macos observer mode notes
  Sources/DocCDocumentation/DocCDocumentation.docc/V5_API_Migration_guide.md
Labels: docs

#3899 Move switch-ruby to install-bundle-dependencies
  .circleci/config.yml
  Tests/UnitTests/Misc/AnyEncodableTests.swift
  Tests/UnitTests/Misc/__Snapshots__/AnyEncodableTests/iOS13-testNestedDictionary.1.json
Labels: ci

#3833 Fix a few flaky tests
  .circleci/config.yml
  .swiftlint.yml
  Sources/Networking/HTTPClient/HTTPClient.swift
  Sources/Purchasing/StoreKitAbstractions/PromotionalOffer.swift
  Sources/Purchasing/StoreKitAbstractions/SK2StoreProduct.swift
  Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/PurchasesAPI.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
  Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift
  Tests/BackendIntegrationTests/OfflineStoreKitIntegrationTests.swift
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
  Tests/BackendIntegrationTests/StoreKitObserverModeIntegrationTests.swift
  Tests/StoreKitUnitTests/StoreKit2/StoreKit2TransactionListenerTests.swift
  Tests/StoreKitUnitTests/TestHelpers/StoreKitTestHelpers.swift
  Tests/TestingApps/PurchaseTester/RevenueCat_IntegrationPurchaseTesterConfiguration.storekit
  fastlane/Fastfile
  fastlane/README.md
  fastlane/actions/retry_scan_save_failed_tests.rb
Labels: test

#3913 Only install `swiftlint` on Xcode 15 jobs
  .circleci/config.yml
  .swiftlint.yml
  Sources/Networking/HTTPClient/HTTPClient.swift
  Sources/Purchasing/StoreKitAbstractions/PromotionalOffer.swift
  Sources/Purchasing/StoreKitAbstractions/SK2StoreProduct.swift
  Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/PurchasesAPI.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
Labels: ci

#3915 Remove SK2 warning
  Sources/Misc/StoreKitVersion.swift
Labels: storekit2, docs

#3906 RemoteImage Low Res Image support
  RevenueCatUI/Data/TemplateViewConfiguration+Images.swift
  RevenueCatUI/Templates/Other platforms/WatchTemplateView.swift
  RevenueCatUI/Templates/Template1View.swift
  RevenueCatUI/Templates/Template2View.swift
  RevenueCatUI/Templates/Template3View.swift
  RevenueCatUI/Templates/Template5View.swift
  RevenueCatUI/Views/LoadingPaywallView.swift
  RevenueCatUI/Views/RemoteImage.swift
  RevenueCatUI/Views/TemplateBackgroundImageView.swift
  Sources/Paywalls/PaywallData.swift
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedIconsGeneratesDefaultPaywall-watchOS.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedIconsGeneratesDefaultPaywall.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedTemplateNameGeneratesDefaultPaywall-watchOS.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedTemplateNameGeneratesDefaultPaywall.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedVariableGeneratesDefaultPaywall-watchOS.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedVariableGeneratesDefaultPaywall.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedVariableInFeaturesGeneratesDefaultPaywall-watchOS.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedVariableInFeaturesGeneratesDefaultPaywall.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateMissingPaywall-watchOS.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateMissingPaywall.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateMissingPaywallWithSpanishLocalization-watchOS.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateMissingPaywallWithSpanishLocalization.1.json
  Tests/TestingApps/PaywallsTester/PaywallsTester/Config/SamplePaywalls.swift
  Tests/UnitTests/Networking/Responses/Fixtures/Offerings.json
  Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-Sample1.json
  Tests/UnitTests/Networking/Responses/OfferingsDecodingTests.swift
  Tests/UnitTests/Paywalls/PaywallDataTests.swift
Labels: feat

#3922 SPMInstallation tests deployment version increase
  Tests/InstallationTests/SPMInstallation/SPMInstallation.xcodeproj/project.pbxproj
Labels: build

#3929 Revert to use xcode 14 to fix deploys
  .circleci/config.yml
  Tests/UnitTests/Misc/__Snapshots__/AnyEncodableTests/iOS13-testNestedDictionary.1.json
Labels: ci

#3925 Only POST AppTransaction in syncPurchases if No Transactions Present
  Sources/Networking/Operations/PostOfferForSigningOperation.swift
  Sources/Networking/Operations/PostReceiptDataOperation.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/StoreKit2/StoreKit2TransactionFetcher.swift
  Sources/Purchasing/StoreKitAbstractions/EncodedAppleReceipt.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorSK1Tests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorSK2Tests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/UnitTests/Misc/CustomerInfo+TestExtensions.swift
  Tests/UnitTests/Mocks/MockStoreKit2TransactionFetcher.swift
  Tests/UnitTests/Networking/Backend/BackendPostReceiptDataTests.swift
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS16-testPostsReceiptDataWithAppTransactionAndNoReceiptCorrectly.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS17-testPostsReceiptDataWithAppTransactionAndNoReceiptCorrectly.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/macOS-testPostsReceiptDataWithAppTransactionAndNoReceiptCorrectly.1.json
Labels: enhancement, feat
