Repository RevenueCat/purchases-ios, pull requests merged in 2024-02, with the labels that each got.

#3619 `CustomerInfo`: conform to `Identifiable`
  Sources/Identity/CustomerInfo.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/CustomerInfoAPI.swift
Labels: feat

#3620 `Paywalls`: `.onRestoreCompleted` is invoked after the restore dialog is dismissed
  RevenueCatUI/Data/Strings.swift
  RevenueCatUI/Purchasing/PurchaseHandler.swift
  RevenueCatUI/Views/FooterView.swift
  Tests/RevenueCatUITests/PaywallFooterTests.swift
  Tests/RevenueCatUITests/PresentIfNeededTests.swift
  Tests/RevenueCatUITests/PurchaseCompletedHandlerTests.swift
  Tests/RevenueCatUITests/Purchasing/PurchaseHandlerTests.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Views/AppContentView.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Views/OfferingsList.swift
Labels: fix, RevenueCatUI

#3625 `Paywalls`: improve "offering has no configured paywall" error
  RevenueCatUI/Data/PaywallData+Validation.swift
  Tests/RevenueCatUITests/Data/PaywallDataValidationTests.swift
  Tests/purchases-ios-snapshots-commit
Labels: refactor

#3626 `PaywallViewController`: expose `fontName` for `CustomFontProvider`
  RevenueCatUI/UIKit/PaywallFooterViewController.swift
  RevenueCatUI/UIKit/PaywallViewController.swift
  Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewControllerAPI.swift
Labels: RevenueCatUI

#3628 `PaywallViewController`: expose `fontName` for `CustomFontProvider` (by @Jjastiny)
  RevenueCatUI/UIKit/PaywallFooterViewController.swift
  RevenueCatUI/UIKit/PaywallViewController.swift
  Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewControllerAPI.swift
Labels: feat, RevenueCatUI

#3627 `Paywalls`: new `.onPurchaseStarted` modifier
  RevenueCatUI/PaywallView.swift
  RevenueCatUI/Purchasing/PurchaseHandler.swift
  RevenueCatUI/UIKit/PaywallViewController.swift
  RevenueCatUI/View+PresentPaywall.swift
  RevenueCatUI/View+PresentPaywallFooter.swift
  RevenueCatUI/View+PurchaseRestoreCompleted.swift
  Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewAPI.swift
  Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewControllerAPI.swift
  Tests/RevenueCatUITests/Helpers/AsyncTestHelpers.swift
  Tests/RevenueCatUITests/PaywallFooterTests.swift
  Tests/RevenueCatUITests/PresentIfNeededTests.swift
  Tests/RevenueCatUITests/PurchaseCompletedHandlerTests.swift
  Tests/RevenueCatUITests/Purchasing/PurchaseHandlerTests.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Views/UpsellView.swift
Labels: feat, RevenueCatUI

#3629 `Paywalls`: add 4 new variables
  RevenueCatUI/Data/Localization.swift
  RevenueCatUI/Data/Variables.swift
  RevenueCatUI/Helpers/Package+VariableDataProvider.swift
  Tests/RevenueCatUITests/Data/PackageVariablesTests.swift
  Tests/RevenueCatUITests/Data/VariablesTests.swift
Labels: RevenueCatUI

#3633 `Paywalls`: fix finding locales with different regions
  Sources/FoundationExtensions/Locale+Extensions.swift
  Sources/Paywalls/PaywallData+Localization.swift
  Tests/UnitTests/FoundationExtensions/LocaleExtensionsTests.swift
  Tests/UnitTests/Paywalls/PaywallDataTests.swift
Labels: fix, RevenueCatUI

#3638 `Paywalls`: new `presentationMode` parameter (by @Lascorbe)
  RevenueCatUI/View+PresentPaywall.swift
  Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewAPI.swift
Labels: RevenueCatUI

#3639 `NonSubscriptionTransaction`: expose `storeTransactionIdentifier`
  Sources/Purchasing/NonSubscriptionTransaction.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCNonSubscriptionTransactionAPI.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester/NonSubscriptionTransactionAPI.swift
Labels: feat

#3640 `Xcode 15.3 beta 2`: remove `nonisolated` workaround
  Sources/Support/DebugUI/DebugViewModel.swift
  Sources/Support/StoreMessagesHelper.swift
  Tests/StoreKitUnitTests/StoreKitConfigTestCase.swift
Labels: refactor

#3642 Add explicit `visionOS` deployment target
  RevenueCat.xcodeproj/project.pbxproj
Labels: fix, xrOS

#3643 `CircleCI`: remove duplicate `install-dependencies`
  .circleci/config.yml
Labels: ci

#3641 [SK2] Set StoreKit version when enabling observer mode
  Sources/Logging/Strings/ConfigureStrings.swift
  Sources/Misc/Obsoletions.swift
  Sources/Purchasing/Configuration.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesType.swift
  Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/ConfigurationAPI.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCConfigurationAPI.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester/ConfigurationAPI.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Core/ConfiguredPurchases.swift
  Tests/UnitTests/Purchasing/ConfigurationTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
Labels: storekit2, feat

#3650 `Tests`: fix iOS 15 test crash
  Tests/StoreKitUnitTests/StoreMessagesHelperTests.swift
Labels: test

#3649 `Paywalls`: add logs for localization lookup
  Sources/Logging/Strings/PaywallsStrings.swift
  Sources/Paywalls/PaywallData+Localization.swift
Labels: refactor, RevenueCatUI

#3615 Bump deployment target to `iOS 13` / `tvOS 13` / `macOS 10.15`
  .circleci/config.yml
  Package.swift
  Package@swift-5.7.swift
  Package@swift-5.8.swift
  README.md
  RevenueCat.podspec
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI.podspec
  Sources/Support/SwiftVersionCheck.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester.xcodeproj/project.pbxproj
  Tests/APITesters/ReceiptParserAPITester/ReceiptParserAPITester.xcodeproj/project.pbxproj
  Tests/APITesters/SwiftAPITester/SwiftAPITester.xcodeproj/project.pbxproj
  Tests/StoreKitUnitTests/StoreMessagesHelperTests.swift
  Tests/StoreKitUnitTests/TestHelpers/AvailabilityChecks.swift
  Tests/UnitTests/StoreKitExtensions/SKErrorTests.swift
Labels: breaking

#3654 Fix installation tests
  Tests/InstallationTests/CocoapodsInstallation/CocoapodsInstallation.xcodeproj/project.pbxproj
  Tests/InstallationTests/SPMInstallation/SPMInstallation.xcodeproj/project.pbxproj
Labels: build

#3657 `Paywalls`: prioritize `Locale.current` over `Locale.preferredLocales`
  Sources/Logging/Strings/PaywallsStrings.swift
  Sources/Paywalls/PaywallData+Localization.swift
  Tests/UnitTests/Paywalls/PaywallDataTests.swift
Labels: fix, RevenueCatUI

#3670 `Paywalls`: fix localization when installing through `CocoaPods`
  RevenueCatUI.podspec
Labels: fix, RevenueCatUI

#3673 Run load shedder integration tests on release branches
  .circleci/config.yml
Labels: ci

#3675 `CI`: split load shedder integration tests
  .circleci/config.yml
  BackendIntegrationTests/BackendIntegrationTests-Shedder.xctestplan
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCat.xcodeproj/xcshareddata/xcschemes/BackendIntegrationTests.xcscheme
Labels: ci

#3679 `Paywalls`: add support for image overrides in `PaywallCacheWarming`
  Sources/Paywalls/PaywallCacheWarming.swift
  Tests/UnitTests/Paywalls/PaywallCacheWarmingTests.swift
Labels: refactor

#3678 `Paywalls`: fix template 1 header overflow
  RevenueCatUI/Templates/Template1View.swift
  Tests/purchases-ios-snapshots-commit
Labels: fix, RevenueCatUI

#3668 `Paywalls`: processing multi-tier `TemplateViewConfiguration`
  RevenueCatUI/Data/Errors/TemplateError.swift
  RevenueCatUI/Data/IntroEligibility/IntroEligibilityViewModel.swift
  RevenueCatUI/Data/PaywallData+Validation.swift
  RevenueCatUI/Data/TemplateViewConfiguration.swift
  RevenueCatUI/Data/TestData.swift
  RevenueCatUI/TemplatePackageSetting.swift
  RevenueCatUI/Templates/TemplateViewType.swift
  Sources/Paywalls/PaywallData+Localization.swift
  Sources/Paywalls/PaywallData.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PaywallAPI.swift
  Tests/RevenueCatUITests/Data/TemplateViewConfigurationTests.swift
  Tests/RevenueCatUITests/Helpers/DataExtensions.swift
  Tests/UnitTests/Paywalls/PaywallDataMultiTierTests.swift
  Tests/UnitTests/Paywalls/PaywallDataTests.swift
Labels: refactor

#3682 `Paywalls`: improve `PreviewableTemplate`'s display name
  RevenueCatUI/Helpers/PreviewHelpers.swift
Labels: refactor

#3680 `CI`: skip `RevenueCatUI` API tests when generating snapshots
  .circleci/config.yml
Labels: ci

#3685 `Paywalls`: fix `PaywallColor.init(light:dark:)`
  RevenueCatUI/Helpers/ColorInformation+MultiScheme.swift
Labels: fix, RevenueCatUI

#3683 `Paywalls`: don't dismiss footer paywalls automatically
  RevenueCatUI/PaywallView.swift
Labels: RevenueCatUI

#3669 `Paywalls`: validation for multi-tier paywalls
  RevenueCatUI/Data/PaywallData+Validation.swift
  RevenueCatUI/Data/PaywallTemplate.swift
  RevenueCatUI/Data/TestData.swift
  RevenueCatUI/TemplatePackageSetting.swift
  RevenueCatUI/Templates/TemplateViewType.swift
  Tests/RevenueCatUITests/Data/PaywallDataValidationTests.swift
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedIconsInTiersGeneratesDefaultPaywall.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedVariableInTierFeaturesGeneratesDefaultPaywall.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedVariableInTierLocalizationGeneratesDefaultPaywall.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateMultiTierPaywallWithMissingTierLocalization.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateMultiTierPaywallWithMissingTierNames.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateMultiTierPaywallWithMissingTiers.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateMultiTierPaywallWithNoTierLocalization.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateValidMultiTierPaywall.1.json
  Tests/TestingApps/PaywallsTester/PaywallsTester/SamplePaywalls.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Views/SamplePaywallsList.swift
  Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-multitier1.json
  Tests/UnitTests/Paywalls/PaywallDataMultiTierTests.swift
Labels: refactor

#3686 `Paywalls`: template 7 allows color overrides by tier
  RevenueCatUI/Data/TemplateViewConfiguration.swift
  RevenueCatUI/Data/TestData.swift
  RevenueCatUI/Helpers/ColorInformation+MultiScheme.swift
  RevenueCatUI/Templates/Template7View.swift
  RevenueCatUI/Templates/TemplateViewType.swift
  RevenueCatUI/Views/PurchaseButton.swift
  Sources/Paywalls/PaywallData.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PaywallAPI.swift
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateValidMultiTierPaywall.1.json
  Tests/TestingApps/PaywallsTester/PaywallsTester/SamplePaywalls.swift
  Tests/purchases-ios-snapshots-commit
Labels: refactor

#3687 `Paywalls`: template 7 displays tier in condensed mode
  RevenueCatUI/Templates/Template7View.swift
  RevenueCatUI/Views/TierSelectorView.swift
  Tests/purchases-ios-snapshots-commit
Labels: refactor

#3690 New `Package.presentedOfferingContext`
  Sources/Logging/Strings/OfferingStrings.swift
  Sources/Logging/Strings/PurchaseStrings.swift
  Sources/Purchasing/Package.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Support/PaywallExtensions.swift
  Tests/APITesters/CustomEntitlementComputationSwiftAPITester/CustomEntitlementComputationSwiftAPITester.xcodeproj/project.pbxproj
  Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/PackageAPI.swift
  Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/PresentedOfferingContextAPI.swift
  Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/main.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester.xcodeproj/project.pbxproj
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPackageAPI.m
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPresentedOfferingContext.h
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPresentedOfferingContext.m
  Tests/APITesters/ObjCAPITester/ObjCAPITester/main.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester.xcodeproj/project.pbxproj
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PackageAPI.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PresentedOfferingContextAPI.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/main.swift
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
Labels: feat

#3692 `Paywalls`: Add `purchaseCancelled` parameter to `paywallFooter` modifier
  RevenueCatUI/View+PresentPaywallFooter.swift
  Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewAPI.swift
Labels: refactor

#3694 `Paywalls`: new `.onRestoreStarted` modifier
  RevenueCatUI/PaywallView.swift
  RevenueCatUI/Purchasing/PurchaseHandler.swift
  RevenueCatUI/UIKit/PaywallViewController.swift
  RevenueCatUI/View+PresentPaywall.swift
  RevenueCatUI/View+PresentPaywallFooter.swift
  RevenueCatUI/View+PurchaseRestoreCompleted.swift
  Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewAPI.swift
  Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewControllerAPI.swift
  Tests/RevenueCatUITests/PaywallFooterTests.swift
  Tests/RevenueCatUITests/PresentIfNeededTests.swift
  Tests/RevenueCatUITests/PurchaseCompletedHandlerTests.swift
  Tests/RevenueCatUITests/Purchasing/PurchaseHandlerTests.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Views/UpsellView.swift
Labels: feat

#3697 Add more Paywalls API tests
  Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewAPI.swift
Labels: test

#3698 Remove `restoreStarted` from extensions
  RevenueCatUI/View+PresentPaywall.swift
  RevenueCatUI/View+PresentPaywallFooter.swift
  Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewAPI.swift
Labels: refactor

#3693 `Paywalls`: new `.onPurchaseStarted(package)` modifier
  RevenueCatUI/PaywallView.swift
  RevenueCatUI/Purchasing/PurchaseHandler.swift
  RevenueCatUI/UIKit/PaywallViewController.swift
  RevenueCatUI/View+PresentPaywall.swift
  RevenueCatUI/View+PresentPaywallFooter.swift
  RevenueCatUI/View+PurchaseRestoreCompleted.swift
  Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewAPI.swift
  Tests/RevenueCatUITests/PaywallFooterTests.swift
  Tests/RevenueCatUITests/PresentIfNeededTests.swift
  Tests/RevenueCatUITests/PurchaseCompletedHandlerTests.swift
  Tests/RevenueCatUITests/Purchasing/PurchaseHandlerTests.swift
Labels: feat

#3700 `[SK2]`: Fix syncPurchases
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorSK2Tests.swift
  Tests/StoreKitUnitTests/StoreKit2/StoreKit2TransactionFetcherTests.swift
  Tests/StoreKitUnitTests/StoreProductTests.swift
  Tests/StoreKitUnitTests/TestHelpers/StoreKitConfigTestCase+Extensions.swift
Labels: fix

#3658 Add v5 migration guide and update changelog
  README.md
  Sources/DocCDocumentation/DocCDocumentation.docc/RevenueCat.md
  Sources/DocCDocumentation/DocCDocumentation.docc/V5_API_Migration_guide.md
  fastlane/Fastfile
  scripts/docs/v5_api_migration_guide.html
Labels: docs

#3706 Commit all docs files
  fastlane/Fastfile
Labels: docs

#3711 Do not update the documentation index.html file if version is prerelease
  fastlane/Fastfile
Labels: docs

#3707 Add `currentOffering(forPlacement: String)` to `Offerings`
  Sources/Identity/CustomerInfoManager.swift
  Sources/Logging/Strings/PurchaseStrings.swift
  Sources/Networking/Operations/PostReceiptDataOperation.swift
  Sources/Networking/Responses/OfferingsResponse.swift
  Sources/Purchasing/Offerings.swift
  Sources/Purchasing/OfferingsFactory.swift
  Sources/Purchasing/Package.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/Purchases/TransactionPoster.swift
  Sources/Support/PaywallExtensions.swift
  Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/PresentedOfferingContextAPI.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester.xcodeproj/project.pbxproj
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCOfferingsAPI.m
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPresentedOfferingContext.m
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPresentedOfferingContextAPI.h
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPresentedOfferingContextAPI.m
  Tests/APITesters/ObjCAPITester/ObjCAPITester/main.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester/OfferingsAPI.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PresentedOfferingContextAPI.swift
  Tests/BackendIntegrationTests/PaywallEventsIntegrationTests.swift
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
  Tests/StoreKitUnitTests/OfferingsManagerStoreKitTests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/StoreKitUnitTests/Support/DebugViewSwiftUITests.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift
  Tests/UnitTests/Caching/DeviceCacheTests.swift
  Tests/UnitTests/Identity/CustomerInfoManagerPostReceiptTests.swift
  Tests/UnitTests/Misc/PurchasesDiagnosticsTests.swift
  Tests/UnitTests/Mocks/MockOfferingsFactory.swift
  Tests/UnitTests/Networking/Backend/BackendPostReceiptDataTests.swift
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS12-testPostsReceiptDataWithPresentedOfferingContext.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS13-testPostsReceiptDataWithPresentedOfferingContext.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS14-testPostsReceiptDataWithPresentedOfferingContext.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS15-testPostsReceiptDataWithPresentedOfferingContext.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS16-testPostsReceiptDataWithPresentedOfferingContext.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS17-testPostsReceiptDataWithPresentedOfferingContext.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/macOS-testPostsReceiptDataWithPresentedOfferingContext.1.json
  Tests/UnitTests/Paywalls/PaywallCacheWarmingTests.swift
  Tests/UnitTests/Purchasing/OfferingsManagerTests.swift
  Tests/UnitTests/Purchasing/OfferingsTests.swift
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesGetOfferingsTests.swift
  Tests/UnitTests/Purchasing/Purchases/TransactionPosterTests.swift
  Tests/UnitTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift
Labels: feat

#3730 Add targeting to `PresentedOfferingContext`
  Sources/Networking/Operations/PostReceiptDataOperation.swift
  Sources/Networking/Responses/OfferingsResponse.swift
  Sources/Purchasing/Offerings.swift
  Sources/Purchasing/OfferingsFactory.swift
  Sources/Purchasing/Package.swift
  Sources/Support/PaywallExtensions.swift
  Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/PresentedOfferingContextAPI.swift
  Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/main.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPresentedOfferingContextAPI.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PresentedOfferingContextAPI.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/main.swift
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
  Tests/StoreKitUnitTests/OfferingsManagerStoreKitTests.swift
  Tests/StoreKitUnitTests/Support/DebugViewSwiftUITests.swift
  Tests/UnitTests/Caching/DeviceCacheTests.swift
  Tests/UnitTests/Misc/PurchasesDiagnosticsTests.swift
  Tests/UnitTests/Mocks/MockOfferingsFactory.swift
  Tests/UnitTests/Networking/Backend/BackendPostReceiptDataTests.swift
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS12-testPostsReceiptDataWithPresentedOfferingContext.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS13-testPostsReceiptDataWithPresentedOfferingContext.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS14-testPostsReceiptDataWithPresentedOfferingContext.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS15-testPostsReceiptDataWithPresentedOfferingContext.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS16-testPostsReceiptDataWithPresentedOfferingContext.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS17-testPostsReceiptDataWithPresentedOfferingContext.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/macOS-testPostsReceiptDataWithPresentedOfferingContext.1.json
  Tests/UnitTests/Paywalls/PaywallCacheWarmingTests.swift
  Tests/UnitTests/Purchasing/OfferingsManagerTests.swift
  Tests/UnitTests/Purchasing/OfferingsTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesGetOfferingsTests.swift
  fastlane/Fastfile
Labels: feat

#3709 New `syncAttributesAndOfferingsIfNeeded` method
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Logging/Strings/IdentityStrings.swift
  Sources/Misc/RateLimiter.swift
  Sources/Purchasing/OfferingsManager.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesType.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift
  Tests/UnitTests/Misc/RateLimiterRests.swift
  Tests/UnitTests/Mocks/MockOfferingsManager.swift
  Tests/UnitTests/Mocks/MockPurchases.swift
  Tests/UnitTests/Mocks/MockSubscriberAttributesManager.swift
  Tests/UnitTests/Purchasing/OfferingsManagerTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesSyncAttributesAndOfferingsIfNeededTests.swift
Labels: feat

#3713 Spelling typo fix to comment
  Sources/Purchasing/CachingTrialOrIntroPriceEligibilityChecker.swift
Labels: docs

#3708 Paywalls: add `updateWithDisplayCloseButton` to `PaywallViewController`
  RevenueCatUI/UIKit/PaywallViewController.swift
Labels: feat

#3740 [EXTERNAL] Spelling typo fix to comment (#3713) via @vdeaugustine
  Sources/Purchasing/CachingTrialOrIntroPriceEligibilityChecker.swift
Labels: docs
