Repository RevenueCat/purchases-ios, pull requests merged in 2024-03, with the labels that each got.

#3603 `Xcode 15.3`: fix warnings on Integration Tests
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  Package.swift
  Package@swift-5.7.swift
  Package@swift-5.8.swift
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCat.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
  Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift
  Tests/BackendIntegrationTests/StoreKitObserverModeIntegrationTests.swift
  Tests/StoreKitUnitTests/LocalReceiptParserStoreKitTests.swift
  Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK2Tests.swift
  Tests/UnitTests/Misc/XCTestCase+Extensions.swift
Labels: blocked, test

#3744 Revert "`Xcode 15.3`: fix warnings on Integration Tests"
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  Package.swift
  Package@swift-5.7.swift
  Package@swift-5.8.swift
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCat.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
  Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift
  Tests/BackendIntegrationTests/StoreKitObserverModeIntegrationTests.swift
  Tests/StoreKitUnitTests/LocalReceiptParserStoreKitTests.swift
  Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK2Tests.swift
  Tests/UnitTests/Misc/XCTestCase+Extensions.swift
Labels: ci

#3747 Remove unneeded tests for StoreKit2 with JWS
  BackendIntegrationTests/BackendIntegrationTests-SK2.xctestplan
Labels: test

#3751 Fix for passing `TargetingContext` when using `currentOffering(forPlacement:)`
  Sources/Purchasing/Offerings.swift
  Tests/UnitTests/Purchasing/OfferingsTests.swift
Labels: fix

#3753 PaywallsTester: fix compilation
  Tests/TestingApps/PaywallsTester/PaywallsTester/Views/UpsellView.swift
Labels: test

#3759 Pin xcbeautify version for xcode 14 tests
  .circleci/config.yml
Labels: ci

#3738 PaywallViewController: option to not automatically dismiss and add `onRequestedDismissal`
  RevenueCatUI/PaywallView.swift
  RevenueCatUI/Purchasing/PurchaseHandler.swift
  RevenueCatUI/UIKit/PaywallFooterViewController.swift
  RevenueCatUI/UIKit/PaywallViewController.swift
  RevenueCatUI/View+PurchaseRestoreCompleted.swift
  Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewAPI.swift
  Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewControllerAPI.swift
Labels: feat

#3760 [EXTERNAL] Fix Typos in ReceiptStrings.swift (#3756) via @nickkohrn
  Sources/LocalReceiptParsing/Helpers/ReceiptStrings.swift
  Sources/LocalReceiptParsing/PurchasesReceiptParser.swift
  Tests/UnitTests/Purchasing/ReceiptStringsTests.swift
Labels: fix

#3766 Add lane to trigger bumps
  Gemfile.lock
  fastlane/.env.SAMPLE
  fastlane/Fastfile
  fastlane/README.md
Labels: ci

#3773 Add `RC_BILLING` store
  Sources/CodableExtensions/Store+Extensions.swift
  Sources/Purchasing/EntitlementInfo.swift
  Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/EntitlementInfoAPI.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCEntitlementInfoAPI.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester/EntitlementInfoAPI.swift
  Tests/UnitTests/Purchasing/EntitlementInfosTests.swift
Labels: refactor

#3772 [EXTERNAL] Cocoapods support for privacy manifest
  RevenueCat.podspec
Labels: fix

#3774 Release/4.39.1
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  RevenueCat.podspec
  RevenueCatUI.podspec
  Sources/Info.plist
  Sources/Misc/SystemInfo.swift
  Tests/BackendIntegrationTestApp/Info.plist
  Tests/BackendIntegrationTests/Info.plist
  Tests/InstallationTests/CommonFiles/RevenueCat-Swift.h
  Tests/UnitTests/Info.plist
  Tests/UnitTestsHostApp/Info.plist
  scripts/docs/index.html
  scripts/docs/v4_api_migration_guide.html
Labels: next_release

#3775 [EXTERNAL] Cocoapods support for privacy manifest (#3772) via @sdurban
  RevenueCat.podspec
Labels: feat
