Repository RevenueCat/purchases-ios, pull requests merged in 2024-07, with the labels that each got.

#4005 Throw error for invalid Apple In App Subscription Key in debug POST /receipt requests
  Sources/Error Handling/BackendError.swift
  Sources/Logging/Strings/ConfigureStrings.swift
  Sources/Networking/Operations/GetCustomerInfoOperation.swift
  Sources/Networking/Operations/Handling/CustomerInfoResponseHandler.swift
  Sources/Networking/Operations/PostReceiptDataOperation.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/UnitTests/OfflineEntitlements/CustomerInfoResponseHandlerTests.swift
Labels: feat

#4009 Obsolete all observer mode configure functions
  Sources/Misc/Deprecations.swift
  Sources/Misc/Obsoletions.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
Labels: fix

#4010 Bring back ci jobs
  .circleci/config.yml
Labels: ci

#4011 Release/5.0.0
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  RevenueCat.podspec
  RevenueCatUI.podspec
  Sources/Info.plist
  Sources/Misc/SystemInfo.swift
  Tests/BackendIntegrationTestApp/Info.plist
  Tests/BackendIntegrationTests/Info.plist
  Tests/InstallationTests/CommonFiles/RevenueCat-Swift.h
  Tests/UnitTests/Info.plist
  Tests/UnitTestsHostApp/Info.plist
  scripts/docs/index.html
  scripts/docs/v4_api_migration_guide.html
Labels: next_release

#4013 Use available resource class for backend-integration-tests-offline-job
  .circleci/config.yml
Labels: ci

#4015 Update Purchase Tester for 5.0.0
  Tests/TestingApps/PurchaseTesterSwiftUI/Core/ConfiguredPurchases.swift
Labels: fix

#4014 CI Build Docs Improvements
  .circleci/config.yml
  fastlane/Fastfile
Labels: ci

#4019 Update v5 migration guide to contain current latest version
  scripts/docs/v5_api_migration_guide.html
Labels: docs

#3973 Paywalls with custom purchase and restore logic handlers
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/Data/Errors/PaywallError.swift
  RevenueCatUI/Data/PaywallViewConfiguration.swift
  RevenueCatUI/Data/Strings.swift
  RevenueCatUI/Helpers/Logger.swift
  RevenueCatUI/PaywallView.swift
  RevenueCatUI/Purchasing/MockPurchases.swift
  RevenueCatUI/Purchasing/PaywallPurchasesType.swift
  RevenueCatUI/Purchasing/PurchaseHandler+TestData.swift
  RevenueCatUI/Purchasing/PurchaseHandler.swift
  RevenueCatUI/UIKit/PaywallViewController.swift
  RevenueCatUI/View+PresentPaywall.swift
  RevenueCatUI/View+PresentPaywallFooter.swift
  RevenueCatUI/View+PurchaseRestoreCompleted.swift
  RevenueCatUI/Views/DebugErrorView.swift
  RevenueCatUI/Views/LoadingPaywallView.swift
  Sources/Purchasing/Configuration.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
  Tests/RevenueCatUITests/PaywallFooterTests.swift
  Tests/RevenueCatUITests/PresentIfNeededTests.swift
  Tests/RevenueCatUITests/PurchaseCompletedHandlerTests.swift
  Tests/RevenueCatUITests/Purchasing/PurchaseHandlerTests.swift
  Tests/RevenueCatUITests/Templates/ExternalPurchaseAndRestoreTests.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Config/Configuration.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingList/OfferingButton.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/PaywallPresenter.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/SamplePaywallsList.swift
Labels: feat

#4024 Paywalls tester with sandbox purchases
  Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/project.pbxproj
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/AppContentView.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingList/APIKeyDashboardList.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/PaywallPresenter.swift
Labels: test

#4029 Bring official `xcodes` back to CI
  .circleci/config.yml
Labels: ci

#4035 Prevent paywall PurchaseHandler from being cleared on rerender
  RevenueCatUI/Data/PaywallViewConfiguration.swift
  RevenueCatUI/PaywallView.swift
  RevenueCatUI/View+PresentPaywall.swift
Labels: fix

#3959 [Customer Center] Build feedback survey from JSON
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/CustomerCenter/Data/FeedbackSurveyData.swift
  RevenueCatUI/CustomerCenter/ManageSubscriptionsButtonStyle.swift
  RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptionsViewModel.swift
  RevenueCatUI/CustomerCenter/Views/FeedbackSurveyView.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
Labels: feat, Customer Center Workflow

#4033 Multi-tier paywall - offer overrides
  RevenueCatUI/Data/ProcessedLocalizedConfiguration.swift
  RevenueCatUI/Data/TestData.swift
  RevenueCatUI/Data/Variables.swift
  RevenueCatUI/Helpers/Package+VariableDataProvider.swift
  RevenueCatUI/Templates/Template4View.swift
  RevenueCatUI/Templates/Template5View.swift
  RevenueCatUI/Templates/Template7View.swift
  Sources/Paywalls/PaywallData.swift
  Tests/BackendIntegrationTests/__Snapshots__/LoadShedderIntegrationTests/testCanGetOfferings.1.json
  Tests/BackendIntegrationTests/__Snapshots__/StoreKitIntegrationTests/testCanGetOfferings.1.json
  Tests/RevenueCatUITests/Data/VariablesTests.swift
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedIconsGeneratesDefaultPaywall-watchOS.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedIconsGeneratesDefaultPaywall.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedIconsInTiersGeneratesDefaultPaywall-watchOS.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedIconsInTiersGeneratesDefaultPaywall.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedTemplateNameGeneratesDefaultPaywall-watchOS.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedTemplateNameGeneratesDefaultPaywall.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedVariableGeneratesDefaultPaywall-watchOS.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedVariableGeneratesDefaultPaywall.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedVariableInFeaturesGeneratesDefaultPaywall-watchOS.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedVariableInFeaturesGeneratesDefaultPaywall.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedVariableInTierFeaturesGeneratesDefaultPaywall-watchOS.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedVariableInTierFeaturesGeneratesDefaultPaywall.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedVariableInTierLocalizationGeneratesDefaultPaywall-watchOS.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedVariableInTierLocalizationGeneratesDefaultPaywall.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateMissingPaywall-watchOS.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateMissingPaywall.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateMissingPaywallWithSpanishLocalization-watchOS.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateMissingPaywallWithSpanishLocalization.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateMultiTierPaywallWithMissingTierLocalization-watchOS.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateMultiTierPaywallWithMissingTierLocalization.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateMultiTierPaywallWithMissingTierNames-watchOS.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateMultiTierPaywallWithMissingTierNames.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateMultiTierPaywallWithMissingTiers-watchOS.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateMultiTierPaywallWithMissingTiers.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateMultiTierPaywallWithNoTierLocalization-watchOS.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateMultiTierPaywallWithNoTierLocalization.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateSingleTierPaywallWithMissingLocalization-watchOS.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateSingleTierPaywallWithMissingLocalization.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateValidMultiTierPaywall-watchOS.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateValidMultiTierPaywall.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateValidPaywall-watchOS.1.json
  Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateValidPaywall.1.json
  Tests/RevenueCatUITests/Resources/header.heic
  Tests/RevenueCatUITests/Templates/Template1ViewTests.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Config/SamplePaywalls.swift
  Tests/UnitTests/TestHelpers/SnapshotTesting+Extensions.swift
  Tests/purchases-ios-snapshots-commit
Labels: feat

#4055 [Customer Center] Adds the Customer Center to PaywallsTester
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/SamplePaywallsList.swift
Labels: test

#4073 Only checks staged files for leftover API keys.
  scripts/pre-commit.sh
Labels: fix

#4051 added new workflow to trigger all tests
  .circleci/config.yml
  .github/workflows/trigger_all_tests.yml
Labels: ci

#4075 [Ci] Fix trigger to run all tests from github actions
  .circleci/config.yml
  .github/workflows/trigger_all_tests.yml
Labels: ci

#4079 Fix release train deploy workflow
  .circleci/config.yml
Labels: ci

#4080 Fix release release trains part 2
  .circleci/config.yml
Labels: ci

#4081 Fix docs deploy and add manual trigger on CI
  .circleci/config.yml
  fastlane/Fastfile
Labels: ci

#4072 [Customer Center] Improves the UI of the current subscription
  RevenueCatUI/CustomerCenter/Data/CustomerCenterConfigTestData.swift
  RevenueCatUI/CustomerCenter/Data/SubscriptionInformation.swift
  RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptionsViewModel.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
  Tests/RevenueCatUITests/CustomerCenter/ManageSubscriptionsViewModelTests.swift
Labels: refactor

#4078 Use newer Alert API for showing customer restored alert
  RevenueCatUI/Views/FooterView.swift
Labels: fix

#4057 [CustomerCenter] Add action handler
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/CustomerCenter/Data/CustomerCenterAction.swift
  RevenueCatUI/CustomerCenter/View+PresentCustomerCenter.swift
  RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptionsViewModel.swift
  RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
  RevenueCatUI/CustomerCenter/Views/RestorePurchasesAlert.swift
  Tests/RevenueCatUITests/CustomerCenter/CustomerCenterViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/ManageSubscriptionsViewModelTests.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/SamplePaywallsList.swift
Labels: feat

#4076 [CI]: fix CI test trigger parameters
  .circleci/config.yml
  .github/workflows/trigger_all_tests.yml
Labels: ci

#4085 Fix prepare next version job
  .circleci/config.yml
Labels: ci

#4087 Add missing @PublicForExternalTesting that broke PaywallsTester
  RevenueCatUI/Data/TestData.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Config/SamplePaywalls.swift
Labels: build

#3968 [Customer Center] Promotional Offers support
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/CustomerCenter/Abstractions/CustomerCenterPurchasesType.swift
  RevenueCatUI/CustomerCenter/Abstractions/ManageSubscriptionsPurchaseType.swift
  RevenueCatUI/CustomerCenter/CustomerInfo+CurrentEntitlement.swift
  RevenueCatUI/CustomerCenter/Data/CustomerCenterConfigTestData.swift
  RevenueCatUI/CustomerCenter/Data/CustomerCenterEnvironment.swift
  RevenueCatUI/CustomerCenter/Data/CustomerCenterError.swift
  RevenueCatUI/CustomerCenter/Data/CustomerCenterPurchases.swift
  RevenueCatUI/CustomerCenter/Data/FeedbackSurveyData.swift
  RevenueCatUI/CustomerCenter/Data/LoadPromotionalOfferUseCase.swift
  RevenueCatUI/CustomerCenter/Data/PromotionalOfferData.swift
  RevenueCatUI/CustomerCenter/ViewModels/FeedbackSurveyViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptionsViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/PromotionalOfferViewModel.swift
  RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
  RevenueCatUI/CustomerCenter/Views/FeedbackSurveyView.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
  RevenueCatUI/CustomerCenter/Views/PromotionalOfferView.swift
  RevenueCatUI/Data/Strings.swift
  RevenueCatUI/Resources/en.lproj/Localizable.strings
  RevenueCatUI/Resources/en_AU.lproj/Localizable.strings
  RevenueCatUI/Resources/en_CA.lproj/Localizable.strings
  RevenueCatUI/Resources/en_GB.lproj/Localizable.strings
  RevenueCatUI/Resources/en_US.lproj/Localizable.strings
  RevenueCatUI/Resources/es_419.lproj/Localizable.strings
  RevenueCatUI/Resources/es_ES.lproj/Localizable.strings
  Sources/CustomerCenter/CustomerCenterConfigData.swift
  Sources/Networking/Responses/CustomerCenterConfigResponse.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/CustomerCenterConfigDataAPI.swift
  Tests/RevenueCatUITests/CustomerCenter/ManageSubscriptionsViewModelTests.swift
  Tests/UnitTests/CustomerCenter/CustomerCenterConfigDataTests.swift
  Tests/UnitTests/Networking/Backend/BackendGetCustomerCenterConfigTests.swift
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerCenterConfigTests/iOS13-testGetCustomerCenterConfig.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerCenterConfigTests/iOS13-testGetCustomerCenterConfigCachesForSameUserID.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerCenterConfigTests/iOS13-testGetCustomerCenterConfigCallsHTTPMethod.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerCenterConfigTests/iOS13-testGetCustomerCenterConfigCallsHTTPMethodWithRandomDelay.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerCenterConfigTests/iOS13-testGetCustomerCenterConfigFailSendsNil.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerCenterConfigTests/iOS13-testGetCustomerCenterConfigNetworkErrorSendsError.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerCenterConfigTests/iOS13-testGetCustomerCenterConfigPassesLocales.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerCenterConfigTests/iOS13-testGetCustomerConfigDoesntCacheForMultipleUserID.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerCenterConfigTests/iOS13-testGetCustomerConfigDoesntCacheForMultipleUserID.2.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerCenterConfigTests/iOS13-testRepeatedRequestsLogDebugMessage.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerCenterConfigTests/iOS16-testGetCustomerCenterConfig.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerCenterConfigTests/iOS16-testGetCustomerCenterConfigCachesForSameUserID.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerCenterConfigTests/iOS16-testGetCustomerCenterConfigCallsHTTPMethod.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerCenterConfigTests/iOS16-testGetCustomerCenterConfigCallsHTTPMethodWithRandomDelay.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerCenterConfigTests/iOS16-testGetCustomerCenterConfigFailSendsNil.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerCenterConfigTests/iOS16-testGetCustomerCenterConfigNetworkErrorSendsError.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerCenterConfigTests/iOS16-testGetCustomerCenterConfigPassesLocales.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerCenterConfigTests/iOS16-testGetCustomerConfigDoesntCacheForMultipleUserID.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerCenterConfigTests/iOS16-testGetCustomerConfigDoesntCacheForMultipleUserID.2.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerCenterConfigTests/iOS16-testRepeatedRequestsLogDebugMessage.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostDiagnosticsTests/iOS16-testPostDiagnosticsEventsWithMultipleEvents.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostDiagnosticsTests/iOS16-testPostDiagnosticsEventsWithOneEvent.1.json
Labels: feat, Customer Center Workflow

#4092 Fix PaywallsTester by changing TestData DEBUG checks
  RevenueCatUI/Data/TestData.swift
Labels: build

#4089 Move No subscriptions page strings to Localization
  RevenueCatUI/CustomerCenter/Views/NoSubscriptionsView.swift
  Sources/CustomerCenter/CustomerCenterConfigData.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/SamplePaywallsList.swift
Labels: refactor

#3983 [Customer Center] Add colors support
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/CustomerCenter/Data/CustomerCenterConfigTestData.swift
  RevenueCatUI/CustomerCenter/Data/CustomerCenterEnvironment.swift
  RevenueCatUI/CustomerCenter/ManageSubscriptionsButtonStyle.swift
  RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
  RevenueCatUI/CustomerCenter/Views/FeedbackSurveyView.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
  RevenueCatUI/CustomerCenter/Views/NoSubscriptionsView.swift
  RevenueCatUI/CustomerCenter/Views/PromotionalOfferView.swift
  RevenueCatUI/CustomerCenter/Views/TintedProgressView.swift
  Sources/CustomerCenter/CustomerCenterConfigData.swift
  Sources/Networking/Responses/CustomerCenterConfigResponse.swift
  Tests/UnitTests/CustomerCenter/CustomerCenterConfigDataTests.swift
  Tests/UnitTests/Networking/Backend/BackendGetCustomerCenterConfigTests.swift
Labels: feat, Customer Center Workflow

#4088 Cleanup `trigger_all_tests` github workflow
  .github/workflows/trigger_all_tests.yml
Labels: ci

#4083 [Customer Center] SubscriptionDetailsView gets its strings from CommonLocalizedString.
  RevenueCatUI/CustomerCenter/Data/SubscriptionInformation.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
  Sources/CustomerCenter/CustomerCenterConfigData.swift
Labels: refactor, Customer Center Workflow

#4093 PaywallsTester: fix macOS build
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingList/APIKeyDashboardList.swift
Labels: ci

#4098 Server Provided Backoff Interval Validation
  Sources/Networking/HTTPClient/HTTPClient.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
Labels: fix

#4100 Treat Retry-After Header As Seconds
  Sources/Networking/HTTPClient/HTTPClient.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
Labels: fix

#4102 Release/5.2.1
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  RevenueCat.podspec
  RevenueCatUI.podspec
  Sources/Info.plist
  Sources/Misc/SystemInfo.swift
  Tests/BackendIntegrationTestApp/Info.plist
  Tests/BackendIntegrationTests/Info.plist
  Tests/UnitTests/Info.plist
  Tests/UnitTestsHostApp/Info.plist
  scripts/docs/index.html
  scripts/docs/v4_api_migration_guide.html
  scripts/docs/v5_api_migration_guide.html
Labels: next_release

#4110 [External] Add missing SwiftUI environment for previews (#4109) via @noahsmartin
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/AppList.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/Login/LoginWall.swift
Labels: ci

#4114 Fixes trigger_all_tests.yml triggering on every issue comment
  .github/workflows/trigger_all_tests.yml
Labels: ci

#4112 Clarify Instructions to Run All Manual Tests
  .circleci/config.yml
Labels: ci, docs

#4107 Only Retry POST Receipt Paths for 429
  Sources/Networking/HTTPClient/HTTPClient.swift
  Sources/Networking/HTTPClient/HTTPRequest.swift
  Sources/Networking/Operations/PostReceiptDataOperation.swift
  Tests/BackendIntegrationTests/OtherIntegrationTests.swift
  Tests/BackendIntegrationTests/SignatureVerificationIntegrationTests.swift
  Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
  Tests/UnitTests/Networking/HTTPRequestTests.swift
Labels: refactor

#4115 Release/5.2.2
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  RevenueCat.podspec
  RevenueCatUI.podspec
  Sources/Info.plist
  Sources/Misc/SystemInfo.swift
  Tests/BackendIntegrationTestApp/Info.plist
  Tests/BackendIntegrationTests/Info.plist
  Tests/UnitTests/Info.plist
  Tests/UnitTestsHostApp/Info.plist
  scripts/docs/index.html
  scripts/docs/v4_api_migration_guide.html
  scripts/docs/v5_api_migration_guide.html
Labels: next_release

#4122 [Customer Center] Fix project.pbxproj
  RevenueCat.xcodeproj/project.pbxproj
Labels: fix, Customer Center Workflow

#4113 Re-added the RevenueCatUI tests job on every commit
  .circleci/config.yml
Labels: ci

#4135 Fix trigger all tests branch
  .github/workflows/trigger_all_tests.yml
Labels: ci

#4133 temporarily disables purchasetester deploy
  .circleci/config.yml
Labels: ci

#4138 [Customer Center] Fix checking eligibility
  RevenueCatUI/CustomerCenter/ViewModels/FeedbackSurveyViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptionsViewModel.swift
  Tests/RevenueCatUITests/CustomerCenter/ManageSubscriptionsViewModelTests.swift
Labels: fix, Customer Center Workflow

#4131 More project structure cleanup
  .circleci/config.yml
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCat.xcodeproj/xcshareddata/xcschemes/PurchaseTester.xcscheme
  Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/project.pbxproj
  Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/xcshareddata/xcschemes/PurchaseTester.xcscheme
  Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcworkspace/contents.xcworkspacedata
  Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTesterStoreKitConfiguration.storekit
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/RevenueCat_SwiftUIConfiguration.storekit
  fastlane/Fastfile
  scripts/pre-commit.sh
Labels: ci
