Repository RevenueCat/purchases-ios, pull requests merged in 2024-04, with the labels that each got.

#3782 Fix offerings integration test
  Tests/BackendIntegrationTests/__Snapshots__/StoreKitIntegrationTests/testCanGetOfferings.1.json
Labels: test

#3779 Add enum entry for external purchases store
  Sources/CodableExtensions/Store+Extensions.swift
  Sources/Purchasing/EntitlementInfo.swift
  Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/EntitlementInfoAPI.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCEntitlementInfoAPI.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester/EntitlementInfoAPI.swift
  Tests/UnitTests/Purchasing/EntitlementInfosTests.swift
Labels: fix

#3781 iOS append events to JSONL file and get diagnostics events
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Diagnostics/DiagnosticsEntry.swift
  Sources/Diagnostics/DiagnosticsFileHandler.swift
  Sources/Misc/Codable/AnyEncodable.swift
  Tests/UnitTests/Diagnostics/DiagnosticsFileHandlerTests.swift
  Tests/UnitTests/Diagnostics/FileHandlerTests.swift
Labels: feat

#3785 Add async `syncAttributesAndOfferingsIfNeeded()`
  Sources/Misc/Concurrency/Purchases+async.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesType.swift
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
  Tests/UnitTests/Mocks/MockPurchases.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesSyncAttributesAndOfferingsIfNeededTests.swift
Labels: refactor

#3791 Add HTTPRequest.DiagnosticsPath
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Diagnostics/Networking/DiagnosticsHTTPRequestPath.swift
  Sources/Networking/HTTPClient/HTTPRequest.swift
  Sources/Networking/HTTPClient/HTTPRequestPath.swift
Labels: feat

#3792 Add name to VerificationResult
  Sources/Security/VerificationResult.swift
Labels: refactor

#3790 Add name property to HTTPRequestPath
  Sources/Networking/HTTPClient/HTTPRequestPath.swift
  Sources/Paywalls/Events/Networking/PaywallHTTPRequestPath.swift
Labels: refactor

#3793 Add origin to HTTPResponseType
  Sources/Networking/HTTPClient/ETagManager.swift
  Sources/Networking/HTTPClient/HTTPResponse.swift
Labels: refactor

#3789 Prevent Template 4 from wrapping Lifetime
  RevenueCatUI/Templates/Template4View.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/SamplePaywalls.swift
Labels: fix

#3795 Create DiagnosticsPostOperation
  Package.resolved
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Diagnostics/DiagnosticsEvent.swift
  Sources/Diagnostics/Networking/DiagnosticsEventsRequest.swift
  Sources/Diagnostics/Networking/DiagnosticsPostOperation.swift
  Sources/Networking/InternalAPI.swift
  Tests/UnitTests/Mocks/MockHTTPClient.swift
  Tests/UnitTests/Networking/Backend/BackendPostDiagnosticsTests.swift
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostDiagnosticsTests/iOS17-testPostDiagnosticsEventsWithMultipleEvents.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostDiagnosticsTests/iOS17-testPostDiagnosticsEventsWithOneEvent.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostDiagnosticsTests/macOS-testPostDiagnosticsEventsWithMultipleEvents.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostDiagnosticsTests/macOS-testPostDiagnosticsEventsWithOneEvent.1.json
Labels: refactor

#3801 Add option to intercept touch events in `PaywallViewController`
  RevenueCatUI/UIKit/PaywallFooterViewController.swift
  RevenueCatUI/UIKit/PaywallViewController.swift
  Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewControllerAPI.swift
Labels: refactor

#3784 Create `DiagnosticsTracker`
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Diagnostics/DiagnosticsTracker.swift
  Sources/Logging/Strings/DiagnosticsStrings.swift
  Sources/Misc/Deprecations.swift
  Sources/Purchasing/Configuration.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
  Tests/UnitTests/Purchasing/ConfigurationTests.swift
Labels: feat

#3805 Paywalls: Allow closed button color to be configured
  RevenueCatUI/Helpers/ColorInformation+MultiScheme.swift
  RevenueCatUI/PaywallView.swift
  RevenueCatUI/Templates/TemplateViewType.swift
  Sources/Paywalls/PaywallData.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/SamplePaywalls.swift
Labels: feat

#3810 Update Diagnostics Tests With SK2
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostDiagnosticsTests/iOS17-testPostDiagnosticsEventsWithMultipleEvents.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostDiagnosticsTests/iOS17-testPostDiagnosticsEventsWithOneEvent.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostDiagnosticsTests/macOS-testPostDiagnosticsEventsWithMultipleEvents.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostDiagnosticsTests/macOS-testPostDiagnosticsEventsWithOneEvent.1.json
Labels: test

#3815 Only update docs index on latest stable releases
  Gemfile.lock
  fastlane/Fastfile
Labels: ci

#3814 4. Paywalls Tester: Sign in persistence + Sign Out
  Tests/TestingApps/PaywallsTester/PaywallsTester/Data/ApplicationData.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Networking/HTTPClient.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/PaywallsTester.entitlements
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/AppList.swift
Labels: feat

#3813 3. Paywalls Tester: show offerings/paywalls from RC account
  Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/project.pbxproj
  Tests/TestingApps/PaywallsTester/PaywallsTester/Data/ApplicationData.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Mocks/MockData.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Networking/HTTPClient.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/PaywallsTester.entitlements
  Tests/TestingApps/PaywallsTester/PaywallsTester/Responses/OfferingsResponse.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Responses/PaywallsResponse.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/AppContentView.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/AppList.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/Login/LoginWall.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingsList.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/SamplePaywallsList.swift
Labels: feat

#3812 2. Paywalls Tester: Authentication Logic + Log in wall
  Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/project.pbxproj
  Tests/TestingApps/PaywallsTester/PaywallsTester/Data/ApplicationData.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Mocks/MockData.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Networking/HTTPClient.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/PaywallsTester.entitlements
  Tests/TestingApps/PaywallsTester/PaywallsTester/Responses/OfferingsResponse.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Responses/PaywallsResponse.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/SimpleApp.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Utility Views/AsyncButton.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Utility Views/ErrorDisplay.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/AppContentView.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/AppList.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/Login/LoginScreen.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/Login/LoginWall.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingsList.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/SamplePaywallsList.swift
Labels: feat

#3821 Syncs diagnostics on initialization
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Logging/Strings/DiagnosticsStrings.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
  Tests/UnitTests/Mocks/MockDiagnosticsSynchronizer.swift
Labels: refactor

#3827 Sync repo in an SPM-friendly way
  .circleci/config.yml
Labels: build

#3826 Support SK2 in Basic Configure Functions
  Sources/DocCDocumentation/DocCDocumentation.docc/Purchases.md
  Sources/DocCDocumentation/DocCDocumentation.docc/RevenueCat.md
  Sources/Misc/Obsoletions.swift
  Sources/Misc/StoreKitVersion.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
  Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
Labels: breaking, feat

#3822 Update Package.resolved
  RevenueCat.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: dependencies

#3834 Push to SPM after release has been made
  .circleci/config.yml
Labels: build

#3847 Fix backend integration test
  Tests/BackendIntegrationTests/OtherIntegrationTests.swift
Labels: test

#3844 `Paywalls`: Update Norwegian "restore" localization
  RevenueCatUI/Resources/no.lproj/Localizable.strings
Labels: fix

#3823 Add diagnostics event for Customer Info verification
  Sources/Diagnostics/DiagnosticsEvent.swift
  Sources/Diagnostics/DiagnosticsFileHandler.swift
  Sources/Diagnostics/DiagnosticsTracker.swift
  Sources/Diagnostics/Networking/DiagnosticsEventsRequest.swift
  Sources/Identity/CustomerInfoManager.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/UnitTests/Diagnostics/DiagnosticsFileHandlerTests.swift
  Tests/UnitTests/Diagnostics/DiagnosticsSynchronizerTests.swift
  Tests/UnitTests/Diagnostics/DiagnosticsTrackerTests.swift
  Tests/UnitTests/Identity/CustomerInfoManagerTests.swift
  Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
  Tests/UnitTests/Networking/Backend/BackendPostDiagnosticsTests.swift
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostDiagnosticsTests/iOS15-testPostDiagnosticsEventsWithMultipleEvents.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostDiagnosticsTests/iOS15-testPostDiagnosticsEventsWithOneEvent.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostDiagnosticsTests/iOS17-testPostDiagnosticsEventsWithMultipleEvents.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostDiagnosticsTests/iOS17-testPostDiagnosticsEventsWithOneEvent.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostDiagnosticsTests/macOS-testPostDiagnosticsEventsWithMultipleEvents.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostDiagnosticsTests/macOS-testPostDiagnosticsEventsWithOneEvent.1.json
Labels: refactor

#3852 Typo fix
  Sources/Logging/Strings/PurchaseStrings.swift
Labels: fix

#3858 Change deploy-purchase-tester to use xcode 15
  .circleci/config.yml
Labels: ci

#3861 Update config.yml for SPM repo copy
  .circleci/config.yml
Labels: build
