Repository RevenueCat/purchases-ios, pull requests merged in 2024-09, with the labels that each got.

#4234 [Customer Center] Build `WrongPlatformView` from JSON
  RevenueCatUI/CustomerCenter/Views/CompatibilityContentUnavailableView.swift
  RevenueCatUI/CustomerCenter/Views/NoSubscriptionsView.swift
  RevenueCatUI/CustomerCenter/Views/WrongPlatformView.swift
  Sources/CustomerCenter/CustomerCenterConfigData.swift
Labels: fix, Customer Center Workflow

#4236 [Diagnostics] Add `backend_error_code` property
  Sources/Diagnostics/DiagnosticsEvent.swift
  Sources/Diagnostics/DiagnosticsTracker.swift
  Sources/Diagnostics/Networking/DiagnosticsEventsRequest.swift
  Sources/Networking/HTTPClient/HTTPClient.swift
  Tests/UnitTests/Diagnostics/DiagnosticsTrackerTests.swift
  Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
Labels: refactor

#4230 Paywalls Components Viewmodels + partial localization support
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/Data/Strings.swift
  RevenueCatUI/PaywallView.swift
  RevenueCatUI/Templates/Components/Image/ImageComponentView.swift
  RevenueCatUI/Templates/Components/Image/ImageComponentViewModel.swift
  RevenueCatUI/Templates/Components/LinkButton/LinkButtonComponentView.swift
  RevenueCatUI/Templates/Components/LinkButton/LinkButtonComponentViewModel.swift
  RevenueCatUI/Templates/Components/PaywallComponentTypeTransformers.swift
  RevenueCatUI/Templates/Components/PaywallComponentViewModel.swift
  RevenueCatUI/Templates/Components/Spacer/SpacerComponentView.swift
  RevenueCatUI/Templates/Components/Spacer/SpacerComponentViewModel.swift
  RevenueCatUI/Templates/Components/Stack/StackComponentView.swift
  RevenueCatUI/Templates/Components/Stack/StackComponentViewModel.swift
  RevenueCatUI/Templates/Components/StackComponentView.swift
  RevenueCatUI/Templates/Components/TemplateComponentsView.swift
  RevenueCatUI/Templates/Components/Text/TextComponentView.swift
  RevenueCatUI/Templates/Components/Text/TextComponentViewModel.swift
  RevenueCatUI/Templates/Components/TextComponentView.swift
  Sources/Networking/Responses/OfferingsResponse.swift
  Sources/Paywalls/Components/PaywallComponentBase.swift
  Sources/Paywalls/Components/PaywallComponentBases.swift
  Sources/Paywalls/Components/PaywallComponentPropertyTypes.swift
  Sources/Paywalls/Components/PaywallImageComponent.swift
  Sources/Paywalls/Components/PaywallStackComponent.swift
  Sources/Paywalls/Components/PaywallTextComopnent.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Config/SamplePaywalls.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingList/APIKeyDashboardList.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/SamplePaywallsList.swift
Labels: feat, Paywalls Components

#4241 Add missing `#if PAYWALL_COMPONENTS`
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/SamplePaywallsList.swift
Labels: build

#4244 Update `fastlane-plugin-revenuecat_internal`
  Gemfile.lock
Labels: ci

#4237 Paywall Components Localized Strings
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/Data/Strings.swift
  RevenueCatUI/Templates/Components/Image/ImageComponentViewModel.swift
  RevenueCatUI/Templates/Components/LinkButton/LinkButtonComponentViewModel.swift
  RevenueCatUI/Templates/Components/PaywallComponentTypeTransformers.swift
  RevenueCatUI/Templates/Components/PaywallComponentViewModel.swift
  RevenueCatUI/Templates/Components/Stack/StackComponentViewModel.swift
  RevenueCatUI/Templates/Components/TemplateComponentsView+extensions.swift
  RevenueCatUI/Templates/Components/TemplateComponentsView.swift
  RevenueCatUI/Templates/Components/Text/TextComponentViewModel.swift
  Sources/Networking/Responses/OfferingsResponse.swift
  Sources/Paywalls/Components/PaywallComponentBase.swift
  Sources/Paywalls/Components/PaywallComponentLocalization.swift
  Sources/Paywalls/Components/PaywallComponentPropertyTypes.swift
  Sources/Paywalls/Components/PaywallPurchaseButtonComponent.swift
  Sources/Paywalls/Components/PaywallTextComopnent.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/project.pbxproj
  Tests/TestingApps/PaywallsTester/PaywallsTester/Config/SamplePaywalls.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Extensions/ArrayExtensions.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Extensions/PaywallComponentCollectionExtensions.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/SamplePaywallsList.swift
Labels: pr:feat, Paywalls Components

#4245 [SK2] send unsynced attributes when syncing purchases
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorSK2Tests.swift
Labels: pr:fix

#4252 Fixes SwiftLint violation of rule optional_data_string_conversion
  Tests/UnitTests/TestHelpers/SnapshotTesting+Extensions.swift
Labels: pr:ci, pr:refactor

#4243 Fixes a Paywall Template 7 crash when none of the tiers have any available products.
  RevenueCatUI/Data/TemplateViewConfiguration.swift
  Tests/RevenueCatUITests/Data/TemplateViewConfigurationTests.swift
Labels: pr:fix

#4231 Add warnings and clarifications to v5 migration docs
  Sources/DocCDocumentation/DocCDocumentation.docc/V5_API_Migration_guide.md
Labels: pr:docs

#4256 Do not embed `RevenueCat.framework` in `RevenueCatUI`
  RevenueCat.xcodeproj/project.pbxproj
Labels: pr:build

#4251 [POC] Components have selected version of themselves
  RevenueCatUI/Templates/Components/Image/ImageComponentView.swift
  RevenueCatUI/Templates/Components/Image/ImageComponentViewModel.swift
  RevenueCatUI/Templates/Components/LinkButton/LinkButtonComponentView.swift
  RevenueCatUI/Templates/Components/LinkButton/LinkButtonComponentViewModel.swift
  RevenueCatUI/Templates/Components/Package/PackageComponentView.swift
  RevenueCatUI/Templates/Components/Package/PackageComponentViewModel.swift
  RevenueCatUI/Templates/Components/PurchaseButton/PurchaseButtonComponentView.swift
  RevenueCatUI/Templates/Components/PurchaseButton/PurchaseButtonComponentViewModel.swift
  RevenueCatUI/Templates/Components/Spacer/SpacerComponentViewModel.swift
  RevenueCatUI/Templates/Components/Stack/StackComponentView.swift
  RevenueCatUI/Templates/Components/Stack/StackComponentViewModel.swift
  RevenueCatUI/Templates/Components/Text/TextComponentView.swift
  RevenueCatUI/Templates/Components/Text/TextComponentViewModel.swift
  Sources/Paywalls/Components/PaywallImageComponent.swift
  Sources/Paywalls/Components/PaywallLinkButtonComponent.swift
  Sources/Paywalls/Components/PaywallPackageComponent.swift
  Sources/Paywalls/Components/PaywallPackagesComponent.swift
  Sources/Paywalls/Components/PaywallPurchaseButtonComponent.swift
  Sources/Paywalls/Components/PaywallSpacerComponent.swift
  Sources/Paywalls/Components/PaywallStackComponent.swift
  Sources/Paywalls/Components/PaywallTextComopnent.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Config/SamplePaywalls.swift
Labels: pr:feat

#4238 Add `$kochavaDeviceId` attribution convenience method
  Sources/Purchasing/Purchases/Attribution.swift
  Sources/SubscriberAttributes/ReservedSubscriberAttributes.swift
  Sources/SubscriberAttributes/SubscriberAttributesManager.swift
  Tests/APITesters/AllAPITests/ObjcAPITester/RCAttributionAPI.m
  Tests/APITesters/AllAPITests/SwiftAPITester/AttributionAPI.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Customer/SubscriberAttributesView.swift
  Tests/UnitTests/Mocks/MockSubscriberAttributesManager.swift
  Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
  Tests/UnitTests/SubscriberAttributes/SubscriberAttributesManagerTests.swift
Labels: pr:feat

#4257 Remove usage of adServicesToken in syncPurchases
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
Labels: pr:fix

#4265 Revert "Add `$kochavaDeviceId` attribution convenience method (#4238)"
  Sources/Purchasing/Purchases/Attribution.swift
  Sources/SubscriberAttributes/ReservedSubscriberAttributes.swift
  Sources/SubscriberAttributes/SubscriberAttributesManager.swift
  Tests/APITesters/AllAPITests/ObjcAPITester/RCAttributionAPI.m
  Tests/APITesters/AllAPITests/SwiftAPITester/AttributionAPI.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Customer/SubscriberAttributesView.swift
  Tests/UnitTests/Mocks/MockSubscriberAttributesManager.swift
  Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
  Tests/UnitTests/SubscriberAttributes/SubscriberAttributesManagerTests.swift
Labels: pr:refactor

#4254 Update StoreKit Version Info in GitHub Issues Template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: pr:docs

#4273 [Paywalls] Use store product for `{{ sub_period }}` duration
  RevenueCatUI/Helpers/Package+VariableDataProvider.swift
  Tests/RevenueCatUITests/Data/PackageVariablesTests.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Products.storekit
Labels: pr:fix

#4272 Update allowSharingAppStoreAccount deprecation message
  Sources/Purchasing/Purchases/Purchases.swift
Labels: pr:docs

#4271 Stateobject instantiation fix
  RevenueCatUI/CustomerCenter/Views/FeedbackSurveyView.swift
  RevenueCatUI/CustomerCenter/Views/PromotionalOfferView.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/SamplePaywallsList.swift
Labels: pr:fix, Customer Center Workflow

#4275 Round price per period calculations to nearest 2-decimal
  Sources/Purchasing/StoreKitAbstractions/SubscriptionPeriod.swift
  Tests/RevenueCatUITests/Data/PackageVariablesTests.swift
  Tests/RevenueCatUITests/Data/VariablesTests.swift
  Tests/StoreKitUnitTests/StoreProductTests.swift
  Tests/UnitTests/Purchasing/StoreKitAbstractions/SubscriptionPeriodTests.swift
  Tests/purchases-ios-snapshots-commit
Labels: pr:fix

#4286 Replace withCheckedThrowingContinuation Calls With withUnsafeThrowingContinuation
  Sources/FoundationExtensions/AsyncExtensions.swift
  Sources/Misc/Concurrency/Purchases+async.swift
  Sources/Purchasing/ReceiptFetcher.swift
  Tests/BackendIntegrationTests/Helpers/ExternalPurchasesManager.swift
  Tests/BackendIntegrationTests/Helpers/SK1ProductFetcher.swift
  Tests/RevenueCatUITests/ImageLoaderTests.swift
  Tests/RevenueCatUITests/Purchasing/PurchaseHandlerTests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorSK1Tests.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Helpers/ProductFetcherSK1.swift
Labels: pr:fix

#4294 Cleanup of strings in Customer Center
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptionsViewModel.swift
  RevenueCatUI/CustomerCenter/Views/PromotionalOfferView.swift
  RevenueCatUI/CustomerCenter/Views/RestorePurchasesAlert.swift
  RevenueCatUI/Helpers/StoreProduct+Extensions.swift
  RevenueCatUI/Helpers/StoreProductDiscount+Extensions.swift
  RevenueCatUI/Helpers/SubscriptionPeriod+Extensions.swift
  RevenueCatUI/Resources/ar.lproj/Localizable.strings
  RevenueCatUI/Resources/bg.lproj/Localizable.strings
  RevenueCatUI/Resources/ca.lproj/Localizable.strings
  RevenueCatUI/Resources/cs.lproj/Localizable.strings
  RevenueCatUI/Resources/da.lproj/Localizable.strings
  RevenueCatUI/Resources/de.lproj/Localizable.strings
  RevenueCatUI/Resources/el.lproj/Localizable.strings
  RevenueCatUI/Resources/en.lproj/Localizable.strings
  RevenueCatUI/Resources/en_AU.lproj/Localizable.strings
  RevenueCatUI/Resources/en_CA.lproj/Localizable.strings
  RevenueCatUI/Resources/en_GB.lproj/Localizable.strings
  RevenueCatUI/Resources/en_US.lproj/Localizable.strings
  RevenueCatUI/Resources/es_419.lproj/Localizable.strings
  RevenueCatUI/Resources/es_ES.lproj/Localizable.strings
  RevenueCatUI/Resources/fi.lproj/Localizable.strings
  RevenueCatUI/Resources/fr_CA.lproj/Localizable.strings
  RevenueCatUI/Resources/he.lproj/Localizable.strings
  RevenueCatUI/Resources/hi.lproj/Localizable.strings
  RevenueCatUI/Resources/hr.lproj/Localizable.strings
  RevenueCatUI/Resources/hu.lproj/Localizable.strings
  RevenueCatUI/Resources/id.lproj/Localizable.strings
  RevenueCatUI/Resources/it.lproj/Localizable.strings
  RevenueCatUI/Resources/ja.lproj/Localizable.strings
  RevenueCatUI/Resources/kk.lproj/Localizable.strings
  RevenueCatUI/Resources/ko.lproj/Localizable.strings
  RevenueCatUI/Resources/ms.lproj/Localizable.strings
  RevenueCatUI/Resources/nl.lproj/Localizable.strings
  RevenueCatUI/Resources/no.lproj/Localizable.strings
  RevenueCatUI/Resources/pl.lproj/Localizable.strings
  RevenueCatUI/Resources/pt_BR.lproj/Localizable.strings
  RevenueCatUI/Resources/pt_PT.lproj/Localizable.strings
  RevenueCatUI/Resources/ro.lproj/Localizable.strings
  RevenueCatUI/Resources/ru.lproj/Localizable.strings
  RevenueCatUI/Resources/sk.lproj/Localizable.strings
  RevenueCatUI/Resources/sv.lproj/Localizable.strings
  RevenueCatUI/Resources/th.lproj/Localizable.strings
  RevenueCatUI/Resources/tr.lproj/Localizable.strings
  RevenueCatUI/Resources/uk.lproj/Localizable.strings
  RevenueCatUI/Resources/vi.lproj/Localizable.strings
  RevenueCatUI/Resources/zh_Hans.lproj/Localizable.strings
  RevenueCatUI/Resources/zh_Hant.lproj/Localizable.strings
  Sources/CustomerCenter/CustomerCenterConfigData.swift
  Tests/RevenueCatUITests/CustomerCenter/ManageSubscriptionsViewModelTests.swift
Labels: pr:fix, pr:RevenueCatUI, feat:Customer Center

#4253 [Diagnostics] Add `apple_purchase_attempt ` event
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Diagnostics/DiagnosticsEvent.swift
  Sources/Diagnostics/DiagnosticsTracker.swift
  Sources/Diagnostics/Networking/DiagnosticsEventsRequest.swift
  Sources/Error Handling/SKError+Extensions.swift
  Sources/Error Handling/StoreKitError+Extensions.swift
  Sources/Error Handling/StoreKitErrorHelper.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Tests/StoreKitUnitTests/BasePurchasesOrchestratorTests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorSK1Tests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorSK2Tests.swift
  Tests/UnitTests/Identity/CustomerInfoManagerTests.swift
  Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
Labels: pr:other

#4300 Remove background from FeedbackSurveyView
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/CustomerCenter/Views/FeedbackSurveyView.swift
Labels: pr:fix, pr:RevenueCatUI, feat:Customer Center

#4247 [Diagnostics] Add `apple_products_request` event
  Sources/Diagnostics/DiagnosticsEvent.swift
  Sources/Diagnostics/DiagnosticsTracker.swift
  Sources/Diagnostics/Networking/DiagnosticsEventsRequest.swift
  Sources/Purchasing/ProductsManager.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/StoreKitUnitTests/BasePurchasesOrchestratorTests.swift
  Tests/StoreKitUnitTests/CachingProductsManagerTests.swift
  Tests/StoreKitUnitTests/OfferingsManagerStoreKitTests.swift
  Tests/StoreKitUnitTests/ProductsManagerTests.swift
  Tests/StoreKitUnitTests/StoreKit2/StoreKit2CachingProductsManagerTests.swift
  Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK1Tests.swift
  Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK2Tests.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Config/Configuration.swift
  Tests/UnitTests/Diagnostics/DiagnosticsTrackerTests.swift
  Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
  Tests/UnitTests/Mocks/MockTrialOrIntroPriceEligibilityChecker.swift
  Tests/UnitTests/Purchasing/CachingProductsManagerTests.swift
  Tests/UnitTests/Purchasing/IntroEligibilityCalculatorTests.swift
  Tests/UnitTests/Purchasing/OfferingsManagerTests.swift
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/Purchasing/Purchases/TransactionPosterTests.swift
  Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Labels: pr:other

#4270 [Diagnostics] Refactor diagnostics track methods to handle background work automatically
  Sources/Diagnostics/DiagnosticsTracker.swift
  Sources/Identity/CustomerInfoManager.swift
  Sources/Networking/HTTPClient/HTTPClient.swift
  Sources/Purchasing/ProductsManager.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Tests/UnitTests/Diagnostics/DiagnosticsTrackerTests.swift
  Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
  Tests/UnitTests/Mocks/MockOperationDispatcher.swift
Labels: pr:other

#4304 More customer center docs and fix init
  RevenueCatUI/CustomerCenter/Data/CustomerCenterAction.swift
  RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
Labels: pr:fix, pr:RevenueCatUI, feat:Customer Center

#4261 [Paywall Components] Match properties and behaviors from dashboard
  RevenueCatUI/Helpers/ImageLoader.swift
  RevenueCatUI/Modifiers/ViewExtensions.swift
  RevenueCatUI/Templates/Components/Image/ImageComponentView.swift
  RevenueCatUI/Templates/Components/Image/ImageComponentViewModel.swift
  RevenueCatUI/Templates/Components/LinkButton/LinkButtonComponentView.swift
  RevenueCatUI/Templates/Components/PaywallComponentTypeTransformers.swift
  RevenueCatUI/Templates/Components/PaywallComponentViewModel.swift
  RevenueCatUI/Templates/Components/Stack/StackComponentView.swift
  RevenueCatUI/Templates/Components/Stack/StackComponentViewModel.swift
  RevenueCatUI/Templates/Components/TemplateComponentsView+extensions.swift
  RevenueCatUI/Templates/Components/TemplateComponentsView.swift
  RevenueCatUI/Templates/Components/Text/TextComponentView.swift
  RevenueCatUI/Templates/Components/Text/TextComponentViewModel.swift
  RevenueCatUI/UIKit/PaywallViewController.swift
  RevenueCatUI/Views/RemoteImage.swift
  Sources/Networking/Responses/OfferingsResponse.swift
  Sources/Paywalls/Components/PaywallComponentBase.swift
  Sources/Paywalls/Components/PaywallComponentLocalization.swift
  Sources/Paywalls/Components/PaywallComponentPropertyTypes.swift
  Sources/Paywalls/Components/PaywallImageComponent.swift
  Sources/Paywalls/Components/PaywallStackComponent.swift
  Sources/Paywalls/Components/PaywallTextComopnent.swift
  Tests/RevenueCatUITests/ImageLoaderTests.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Config/SamplePaywalls.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Extensions/PaywallComponentCollectionExtensions.swift
Labels: pr:fix, pr:RevenueCatUI, feat:Paywall Components

#4305 Remove `CUSTOMER_CENTER_ENABLED`
  RevenueCatUI/CustomerCenter/Abstractions/CustomerCenterPurchasesType.swift
  RevenueCatUI/CustomerCenter/Abstractions/ManageSubscriptionsPurchaseType.swift
  RevenueCatUI/CustomerCenter/ButtonStyles.swift
  RevenueCatUI/CustomerCenter/ColorFromAppearance.swift
  RevenueCatUI/CustomerCenter/CustomerInfo+CurrentEntitlement.swift
  RevenueCatUI/CustomerCenter/Data/CustomerCenterAction.swift
  RevenueCatUI/CustomerCenter/Data/CustomerCenterConfigTestData.swift
  RevenueCatUI/CustomerCenter/Data/CustomerCenterEnvironment.swift
  RevenueCatUI/CustomerCenter/Data/CustomerCenterError.swift
  RevenueCatUI/CustomerCenter/Data/CustomerCenterPurchases.swift
  RevenueCatUI/CustomerCenter/Data/FeedbackSurveyData.swift
  RevenueCatUI/CustomerCenter/Data/LoadPromotionalOfferUseCase.swift
  RevenueCatUI/CustomerCenter/Data/PromotionalOfferData.swift
  RevenueCatUI/CustomerCenter/Data/SemanticVersion.swift
  RevenueCatUI/CustomerCenter/Data/SubscriptionInformation.swift
  RevenueCatUI/CustomerCenter/URLUtilities.swift
  RevenueCatUI/CustomerCenter/View+PresentCustomerCenter.swift
  RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewState.swift
  RevenueCatUI/CustomerCenter/ViewModels/FeedbackSurveyViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptionsViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/PromotionalOfferViewModel.swift
  RevenueCatUI/CustomerCenter/Views/AppUpdateWarningView.swift
  RevenueCatUI/CustomerCenter/Views/CompatibilityContentUnavailableView.swift
  RevenueCatUI/CustomerCenter/Views/CompatibilityNavigationStack.swift
  RevenueCatUI/CustomerCenter/Views/CompatibilityTopBarTrailing.swift
  RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
  RevenueCatUI/CustomerCenter/Views/FeedbackSurveyView.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
  RevenueCatUI/CustomerCenter/Views/NoSubscriptionsView.swift
  RevenueCatUI/CustomerCenter/Views/PromotionalOfferView.swift
  RevenueCatUI/CustomerCenter/Views/RestorePurchasesAlert.swift
  RevenueCatUI/CustomerCenter/Views/SubscriptionDetailsView.swift
  RevenueCatUI/CustomerCenter/Views/TintedProgressView.swift
  RevenueCatUI/CustomerCenter/Views/WrongPlatformView.swift
  Sources/CustomerCenter/CustomerCenterConfigData.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/APITesters/AllAPITests/SwiftAPITester/CustomerCenterConfigDataAPI.swift
  Tests/RevenueCatUITests/CustomerCenter/CustomerCenterViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/ManageSubscriptionsViewModelTests.swift
  Tests/RevenueCatUITests/Data/SemanticVersionTests.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/SamplePaywallsList.swift
  Tests/UnitTests/CustomerCenter/CustomerCenterConfigDataTests.swift
  Tests/UnitTests/Networking/Backend/BackendGetCustomerCenterConfigTests.swift
  fastlane/Fastfile
Labels: pr:RevenueCatUI, feat:Customer Center, pr:other

#4312 Adds an `onDismiss` callback to `ErrorDisplay`
  RevenueCatUI/PaywallView.swift
  RevenueCatUI/Views/ErrorDisplay.swift
Labels: pr:other, pr:force_patch

#4320 Fix iOS 15 tests
  Sources/Diagnostics/DiagnosticsTracker.swift
  Tests/StoreKitUnitTests/ProductsManagerTests.swift
  Tests/UnitTests/Mocks/MockOperationDispatcher.swift
Labels: pr:other
