Repository RevenueCat/purchases-ios, pull requests merged in 2025-04, with the labels that each got.

#4936 Add diagnostics event when AppTransaction fails to be fetched
  Sources/Diagnostics/DiagnosticsEvent.swift
  Sources/Diagnostics/DiagnosticsTracker.swift
  Sources/OfflineEntitlements/OfflineCustomerInfoCreator.swift
  Sources/OfflineEntitlements/PurchasedProductsFetcher.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/StoreKit2/StoreKit2TransactionFetcher.swift
  Tests/StoreKitUnitTests/OfflineEntitlements/PurchasedProductsFetcherTests.swift
  Tests/StoreKitUnitTests/StoreKit2/StoreKit2TransactionFetcherTests.swift
  Tests/UnitTests/Diagnostics/DiagnosticsTrackerTests.swift
  Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
Labels: pr:other

#4929 [Diagnostics] Sync diagnostics if file reaches lower size limit
  Sources/Diagnostics/DiagnosticsFileHandler.swift
  Sources/Diagnostics/Networking/DiagnosticsSynchronizer.swift
  Sources/Logging/Strings/DiagnosticsStrings.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/UnitTests/Diagnostics/DiagnosticsFileHandlerTests.swift
  Tests/UnitTests/Diagnostics/DiagnosticsSynchronizerTests.swift
Labels: pr:other

#4946 Improve Korean translation
  RevenueCatUI/Resources/ko.lproj/Localizable.strings
Labels: pr:other

#4948 [Diagnostics] Add `storefront` property to more events
  Sources/Diagnostics/DiagnosticsTracker.swift
  Sources/Purchasing/ProductsManager.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/StoreKit1/StoreKit1Wrapper.swift
  Sources/Purchasing/TrialOrIntroPriceEligibilityChecker.swift
  Tests/StoreKitUnitTests/ProductsManagerTests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorSK1Tests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorSK2Tests.swift
  Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK1Tests.swift
  Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK2Tests.swift
  Tests/UnitTests/Diagnostics/DiagnosticsTrackerTests.swift
  Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
  Tests/UnitTests/Mocks/MockPaymentQueue.swift
  Tests/UnitTests/Purchasing/StoreKit1WrapperTests.swift
Labels: pr:other

#4922 Add previews for `RestorePurchasesAlert`
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/CustomerCenter/Views/RestorePurchasesAlert.swift
  RevenueCatUI/Helpers/EmergeRenderingMode.swift
Labels: pr:RevenueCatUI, feat:Customer Center, pr:other

#4917 feat: Reload customer center onCustomerCenterPromotionalOfferSuccess
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/CustomerCenter/Actions/CustomerCenter+PreferenceKeys.swift
  RevenueCatUI/CustomerCenter/Actions/CustomerCenterView+Actions.swift
  RevenueCatUI/CustomerCenter/Data/CustomerCenterActionViewModifier.swift
  RevenueCatUI/CustomerCenter/Data/CustomerCenterActionWrapper.swift
  RevenueCatUI/CustomerCenter/Data/CustomerCenterManagementOption.swift
  RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptions/ManageSubscriptionsViewModel.swift
  RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
  Tests/RevenueCatUITests/CustomerCenter/CustomerCenterActionWrapperTests.swift
Labels: pr:feat, pr:RevenueCatUI, feat:Customer Center

#4950 fix: Allow two lines for feedback survey title
  RevenueCatUI/CustomerCenter/Views/FeedbackSurveyView.swift
Labels: pr:fix, pr:RevenueCatUI, feat:Customer Center

#4952 Use Swift Int for VirtualCurrencyInfo.balance
  Sources/Networking/Responses/CustomerInfoResponse.swift
  Sources/Purchasing/VirtualCurrencyInfo.swift
Labels: pr:other, feat:Virtual Currencies

#4958 Only preview `RestorePurchasesAlert` on iOS
  RevenueCatUI/CustomerCenter/Views/RestorePurchasesAlert.swift
Labels: pr:RevenueCatUI, feat:Customer Center, pr:other

#4949 feat: Add log for promo offer eligibility
  RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptions/ManageSubscriptionsViewModel.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsButtonsView.swift
  RevenueCatUI/Data/Strings.swift
Labels: feat:Customer Center, pr:other

#4921 feat: Change default copy for web_subscription_manage
  Sources/CustomerCenter/CustomerCenterConfigData.swift
Labels: pr:feat, pr:RevenueCatUI, feat:Customer Center

#4960 Fix `CustomerCenterViewController` view
  RevenueCatUI/CustomerCenter/Views/UIKit Compatibility/CustomerCenterViewController.swift
Labels: pr:fix

#4930 Replace initial alert dialog with a progress view when restoring in Customer Center
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptions/ManageSubscriptionsViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/RestorePurchasesAlertViewModel.swift
  RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
  RevenueCatUI/CustomerCenter/Views/NoSubscriptionsView.swift
  RevenueCatUI/CustomerCenter/Views/RestorePurchasesAlert.swift
  Sources/CustomerCenter/CustomerCenterConfigData.swift
  Tests/RevenueCatUITests/CustomerCenter/CustomerCenterViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/ManageSubscriptionsViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/Mocks/MockCustomerCenterPurchases.swift
Labels: pr:fix, pr:RevenueCatUI, feat:Customer Center

#4933 Update strings for restore purchases alerts
  RevenueCatUI/CustomerCenter/Views/RestorePurchasesAlert.swift
  Sources/CustomerCenter/CustomerCenterConfigData.swift
Labels: pr:fix, pr:RevenueCatUI, feat:Customer Center

#4964 Remove Identifiable conformance from StoreKit2PurchaseIntentListenerType
  Sources/Purchasing/StoreKit2/StoreKit2PurchaseIntentListener.swift
Labels: bug, pr:fix

#4957 [Customer center] unify and propagate Purchases provider
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/CustomerCenter/Abstractions/CustomerCenterPurchasesType.swift
  RevenueCatUI/CustomerCenter/Abstractions/ManageSubscriptionsPurchaseType.swift
  RevenueCatUI/CustomerCenter/ContactSupportUtilities.swift
  RevenueCatUI/CustomerCenter/Data/CustomerCenterPurchases.swift
  RevenueCatUI/CustomerCenter/Data/LoadPromotionalOfferUseCase.swift
  RevenueCatUI/CustomerCenter/Extensions/CustomerCenterConfigDataSupport+URL.swift
  RevenueCatUI/CustomerCenter/ViewModels/FeedbackSurveyViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptions/ManageSubscriptionsViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/PromotionalOfferViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/PurchaseHistory/PurchaseDetailViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/PurchaseHistory/PurchaseHistoryViewModel.swift
  RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
  RevenueCatUI/CustomerCenter/Views/FeedbackSurveyView.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
  RevenueCatUI/CustomerCenter/Views/PromotionalOfferView.swift
  RevenueCatUI/CustomerCenter/Views/PurchaseHistory/PurchaseHistoryView.swift
  RevenueCatUI/CustomerCenter/Views/PurchaseHistory/PurchaseLinkView.swift
  RevenueCatUI/CustomerCenter/Views/RestorePurchasesAlert.swift
  RevenueCatUI/CustomerCenter/Views/WrongPlatformView.swift
  Tests/RevenueCatUITests/CustomerCenter/ContactSupportUtilitiesTests.swift
  Tests/RevenueCatUITests/CustomerCenter/FeedbackSurveyViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/ManageSubscriptionsViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/Mocks/MockCustomerCenterPurchases.swift
Labels: pr:other

#4975 Make Paywalls v2 Text use verbatim
  RevenueCatUI/Templates/V2/Components/Text/TextComponentView.swift
Labels: pr:fix, pr:RevenueCatUI, feat:PaywallV2

#4969 Remove preprocessor script for PaywallsTester
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
  RevenueCatUI/Data/IntroEligibility/TrialOrIntroEligibilityChecker+TestData.swift
  RevenueCatUI/Data/IntroEligibility/TrialOrIntroEligibilityChecker.swift
  RevenueCatUI/Data/PaywallTemplate.swift
  RevenueCatUI/Data/PaywallViewConfiguration.swift
  RevenueCatUI/Data/TestData.swift
  RevenueCatUI/Modifiers/ViewExtensions.swift
  RevenueCatUI/PaywallView.swift
  RevenueCatUI/Purchasing/PurchaseHandler.swift
  RevenueCatUI/Templates/V2/Components/Stack/StackComponentView.swift
  RevenueCatUI/View+PresentPaywallFooter.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/project.pbxproj
  Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/xcshareddata/xcschemes/PaywallsTester - Live Config.xcscheme
  Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/xcshareddata/xcschemes/PaywallsTester - SK config.xcscheme
  Tests/TestingApps/PaywallsTester/PaywallsTester/Config/SamplePaywalls.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/CustomPaywall.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/CustomPaywallContent.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/CustomerCenterUIKitView.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingList/APIKeyDashboardList.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingList/OfferingsList.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/PaywallPresenter.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/PaywallViewMode+Extensions.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/SamplePaywallsList.swift
  Tests/TestingApps/PaywallsTester/Postprocessor.sh
  Tests/TestingApps/PaywallsTester/Preprocessor.sh
Labels: pr:other

#4977 Fixes unit tests compilation on Xcode 16.3/iOS 18.4
  Tests/StoreKitUnitTests/StoreProductTests.swift
  Tests/UnitTests/Purchasing/StoreKitAbstractions/SubscriptionPeriodTests.swift
Labels: pr:other

#4973 Add promotional offer APIs to `CustomEntitlementComputation` V4 SDK
  Examples/testCustomEntitlementsComputation/testCustomEntitlementsComputation/ContentView.swift
  Gemfile.lock
  Sources/Misc/Concurrency/Purchases+async.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/BackendIntegrationTests/LoadShedderIntegrationTests.swift
  Tests/BackendIntegrationTests/__Snapshots__/LoadShedderIntegrationTests/testCanGetOfferings.1.json
Labels: pr:other

#4980 Updates the changelog for hotfix 4.43.5.
  CHANGELOG.md
Labels: pr:other

#4984 Adds CEC V5 migration guide
  Sources/DocCDocumentation/DocCDocumentation.docc/CEC_V5_API_Migration_guide.md
Labels: pr:other

#4990 Fix Paywalls v2 Text component to not localized from bundle but support markdown
  RevenueCatUI/Templates/V2/Components/Text/TextComponentView.swift
Labels: pr:fix, pr:RevenueCatUI, feat:PaywallV2

#4947 UI preview mode: enable customer center previews
  RevenueCatUI/CustomerCenter/Abstractions/CustomerCenterPurchasesType.swift
  RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
  RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
  Sources/Purchasing/StoreKitAbstractions/StoreProductDiscount.swift
  Tests/RevenueCatUITests/CustomerCenter/Mocks/MockCustomerCenterPurchases.swift
Labels: pr:other

#4992 fix: Unify finding active transaction for customer center
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/CustomerCenter/Data/LoadPromotionalOfferUseCase.swift
  RevenueCatUI/CustomerCenter/Extensions/CustomerInfo+ActiveTransaction.swift
  RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
Labels: pr:fix, feat:Customer Center

#4995 Fix paywalls text component compilation for iOS 15
  RevenueCatUI/Templates/V2/Components/Text/TextComponentView.swift
Labels: pr:fix, pr:RevenueCatUI, feat:PaywallV2

#4997 Add `getStorefront` APIs
  Sources/Misc/Concurrency/Purchases+async.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesType.swift
  Tests/APITesters/AllAPITests/ObjcAPITester/RCPurchasesAPI.m
  Tests/APITesters/AllAPITests/SwiftAPITester/PurchasesAPI.swift
  Tests/UnitTests/Mocks/MockPurchases.swift
Labels: pr:feat

#5001 [Paywalls v2] Fixes decoding `TabControlType`
  Sources/Paywalls/Components/PaywallTabsComponent.swift
Labels: pr:other

#4996 Parses the PR number from the merge queue branch name.
  fastlane/Fastfile
Labels: pr:other

#4967 Added purchase button in package SwiftUI Preview example
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/Templates/V2/Components/Packages/PurchaseButton/PurchaseButtonComponentView.swift
  RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/PurchaseButtonInPackage.swift
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#5005 [Diagnostics] Add extra fields when tracking AppTransaction errors
  Sources/Diagnostics/DiagnosticsTracker.swift
  Sources/Purchasing/StoreKit2/StoreKit2TransactionFetcher.swift
  Tests/UnitTests/Diagnostics/DiagnosticsTrackerTests.swift
  Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
Labels: pr:other

#4955 [Paywalls V2] Add default values for enums
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/Templates/V2/Components/Button/ButtonComponentView.swift
  RevenueCatUI/Templates/V2/Components/Button/ButtonComponentViewModel.swift
  RevenueCatUI/Templates/V2/ViewHelpers/Shape.swift
  Sources/Paywalls/Components/Common/PaywallComponentPropertyTypes.swift
  Sources/Paywalls/Components/PaywallButtonComponent.swift
  Sources/Paywalls/Components/PaywallCarouselComponent.swift
  Sources/Paywalls/Components/PaywallStackComponent.swift
  Sources/Paywalls/Components/PaywallTimelineComponent.swift
  Tests/UnitTests/Paywalls/Components/Properties/DefaultEnumTests.swift
Labels: pr:fix, pr:RevenueCatUI, feat:PaywallV2

#5007 Update internal fastlane plugin to not try new scan run when retried tests eventually passed
  Gemfile.lock
Labels: do not merge, pr:other

#5008 Maybe fix some flaky PaywallViewEventsTests in CI
  Tests/RevenueCatUITests/PaywallViewEventsTests.swift
Labels: pr:other

#5002 Log a warning to iOS 18.4 Simulator users with empty offerings
  Sources/Logging/Strings/OfferingStrings.swift
  Sources/Misc/SystemInfo.swift
  Sources/Purchasing/OfferingsManager.swift
Labels: pr:other

#4993 fix: Reload customer center on subscription cancelled
  RevenueCatUI/CustomerCenter/Abstractions/CustomerCenterPurchasesType.swift
  RevenueCatUI/CustomerCenter/Data/CustomerCenterActionViewModifier.swift
  RevenueCatUI/CustomerCenter/Data/CustomerCenterPurchases.swift
  RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/FeedbackSurveyViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptions/ManageSubscriptionsViewModel.swift
  RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
  Tests/RevenueCatUITests/CustomerCenter/CustomerCenterActionWrapperTests.swift
  Tests/RevenueCatUITests/CustomerCenter/Mocks/MockCustomerCenterPurchases.swift
Labels: pr:fix, feat:Customer Center

#5012 Fix Magic Weather SwiftUI compilation error by @pattogato at #4987
  Examples/MagicWeatherSwiftUI/Shared/Sources/Helpers/Extensions.swift
Labels: pr:other

#5011 [Customer center] missing inject of Purchases provider
  RevenueCatUI/CustomerCenter/ViewModels/RestorePurchasesAlertViewModel.swift
  RevenueCatUI/CustomerCenter/Views/RestorePurchasesAlert.swift
Labels: pr:other

#5016 [Paywalls v2] fixes crash when getting invalid URL from paywall components localization
  RevenueCatUI/Templates/V2/Components/Button/ButtonComponentViewModel.swift
  Sources/Paywalls/Components/Common/PaywallComponentLocalization.swift
Labels: pr:fix

#4979 [DX-345] Update the `testSDKHealth` to use the new `/health_report` endpoint
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Networking/Backend.swift
  Sources/Networking/HTTPClient/HTTPRequestPath.swift
  Sources/Networking/InternalAPI.swift
  Sources/Networking/Operations/HealthReportOperation.swift
  Sources/Networking/Responses/HealthReportResponse.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesType.swift
  Sources/Support/DebugUI/DebugContentViews.swift
  Sources/Support/DebugUI/DebugViewModel.swift
  Sources/Support/DebugUI/ProductStatus+Icon.swift
  Sources/Support/DebugUI/SDKHealthCheckStatus+Icon.swift
  Sources/Support/DebugUI/SDKHealthStatus+Icon.swift
  Sources/Support/HealthReport+Validate.swift
  Sources/Support/PurchasesDiagnostics.swift
  Tests/StoreKitUnitTests/Support/DebugViewSwiftUITests.swift
  Tests/UnitTests/Misc/PurchasesDiagnosticsTests.swift
  Tests/UnitTests/Mocks/MockPurchases.swift
Labels: pr:other

#5020 [Paywalls v2] Adds logs to indicate whether URLs are opened successfully
  RevenueCatUI/Data/Strings.swift
  RevenueCatUI/Templates/V2/Components/Button/ButtonComponentView.swift
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#5013 feat: Introduce maestro for UI testing
  Examples/rc-maestro/.gitignore
  Examples/rc-maestro/Project.swift
  Examples/rc-maestro/Tuist.swift
  Examples/rc-maestro/Tuist/Package.swift
  Examples/rc-maestro/maestro/config.yaml
  Examples/rc-maestro/maestro/customer_center/change_plans/customer_center_change_plans.yaml
  Examples/rc-maestro/maestro/customer_center/manage_subscriptions/customer_center_manage_subscriptions_empty.yaml
  Examples/rc-maestro/maestro/customer_center/manage_subscriptions/customer_center_manage_subscriptions_restore_purchases.yaml
  Examples/rc-maestro/maestro/customer_center/manage_subscriptions/customer_center_manage_subscriptions_see_all_purchases.yaml
  Examples/rc-maestro/maestro/customer_center/promo_offer/customer_center_accept_promo_offer.yaml
  Examples/rc-maestro/maestro/utils/buy_product.yaml
  Examples/rc-maestro/maestro/utils/open_customer_center.yaml
  Examples/rc-maestro/rc-maestro/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Examples/rc-maestro/rc-maestro/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Examples/rc-maestro/rc-maestro/Resources/Assets.xcassets/Contents.json
  Examples/rc-maestro/rc-maestro/Resources/Local.xcconfig.sample
  Examples/rc-maestro/rc-maestro/Resources/Preview Content/Preview Assets.xcassets/Contents.json
  Examples/rc-maestro/rc-maestro/Resources/StoreKit/StoreKitConfigDefault.storekit
  Examples/rc-maestro/rc-maestro/Sources/rc-maestro/ContentView.swift
  Examples/rc-maestro/rc-maestro/Sources/rc-maestro/RcMaestroApp.swift
  RevenueCatUI/CustomerCenter/Views/PromotionalOfferView.swift
  mise.toml
Labels: enhancement, pr:feat, pr:RevenueCatUI, feat:Customer Center

#4970 Use fallback API hosts when receiving server down response
  Sources/Diagnostics/Networking/DiagnosticsHTTPRequestPath.swift
  Sources/Logging/Strings/NetworkStrings.swift
  Sources/Networking/HTTPClient/HTTPClient.swift
  Sources/Networking/HTTPClient/HTTPRequestPath.swift
  Sources/Paywalls/Events/Networking/PaywallHTTPRequestPath.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
Labels: pr:other

#5018 Add load shedder integration tests for consumable and non-consumable products
  Tests/BackendIntegrationTests/LoadShedderIntegrationTests.swift
Labels: pr:other

#5021 fix compilation issues in older versions of Xcode
  Sources/Support/DebugUI/ProductStatus+Icon.swift
  Sources/Support/DebugUI/SDKHealthCheckStatus+Icon.swift
  Sources/Support/DebugUI/SDKHealthStatus+Icon.swift
  Sources/Support/HealthReport+Validate.swift
Labels: pr:other

#5022 Fix Backwards compatibility errors introduced by new `testSDKHealthCheck` implementation
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Support/DebugUI/DebugContentViews.swift
  Sources/Support/DebugUI/DebugViewModel.swift
  Sources/Support/DebugUI/ProductStatus+Icon.swift
  Sources/Support/DebugUI/SDKHealthCheckStatus+Icon.swift
  Sources/Support/DebugUI/SDKHealthStatus+Icon.swift
  Sources/Support/HealthReport+Validate.swift
  Sources/Support/PurchasesDiagnostics.swift
  Sources/Support/SDKHealthError+CustomNSError.swift
  Tests/UnitTests/Misc/PurchasesDiagnosticsTests.swift
Labels: bug, pr:fix

#5023 fix: Wrap viewmodel binding into another binding
  RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
Labels: pr:fix, pr:RevenueCatUI, feat:Customer Center

#5024 [Paywalls v2] Fixes blank lines not showing up
  RevenueCatUI/Templates/V2/Components/Text/TextComponentView.swift
Labels: pr:fix, pr:RevenueCatUI, feat:PaywallV2
