Repository RevenueCat/purchases-ios, pull requests merged in 2025-10, with the labels that each got.

#5615 fix broken RevenueCat.xcworkspace
  RevenueCat.xcodeproj/project.pbxproj
Labels: pr:other

#5614 Show latest expired if no active subscriptions
  RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
  Tests/RevenueCatUITests/CustomerCenter/CustomerCenterViewModelTests.swift
Labels: pr:fix, pr:RevenueCatUI, feat:Customer Center

#5619 Update fastlane-plugin-revenuecat_internal
  Gemfile.lock
Labels: pr:other

#5624 Updates fastlane-plugin-revenuecat_internal
  Gemfile.lock
Labels: pr:other

#5622 Update `fastlane-plugin-revenuecat_internal`
  Gemfile.lock
Labels: pr:other

#5629 Make managementURL public in SubscriptionInfo
  Sources/Identity/SubscriptionInfo.swift
  Tests/APITesters/AllAPITests/ObjcAPITester/RCSubscriptionInfoAPI.m
  Tests/APITesters/AllAPITests/SwiftAPITester/SubscriptionInfoAPI.swift
Labels: pr:other

#5628 MON-1374: Handle Promotional offer text in paywalls
  RevenueCatUI/Data/TestData.swift
  RevenueCatUI/Templates/V2/Components/Text/TextComponentView.swift
  RevenueCatUI/Templates/V2/Components/Text/TextComponentViewModel.swift
  RevenueCatUI/Templates/V2/Variables/VariableHandlerV2.swift
  Tests/RevenueCatUITests/PaywallsV2/VariableHandlerV2Tests.swift
Labels: pr:fix

#5636 [DX-520] Do not log unknown errors from health report endpoint
  Sources/Support/SDKHealthManager.swift
  Tests/UnitTests/Misc/SDKHealthManagerTests.swift
Labels: pr:fix
