Repository RevenueCat/purchases-ios, pull requests merged in 2025-09, with the labels that each got.

#5470 Extend appTarget settings to pass custom settings
  Examples/testCustomEntitlementsComputation/Project.swift
  Examples/testCustomEntitlementsComputation/testCustomEntitlementsComputation.xcodeproj/project.pbxproj
  Tuist/ProjectDescriptionHelpers/Settings.swift
Labels: pr:other

#5515 Post receipt in for purchases in Test Store
  Sources/Purchasing/Purchases/TransactionPoster.swift
  Sources/Purchasing/SimulatedStore/SimulatedStorePurchaseHandler.swift
  Tests/UnitTests/Purchasing/Purchases/TransactionPosterTests.swift
  Tests/UnitTests/SimulatedStore/SimulatedStorePurchaseHandlerTests.swift
Labels: pr:other

#5517 Fix markdown bold text in paywalls
  RevenueCatUI/Templates/V2/Components/Text/TextComponentView.swift
Labels: pr:fix, pr:RevenueCatUI, feat:PaywallV2

#5524 Fix compilation of RevenueCatUI in Xcode 14
  RevenueCatUI/CustomerCenter/ButtonStyles.swift
  RevenueCatUI/CustomerCenter/Views/ActiveSubscriptionButtonsView.swift
  RevenueCatUI/CustomerCenter/Views/NoSubscriptionsCardView.swift
  RevenueCatUI/CustomerCenter/Views/PurchaseCardView.swift
  RevenueCatUI/CustomerCenter/Views/RelevantPurchasesListView.swift
  RevenueCatUI/CustomerCenter/Views/ScrollViewSection.swift
Labels: pr:other

#5531 Fix simulated failed purchase in Test Store
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Tests/UnitTests/SimulatedStore/PurchasesOrchestratorSimulatedStoreTests.swift
Labels: pr:other

#5566 Tuist: rename generated Xcode workspace to RevenueCat-Tuist.xcworkspace
  .gitignore
  Workspace.swift
Labels: pr:other

#5572 Fix a flaky test
  Tests/UnitTests/Caching/FileRepositoryTests.swift
Labels: pr:other

#5581 Open promotional offers from CustomerCenter Detail screen
  RevenueCatUI/CustomerCenter/ViewModels/BaseManageSubscriptionViewModel.swift
  RevenueCatUI/CustomerCenter/Views/SubscriptionDetailView.swift
Labels: pr:fix, pr:RevenueCatUI, feat:Customer Center

#5587 Fix compilation error with XCFramework in Xcode 26
  Sources/Misc/Obsoletions.swift
Labels: pr:fix

#5588 Fix flaky snapshot test
  RevenueCatUI/Templates/V2/ViewHelpers/BadgeModifier.swift
Labels: pr:other

#5597 Remove `github_rate_limit` in release trains
  .circleci/config.yml
  Contributing/RELEASING.md
  Gemfile.lock
Labels: pr:other

#5601 Add Monetization as CODEOWNER
  .github/CODEOWNERS
Labels: pr:other

#5546 [DENG-1362] Reduce repeated logs
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/Data/Strings.swift
  RevenueCatUI/Templates/V2/ViewModelHelpers/UIConfigProvider.swift
  Tests/RevenueCatUITests/Helpers/TestCase.swift
  Tests/RevenueCatUITests/Helpers/TestLogHandler.swift
  Tests/RevenueCatUITests/PaywallsV2/UIConfigProviderTests.swift
Labels: pr:fix, pr:RevenueCatUI, feat:PaywallV2

#5603 MON-1231 - Fix badge border
  RevenueCatUI/Templates/V2/Components/Stack/StackComponentViewModel.swift
  RevenueCatUI/Templates/V2/ViewHelpers/BadgeModifier.swift
Labels: pr:fix, paywalls_v2

#5591 Fix paywalls button bottom sheet
  RevenueCatUI/Templates/V2/Components/Button/BottomSheetView.swift
  RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/ButtonWithFooterPreview.swift
  RevenueCatUI/Views/RemoteImage.swift
  Sources/Paywalls/Components/PaywallButtonComponent.swift
  Sources/Paywalls/Components/PaywallV2CacheWarming.swift
Labels: pr:feat, pr:RevenueCatUI, feat:PaywallV2
