Repository RevenueCat/purchases-ios, pull requests merged in 2025-03, with the labels that each got.

#4839 Use array instead of sets in diagnostics events
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Diagnostics/DiagnosticsEvent.swift
  Sources/Diagnostics/DiagnosticsTracker.swift
  Sources/Misc/Codable/AnyEncodable.swift
  Sources/Purchasing/ProductsManager.swift
  Tests/StoreKitUnitTests/ProductsManagerTests.swift
  Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
  Tests/UnitTests/TestHelpers/AnyEncodable+Equatable.swift
  Tests/UnitTests/TestHelpers/DiagnosticsEvent+Equatable.swift
Labels: pr:other

#4835 [Diagnostics] Add extra parameters to `applePurchaseAttempt`
  Sources/Diagnostics/DiagnosticsEvent.swift
  Sources/Diagnostics/DiagnosticsTracker.swift
  Sources/Diagnostics/Networking/DiagnosticsEventsRequest.swift
  Sources/Logging/Strings/StoreKitStrings.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Tests/StoreKitUnitTests/BasePurchasesOrchestratorTests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorSK1Tests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorSK2Tests.swift
  Tests/UnitTests/Diagnostics/DiagnosticsTrackerTests.swift
  Tests/UnitTests/Mocks/MockDateProvider.swift
  Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
Labels: pr:other

#4842 [Paywalls] Always use normal stack if the relevant axis size is fit
  RevenueCatUI/Templates/V2/Components/Stack/StackComponentViewModel.swift
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#4846 Fix potential wrong count on diagnosis sync
  Sources/Diagnostics/DiagnosticsFileHandler.swift
  Sources/Diagnostics/Networking/DiagnosticsSynchronizer.swift
  Tests/UnitTests/Diagnostics/DiagnosticsFileHandlerTests.swift
  Tests/UnitTests/Diagnostics/DiagnosticsSynchronizerTests.swift
Labels: pr:other

#4847 `Offering` `hasPaywall` getter
  RevenueCatUI/PaywallView.swift
  RevenueCatUI/UIKit/PaywallViewController.swift
  RevenueCatUI/View+PresentPaywall.swift
  Sources/Purchasing/Offering.swift
  Tests/APITesters/AllAPITests/SwiftAPITester/OfferingAPI.swift
  Tests/UnitTests/Networking/Responses/BaseHTTPResponseTest.swift
  Tests/UnitTests/Networking/Responses/CustomerInfoDecodingTests.swift
  Tests/UnitTests/Networking/Responses/Fixtures/OfferingsWithPaywallComponents.json
  Tests/UnitTests/Networking/Responses/GetIntroEligibilityDecodingTests.swift
  Tests/UnitTests/Networking/Responses/OfferingsDecodingTests.swift
  Tests/UnitTests/Networking/Responses/PaywallComponentsDataTests.swift
  Tests/UnitTests/Networking/Responses/PaywallDataDecodingTests.swift
  Tests/UnitTests/Networking/Responses/PostOfferDecodingTests.swift
  Tests/UnitTests/Networking/Responses/ProductEntitlementMappingDecodingTests.swift
  Tests/UnitTests/Networking/Responses/UIConfigDecodingTests.swift
  Tests/UnitTests/Paywalls/PaywallDataMultiTierTests.swift
  Tests/UnitTests/Paywalls/PaywallDataTests.swift
  Tests/UnitTests/Purchasing/OfferingsTests.swift
Labels: pr:feat

#4848 Add activity indicator to restore purchases button behavior
  RevenueCatUI/Purchasing/PurchaseHandler.swift
  RevenueCatUI/Templates/V2/Components/Button/ButtonComponentView.swift
  RevenueCatUI/Templates/V2/Components/Button/ButtonComponentViewModel.swift
  RevenueCatUI/Templates/V2/Components/Packages/PurchaseButton/PurchaseButtonComponentView.swift
  RevenueCatUI/Templates/V2/ViewHelpers/ProgressViewModifier.swift
Labels: pr:fix, pr:RevenueCatUI, feat:PaywallV2

#4849 Run `all-tests` on `main` and notify Slack
  .circleci/config.yml
Labels: pr:other

#4845 Virtual Currency Balances
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Identity/CustomerInfo.swift
  Sources/Networking/Responses/CustomerInfoResponse.swift
  Sources/Purchasing/VirtualCurrencyInfo.swift
  Tests/APITesters/AllAPITests/AllAPITests.xcodeproj/project.pbxproj
  Tests/APITesters/AllAPITests/ObjcAPITester/RCCustomerInfoAPI.m
  Tests/APITesters/AllAPITests/ObjcAPITester/RCVirtualCurrencyInfoAPI.h
  Tests/APITesters/AllAPITests/ObjcAPITester/RCVirtualCurrencyInfoAPI.m
  Tests/APITesters/AllAPITests/SwiftAPITester/CustomerInfoAPI.swift
  Tests/APITesters/AllAPITests/SwiftAPITester/VirtualCurrencyInfoAPI.swift
  Tests/UnitTests/Purchasing/CustomerInfoTests.swift
Labels: pr:feat, feat:Virtual Currencies

#4850 feat: Add onClose handler support for CustomerCenter
  RevenueCatUI/CustomerCenter/ButtonStyles.swift
  RevenueCatUI/CustomerCenter/View+PresentCustomerCenter.swift
  RevenueCatUI/CustomerCenter/Views/AppUpdateWarningView.swift
  RevenueCatUI/CustomerCenter/Views/CustomerCenterNavigationOptions.swift
  RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
  RevenueCatUI/CustomerCenter/Views/NoSubscriptionsView.swift
  RevenueCatUI/CustomerCenter/Views/WrongPlatformView.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/SamplePaywallsList.swift
Labels: pr:feat, feat:Customer Center

#4852 chore: Disable EventsManagerIntegrationTests till fixed
  BackendIntegrationTests/BackendIntegrationTests-All-CI.xctestplan
  BackendIntegrationTests/BackendIntegrationTests-All.xctestplan
  BackendIntegrationTests/BackendIntegrationTests-CustomEntitlements.xctestplan
  BackendIntegrationTests/BackendIntegrationTests-Offline.xctestplan
  BackendIntegrationTests/BackendIntegrationTests-Other.xctestplan
  BackendIntegrationTests/BackendIntegrationTests-SK1.xctestplan
  BackendIntegrationTests/BackendIntegrationTests-SK2.xctestplan
  BackendIntegrationTests/BackendIntegrationTests-Shedder.xctestplan
Labels: pr:other

#4824 feat: disable postAttributionData requests when in UI preview mode
  Sources/Attribution/AttributionPoster.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/StoreKitUnitTests/BasePurchasesOrchestratorTests.swift
  Tests/UnitTests/Attribution/AttributionPosterTests.swift
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Labels: pr:other

#4856 Have snapshot tests use same encoding as SDK
  Tests/UnitTests/Networking/Responses/__Snapshots__/CustomerInfoDecodingTests/testEncoding.1.json
  Tests/UnitTests/Networking/Responses/__Snapshots__/CustomerInfoDecodingTests/testEncodingWithFailedVerificationResponse.1.json
  Tests/UnitTests/Networking/Responses/__Snapshots__/CustomerInfoDecodingTests/testEncodingWithVerifiedResponse.1.json
  Tests/UnitTests/TestHelpers/SnapshotTesting+Extensions.swift
Labels: pr:other

#4843 Create `DiagnosticsEvent.Properties` for type safe diagnostics
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Diagnostics/DiagnosticsEvent.swift
  Sources/Diagnostics/DiagnosticsTracker.swift
  Sources/Diagnostics/Networking/DiagnosticsEventsRequest.swift
  Sources/Purchasing/ProductsManager.swift
  Tests/UnitTests/Diagnostics/DiagnosticsFileHandlerTests.swift
  Tests/UnitTests/Diagnostics/DiagnosticsSynchronizerTests.swift
  Tests/UnitTests/Diagnostics/DiagnosticsTrackerTests.swift
  Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
  Tests/UnitTests/Networking/Backend/BackendPostDiagnosticsTests.swift
  Tests/UnitTests/Networking/Requests/DiagnosticsEventEncodingTests.swift
  Tests/UnitTests/Networking/Requests/__Snapshots__/DiagnosticsEventEncodingTests/testEncoding.1.json
  Tests/UnitTests/TestHelpers/AnyEncodable+Equatable.swift
  Tests/UnitTests/TestHelpers/DiagnosticsEvent+Equatable.swift
Labels: pr:other

#4857 [Diagnostics] add missing parameter to `http_request_performed` event
  Sources/Diagnostics/DiagnosticsEvent.swift
  Sources/Diagnostics/DiagnosticsTracker.swift
  Sources/Networking/HTTPClient/HTTPClient.swift
  Tests/UnitTests/Diagnostics/DiagnosticsTrackerTests.swift
  Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
  Tests/UnitTests/Networking/Requests/DiagnosticsEventEncodingTests.swift
  Tests/UnitTests/Networking/Requests/__Snapshots__/DiagnosticsEventEncodingTests/testEncoding.1.json
Labels: pr:other

#4859 fix: diagnostics parameter key name
  Sources/Diagnostics/DiagnosticsEvent.swift
  Sources/Diagnostics/DiagnosticsTracker.swift
  Tests/UnitTests/Diagnostics/DiagnosticsTrackerTests.swift
  Tests/UnitTests/Networking/Requests/DiagnosticsEventEncodingTests.swift
  Tests/UnitTests/Networking/Requests/__Snapshots__/DiagnosticsEventEncodingTests/testEncoding.1.json
Labels: pr:other

#4855 Remove resetting `appSessionId` for customer center + add `appSessionId` and `eventId` to diagnostics events
  Sources/Diagnostics/DiagnosticsEvent.swift
  Sources/Diagnostics/DiagnosticsTracker.swift
  Sources/Misc/SystemInfo.swift
  Sources/Paywalls/Events/PaywallEventsManager.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/UnitTests/Diagnostics/DiagnosticsFileHandlerTests.swift
  Tests/UnitTests/Diagnostics/DiagnosticsSynchronizerTests.swift
  Tests/UnitTests/Diagnostics/DiagnosticsTrackerTests.swift
  Tests/UnitTests/Mocks/MockPaywallEventsManager.swift
  Tests/UnitTests/Networking/Backend/BackendPostDiagnosticsTests.swift
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostDiagnosticsTests/iOS15-testPostDiagnosticsEventsWithMultipleEvents.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostDiagnosticsTests/iOS15-testPostDiagnosticsEventsWithOneEvent.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostDiagnosticsTests/iOS16-testPostDiagnosticsEventsWithMultipleEvents.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostDiagnosticsTests/iOS16-testPostDiagnosticsEventsWithOneEvent.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostDiagnosticsTests/iOS17-testPostDiagnosticsEventsWithMultipleEvents.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostDiagnosticsTests/iOS17-testPostDiagnosticsEventsWithOneEvent.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostDiagnosticsTests/iOS18-testPostDiagnosticsEventsWithMultipleEvents.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostDiagnosticsTests/iOS18-testPostDiagnosticsEventsWithOneEvent.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostDiagnosticsTests/macOS-testPostDiagnosticsEventsWithMultipleEvents.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostDiagnosticsTests/macOS-testPostDiagnosticsEventsWithOneEvent.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostDiagnosticsTests/watchOS-testPostDiagnosticsEventsWithMultipleEvents.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostDiagnosticsTests/watchOS-testPostDiagnosticsEventsWithOneEvent.1.json
  Tests/UnitTests/Networking/Requests/DiagnosticsEventEncodingTests.swift
  Tests/UnitTests/Networking/Requests/__Snapshots__/DiagnosticsEventEncodingTests/testEncoding.1.json
  Tests/UnitTests/Paywalls/Events/PaywallEventsManagerTests.swift
  Tests/UnitTests/Paywalls/Events/PurchasesPaywallEventsTests.swift
Labels: pr:other

#4860 Update `customerInfo` from an `AsyncStream` instead of the `PurchasesDelegate` in the SwiftUI sample app
  Examples/MagicWeatherSwiftUI/Shared/Sources/Lifecycle/PurchasesDelegateHandler.swift
  Examples/MagicWeatherSwiftUI/Shared/Sources/ViewModels/UserViewModel.swift
Labels: pr:other

#4861 [Diagnostics] add `max_diagnostics_sync_retries_reached` event
  Sources/Diagnostics/DiagnosticsEvent.swift
  Sources/Diagnostics/DiagnosticsTracker.swift
  Sources/Diagnostics/Networking/DiagnosticsSynchronizer.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/UnitTests/Diagnostics/DiagnosticsSynchronizerTests.swift
  Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
Labels: pr:other

#4863 [Diagnostics] add `clearing_diagnostics_after_failed_sync` event
  Sources/Diagnostics/DiagnosticsEvent.swift
  Sources/Diagnostics/DiagnosticsTracker.swift
  Sources/Diagnostics/Networking/DiagnosticsSynchronizer.swift
  Tests/UnitTests/Diagnostics/DiagnosticsSynchronizerTests.swift
  Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
Labels: pr:other

#4864 Change Parsing of VirtualCurrencyInfo.balance from amount to balance
  Sources/Networking/Responses/CustomerInfoResponse.swift
  Sources/Purchasing/VirtualCurrencyInfo.swift
  Tests/UnitTests/Purchasing/CustomerInfoTests.swift
Labels: pr:other, feat:Virtual Currencies

#4680 Add root error info to public error
  Sources/Error Handling/ErrorDetails.swift
  Sources/Error Handling/PurchasesError.swift
  Sources/Logging/Strings/StoreKitStrings.swift
  Tests/APITesters/AllAPITests/SwiftAPITester/ErrorCodesAPI.swift
  Tests/UnitTests/Purchasing/ErrorUtilsTests.swift
Labels: pr:other

#4865 [Diagnostics] add `entered_offline_entitlements_mode` event
  Sources/Diagnostics/DiagnosticsEvent.swift
  Sources/Diagnostics/DiagnosticsTracker.swift
  Sources/OfflineEntitlements/OfflineCustomerInfoCreator.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
  Tests/UnitTests/Mocks/MockOfflineCustomerInfoCreator.swift
  Tests/UnitTests/OfflineEntitlements/CustomerInfoResponseHandlerTests.swift
  Tests/UnitTests/OfflineEntitlements/OfflineCustomerInfoCreatorTests.swift
Labels: pr:other

#4862 chore: `EventsManagerIntegrationTests` working as expected
  BackendIntegrationTests/BackendIntegrationTests-All-CI.xctestplan
  BackendIntegrationTests/BackendIntegrationTests-All.xctestplan
  BackendIntegrationTests/BackendIntegrationTests-CustomEntitlements.xctestplan
  BackendIntegrationTests/BackendIntegrationTests-Offline.xctestplan
  BackendIntegrationTests/BackendIntegrationTests-Other.xctestplan
  BackendIntegrationTests/BackendIntegrationTests-SK1.xctestplan
  BackendIntegrationTests/BackendIntegrationTests-SK2.xctestplan
  BackendIntegrationTests/BackendIntegrationTests-Shedder.xctestplan
  Tests/BackendIntegrationTests/EventsManagerIntegrationTests.swift
  Tests/UnitTests/TestHelpers/TestLogHandler.swift
Labels: enhancement, pr:other

#4837 chore: Remove unused key from customer center event
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/CustomerCenter/ViewModels/FeedbackSurveyViewModel.swift
  Sources/CustomerCenter/Events/CustomerCenterEvent.swift
  Sources/CustomerCenter/Events/EventsRequest+CustomerCenter.swift
  Tests/BackendIntegrationTests/EventsManagerIntegrationTests.swift
  Tests/RevenueCatUITests/CustomerCenter/FeedbackSurveyViewModelTests.swift
  Tests/UnitTests/CustomerCenter/Events/CustomerCenterAnswerSubmittedEventTests.swift
Labels: enhancement, feat:Customer Center, pr:other

#4867 [Diagnostics] add `error_entering_offline_entitlements_mode` event
  Sources/Diagnostics/DiagnosticsEvent.swift
  Sources/Diagnostics/DiagnosticsTracker.swift
  Sources/OfflineEntitlements/OfflineCustomerInfoCreator.swift
  Tests/UnitTests/Diagnostics/DiagnosticsTrackerTests.swift
  Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
  Tests/UnitTests/OfflineEntitlements/OfflineCustomerInfoCreatorTests.swift
Labels: pr:other

#4868 [Diagnostics] fix diagnostics sync retry logic
  Sources/Diagnostics/Networking/DiagnosticsSynchronizer.swift
  Tests/UnitTests/Diagnostics/DiagnosticsSynchronizerTests.swift
Labels: pr:other

#4870 Fallback to using variations of language code, script, and region for unknown `Locale` (ex: `zh_CN` will look for `zh_Hans`)
  RevenueCatUI/Templates/V2/Localizations/LocaleExtensions.swift
  RevenueCatUI/Templates/V2/Localizations/LocaleFinder.swift
  Tests/RevenueCatUITests/PaywallsV2/LocaleFinderTests.swift
Labels: pr:fix, pr:RevenueCatUI

#4866 [Diagnostics] Add offerings start and result events
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Caching/CacheStatus.swift
  Sources/Caching/DeviceCache.swift
  Sources/Diagnostics/DiagnosticsEvent.swift
  Sources/Diagnostics/DiagnosticsTracker.swift
  Sources/Purchasing/OfferingsManager.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/StoreKitUnitTests/BasePurchasesOrchestratorTests.swift
  Tests/StoreKitUnitTests/OfferingsManagerStoreKitTests.swift
  Tests/UnitTests/Caching/DeviceCacheTests.swift
  Tests/UnitTests/Diagnostics/DiagnosticsTrackerTests.swift
  Tests/UnitTests/Mocks/MockDeviceCache.swift
  Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
  Tests/UnitTests/Mocks/MockOfferingsManager.swift
  Tests/UnitTests/Purchasing/OfferingsManagerTests.swift
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesGetOfferingsTests.swift
  Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Labels: pr:other

#4879 Update fastlane plugin
  Gemfile.lock
Labels: pr:other

#4878 feat: Use pod_push_with_error_handling instead of pod_push for pushing Pods
  fastlane/Fastfile
Labels: enhancement, pr:other

#4880 feat: Refresh customer center and purchases after restore
  RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
  Tests/RevenueCatUITests/CustomerCenter/CustomerCenterViewModelTests.swift
Labels: pr:feat, pr:RevenueCatUI, feat:Customer Center

#4881 [Diagnostics] add `get_customer_info_started` and `get_customer_info_result` events
  Sources/Diagnostics/DiagnosticsEvent.swift
  Sources/Diagnostics/DiagnosticsTracker.swift
  Sources/Identity/CustomerInfoManager.swift
  Sources/Identity/IdentityManager.swift
  Sources/Logging/Strings/CustomerInfoStrings.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Tests/UnitTests/Diagnostics/DiagnosticsTrackerTests.swift
  Tests/UnitTests/Identity/CustomerInfoManagerTests.swift
  Tests/UnitTests/Identity/CustomerInfoManagerUIPreviewModeTests.swift
  Tests/UnitTests/Mocks/MockCustomerInfoManager.swift
  Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
  Tests/UnitTests/Networking/Requests/__Snapshots__/DiagnosticsEventEncodingTests/testEncoding.1.json
Labels: pr:other

#4885 [Diagnostics] Add sync purchases tracking (part 1)
  Sources/Diagnostics/DiagnosticsEvent.swift
  Sources/Diagnostics/DiagnosticsTracker.swift
  Tests/UnitTests/Diagnostics/DiagnosticsTrackerTests.swift
  Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
Labels: pr:other

#4888 [Diagnostics] add `apple_purchase_intent_received` event
  Sources/Diagnostics/DiagnosticsEvent.swift
  Sources/Diagnostics/DiagnosticsTracker.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/StoreKit2/StoreKit2PurchaseIntentListener.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorCommonTests.swift
  Tests/UnitTests/Diagnostics/DiagnosticsTrackerTests.swift
  Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
Labels: pr:other

#4872 Add `onCustomerCenterManagementOptionSelected` modifier
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/CustomerCenter/CustomerCenterView+Actions.swift
  RevenueCatUI/CustomerCenter/Data/CustomerCenterActionViewModifier.swift
  RevenueCatUI/CustomerCenter/Data/CustomerCenterActionWrapper.swift
  RevenueCatUI/CustomerCenter/Data/CustomerCenterManagementOption.swift
  RevenueCatUI/CustomerCenter/View+PresentCustomerCenter.swift
  RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptions/ManageSubscriptionsViewModel.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/SamplePaywallsList.swift
Labels: pr:feat, pr:RevenueCatUI, feat:Customer Center

#4893 [Diagnostics] add `apple_present_code_redemption_sheet_request` event
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Diagnostics/DiagnosticsEvent.swift
  Sources/Diagnostics/DiagnosticsTracker.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/UnitTests/Diagnostics/DiagnosticsTrackerTests.swift
  Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesDiagnosticsTrackingTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesRestoreTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesSyncPurchasesTests.swift
  Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Labels: pr:other

#4892 Fix possible memory leaks with diagnostics completion blocks
  Sources/Purchasing/OfferingsManager.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
Labels: pr:other

#4897 Fix unit tests: make `presentCodeRedemptionSheet()` test only run on iOS
  Tests/UnitTests/Purchasing/Purchases/PurchasesDiagnosticsTrackingTests.swift
Labels: pr:other

#4898 [Diagnostics] add `apple_transaction_queue_received` event
  Sources/Diagnostics/DiagnosticsEvent.swift
  Sources/Diagnostics/DiagnosticsTracker.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/StoreKit1/StoreKit1Wrapper.swift
  Tests/UnitTests/Diagnostics/DiagnosticsTrackerTests.swift
  Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
  Tests/UnitTests/Mocks/MockStoreKit1Wrapper.swift
  Tests/UnitTests/Purchasing/StoreKit1WrapperTests.swift
Labels: pr:other

#4900 [Paywalls V2] Fixes badges not being overriden
  RevenueCatUI/Templates/V2/Components/Stack/StackComponentViewModel.swift
Labels: pr:fix, pr:RevenueCatUI, feat:PaywallV2

#4894 [Diagnostics] add `apple_trial_or_intro_eligibility_request` event
  Sources/Diagnostics/DiagnosticsEvent.swift
  Sources/Diagnostics/DiagnosticsTracker.swift
  Sources/Purchasing/IntroEligibilityCalculator.swift
  Sources/Purchasing/ProductsManager.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/TrialOrIntroPriceEligibilityChecker.swift
  Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK1Tests.swift
  Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK2Tests.swift
  Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerUIPreviewModeTests.swift
  Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
  Tests/UnitTests/Mocks/MockIntroEligibilityCalculator.swift
  Tests/UnitTests/Mocks/MockTrialOrIntroPriceEligibilityChecker.swift
  Tests/UnitTests/Purchasing/IntroEligibilityCalculatorTests.swift
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Labels: pr:other

#4902 Skip `TrialOrIntroPriceEligibilityCheckerSK2Tests` in iOS 15
  Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK2Tests.swift
Labels: pr:other

#4886 [Diagnostics] add `purchase_started` and `purchase_result` events
  Sources/Diagnostics/DiagnosticsEvent.swift
  Sources/Diagnostics/DiagnosticsTracker.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorCommonTests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorSK1Tests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorSK2Tests.swift
  Tests/UnitTests/Diagnostics/DiagnosticsTrackerTests.swift
  Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
Labels: pr:other

#4905 Fixing fit mode on background property
  RevenueCatUI/Templates/V2/PaywallsV2View.swift
  RevenueCatUI/Templates/V2/ViewHelpers/BackgroundStyle.swift
  RevenueCatUI/Templates/V2/ViewHelpers/DisplayableColor.swift
  RevenueCatUI/Templates/V2/ViewHelpers/Shape.swift
  Sources/Paywalls/Components/Common/Background.swift
Labels: pr:fix, pr:RevenueCatUI

#4908 fix build issue in iOS 15
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
Labels: pr:other

#4904 [Diagnostics] add `apple_transaction_update_received` event
  Sources/Diagnostics/DiagnosticsEvent.swift
  Sources/Diagnostics/DiagnosticsTracker.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/StoreKit2/StoreKit2TransactionListener.swift
  Tests/StoreKitUnitTests/StoreKit2/StoreKit2TransactionListenerTests.swift
  Tests/UnitTests/Diagnostics/DiagnosticsTrackerTests.swift
  Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
Labels: pr:other

#4909 Fix build issues and tests in older versions of Xcode
  Sources/Purchasing/StoreKit2/StoreKit2TransactionListener.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorCommonTests.swift
  Tests/StoreKitUnitTests/StoreKit2/StoreKit2TransactionListenerTests.swift
Labels: pr:other

#4914 Fix nokogiri CVEs
  Gemfile
  Gemfile.lock
  Tests/InstallationTests/CocoapodsInstallation/Gemfile.lock
Labels: pr:other

#4906 fix: Hide subscription detail if consumable
  RevenueCatUI/CustomerCenter/Data/CustomerCenterConfigTestData.swift
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
  RevenueCatUI/CustomerCenter/Views/SubscriptionDetailsView.swift
Labels: pr:fix, feat:Customer Center

#4869 Carousel fixes
  RevenueCatUI/Templates/V2/Components/Carousel/CarouselComponentView.swift
  RevenueCatUI/Templates/V2/Components/Carousel/CarouselComponentViewModel.swift
  RevenueCatUI/Templates/V2/ViewHelpers/Shape.swift
Labels: pr:fix

#4916 chore: Test action wrapper for customer center
  RevenueCat.xcodeproj/project.pbxproj
  Tests/RevenueCatUITests/CustomerCenter/CustomerCenterActionWrapperTests.swift
Labels: feat:Customer Center, pr:other

#4697 chore: Test if Package.swift is valid on CI for older tooling
  .circleci/config.yml
Labels: enhancement, pr:other

#4915 [Paywalls] Extend the padding by border.width amount in components that support both
  RevenueCatUI/Templates/V2/Components/Carousel/CarouselComponentView.swift
  RevenueCatUI/Templates/V2/Components/Icon/IconComponentView.swift
  RevenueCatUI/Templates/V2/Components/Image/ImageComponentView.swift
  RevenueCatUI/Templates/V2/Components/Stack/StackComponentView.swift
  RevenueCatUI/Templates/V2/ViewModelHelpers/PaywallComponentTypeTransformers.swift
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#4875 [Paywalls] Add support for TimelineItem overrides
  RevenueCatUI/Templates/V2/Components/Timeline/TimelineComponentView.swift
  RevenueCatUI/Templates/V2/Components/Timeline/TimelineComponentViewModel.swift
  RevenueCatUI/Templates/V2/ViewModelHelpers/ViewModelFactory.swift
  Sources/Paywalls/Components/PaywallTimelineComponent.swift
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#4890 [Paywall] Center-align all Timeline component icons by calculating and setting their max width
  RevenueCatUI/Templates/V2/Components/Timeline/TimelineComponentView.swift
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#4924 [Diagnostics] Fix cache fetch policy key not matching specs
  Sources/Diagnostics/DiagnosticsEvent.swift
  Tests/UnitTests/Networking/Requests/DiagnosticsEventEncodingTests.swift
  Tests/UnitTests/Networking/Requests/__Snapshots__/DiagnosticsEventEncodingTests/testEncoding.1.json
Labels: pr:other

#4932 Fix load shedder integration tests after project changes
  Tests/BackendIntegrationTests/LoadShedderIntegrationTests.swift
  Tests/BackendIntegrationTests/__Snapshots__/LoadShedderIntegrationTests/testCanGetOfferings.1.json
Labels: pr:other

#4934 [Paywalls] Fix gradients in angles around 135º
  RevenueCatUI/Views/GradientView.swift
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2
