Repository RevenueCat/purchases-ios, pull requests merged in 2025-07, with the labels that each got.

#5345 Add Purchases.cachedVirtualCurrencies
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesType.swift
  Sources/Virtual Currencies/VirtualCurrencyManager.swift
  Tests/APITesters/AllAPITests/ObjcAPITester/RCPurchasesAPI.m
  Tests/APITesters/AllAPITests/SwiftAPITester/PurchasesAPI.swift
  Tests/UnitTests/Mocks/MockPurchases.swift
  Tests/UnitTests/Mocks/MockVirtualCurrencyManager.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesVirtualCurrenciesTests.swift
  Tests/UnitTests/Virtual Currencies/VirtualCurrencyManagerTests.swift
Labels: pr:feat

#5347 Use VCs in CustomerCenterViewModel
  RevenueCatUI/CustomerCenter/ViewModels/BaseManageSubscriptionViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/RelevantPurchasesListViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/SubscriptionDetailViewModel.swift
  RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
  RevenueCatUI/CustomerCenter/Views/RelevantPurchasesListView.swift
  RevenueCatUI/CustomerCenter/Views/SubscriptionDetailView.swift
  Tests/RevenueCatUITests/CustomerCenter/BaseManageSubscriptionViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/CustomerCenterViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/SubscriptionDetailViewModelTests.swift
Labels: pr:other

#5342 VC Integration Tests
  BackendIntegrationTests/BackendIntegrationTests-Offline.xctestplan
  BackendIntegrationTests/BackendIntegrationTests-Other.xctestplan
  RevenueCat.xcodeproj/project.pbxproj
  Tests/BackendIntegrationTests/OtherIntegrationTests.swift
  Tests/BackendIntegrationTests/VirtualCurrencyIntegrationTests.swift
Labels: pr:other

#5292 Preferred UI locale for UI components
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/Data/PaywallViewConfiguration.swift
  RevenueCatUI/Data/Strings.swift
  RevenueCatUI/PaywallView.swift
  RevenueCatUI/Purchasing/MockPurchases.swift
  RevenueCatUI/Purchasing/PaywallPurchasesType.swift
  RevenueCatUI/Purchasing/PurchaseHandler+TestData.swift
  RevenueCatUI/Purchasing/PurchaseHandler.swift
  RevenueCatUI/Purchasing/Purchases+RevenueCatUI.swift
  RevenueCatUI/Templates/V2/Localizations/LocaleExtensions.swift
  RevenueCatUI/Templates/V2/PaywallsV2View.swift
  RevenueCatUI/Views/LoadingPaywallView.swift
  Sources/Misc/Locale/PreferredLocalesProvider.swift
  Sources/Misc/SystemInfo.swift
  Sources/Paywalls/PaywallData+Localization.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/APITesters/AllAPITests/AllAPITests.xcodeproj/project.pbxproj
  Tests/APITesters/AllAPITests/RevenueCatUISwiftAPITester/Purchases+RevenueCatUI_API.swift
  Tests/RevenueCatUITests/BaseSnapshotTest.swift
  Tests/RevenueCatUITests/Templates/OtherPaywallViewTests.swift
  Tests/RevenueCatUITests/Templates/PaywallViewLocalizationTests.swift
  Tests/RevenueCatUITests/Templates/Template2ViewTests.swift
Labels: pr:feat, pr:RevenueCatUI, feat:Customer Center, feat:PaywallV2

#5312 Consider Offerings cache stale when preferred locales change
  Sources/Caching/DeviceCache.swift
  Sources/Purchasing/OfferingsManager.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/StoreKitUnitTests/BasePurchasesOrchestratorTests.swift
  Tests/StoreKitUnitTests/BeginRefundRequestHelperTests.swift
  Tests/StoreKitUnitTests/ManageSubscriptionsHelperTests.swift
  Tests/StoreKitUnitTests/OfferingsManagerStoreKitTests.swift
  Tests/UnitTests/Attribution/AttributionPosterTests.swift
  Tests/UnitTests/Caching/DeviceCacheTests.swift
  Tests/UnitTests/DeepLink/WebPurchaseRedemptionHelperTests.swift
  Tests/UnitTests/Identity/CustomerInfoManagerTests.swift
  Tests/UnitTests/Identity/IdentityManagerTests.swift
  Tests/UnitTests/Mocks/MockDeviceCache.swift
  Tests/UnitTests/Mocks/MockIdentityManager.swift
  Tests/UnitTests/Mocks/MockSystemInfo.swift
  Tests/UnitTests/OfflineEntitlements/OfflineEntitlementsManagerTests.swift
  Tests/UnitTests/Purchasing/OfferingsManagerTests.swift
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/SubscriberAttributes/DeviceCacheSubscriberAttributesTests.swift
  Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
  Tests/UnitTests/SubscriberAttributes/SubscriberAttributesManagerTests.swift
Labels: pr:other

#5349 Fix google products display for customer center
  RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
  Tests/RevenueCatUITests/CustomerCenter/CustomerCenterViewModelTests.swift
Labels: pr:fix, feat:Customer Center

#5350 fix `Purchases` temporary leak when running SDK health check
  Sources/Purchasing/Purchases/Purchases.swift
Labels: pr:other

#5353 Temporary revert of automatic health reporting in the SDK
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Networking/Backend.swift
  Sources/Networking/HTTPClient/HTTPRequestPath.swift
  Sources/Networking/InternalAPI.swift
  Sources/Networking/Operations/HealthReportAvailabilityOperation.swift
  Sources/Networking/Operations/HealthReportOperation.swift
  Sources/Networking/Responses/HealthReportAvailabilityResponse.swift
  Sources/Networking/Responses/HealthReportResponse.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesType.swift
  Sources/Support/DebugUI/DebugViewModel.swift
  Sources/Support/HealthReport+Validate.swift
  Sources/Support/PaymentAuthorizationProvider.swift
  Sources/Support/PurchasesDiagnostics.swift
  Sources/Support/SDKHealthError+CustomNSError.swift
  Sources/Support/SDKHealthManager.swift
  Tests/UnitTests/Misc/PurchasesDiagnosticsTests.swift
  Tests/UnitTests/Misc/SDKHealthManagerTests.swift
  Tests/UnitTests/Mocks/MockBackend.swift
  Tests/UnitTests/Mocks/MockPurchases.swift
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
  Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Labels: pr:other

#5365 Fixes API tests after changes to public API
  Sources/Networking/Backend.swift
  Sources/Networking/InternalAPI.swift
  Sources/Networking/Operations/HealthReportAvailabilityOperation.swift
  Sources/Networking/Operations/HealthReportOperation.swift
  Sources/Networking/Responses/HealthReportResponse.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/Purchases/PurchasesType.swift
  Sources/Support/HealthReport+Validate.swift
  Sources/Support/PurchasesDiagnostics.swift
  Sources/Support/SDKHealthManager.swift
Labels: bug, pr:fix

#5238 Adding deep link for testing in Paywalls Tester
  Tests/TestingApps/PaywallsTester/PaywallsTester/PaywallsPreview.swift
Labels: pr:other

#5364 Add build configurations for tuist workspace
  Examples/MagicWeather/MagicWeather.xcodeproj/project.pbxproj
  Examples/MagicWeather/Project.swift
  Examples/MagicWeatherSwiftUI/Project.swift
  Examples/PurchaseTester/Project.swift
  Examples/rc-maestro/Project.swift
  Examples/rc-maestro/rc-maestro/Resources/Local.xcconfig.sample
  Examples/testCustomEntitlementsComputation/Project.swift
  Examples/testCustomEntitlementsComputation/testCustomEntitlementsComputation.xcodeproj/project.pbxproj
  Projects/APITesters/Project.swift
  Projects/PaywallTester/Project.swift
  Projects/RevenueCat/Project.swift
  Projects/RevenueCatUI/Project.swift
  Projects/v3LoadShedderIntegration/Project.swift
  Tests/TestPlans/AllTests.xctestplan
  Tuist/ProjectDescriptionHelpers/Configurations.swift
  Tuist/ProjectDescriptionHelpers/Settings.swift
  Tuist/ProjectDescriptionHelpers/SettingsDictionary.swift
  Workspace.swift
Labels: pr:other

#5378 Update default height of paywalls when using .presentIfNeeded on Mac Catalyst to something that is more reasonable.
  RevenueCatUI/View+PresentPaywall.swift
Labels: pr:fix

#5372 Fix rendering of buttons in Mac Catalyst mode when optimized for Mac.
  RevenueCatUI/Templates/V2/PaywallsV2View.swift
  RevenueCatUI/Views/PurchaseButton.swift
Labels: pr:fix

#5381 Use SwiftUI instead of UIKit to present an alert in Paywall Tester app
  Tests/TestingApps/PaywallsTester/PaywallsTester/PaywallsPreview.swift
Labels: pr:other

#5384 Add `@_spi` to initializers of virtual currencies APIs
  Sources/Virtual Currencies/VirtualCurrencies.swift
  Sources/Virtual Currencies/VirtualCurrency.swift
  Tests/UnitTests/Caching/DeviceCacheTests.swift
  Tests/UnitTests/Mocks/MockVirtualCurrencyManager.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesVirtualCurrenciesTests.swift
  Tests/UnitTests/Virtual Currencies/VirtualCurrenciesTests.swift
  Tests/UnitTests/Virtual Currencies/VirtualCurrencyManagerTests.swift
  Tests/UnitTests/Virtual Currencies/VirtualCurrencyTests.swift
Labels: pr:other

#5377 Add a mechanism to test the presentIfNeeded API in the Paywalls tester.
  Tests/TestingApps/PaywallsTester/PaywallsTester/Data/OfferingsPaywallsViewModel.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingList/APIKeyDashboardList.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/PaywallPresenter.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/PaywallViewMode+Extensions.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/SamplePaywallsList.swift
Labels: pr:other

#5395 Potential fix for flaky test
  Tests/BackendIntegrationTests/OfflineStoreKitIntegrationTests.swift
Labels: pr:other

#5393 Tuist: unify project settings
  Examples/MagicWeather/Project.swift
  Examples/MagicWeatherSwiftUI/Project.swift
  Examples/PurchaseTester/Project.swift
  Examples/rc-maestro/Project.swift
  Examples/testCustomEntitlementsComputation/Project.swift
  Projects/APITesters/Project.swift
  Projects/PaywallTester/Project.swift
  Projects/RevenueCat/Project.swift
  Projects/RevenueCatUI/Project.swift
  Projects/v3LoadShedderIntegration/Project.swift
  Tuist/ProjectDescriptionHelpers/Settings.swift
Labels: pr:other

#5396 Add date to failure messages of entitlement verification in tests
  Tests/BackendIntegrationTests/Helpers/BaseStoreKitIntegrationTests+Verification.swift
Labels: pr:other

#5399 Tuist: fix compilation of RevenueCat and RevenueCatUI projects in visionOS
  Tuist/ProjectDescriptionHelpers/Settings.swift
Labels: pr:other

#5376 When taking screenshots for validation, ignore safe area.
  Tests/RevenueCatUITests/PaywallsV2/TakeScreenshot.swift
Labels: pr:other

#5404 Update VC Caching Log Message
  Sources/Logging/Strings/VirtualCurrencyStrings.swift
Labels: pr:fix, feat:Virtual Currencies

#5370 Add an app to run paywall validation tests locally
  Projects/PaywallValidationTester/Project.swift
  RevenueCat.xcodeproj/project.pbxproj
  Tests/RevenueCatUITests/PaywallsV2/PaywallPreviewResourcesLoader.swift
  Tests/RevenueCatUITests/PaywallsV2/TakeScreenshot.swift
  Tests/TestingApps/PaywallValidationTester/Info.plist
  Tests/TestingApps/PaywallValidationTester/PaywallValidationTesterApp.swift
  Tests/TestingApps/PaywallValidationTester/PaywallValidationTesterView.swift
  Workspace.swift
Labels: pr:other

#5417 Replace isLifetimeSubscription for isLifetime
  RevenueCatUI/CustomerCenter/Actions/CustomerCenterConfigData.HelpPath+PurchaseInformation.swift
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation+Mock.swift
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift
  RevenueCatUI/CustomerCenter/Views/PurchaseCardView.swift
  Tests/RevenueCatUITests/CustomerCenter/PurchaseInformationTests.swift
Labels: pr:fix, feat:Customer Center

#5413 Fix issue where previews running on Emerge servers were not following specialized codepaths for previews
  RevenueCatUI/CustomerCenter/ViewModels/VirtualCurrencyBalancesScreenViewModel.swift
  RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
  RevenueCatUI/CustomerCenter/Views/PurchaseHistory/PurchaseHistoryView.swift
  RevenueCatUI/Templates/V2/Components/Packages/PurchaseButton/PurchaseButtonComponentView.swift
  Sources/LocalReceiptParsing/Helpers/ProcessInfo+Extensions.swift
Labels: pr:other

#5375 Fix color space on Mac screenshots.
  Tests/RevenueCatUITests/PaywallsV2/TakeScreenshot.swift
Labels: pr:other

#5422 Add fallback for change plans id and only display selected
  Examples/rc-maestro/rc-maestro/Resources/StoreKit/StoreKitConfiguration.storekit
  Examples/rc-maestro/rc-maestro/Sources/rc-maestro/ContentView.swift
  RevenueCatUI/CustomerCenter/Abstractions/CustomerCenterPurchasesType.swift
  RevenueCatUI/CustomerCenter/Extensions/PurchaseInformation+Creation.swift
  RevenueCatUI/CustomerCenter/ViewModels/BaseManageSubscriptionViewModel.swift
Labels: pr:fix, feat:Customer Center

#5426 Add Test Store Products Manager
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Error Handling/ErrorUtils.swift
  Sources/Misc/PriceFormatterProvider.swift
  Sources/Purchasing/ProductsManager.swift
  Sources/Purchasing/ProductsManagerFactory.swift
  Sources/Purchasing/ProductsManagerType.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Purchasing/StoreKitAbstractions/SubscriptionPeriod.swift
  Sources/Purchasing/TestStore/TestStoreProductsManager.swift
  Sources/Purchasing/TestStore/WebBillingProduct+TestStoreProduct.swift
  Sources/Purchasing/TrialOrIntroPriceEligibilityChecker.swift
  Tests/UnitTests/Mocks/MockOfferingsAPI.swift
  Tests/UnitTests/Purchasing/TestStoreUnitTests/TestStoreMockData.swift
  Tests/UnitTests/Purchasing/TestStoreUnitTests/TestStoreProductsManagerTests.swift
  Tests/UnitTests/Purchasing/TestStoreUnitTests/WebProductToStoreProductConversionTests.swift
Labels: pr:other

#5432 Allow custom URL for empty screen in customer center
  RevenueCatUI/CustomerCenter/Actions/CustomerCenterConfigData.HelpPath+PurchaseInformation.swift
Labels: pr:fix, feat:Customer Center

#5435 Add Azerbaijani locale support for Paywalls
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/Resources/az.lproj/Localizable.strings
  Tests/RevenueCatUITests/PaywallsV2/LocaleFinderTests.swift
Labels: pr:feat, pr:RevenueCatUI

#5371 Add Mac Catalyst and iPad/iPhone app on Mac Paywall Validation Screenshot Generation
  .circleci/config.yml
  Tests/UnitTestsHostApp/fastlane/Matchfile
  fastlane/Fastfile
Labels: pr:other
