Repository RevenueCat/purchases-ios, pull requests merged in 2025-05, with the labels that each got.

#5029 [Paywalls] Add new button component action for web paywall links
  RevenueCatUI/Templates/V2/Components/Button/ButtonComponentView.swift
  RevenueCatUI/Templates/V2/Components/Button/ButtonComponentViewModel.swift
  Sources/Paywalls/Components/PaywallButtonComponent.swift
Labels: pr:other, feat:Paywall Components, feat:PaywallV2

#5017 feat: Add missing pieces for maestro local execution
  .circleci/config.yml
  Examples/rc-maestro/Tuist/Package.swift
  Examples/rc-maestro/maestro/config.yaml
  Examples/rc-maestro/maestro/customer_center/change_plans/customer_center_change_plans.yaml
  Examples/rc-maestro/maestro/customer_center/manage_subscriptions/customer_center_manage_subscriptions_empty.yaml
  Examples/rc-maestro/maestro/customer_center/manage_subscriptions/customer_center_manage_subscriptions_restore_purchases.yaml
  Examples/rc-maestro/maestro/customer_center/manage_subscriptions/customer_center_manage_subscriptions_see_all_purchases.yaml
  Examples/rc-maestro/maestro/customer_center/promo_offer/customer_center_accept_promo_offer.yaml
  Examples/rc-maestro/maestro/customer_center/promo_offer/customer_center_reject_promo_offer.yaml
  Examples/rc-maestro/maestro/utils/cancel_subscription.yaml
  Examples/rc-maestro/rc-maestro/Resources/StoreKit/StoreKitConfigDefault.storekit
  Examples/rc-maestro/rc-maestro/Sources/rc-maestro/ContentView.swift
  fastlane/README.md
Labels: enhancement, pr:RevenueCatUI, pr:other

#5030 Release/5.22.2
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  RevenueCat.podspec
  RevenueCatUI.podspec
  Sources/Info.plist
  Sources/Misc/SystemInfo.swift
  Tests/BackendIntegrationTestApp/Info.plist
  Tests/BackendIntegrationTests/Info.plist
  Tests/BackendIntegrationTests/LoadShedderIntegrationTests.swift
  Tests/InstallationTests/CommonFiles/RevenueCat-Swift.h
  Tests/UnitTests/Info.plist
  Tests/UnitTestsHostApp/Info.plist
  scripts/docs/index.html
  scripts/docs/v4_api_migration_guide.html
  scripts/docs/v5_api_migration_guide.html
Labels: pr:next_release

#5037 other: Use not synced storekit config to avoid unwanted changes
  Examples/rc-maestro/Project.swift
  Examples/rc-maestro/maestro/customer_center/change_plans/customer_center_change_plans.yaml
  Examples/rc-maestro/maestro/customer_center/manage_subscriptions/customer_center_manage_subscriptions_see_all_purchases.yaml
  Examples/rc-maestro/maestro/customer_center/promo_offer/customer_center_accept_promo_offer.yaml
  Examples/rc-maestro/maestro/customer_center/promo_offer/customer_center_reject_promo_offer.yaml
  Examples/rc-maestro/maestro/utils/cancel_subscription.yaml
  Examples/rc-maestro/rc-maestro/Resources/StoreKit/StoreKitConfiguration.storekit
  Examples/rc-maestro/rc-maestro/Sources/rc-maestro/ContentView.swift
Labels: feat:Customer Center, pr:other

#5039 chore: Add right chevron to see all purchases
  RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptions/ManageSubscriptionsViewModel.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
Labels: pr:RevenueCatUI, feat:Customer Center, pr:other

#5035 fix: Hide cancel & refundRequest if subscription is already cancelled
  Examples/rc-maestro/maestro/customer_center/promo_offer/customer_center_reject_promo_offer.yaml
  RevenueCatUI/CustomerCenter/Data/CustomerCenterConfigTestData.swift
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift
  RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptions/ManageSubscriptionsViewModel.swift
  RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
  RevenueCatUI/CustomerCenter/Views/SubscriptionDetailsView.swift
  Tests/RevenueCatUITests/CustomerCenter/ManageSubscriptionsViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/PurchaseInformationTests.swift
Labels: pr:fix, pr:RevenueCatUI, feat:Customer Center

#5041 [Paywalls] Remove url manipulation and alert from web paywall links
  RevenueCatUI/Templates/V2/Components/Button/ButtonComponentView.swift
Labels: pr:other, feat:Paywall Components, feat:PaywallV2

#5044 Add Bottom Sheet View
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/Templates/V2/Components/Button/BottomSheetView.swift
Labels: pr:feat, pr:RevenueCatUI

#5047 feat: Introduce fade transition for loop animated CarouselView
  RevenueCatUI/Templates/V2/Components/Carousel/CarouselComponentView.swift
  Sources/Paywalls/Components/PaywallCarouselComponent.swift
Labels: pr:feat, pr:RevenueCatUI, feat:PaywallV2

#5053 Make sheet take up full screen
  RevenueCatUI/Templates/V2/Components/Button/BottomSheetView.swift
  RevenueCatUI/Templates/V2/Components/Button/ButtonComponentView.swift
  RevenueCatUI/Templates/V2/Components/Root/RootView.swift
  RevenueCatUI/Templates/V2/EnvironmentObjects/OpenSheet.swift
Labels: pr:fix, pr:RevenueCatUI

#5049 Purchase web package
  RevenueCatUI/Data/Strings.swift
  RevenueCatUI/Data/TestData.swift
  RevenueCatUI/Helpers/PaywallData+Default.swift
  RevenueCatUI/Templates/V2/Components/Button/ButtonComponentView.swift
  RevenueCatUI/Templates/V2/Components/ComponentsView.swift
  RevenueCatUI/Templates/V2/Components/Packages/Package/PackageComponentView.swift
  RevenueCatUI/Templates/V2/Components/Packages/PurchaseButton/PurchaseButtonComponentView.swift
  RevenueCatUI/Templates/V2/Components/Packages/PurchaseButton/PurchaseButtonComponentViewModel.swift
  RevenueCatUI/Templates/V2/Components/Stack/StackComponentView.swift
  RevenueCatUI/Templates/V2/Previews/PreviewMock.swift
  RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/FallbackComponentPreview.swift
  RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/FamilySharingTogglePreview.swift
  RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/MultiTierPreview.swift
  RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/PurchaseButtonInPackage.swift
  RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/Template1Preview.swift
  RevenueCatUI/Templates/V2/ViewModelHelpers/ViewModelFactory.swift
  RevenueCatUI/Views/LoadingPaywallView.swift
  Sources/Networking/Responses/OfferingsResponse.swift
  Sources/Paywalls/Components/PaywallPurchaseButtonComponent.swift
  Sources/Purchasing/Offering.swift
  Sources/Purchasing/Offerings.swift
  Sources/Purchasing/OfferingsFactory.swift
  Sources/Purchasing/Package.swift
  Tests/RevenueCatUITests/Data/PackageVariablesTests.swift
  Tests/RevenueCatUITests/Data/PaywallDataValidationTests.swift
  Tests/RevenueCatUITests/Data/TemplateViewConfigurationTests.swift
  Tests/RevenueCatUITests/Data/VariablesTests.swift
  Tests/RevenueCatUITests/Helpers/DataExtensions.swift
  Tests/RevenueCatUITests/Templates/PaywallViewLocalizationTests.swift
  Tests/StoreKitUnitTests/OfferingsManagerStoreKitTests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorSK1Tests.swift
  Tests/StoreKitUnitTests/PurchasesOrchestratorSK2Tests.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Config/SamplePaywalls.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Responses/PaywallsResponse.swift
  Tests/UnitTests/Mocks/MockOfferingsFactory.swift
  Tests/UnitTests/Paywalls/PaywallCacheWarmingTests.swift
  Tests/UnitTests/Purchasing/OfferingsManagerTests.swift
  Tests/UnitTests/Purchasing/OfferingsTests.swift
  Tests/UnitTests/Purchasing/PurchaseParamsTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesGetOfferingsTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesGetProductsTests.swift
Labels: pr:feat

#5055 Add endpoint for fetching web billing products
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Networking/Caching/WebProductsCallback.swift
  Sources/Networking/HTTPClient/HTTPRequest.swift
  Sources/Networking/HTTPClient/HTTPRequestPath.swift
  Sources/Networking/OfferingsAPI.swift
  Sources/Networking/Operations/GetWebProductsOperation.swift
  Sources/Networking/Responses/WebProductsResponse.swift
  Sources/Networking/WebBillingHTTPRequestPath.swift
  Tests/UnitTests/Mocks/MockHTTPClient.swift
  Tests/UnitTests/Mocks/MockOfferingsAPI.swift
Labels: pr:other

#5050 feat: Show subscription list instead of only the active subscription
  Examples/rc-maestro/rc-maestro/Resources/StoreKit/StoreKitConfiguration.storekit
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/CustomerCenter/ButtonStyles.swift
  RevenueCatUI/CustomerCenter/Data/CustomerCenterConfigData+Mock.swift
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift
  RevenueCatUI/CustomerCenter/Data/Transaction.swift
  RevenueCatUI/CustomerCenter/Utilities/IdentifiableURL.swift
  RevenueCatUI/CustomerCenter/ViewModels/BaseManageSubscriptionViewModel/BaseManageSubscriptionViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptionViewModel/ManageSubscriptionViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptions/ManageSubscriptionsViewModel.swift
  RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
  RevenueCatUI/CustomerCenter/Views/FeedbackSurveyView.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscription/ManageSubscriptionView.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscriptions/ManageSubscriptionsButtonsView.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscriptions/ManageSubscriptionsView.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsButtonsView.swift
  RevenueCatUI/CustomerCenter/Views/NoSubscriptionsView.swift
  RevenueCatUI/CustomerCenter/Views/RestorePurchasesAlert.swift
  RevenueCatUI/CustomerCenter/Views/SubscriptionDetailsView.swift
  RevenueCatUI/CustomerCenter/Views/WrongPlatformView.swift
  RevenueCatUI/Data/Strings.swift
  Sources/CustomerCenter/CustomerCenterConfigData.swift
  Sources/Identity/CustomerInfo.swift
  Sources/Identity/SubscriptionInfo.swift
  Sources/Networking/Responses/CustomerCenterConfigResponse.swift
  Sources/Networking/Responses/CustomerInfoResponse.swift
  Tests/RevenueCatUITests/CustomerCenter/ContactSupportUtilitiesTests.swift
  Tests/RevenueCatUITests/CustomerCenter/CustomerCenterViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/ManageSubscriptionsViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/Mocks/MockCustomerCenterPurchases.swift
  Tests/RevenueCatUITests/CustomerCenter/PurchaseInformationTests.swift
  Tests/UnitTests/CustomerCenter/CustomerCenterConfigDataTests.swift
Labels: pr:feat, feat:Customer Center

#5064 Fix sheet view in v2 paywall not covering bottom safe area
  RevenueCatUI/Templates/V2/Components/Button/BottomSheetView.swift
Labels: pr:fix, feat:PaywallV2

#5066 feat: Introducing billing information for PurchaseInformation in CustomerCenter
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/CustomerCenter/Data/CustomerCenterConfigData+Mock.swift
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation+Mock.swift
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift
  RevenueCatUI/CustomerCenter/Data/StoreProductDiscountType+Mock.swift
  RevenueCatUI/CustomerCenter/Extensions/CustomerInfo+ActiveTransaction.swift
  RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptions/ManageSubscriptionsViewModel.swift
  RevenueCatUI/CustomerCenter/Views/CompatibilityLabeledContent.swift
  RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscription/ManageSubscriptionView.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscriptions/ManageSubscriptionsView.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscriptions/PurchaseInformationCardView.swift
  RevenueCatUI/CustomerCenter/Views/RestorePurchasesAlert.swift
  RevenueCatUI/CustomerCenter/Views/SubscriptionDetailsView.swift
  Sources/CustomerCenter/CustomerCenterConfigData.swift
  Tests/RevenueCatUITests/CustomerCenter/CustomerCenterViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/ManageSubscriptionsViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/PurchaseInformationTests.swift
Labels: pr:feat, pr:RevenueCatUI, feat:Customer Center

#5068 Add web billing API key to Configuration builder
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Logging/Strings/NetworkStrings.swift
  Sources/Misc/APIKeys.swift
  Sources/Networking/Backend.swift
  Sources/Networking/HTTPClient/HTTPClient.swift
  Sources/Networking/HTTPClient/HTTPRequestPath.swift
  Sources/Networking/HTTPClient/NetworkError.swift
  Sources/Networking/WebBillingHTTPRequestPath.swift
  Sources/Purchasing/Configuration.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Sources/Security/Signing+ResponseVerification.swift
  Sources/Security/Signing.swift
  Tests/APITesters/AllAPITests/SwiftAPITester/ConfigurationAPI.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Core/ConfiguredPurchases.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTesterWatchOS/PurchaseTesterWatchApp.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/PurchaseTesterApp.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/ConfigurationView.swift
  Tests/UnitTests/Mocks/MockBackendConfiguration.swift
  Tests/UnitTests/Mocks/MockHTTPClient.swift
  Tests/UnitTests/Networking/Backend/BaseBackendTest.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
  Tests/UnitTests/Networking/HTTPResponseTests.swift
  Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
  Tests/UnitTests/Security/SigningTests.swift
  Tests/UnitTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift
Labels: pr:other

#5078 revert 4087a9c
  RevenueCatUI/CustomerCenter/ButtonStyles.swift
  RevenueCatUI/CustomerCenter/Data/CustomerCenterConfigTestData.swift
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation+Mock.swift
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift
  RevenueCatUI/CustomerCenter/Data/StoreProductDiscountType+Mock.swift
  RevenueCatUI/CustomerCenter/Data/Transaction.swift
  RevenueCatUI/CustomerCenter/Extensions/CustomerInfo+ActiveTransaction.swift
  RevenueCatUI/CustomerCenter/Utilities/IdentifiableURL.swift
  RevenueCatUI/CustomerCenter/ViewModels/BaseManageSubscriptionViewModel/BaseManageSubscriptionViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptionViewModel/ManageSubscriptionViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptions/ManageSubscriptionsViewModel.swift
  RevenueCatUI/CustomerCenter/Views/CompatibilityLabeledContent.swift
  RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
  RevenueCatUI/CustomerCenter/Views/FeedbackSurveyView.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscription/ManageSubscriptionView.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscriptions/ManageSubscriptionsButtonsView.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscriptions/ManageSubscriptionsView.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscriptions/PurchaseInformationCardView.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsButtonsView.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
  RevenueCatUI/CustomerCenter/Views/NoSubscriptionsView.swift
  RevenueCatUI/CustomerCenter/Views/RestorePurchasesAlert.swift
  RevenueCatUI/CustomerCenter/Views/SubscriptionDetailsView.swift
  RevenueCatUI/CustomerCenter/Views/WrongPlatformView.swift
  Tests/RevenueCatUITests/CustomerCenter/ContactSupportUtilitiesTests.swift
  Tests/RevenueCatUITests/CustomerCenter/CustomerCenterViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/ManageSubscriptionsViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/Mocks/MockCustomerCenterPurchases.swift
  Tests/RevenueCatUITests/CustomerCenter/PurchaseInformationTests.swift
Labels: pr:other

#5074 Fix flakiness of `uuid` implementation
  Sources/FoundationExtensions/Data+Extensions.swift
Labels: pr:other

#5075 Fix build of RevenueCatUI from Xcode workspace
  RevenueCat.xcodeproj/project.pbxproj
Labels: pr:other

#5079 Improve mock interface for CustomerCenterConfigData
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/CustomerCenter/ButtonStyles.swift
  RevenueCatUI/CustomerCenter/Data/CustomerCenterConfigData+Mock.swift
  RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
  RevenueCatUI/CustomerCenter/Views/FeedbackSurveyView.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
  RevenueCatUI/CustomerCenter/Views/NoSubscriptionsView.swift
  RevenueCatUI/CustomerCenter/Views/RestorePurchasesAlert.swift
  RevenueCatUI/CustomerCenter/Views/SubscriptionDetailsView.swift
  RevenueCatUI/CustomerCenter/Views/WrongPlatformView.swift
  Tests/RevenueCatUITests/CustomerCenter/CustomerCenterViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/ManageSubscriptionsViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/Mocks/MockCustomerCenterPurchases.swift
Labels: enhancement, pr:other

#5080 Add management URL to PurchaseInformation
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCat.xcworkspace/xcshareddata/swiftpm/Package.resolved
  RevenueCatUI/CustomerCenter/Data/CustomerCenterConfigData+Mock.swift
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation+Mock.swift
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift
  RevenueCatUI/CustomerCenter/Data/Transaction.swift
  RevenueCatUI/CustomerCenter/Utilities/IdentifiableURL.swift
  RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptions/ManageSubscriptionsViewModel.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsButtonsView.swift
  RevenueCatUI/CustomerCenter/Views/WrongPlatformView.swift
  Tests/RevenueCatUITests/CustomerCenter/ManageSubscriptionsViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/PurchaseInformationTests.swift
Labels: pr:feat, feat:Customer Center

#5085 Add expirationDate and renewalDate to PurchaseInformation
  RevenueCatUI/CustomerCenter/Data/CustomerCenterConfigData+Mock.swift
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation+Mock.swift
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift
  RevenueCatUI/CustomerCenter/Extensions/CustomerInfo+ActiveTransaction.swift
  RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
  RevenueCatUI/CustomerCenter/Views/CompatibilityLabeledContent.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
Labels: pr:RevenueCatUI, feat:Customer Center, pr:other

#5088 Use dateFormatter inside PurchaseInformation
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift
Labels: pr:other

#5089 Compute active subscriptions for CustomerCenter
  RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
  RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
  Tests/RevenueCatUITests/CustomerCenter/CustomerCenterViewModelTests.swift
Labels: pr:other

#5090 Introduce PurchaseInformationCardView
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/CustomerCenter/Views/PurchaseCardView.swift
Labels: pr:other

#4968 Allow previews of paywalls without offerings previews
  Sources/Purchasing/PackageType.swift
  Tests/UnitTests/Networking/Responses/OfferingsDecodingTests.swift
Labels: pr:other

#5082 Fix some flaky tests
  Tests/StoreKitUnitTests/StoreKit2/StoreKit2TransactionListenerTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
Labels: pr:other

#5031 Add support for cross product promotional offers
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/CustomerCenter/Abstractions/CustomerCenterPurchasesType.swift
  RevenueCatUI/CustomerCenter/Data/CustomerCenterError.swift
  RevenueCatUI/CustomerCenter/Data/DiscountsHandler.swift
  RevenueCatUI/CustomerCenter/Data/LoadPromotionalOfferUseCase.swift
  RevenueCatUI/Data/Strings.swift
  Sources/CustomerCenter/CustomerCenterConfigData.swift
  Sources/Networking/Responses/CustomerCenterConfigResponse.swift
  Tests/RevenueCatUITests/CustomerCenter/DiscountsHandlerTests.swift
  Tests/RevenueCatUITests/CustomerCenter/PurchaseInformationFixtures.swift
  Tests/RevenueCatUITests/Mocks/MockStoreProductDiscount.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Products.storekit
  Tests/UnitTests/CustomerCenter/CustomerCenterConfigDataTests.swift
  Tests/UnitTests/TestHelpers/AsyncTestHelpers.swift
Labels: pr:feat, pr:RevenueCatUI, feat:Customer Center

#5098 Fix watchOS tests
  RevenueCatUI/CustomerCenter/Data/DiscountsHandler.swift
  Tests/RevenueCatUITests/CustomerCenter/DiscountsHandlerTests.swift
Labels: pr:other

#5069 Split `PurchaseInformation.price` into `pricePaid` and `renewalPrice`
  RevenueCatUI/CustomerCenter/Data/CustomerCenterConfigData+Mock.swift
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation+Mock.swift
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift
  RevenueCatUI/CustomerCenter/Data/Transaction.swift
  RevenueCatUI/CustomerCenter/ViewModels/BaseManageSubscriptionViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptions/ManageSubscriptionsViewModel.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
  RevenueCatUI/CustomerCenter/Views/SubscriptionDetailsView.swift
  RevenueCatUI/Data/CustomerInfoFixtures.swift
  Sources/Identity/SubscriptionInfo.swift
  Sources/Networking/Responses/CustomerInfoResponse.swift
  Sources/Purchasing/NonSubscriptionTransaction.swift
  Tests/RevenueCatUITests/CustomerCenter/BaseManageSubscriptionViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/CustomerCenterViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/ManageSubscriptionsViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/PurchaseInformationTests.swift
Labels: pr:fix, feat:Customer Center

#5100 Add billingInformation for PurchaseInformation
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift
  RevenueCatUI/CustomerCenter/Data/Transaction.swift
  RevenueCatUI/CustomerCenter/Views/PurchaseCardView.swift
  Sources/CustomerCenter/CustomerCenterConfigData.swift
  Tests/RevenueCatUITests/CustomerCenter/PurchaseInformationTests.swift
Labels: pr:other

#5102 Introduce ScrollViewWithOSBackground to reuse in Customer Center Views
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/CustomerCenter/Views/ScrollViewWithOSBackground.swift
Labels: pr:RevenueCatUI

#5103 Move RevenueCatUI CustomerCenter mocks from test target to RevenueCatUI
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/CustomerCenter/Mocks/MockCustomerCenterPurchases.swift
  RevenueCatUI/CustomerCenter/Mocks/MockCustomerCenterStoreKitUtilities.swift
  RevenueCatUI/CustomerCenter/Mocks/MockLoadPromotionalOfferUseCase.swift
  RevenueCatUI/CustomerCenter/Mocks/PurchaseInformationFixtures.swift
Labels: pr:other

#5092 Allow custom url on purchase button
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/Templates/V2/Components/Button/ButtonComponentView.swift
  RevenueCatUI/Templates/V2/Components/Button/ButtonComponentViewModel.swift
  RevenueCatUI/Templates/V2/Components/Packages/PurchaseButton/PurchaseButtonComponentView.swift
  RevenueCatUI/Templates/V2/Components/Packages/PurchaseButton/PurchaseButtonComponentViewModel.swift
  RevenueCatUI/Templates/V2/Localizations/LocalizationDictionaryExtensions.swift
  RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/ButtonWithFooterPreview.swift
  RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/FamilySharingTogglePreview.swift
  RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/MultiTierPreview.swift
  RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/PurchaseButtonInPackagePreview.swift
  RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/Template1Preview.swift
  RevenueCatUI/Templates/V2/ViewHelpers/NavigatetoURL.swift
  RevenueCatUI/Templates/V2/ViewModelHelpers/ViewModelFactory.swift
  Sources/Paywalls/Components/PaywallPurchaseButtonComponent.swift
  Tests/UnitTests/Paywalls/Components/PurchaseButtonComponentTests.swift
Labels: pr:feat, pr:RevenueCatUI, feat:PaywallV2

#5096 Update Nimble dependency to v13.7.1
  Package.swift
  Package@swift-5.7.swift
  Package@swift-5.8.swift
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCat.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift
  Tests/BackendIntegrationTests/Helpers/BaseStoreKitIntegrationTests+Verification.swift
  Tests/InstallationTests/XcodeDirectInstallation/XcodeDirectInstallation.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Tests/RevenueCatUITests/BaseSnapshotTest.swift
  Tests/RevenueCatUITests/Data/PaywallDataValidationTests.swift
  Tests/RevenueCatUITests/LocalizationTests.swift
  Tests/StoreKitUnitTests/OfflineEntitlements/CustomerInfoOfflineEntitlementsStoreKitTest.swift
  Tests/StoreKitUnitTests/StoreKitConfigTestCase.swift
  Tests/StoreKitUnitTests/StoreProductTests.swift
  Tests/StoreKitUnitTests/TestHelpers/ImageSnapshot.swift
  Tests/StoreKitUnitTests/TestHelpers/StoreKitTestHelpers.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Tests/UnitTests/Diagnostics/DiagnosticsSynchronizerTests.swift
  Tests/UnitTests/Networking/HTTPClientTests.swift
  Tests/UnitTests/Paywalls/Events/PaywallEventsManagerTests.swift
  Tests/UnitTests/Paywalls/PaywallColorTests.swift
  Tests/UnitTests/Purchasing/ProductsFetcherSK1Tests.swift
  Tests/UnitTests/TestHelpers/AsyncTestHelpers.swift
  Tests/UnitTests/TestHelpers/SnapshotTesting+Extensions.swift
  Tests/UnitTests/TestHelpers/TestLogHandler.swift
Labels: pr:other

#5015 Add Virtual Currencies to Customer Center
  Package.swift
  RevenueCat.podspec
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/CustomerCenter/Data/CustomerCenterConfigTestData.swift
  RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptions/ManageSubscriptionsViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/VirtualCurrencyBalancesScreenViewModel.swift
  RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
  RevenueCatUI/CustomerCenter/Views/NoSubscriptionsView.swift
  RevenueCatUI/CustomerCenter/Views/Virtual Currencies/VirtualCurrenciesListSection.swift
  RevenueCatUI/CustomerCenter/Views/Virtual Currencies/VirtualCurrencyBalanceListRow.swift
  RevenueCatUI/CustomerCenter/Views/Virtual Currencies/VirtualCurrencyBalancesScreen.swift
  RevenueCatUI/Data/CustomerInfoFixtures.swift
  Sources/CustomerCenter/CustomerCenterConfigData.swift
  Sources/Networking/Responses/CustomerCenterConfigResponse.swift
  Tests/RevenueCatUITests/CustomerCenter/ContactSupportUtilitiesTests.swift
  Tests/RevenueCatUITests/CustomerCenter/ManageSubscriptionsViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/VirtualCurrencyBalancesScreenViewModelTests.swift
  Tests/UnitTests/CustomerCenter/CustomerCenterConfigDataTests.swift
  Tests/UnitTests/Networking/Backend/BackendGetCustomerCenterConfigTests.swift
Labels: pr:feat, pr:RevenueCatUI, feat:Customer Center, feat:Virtual Currencies

#5109 Fix vc tests
  Tests/RevenueCatUITests/CustomerCenter/BaseManageSubscriptionViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/ContactSupportUtilitiesTests.swift
  Tests/RevenueCatUITests/CustomerCenter/ManageSubscriptionsViewModelTests.swift
Labels: pr:fix

#5112 Fix ManageSubscriptionView Virtual Currency Previews in Customer Center
  RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
Labels: pr:fix, pr:other, feat:Virtual Currencies

#5101 Deprecate ManageSubscriptionView in favor of ActiveSubscriptionList
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation+Mock.swift
  RevenueCatUI/CustomerCenter/ViewModels/ActiveSubscriptionsListViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptions/ManageSubscriptionsViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/SubscriptionDetailViewModel.swift
  RevenueCatUI/CustomerCenter/Views/ActiveSubscriptionsListView.swift
  RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsButtonsView.swift
  RevenueCatUI/CustomerCenter/Views/PurchaseCardView.swift
  RevenueCatUI/CustomerCenter/Views/SubscriptionDetailView.swift
  Tests/RevenueCatUITests/CustomerCenter/BaseManageSubscriptionViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/ManageSubscriptionsViewModelTests.swift
Labels: pr:feat, pr:RevenueCatUI, feat:Customer Center

#5117 [DX-404] Adds API Tests for SDK Health Report
  Tests/APITesters/AllAPITests/CustomEntitlementComputationSwiftAPITester/PurchasesDiagnosticsAPI.swift
Labels: pr:other

#5122 Add DEBUG check to SDK Health API tests
  Tests/APITesters/AllAPITests/CustomEntitlementComputationSwiftAPITester/PurchasesDiagnosticsAPI.swift
Labels: pr:other

#5123 Introduce ActiveSubscriptionButtonsView to use it inside a scrollview
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/CustomerCenter/ViewModels/BaseManageSubscriptionViewModel.swift
  RevenueCatUI/CustomerCenter/Views/ActiveSubscriptionButtonsView.swift
  RevenueCatUI/CustomerCenter/Views/ActiveSubscriptionsListView.swift
  RevenueCatUI/CustomerCenter/Views/CompatibilityLabeledContent.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsButtonsView.swift
  RevenueCatUI/CustomerCenter/Views/SubscriptionDetailView.swift
Labels: feat:Customer Center, pr:other

#5121 Include PurchaseInformationCardView in SubscriptionDetail
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/CustomerCenter/Data/CustomerCenterConfigData+Mock.swift
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation+Mock.swift
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift
  RevenueCatUI/CustomerCenter/Views/ActiveSubscriptionButtonsView.swift
  RevenueCatUI/CustomerCenter/Views/ActiveSubscriptionsListView.swift
  RevenueCatUI/CustomerCenter/Views/PurchaseCardView.swift
  RevenueCatUI/CustomerCenter/Views/SubscriptionDetailView.swift
  RevenueCatUI/CustomerCenter/Views/SubscriptionDetailsView.swift
  RevenueCatUI/CustomerCenter/Views/WrongPlatformView.swift
  Sources/CustomerCenter/CustomerCenterConfigData.swift
  Tests/RevenueCatUITests/CustomerCenter/BaseManageSubscriptionViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/CustomerCenterViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/PurchaseInformationTests.swift
Labels: pr:feat, feat:Customer Center

#5126 Show other purchases in Purchases List
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation+Mock.swift
  RevenueCatUI/CustomerCenter/ViewModels/BaseManageSubscriptionViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/RelevantPurchasesListViewModel.swift
  RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
  RevenueCatUI/CustomerCenter/Views/RelevantPurchasesListView.swift
  RevenueCatUI/CustomerCenter/Views/ScrollViewSection.swift
  Tests/RevenueCatUITests/CustomerCenter/BaseManageSubscriptionViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/CustomerCenterViewModelTests.swift
Labels: pr:feat, feat:Customer Center

#5125 Fixed locale in RevenueCatUI test data
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/Data/TestData.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Config/SamplePaywalls.swift
Labels: pr:other

#5130 Add restore overlay to RelevantPurchasesListView
  RevenueCatUI/CustomerCenter/Views/RelevantPurchasesListView.swift
Labels: pr:fix, feat:Customer Center

#5129 Fix contact support button UI to match ButtonsView
  RevenueCatUI/CustomerCenter/Views/RelevantPurchasesListView.swift
  RevenueCatUI/CustomerCenter/Views/SubscriptionDetailView.swift
Labels: pr:fix, pr:RevenueCatUI, feat:Customer Center

#5133 Filter changePlans path for lifetime purchases in CustomerCenter
  RevenueCatUI/CustomerCenter/ViewModels/BaseManageSubscriptionViewModel.swift
  Tests/RevenueCatUITests/CustomerCenter/BaseManageSubscriptionViewModelTests.swift
Labels: pr:fix, feat:Customer Center

#5134 Dont show `see all purchases` button if there's nothing else to show
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/CustomerCenter/Extensions/CustomerInfo+SeeAllPurchases.swift
  RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/PurchaseHistory/PurchaseHistoryViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/RelevantPurchasesListViewModel.swift
  RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
  RevenueCatUI/CustomerCenter/Views/RelevantPurchasesListView.swift
Labels: pr:fix, feat:Customer Center

#5143 Add ownership type to PurchaseInformation
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift
  RevenueCatUI/CustomerCenter/Data/Transaction.swift
  Tests/RevenueCatUITests/CustomerCenter/PurchaseInformationTests.swift
Labels: pr:RevenueCatUI, pr:other

#5145 Send slack message for load shedder v3 tests report
  .circleci/config.yml
  fastlane/Fastfile
Labels: pr:other

#5154 Pass CustomerCenterViewModel as a ObservedObject to the detail screen
  RevenueCatUI/CustomerCenter/Data/CustomerCenterActionViewModifier.swift
  RevenueCatUI/CustomerCenter/Data/CustomerCenterActionWrapper.swift
  RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/RelevantPurchasesListViewModel.swift
  RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
  RevenueCatUI/CustomerCenter/Views/RelevantPurchasesListView.swift
  RevenueCatUI/CustomerCenter/Views/SubscriptionDetailView.swift
  RevenueCatUI/CustomerCenter/Views/UIKit Compatibility/CustomerCenterViewController.swift
Labels: pr:fix, feat:Customer Center

#5147 VC Customer Center Minor Design Tweaks
  RevenueCatUI/CustomerCenter/Views/Virtual Currencies/VirtualCurrenciesListSection.swift
  RevenueCatUI/CustomerCenter/Views/Virtual Currencies/VirtualCurrencyBalanceListRow.swift
Labels: pr:RevenueCatUI, pr:other, feat:Virtual Currencies

#5149 Fix Customer Center VC Navigation Warnings
  RevenueCatUI/CustomerCenter/ViewModels/BaseManageSubscriptionViewModel.swift
  RevenueCatUI/CustomerCenter/Views/NoSubscriptionsView.swift
  RevenueCatUI/CustomerCenter/Views/RelevantPurchasesListView.swift
  RevenueCatUI/CustomerCenter/Views/SubscriptionDetailView.swift
  RevenueCatUI/CustomerCenter/Views/Virtual Currencies/VirtualCurrenciesListSection.swift
  RevenueCatUI/CustomerCenter/Views/Virtual Currencies/VirtualCurrenciesScrollViewWithOSBackgroundSection.swift
  Tests/RevenueCatUITests/CustomerCenter/BaseManageSubscriptionViewModelTests.swift
Labels: pr:fix, pr:RevenueCatUI, feat:Virtual Currencies

#5155 Fix some flaky tests (Part 3)
  Tests/UnitTests/Misc/TimingUtilTests.swift
Labels: pr:other

#5159 Minor UI tweaks for CustomerCenter 2.0
  RevenueCatUI/CustomerCenter/ViewModels/BaseManageSubscriptionViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/SubscriptionDetailViewModel.swift
  RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
  RevenueCatUI/CustomerCenter/Views/PurchaseCardView.swift
  RevenueCatUI/CustomerCenter/Views/RelevantPurchasesListView.swift
  RevenueCatUI/CustomerCenter/Views/ScrollViewSection.swift
  RevenueCatUI/CustomerCenter/Views/SubscriptionDetailView.swift
  Tests/RevenueCatUITests/CustomerCenter/SubscriptionDetailViewModelTests.swift
Labels: pr:fix, feat:Customer Center

#5158 Introduce CustomerCenterButtonStyle to highlight CustomerCenter buttons
  RevenueCatUI/CustomerCenter/ButtonStyles.swift
  RevenueCatUI/CustomerCenter/Views/FeedbackSurveyView.swift
  RevenueCatUI/CustomerCenter/Views/SubscriptionDetailView.swift
Labels: pr:fix, feat:Customer Center

#5165 Add README to Maestro app
  Examples/rc-maestro/README.md
Labels: pr:other

#5156 Show feedback for as a sheet instead of a push
  RevenueCatUI/CustomerCenter/ViewModels/FeedbackSurveyViewModel.swift
  RevenueCatUI/CustomerCenter/Views/FeedbackSurveyView.swift
  RevenueCatUI/CustomerCenter/Views/PromotionalOfferView.swift
  RevenueCatUI/CustomerCenter/Views/SubscriptionDetailView.swift
Labels: pr:fix, feat:Customer Center

#5163 CircleCI: save Ruby 3.2.0 installation in cache
  .circleci/config.yml
Labels: pr:other

#5164 fix: Do not reload actions when selecting purchase
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/CustomerCenter/Actions/CustomerCenterConfigData.HelpPath+PurchaseInformation.swift
  RevenueCatUI/CustomerCenter/ViewModels/BaseManageSubscriptionViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/RelevantPurchasesListViewModel.swift
Labels: pr:fix, feat:Customer Center

#5144 Make latestPurchaseDate non-optional in PurchaseInformation
  RevenueCatUI/CustomerCenter/Data/CustomerCenterConfigData+Mock.swift
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation+Mock.swift
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift
  RevenueCatUI/CustomerCenter/Data/Transaction.swift
  RevenueCatUI/CustomerCenter/Views/RelevantPurchasesListView.swift
  RevenueCatUI/CustomerCenter/Views/RestorePurchasesAlert.swift
  Tests/RevenueCatUITests/CustomerCenter/BaseManageSubscriptionViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/PurchaseInformationTests.swift
Labels: pr:RevenueCatUI, pr:other

#5166 reload customer center after re-syncing customer info
  RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/SubscriptionDetailViewModel.swift
  RevenueCatUI/CustomerCenter/Views/SubscriptionDetailView.swift
  Tests/RevenueCatUITests/CustomerCenter/SubscriptionDetailViewModelTests.swift
Labels: pr:fix

#5168 Use correct title for section
  RevenueCatUI/CustomerCenter/Views/RelevantPurchasesListView.swift
Labels: pr:fix

#5172 Add consumable and non consumable for Customer Center test app
  Examples/rc-maestro/rc-maestro/Resources/StoreKit/StoreKitConfiguration.storekit
  Examples/rc-maestro/rc-maestro/Sources/rc-maestro/ContentView.swift
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/CustomerCenter/Actions/CustomerCenterConfigData.HelpPath+PurchaseInformation.swift
  RevenueCatUI/CustomerCenter/ViewModels/BaseManageSubscriptionViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/RelevantPurchasesListViewModel.swift
Labels: pr:other

#5175 Use scrollBounceBehaviorBasedOnSize for CustomerCenter scrollview
  RevenueCatUI/CustomerCenter/Views/ScrollViewWithOSBackground.swift
Labels: feat:Customer Center, pr:other

#5177 Add new test cases for maestro + customer center
  Examples/rc-maestro/maestro/config.yaml
  Examples/rc-maestro/maestro/customer_center/change_plans/customer_center_change_plans.yaml
  Examples/rc-maestro/maestro/customer_center/manage_subscriptions/customer_center_manage_subscriptions_empty.yaml
  Examples/rc-maestro/maestro/customer_center/manage_subscriptions/customer_center_manage_subscriptions_restore_purchases.yaml
  Examples/rc-maestro/maestro/customer_center/manage_subscriptions/customer_center_manage_subscriptions_see_all_purchases.yaml
  Examples/rc-maestro/maestro/customer_center/promo_offer/customer_center_accept_promo_offer.yaml
  Examples/rc-maestro/maestro/customer_center/promo_offer/customer_center_multiple_subs_accept_promo_offer.yaml
  Examples/rc-maestro/maestro/customer_center/promo_offer/customer_center_multiple_subs_reject_promo_offer.yaml
  Examples/rc-maestro/maestro/customer_center/promo_offer/customer_center_reject_promo_offer.yaml
  Examples/rc-maestro/maestro/utils/buy_product.yaml
  Examples/rc-maestro/maestro/utils/cancel_subscription_group.yaml
  Examples/rc-maestro/maestro/utils/promo_offer_accept.yaml
  Examples/rc-maestro/maestro/utils/promo_offer_group_reject.yaml
  Examples/rc-maestro/maestro/utils/promo_offer_reject.yaml
  RevenueCatUI/CustomerCenter/ButtonStyles.swift
Labels: pr:other

#5181 Remove unused durationTitle from PurchaseInformation
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation+Mock.swift
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift
  Tests/RevenueCatUITests/CustomerCenter/BaseManageSubscriptionViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/CustomerCenterViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/PurchaseInformationTests.swift
Labels: pr:other

#5188 remove vc compiler flag
  Package.swift
  RevenueCat.podspec
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI.podspec
  Sources/Identity/CustomerInfo.swift
  Sources/Networking/Responses/CustomerInfoResponse.swift
  Sources/Purchasing/VirtualCurrencyInfo.swift
  Tests/APITesters/AllAPITests/ObjcAPITester/RCCustomerInfoAPI.m
  Tests/APITesters/AllAPITests/ObjcAPITester/RCVirtualCurrencyInfoAPI.h
  Tests/APITesters/AllAPITests/ObjcAPITester/RCVirtualCurrencyInfoAPI.m
  Tests/APITesters/AllAPITests/SwiftAPITester/CustomerInfoAPI.swift
  Tests/APITesters/AllAPITests/SwiftAPITester/VirtualCurrencyInfoAPI.swift
  Tests/UnitTests/Networking/Responses/__Snapshots__/CustomerInfoDecodingTests/testEncoding.1.json
  Tests/UnitTests/Networking/Responses/__Snapshots__/CustomerInfoDecodingTests/testEncodingWithFailedVerificationResponse.1.json
  Tests/UnitTests/Networking/Responses/__Snapshots__/CustomerInfoDecodingTests/testEncodingWithVerifiedResponse.1.json
  Tests/UnitTests/Purchasing/CustomerInfoTests.swift
Labels: pr:other

#5186 fix pre-commit hook to lint files with spaces in the path
  scripts/pre-commit.sh
Labels: pr:other

#5185 Improve descriptions for SDK Health errors
  Sources/Support/SDKHealthError+CustomNSError.swift
  Tests/UnitTests/Misc/PurchasesDiagnosticsTests.swift
Labels: pr:other

#5201 [Paywalls] do not ignore all safe areas when applying the zstack in bottom sheet
  RevenueCatUI/Templates/V2/Components/Button/BottomSheetView.swift
Labels: pr:fix, feat:Paywall Components, feat:PaywallV2

#5206 add missing import Foundation in Tests
  Tests/UnitTests/Mocks/MockBackend.swift
  Tests/UnitTests/Mocks/MockDateProvider.swift
  Tests/UnitTests/Mocks/MockDeviceCache.swift
  Tests/UnitTests/Mocks/MockFileReader.swift
  Tests/UnitTests/Mocks/MockInMemoryCachedOfferings.swift
  Tests/UnitTests/Mocks/MockReceiptFetcher.swift
  Tests/UnitTests/Mocks/MockStoreKit2TransactionListenerDelegate.swift
  Tests/UnitTests/Mocks/MockStoreProductDiscount.swift
  Tests/UnitTests/Mocks/MockSubscriberAttributesManager.swift
  Tests/UnitTests/Mocks/MockSystemInfo.swift
Labels: pr:other
