Repository RevenueCat/purchases-ios, pull requests merged in 2025-02, with the labels that each got.

#4739 feat: Add tests for customer center events encoding
  RevenueCat.xcodeproj/project.pbxproj
  Sources/LocalReceiptParsing/DataConverters/Codable+Extensions.swift
  Tests/UnitTests/CustomerCenter/Events/CustomerCenterAnswerSubmittedEventTests.swift
  Tests/UnitTests/CustomerCenter/Events/CustomerCenterEventCreationDataDefault.swift
  Tests/UnitTests/CustomerCenter/Events/CustomerCenterEventTests.swift
Labels: enhancement, pr:other

#4754 UI preview mode/always fetch offerings
  Sources/Purchasing/OfferingsManager.swift
  Tests/UnitTests/Purchasing/OfferingsManagerTests.swift
Labels: pr:other

#4613 Always call readyForPromotedProduct on main thread/actor
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesDeferredPurchasesTests.swift
Labels: pr:fix

#4758 chore: A simple message for posterity
  Sources/Paywalls/Events/Networking/EventsRequest+Paywall.swift
Labels: enhancement, pr:other

#4756 Document Weak PurchasesDelegate Reference
  Sources/Purchasing/Purchases/Purchases.swift
Labels: pr:other

#4734 Rename RC Billing to Web Billing
  RevenueCatUI/CustomerCenter/Views/WrongPlatformView.swift
  Sources/Purchasing/EntitlementInfo.swift
Labels: pr:other

#4703 chore: Tweak default copy for dateWhenAppWasPurchased
  Sources/CustomerCenter/CustomerCenterConfigData.swift
Labels: feat:Customer Center, pr:other

#4762 Fix Gradient Preview on iOS 15
  RevenueCatUI/Views/GradientView.swift
Labels: pr:fix, pr:RevenueCatUI

#4768 feat: Enable cancellation in CustomerCenter for catalyst
  RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptionsViewModel.swift
Labels: pr:feat, pr:RevenueCatUI, feat:Customer Center

#4771 Fixed issues with finding some locales (ex: `zh-Hans` and `zh-Hant`)
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/Templates/V2/Localizations/LocaleExtensions.swift
  RevenueCatUI/Templates/V2/Localizations/LocaleFinder.swift
  RevenueCatUI/Templates/V2/PaywallsV2View.swift
  RevenueCatUI/Templates/V2/ViewModelHelpers/UIConfigProvider.swift
  Tests/RevenueCatUITests/PaywallsV2/LocaleFinderTests.swift
Labels: pr:fix, pr:RevenueCatUI, feat:PaywallV2

#4769 Fix period abbreviated when multiple days/weeks/months/years
  RevenueCatUI/Templates/V2/Variables/VariableHandlerV2.swift
  Tests/RevenueCatUITests/PaywallsV2/VariableHandlerV2Tests.swift
Labels: do not merge, pr:fix, feat:PaywallV2

#4766 [Paywalls V2] Support generic fonts
  RevenueCatUI/Templates/V2/Components/Text/TextComponentView.swift
  RevenueCatUI/Templates/V2/Components/Text/TextComponentViewModel.swift
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#4776 feat: Introduce ISODurationFormatter
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Misc/DateAndTime/ISODurationFormatter.swift
  Sources/Misc/DateAndTime/ISOPeriodFormatter.swift
  Tests/UnitTests/Misc/ISODurationFormatterTests.swift
Labels: enhancement, pr:other

#4777 Fix for survey answered event not being tracked when not setting a `customerCenterActionHandler`
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/CustomerCenter/Data/FeedbackSurveyData.swift
  RevenueCatUI/CustomerCenter/Data/PromotionalOfferData.swift
  RevenueCatUI/CustomerCenter/ViewModels/FeedbackSurveyViewModel.swift
  Sources/CustomerCenter/CustomerCenterConfigData.swift
  Tests/RevenueCatUITests/CustomerCenter/FeedbackSurveyViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/ManageSubscriptionsViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/Mocks/MockLoadPromotionalOfferUseCase.swift
Labels: pr:fix, pr:RevenueCatUI, feat:Customer Center

#4780 Hooks up purchase handler preference keys for Paywalls V2
  RevenueCatUI/PaywallView.swift
  RevenueCatUI/Templates/V2/PaywallsV2View.swift
  RevenueCatUI/Templates/V2/Previews/PreviewMock.swift
  RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/FamilySharingTogglePreview.swift
  RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/MultiTierPreview.swift
  RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/Template1Preview.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/PaywallPresenter.swift
Labels: pr:fix, pr:RevenueCatUI, feat:PaywallV2

#4778 fix: Track impression in CustomerCenter only once
  RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
  RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
  Tests/RevenueCatUITests/CustomerCenter/CustomerCenterViewModelTests.swift
Labels: pr:fix, pr:RevenueCatUI, feat:Customer Center

#4781 [Paywalls V2] Add `visible` property to all components (and overrides to ones that were missing)
  RevenueCatUI/Templates/V2/Components/Icon/IconComponentView.swift
  RevenueCatUI/Templates/V2/Components/Icon/IconComponentViewModel.swift
  RevenueCatUI/Templates/V2/Components/Image/ImageComponentView.swift
  RevenueCatUI/Templates/V2/Components/Image/ImageComponentViewModel.swift
  RevenueCatUI/Templates/V2/Components/Stack/StackComponentView.swift
  RevenueCatUI/Templates/V2/Components/Stack/StackComponentViewModel.swift
  RevenueCatUI/Templates/V2/Components/Tabs/TabsComponentView.swift
  RevenueCatUI/Templates/V2/Components/Tabs/TabsComponentViewModel.swift
  RevenueCatUI/Templates/V2/Components/Text/TextComponentView.swift
  RevenueCatUI/Templates/V2/Components/Text/TextComponentViewModel.swift
  RevenueCatUI/Templates/V2/Components/Timeline/TimelineComponentView.swift
  RevenueCatUI/Templates/V2/Components/Timeline/TimelineComponentViewModel.swift
  RevenueCatUI/Templates/V2/ViewModelHelpers/PaywallComponentTypeTransformers.swift
  Sources/Paywalls/Components/Common/ComponentOverrides.swift
  Sources/Paywalls/Components/Common/PaywallComponentBase.swift
  Sources/Paywalls/Components/PaywallIconComponent.swift
  Sources/Paywalls/Components/PaywallImageComponent.swift
  Sources/Paywalls/Components/PaywallPackageComponent.swift
  Sources/Paywalls/Components/PaywallStackComponent.swift
  Sources/Paywalls/Components/PaywallStickyFooterComponent.swift
  Sources/Paywalls/Components/PaywallTabsComponent.swift
  Sources/Paywalls/Components/PaywallTextComponent.swift
  Sources/Paywalls/Components/PaywallTimelineComponent.swift
Labels: pr:fix, pr:RevenueCatUI, feat:PaywallV2

#4767 [Paywalls V2] Added `overflow` property to stack
  RevenueCatUI/Templates/V2/Components/Root/RootView.swift
  RevenueCatUI/Templates/V2/Components/Stack/StackComponentView.swift
  RevenueCatUI/Templates/V2/Components/Stack/StackComponentViewModel.swift
  RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/Template1Preview.swift
  Sources/Paywalls/Components/PaywallStackComponent.swift
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#4786 UI Preview Mode: mock `CustomerInfo`
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Identity/CustomerInfoManager.swift
  Tests/UnitTests/Identity/CustomerInfoManagerUIPreviewModeTests.swift
Labels: pr:other

#4788 [Paywalls V2] Scroll fix for background/padding/border
  RevenueCatUI/Templates/V2/Components/Stack/StackComponentView.swift
Labels: pr:fix, pr:RevenueCatUI, feat:PaywallV2

#4722 [Paywalls V2] Carousel component
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/Templates/V2/Components/Carousel/CarouselComponentView.swift
  RevenueCatUI/Templates/V2/Components/Carousel/CarouselComponentViewModel.swift
  RevenueCatUI/Templates/V2/Components/ComponentsView.swift
  RevenueCatUI/Templates/V2/ViewModelHelpers/PaywallComponentViewModel.swift
  RevenueCatUI/Templates/V2/ViewModelHelpers/ViewModelFactory.swift
  Sources/Networking/Responses/RevenueCatUI/UIConfig.swift
  Sources/Paywalls/Components/Common/PaywallComponentBase.swift
  Sources/Paywalls/Components/PaywallCarouselComponent.swift
  Sources/Paywalls/Components/PaywallV2CacheWarming.swift
Labels: pr:feat, pr:RevenueCatUI, feat:PaywallV2

#4792 fix: Remove NavigationView/NavigationStack from AppWarningView
  RevenueCatUI/CustomerCenter/Views/AppUpdateWarningView.swift
Labels: pr:fix, pr:RevenueCatUI, feat:Customer Center

#4794 fix: Remove force unwrapping from PurchaseHistoryView
  RevenueCatUI/CustomerCenter/Views/PurchaseHistory/PurchaseHistoryView.swift
Labels: enhancement, pr:fix, pr:RevenueCatUI, feat:Customer Center

#4782 Add prepaid as a period type
  Sources/CodableExtensions/PeriodType+Extensions.swift
  Sources/Identity/SubscriptionInfo.swift
  Sources/Purchasing/EntitlementInfo.swift
  Tests/APITesters/AllAPITests/CustomEntitlementComputationSwiftAPITester/EntitlementInfoAPI.swift
  Tests/APITesters/AllAPITests/CustomEntitlementComputationSwiftAPITester/PurchasesAPI.swift
  Tests/APITesters/AllAPITests/ObjcAPITester/RCEntitlementInfoAPI.m
  Tests/APITesters/AllAPITests/ObjcAPITester/RCPurchasesAPI.m
  Tests/APITesters/AllAPITests/SwiftAPITester/EntitlementInfoAPI.swift
  Tests/APITesters/AllAPITests/SwiftAPITester/PurchasesAPI.swift
  Tests/InstallationTests/CommonFiles/RevenueCat-Swift.h
  Tests/UnitTests/Purchasing/EntitlementInfosTests.swift
Labels: pr:fix

#4795 Use RC API key for local development from local.xcconfig
  Local.xcconfig.SAMPLE
  RevenueCat.xcodeproj/project.pbxproj
  Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/project.pbxproj
  Tests/TestingApps/PaywallsTester/PaywallsTester/Config/ConfigItem.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Config/LocalConfigItems.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Info.plist
  Tests/TestingApps/PurchaseTesterSwiftUI/Core/Constants.swift
  Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester-Info.plist
  Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/project.pbxproj
  Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTesterWatchOS/Info.plist
  Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/ConfigurationView.swift
  scripts/pre-commit.sh
Labels: pr:other

#4793 Fix paywall refreshable bug
  RevenueCatUI/Modifiers/ViewExtensions.swift
  RevenueCatUI/PaywallView.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingList/APIKeyDashboardList.swift
Labels: pr:fix, pr:RevenueCatUI

#4798 Config item rename
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/Modifiers/ViewExtensions.swift
  RevenueCatUI/PaywallView.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/project.pbxproj
  Tests/TestingApps/PaywallsTester/PaywallsTester/Config/Configuration.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Config/Constants.swift
  Tests/TestingApps/PaywallsTester/ci_scripts/ci_pre_xcodebuild.sh
  scripts/pre-commit.sh
Labels: pr:other

#4801 [Paywalls V2] Fixes parsing generic fonts.
  RevenueCatUI/Templates/V2/Components/Text/TextComponentView.swift
  RevenueCatUI/Templates/V2/Components/Text/TextComponentViewModel.swift
Labels: pr:fix, pr:RevenueCatUI, feat:PaywallV2

#4804 UI preview mode: disable log in and log out
  Sources/Error Handling/BackendError.swift
  Sources/Error Handling/ErrorUtils.swift
  Sources/Identity/IdentityManager.swift
  Tests/UnitTests/Identity/IdentityManagerTests.swift
Labels: pr:other

#4803 [Paywalls] Fix onRestoreComplete callback not being called
  RevenueCatUI/Templates/V2/Components/Button/ButtonComponentView.swift
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#4808 Add no quotes hints to build settings in `Local.xcconfig.SAMPLE`
  Local.xcconfig.SAMPLE
Labels: pr:other

#4799 [Diagnostics] Fix store kit error description tracking
  Sources/Error Handling/StoreKitErrorHelper.swift
  Tests/StoreKitUnitTests/ProductsManagerTests.swift
Labels: pr:other

#4800 UI Preview mode: avoid intro eligibility request
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Purchasing/TrialOrIntroPriceEligibilityChecker.swift
  Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerUIPreviewModeTests.swift
  Tests/UnitTests/Mocks/MockSystemInfo.swift
Labels: pr:other

#4807 fix: [AppUpdateWarningView] Tweak buttons bottom alignment and padding
  RevenueCatUI/CustomerCenter/Views/AppUpdateWarningView.swift
Labels: pr:fix, pr:RevenueCatUI, feat:Customer Center

#4809 UI preview mode: disable cache updates
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesGetOfferingsTests.swift
Labels: pr:other

#4814 Fix SDK Compilation on Xcode 16.3/iOS 18.4 Beta 1
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift
Labels: pr:fix

#4810 fix: workaround to allow using proxy URL in `Local.xcconfig`
  Local.xcconfig.SAMPLE
  Tests/TestingApps/PaywallsTester/PaywallsTester/Config/Constants.swift
  Tests/TestingApps/PaywallsTester/PaywallsTester/Info.plist
Labels: pr:other

#4811 [Paywalls] Fix badge background not using the new background field instead of ba…
  RevenueCatUI/Templates/V2/ViewHelpers/BadgeModifier.swift
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#4819 Adds `buildServer.json` to `.gitignore`
  .gitignore
Labels: pr:other

#4817 [Paywalls V2] Adds a note on publishing to the missing paywall error.
  RevenueCatUI/Data/PaywallData+Validation.swift
  Tests/purchases-ios-snapshots-commit
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#4784 feat: Introduce refund window to control if a refund is offered for a purchase
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/CustomerCenter/Data/CustomerCenterConfigTestData.swift
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift
  RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptions/ManageSubscriptionsViewModel.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
  RevenueCatUI/CustomerCenter/Views/WrongPlatformView.swift
  Sources/CustomerCenter/CustomerCenterConfigData.swift
  Sources/Misc/DateAndTime/Clock.swift
  Sources/Misc/DateAndTime/ISODurationFormatter.swift
  Sources/Networking/Responses/CustomerCenterConfigResponse.swift
  Tests/RevenueCatUITests/CustomerCenter/FeedbackSurveyViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/ManageSubscriptionsViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/PurchaseInformationTests.swift
  Tests/RevenueCatUITests/CustomerCenter/SubscriptionInformationFixtures.swift
  Tests/UnitTests/CustomerCenter/CustomerCenterConfigDataTests.swift
  Tests/UnitTests/Mocks/MockSystemInfo.swift
  Tests/UnitTests/Mocks/TestClock.swift
Labels: pr:feat, pr:RevenueCatUI, feat:Customer Center

#4805 feat: Don't show refund if free subscription
  RevenueCatUI/CustomerCenter/Data/CustomerCenterConfigTestData.swift
  RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift.orig
  RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptions/ManageSubscriptionsViewModel.swift
  RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
  RevenueCatUI/CustomerCenter/Views/WrongPlatformView.swift
  Tests/RevenueCatUITests/CustomerCenter/ManageSubscriptionsViewModelTests.swift
Labels: pr:feat, pr:RevenueCatUI, feat:Customer Center

#4822 Correctly set PaywallsTester app API key by the CI
  Tests/TestingApps/PaywallsTester/ci_scripts/ci_pre_xcodebuild.sh
Labels: pr:fix

#4404 Post error test results to Slack
  .circleci/config.yml
Labels: pr:other

#4823 feat: Hide refund for purchases in trial period
  RevenueCatUI/CustomerCenter/Data/CustomerCenterConfigTestData.swift
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift
  RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptions/ManageSubscriptionsViewModel.swift
  Tests/RevenueCatUITests/CustomerCenter/ManageSubscriptionsViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/PurchaseInformationTests.swift
Labels: pr:feat, pr:RevenueCatUI, feat:Customer Center

#4821 chore: Delete .orig file and ignore in git ignore
  .gitignore
  RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift.orig
Labels: enhancement, pr:other

#4718 v4: Fix crash in iOS 11-12 when using MainActor
  Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
  Sources/Purchasing/StoreKit1/StoreKitRequestFetcher.swift
  Tests/UnitTests/Mocks/MockRequestFetcher.swift
Labels: pr:fix

#4828 [Diagnostics] Add `requestedProductIds` and `notFoundProductIds` to `appleProductsRequest`
  Sources/Diagnostics/DiagnosticsEvent.swift
  Sources/Diagnostics/DiagnosticsTracker.swift
  Sources/Diagnostics/Networking/DiagnosticsEventsRequest.swift
  Sources/Purchasing/ProductsManager.swift
  Tests/StoreKitUnitTests/ProductsManagerTests.swift
  Tests/UnitTests/Diagnostics/DiagnosticsTrackerTests.swift
  Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
Labels: pr:other

#4834 Update changelog with 4.43.3 and 4.43.4
  CHANGELOG.md
Labels: pr:other

#4830 chore: Add integration test for analytics events
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Logging/Strings/AnalyticsStrings.swift
  Sources/Logging/Strings/Strings.swift
  Sources/Paywalls/Events/PaywallEventsManager.swift
  Tests/BackendIntegrationTests/EventsManagerIntegrationTests.swift
Labels: enhancement, pr:other

#4840 Fix compilation issues in Xcode 16.3 beta
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift
Labels: pr:fix
