Repository RevenueCat/purchases-ios, pull requests merged in 2025-06, with the labels that each got.

#5213 Use effectiveVersion.debugDescription in StoreKitVersionTests
  RevenueCat.xcodeproj/project.pbxproj
  Tests/UnitTests/Misc/StoreKitVersionTests.swift
Labels: pr:other

#5221 Use env openURL instead of SFSafariVC to open mailto
  RevenueCatUI/CustomerCenter/Views/SubscriptionDetailView.swift
Labels: pr:fix, feat:Customer Center

#5226 Fix StoreKitVersionTests on iOS 15
  Tests/StoreKitUnitTests/TestHelpers/AvailabilityChecks.swift
  Tests/UnitTests/Misc/StoreKitVersionTests.swift
Labels: pr:other

#4981 Add Paddle Store enum case
  RevenueCatUI/CustomerCenter/Extensions/Store+Localization.swift
  RevenueCatUI/Data/CustomerInfoFixtures.swift
  Sources/CodableExtensions/Store+Extensions.swift
  Sources/CustomerCenter/CustomerCenterConfigData.swift
  Sources/Purchasing/EntitlementInfo.swift
  Tests/APITesters/AllAPITests/CustomEntitlementComputationSwiftAPITester/EntitlementInfoAPI.swift
  Tests/APITesters/AllAPITests/ObjcAPITester/RCEntitlementInfoAPI.m
  Tests/APITesters/AllAPITests/SwiftAPITester/EntitlementInfoAPI.swift
  Tests/RevenueCatUITests/CustomerCenter/PurchaseInformationTests.swift
  Tests/UnitTests/Purchasing/EntitlementInfosTests.swift
Labels: pr:feat

#5229 Fix broken URLs in 4 -> 5 Migration Guides
  Sources/DocCDocumentation/DocCDocumentation.docc/CEC_V5_API_Migration_guide.md
  Sources/DocCDocumentation/DocCDocumentation.docc/V5_API_Migration_guide.md
Labels: pr:other

#5162 Fixed overflowing images
  RevenueCatUI/Templates/V2/Components/Image/ImageComponentView.swift
Labels: pr:fix, pr:RevenueCatUI, feat:PaywallV2

#5224 Reset alertType state for RestorePurchasesAlertViewModel before dismissing
  RevenueCatUI/CustomerCenter/Views/RestorePurchasesAlert.swift
Labels: pr:fix, feat:Customer Center

#5233 Add error throwing tests to custom fonts
  RevenueCat.xcodeproj/project.pbxproj
  Tests/UnitTests/Paywalls/PaywallCacheWarmingTests.swift
Labels: pr:other

#5220 Trigger download of font that failed to load in a paywall
  RevenueCatUI/Purchasing/MockPurchases.swift
  RevenueCatUI/Purchasing/PaywallPurchasesType.swift
  RevenueCatUI/Purchasing/PurchaseHandler.swift
  RevenueCatUI/Templates/V2/Components/Text/TextComponentViewModel.swift
  RevenueCatUI/Templates/V2/ViewHelpers/DisplayableColor.swift
  RevenueCatUI/Templates/V2/ViewModelHelpers/UIConfigProvider.swift
  RevenueCatUI/Views/LoadingPaywallView.swift
  Sources/Logging/Strings/PaywallsStrings.swift
  Sources/Networking/Responses/RevenueCatUI/UIConfig.swift
  Sources/Paywalls/PaywallCacheWarming.swift
  Sources/Paywalls/PaywallFontManagerType.swift
  Sources/Purchasing/Purchases/Purchases.swift
Labels: pr:other

#5209 [Paywalls] Use tab id instead of tab index to select tab
  RevenueCatUI/Templates/V2/Components/Tabs/TabControlButtonComponentView.swift
  RevenueCatUI/Templates/V2/Components/Tabs/TabControlToggleComponentView.swift
  RevenueCatUI/Templates/V2/Components/Tabs/TabsComponentView.swift
  RevenueCatUI/Templates/V2/Components/Tabs/TabsComponentViewModel.swift
  RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/FamilySharingTogglePreview.swift
  RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/MultiTierPreview.swift
  Sources/Paywalls/Components/PaywallTabsComponent.swift
Labels: pr:other, feat:Paywall Components, feat:PaywallV2

#5182 Use groupID to present manageSubscriptions sheet
  RevenueCatUI/CustomerCenter/Abstractions/CustomerCenterPurchasesType.swift
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift
  RevenueCatUI/CustomerCenter/Views/SubscriptionDetailView.swift
Labels: pr:feat, feat:Customer Center

#5178 Introduce NoSubscriptions card view for empty states
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/CustomerCenter/Views/FallbackNoSubscriptionsView.swift
  RevenueCatUI/CustomerCenter/Views/NoSubscriptionsCardView.swift
  RevenueCatUI/CustomerCenter/Views/RelevantPurchasesListView.swift
  RevenueCatUI/CustomerCenter/Views/SubscriptionDetailView.swift
Labels: pr:feat, feat:Customer Center

#5200 SampleCat: A new iOS Sample app that guides users through any configuration issues
  Examples/SampleCat/SampleCat.xcodeproj/project.pbxproj
  Examples/SampleCat/SampleCat.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Examples/SampleCat/SampleCat.xcodeproj/xcshareddata/xcschemes/SampleCat.xcscheme
  Examples/SampleCat/SampleCat/Constants.swift
  Examples/SampleCat/SampleCat/HealthViewModel.swift
  Examples/SampleCat/SampleCat/SampleCatApp.swift
  Examples/SampleCat/SampleCat/Screens/ContentView.swift
  Examples/SampleCat/SampleCat/Screens/FullScreenErrorView.swift
  Examples/SampleCat/SampleCat/Screens/Offerings/OfferingCell.swift
  Examples/SampleCat/SampleCat/Screens/Offerings/OfferingPackagesView.swift
  Examples/SampleCat/SampleCat/Screens/Offerings/OfferingViewModel.swift
  Examples/SampleCat/SampleCat/Screens/Offerings/OfferingsView.swift
  Examples/SampleCat/SampleCat/Screens/Offerings/PackageViewModel.swift
  Examples/SampleCat/SampleCat/Screens/Products/ProductViewModel.swift
  Examples/SampleCat/SampleCat/Screens/Products/ProductsView.swift
  Examples/SampleCat/SampleCat/Screens/Views/PurchasableCell.swift
  Examples/SampleCat/SampleCat/Screens/Views/PurchasableViewModel.swift
  Examples/SampleCat/SampleCat/UserViewModel.swift
  Examples/SampleCat/SampleCat/Utils/Assets.xcassets/AccentColor.colorset/Contents.json
  Examples/SampleCat/SampleCat/Utils/Assets.xcassets/AppIcon.appiconset/Artboard.png
  Examples/SampleCat/SampleCat/Utils/Assets.xcassets/AppIcon.appiconset/Contents.json
  Examples/SampleCat/SampleCat/Utils/Assets.xcassets/Contents.json
  Examples/SampleCat/SampleCat/Utils/Assets.xcassets/RC-blue.colorset/Contents.json
  Examples/SampleCat/SampleCat/Utils/Assets.xcassets/RC-green.colorset/Contents.json
  Examples/SampleCat/SampleCat/Utils/Assets.xcassets/Visuals/Contents.json
  Examples/SampleCat/SampleCat/Utils/Assets.xcassets/Visuals/visual-error.imageset/Contents.json
  Examples/SampleCat/SampleCat/Utils/Assets.xcassets/Visuals/visual-error.imageset/visual-error.heic
  Examples/SampleCat/SampleCat/Utils/Assets.xcassets/Visuals/visual-error.imageset/visual-error@2x.heic
  Examples/SampleCat/SampleCat/Utils/Assets.xcassets/Visuals/visual-error.imageset/visual-error@3x.heic
  Examples/SampleCat/SampleCat/Utils/Assets.xcassets/Visuals/visual-offerings.imageset/Contents.json
  Examples/SampleCat/SampleCat/Utils/Assets.xcassets/Visuals/visual-offerings.imageset/visual-offerings.heic
  Examples/SampleCat/SampleCat/Utils/Assets.xcassets/Visuals/visual-offerings.imageset/visual-offerings@2x.heic
  Examples/SampleCat/SampleCat/Utils/Assets.xcassets/Visuals/visual-offerings.imageset/visual-offerings@3x.heic
  Examples/SampleCat/SampleCat/Utils/Assets.xcassets/Visuals/visual-products.imageset/Contents.json
  Examples/SampleCat/SampleCat/Utils/Assets.xcassets/Visuals/visual-products.imageset/visual-products.heic
  Examples/SampleCat/SampleCat/Utils/Assets.xcassets/Visuals/visual-products.imageset/visual-products@2x.heic
  Examples/SampleCat/SampleCat/Utils/Assets.xcassets/Visuals/visual-products.imageset/visual-products@3x.heic
  Examples/SampleCat/SampleCat/Utils/Assets.xcassets/noise-pattern.imageset/Contents.json
  Examples/SampleCat/SampleCat/Utils/Assets.xcassets/noise-pattern.imageset/noise-pattern.heic
  Examples/SampleCat/SampleCat/Utils/Assets.xcassets/noise-pattern.imageset/noise-pattern@2x.heic
  Examples/SampleCat/SampleCat/Utils/Assets.xcassets/noise-pattern.imageset/noise-pattern@3x.heic
  Examples/SampleCat/SampleCat/Utils/Extensions/AppHealth+Ext.swift
  Examples/SampleCat/SampleCat/Utils/Views/ConceptIntroductionView.swift
  Examples/SampleCat/SampleCat/Utils/Views/ContentBackgroundView.swift
  Examples/SampleCat/SampleCat/Utils/Views/Spinner/Shapes/BallShape.swift
  Examples/SampleCat/SampleCat/Utils/Views/Spinner/Shapes/YarnShape.swift
  Examples/SampleCat/SampleCat/Utils/Views/Spinner/Spinner.swift
  Examples/SampleCat/SampleCatStoreKitConfiguration.storekit
  fastlane/Fastfile
  scripts/pre-commit.sh
Labels: danger-bypass-size-limit, pr:other

#5239 Add font_weight_int to TextComponent & PartialTextComponent
  RevenueCatUI/Templates/V2/Components/Text/TextComponentViewModel.swift
  Sources/Paywalls/Components/PaywallTextComponent.swift
Labels: pr:other, feat:PaywallV2

#5237 New schema for `UIConfig.FontInfo`
  RevenueCatUI/Templates/V2/Components/Text/TextComponentView.swift
  RevenueCatUI/Templates/V2/Components/Text/TextComponentViewModel.swift
  RevenueCatUI/Templates/V2/ViewModelHelpers/UIConfigProvider.swift
  Sources/Logging/Strings/PaywallsStrings.swift
  Sources/Networking/Responses/RevenueCatUI/UIConfig.swift
  Sources/Paywalls/Components/PaywallTextComponent.swift
  Sources/Paywalls/PaywallCacheWarming.swift
  Sources/Paywalls/PaywallFontManagerType.swift
  Tests/UnitTests/Networking/Responses/UIConfigDecodingTests.swift
  Tests/UnitTests/Paywalls/PaywallCacheWarmingTests.swift
Labels: pr:other

#5240 Warm up caches in parallel
  Sources/Purchasing/Purchases/Purchases.swift
Labels: pr:other

#5176 Add accessibility identifier to PurchaseCardView
  RevenueCatUI/CustomerCenter/Views/PurchaseCardView.swift
  RevenueCatUI/CustomerCenter/Views/ScrollViewSection.swift
  RevenueCatUI/CustomerCenter/Views/SubscriptionDetailView.swift
Labels: pr:other

#5250 Add Danger rule to avoid submodules
  Dangerfile
Labels: pr:other

#5254 Fix Xcode 16 compilation error
  Sources/Purchasing/StoreKit2/StoreKit2PurchaseIntentListener.swift
Labels: pr:other

#5256 Use Mint 0.17.5 for `run-test-ios-14` CI job
  .circleci/config.yml
Labels: pr:other

#5203 Update CustomerInfo sample with is_sandbox to make sure it works
  Tests/UnitTests/OfflineEntitlements/CustomerInfoResponseHandlerTests.swift
Labels: pr:other

#5263 Trigger promotional offer callback from `PromotionalOfferViewModel`
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/CustomerCenter/ViewModels/BaseManageSubscriptionViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/FeedbackSurveyViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/PromotionalOfferViewModel.swift
  RevenueCatUI/CustomerCenter/Views/FeedbackSurveyView.swift
  RevenueCatUI/CustomerCenter/Views/PromotionalOfferView.swift
  Tests/RevenueCatUITests/CustomerCenter/PromotionalOfferViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/PurchaseInformationTests.swift
  Tests/RevenueCatUITests/Mocks/MockTransaction.swift
Labels: pr:fix, feat:Customer Center

#5267 Enable markdown in paywalls in iOS 15 and watchOS 8
  RevenueCatUI/Templates/V2/Components/Text/TextComponentView.swift
Labels: pr:fix

#5261 Renamed isActive to isExpired in PurchaseInformation
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation+Mock.swift
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift
  RevenueCatUI/CustomerCenter/ViewModels/PurchaseHistory/PurchaseInformation+History.swift
  RevenueCatUI/CustomerCenter/Views/PurchaseCardView.swift
  RevenueCatUI/CustomerCenter/Views/RelevantPurchasesListView.swift
  RevenueCatUI/CustomerCenter/Views/SubscriptionDetailView.swift
  Tests/RevenueCatUITests/CustomerCenter/BaseManageSubscriptionViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/SubscriptionDetailViewModelTests.swift
Labels: pr:other

#5249 Delete duplicate OfferingsList.swift from PaywallTester
  RevenueCat.xcodeproj/project.pbxproj
  Tests/TestingApps/PaywallsTester/PaywallsTester/Views/OfferingsList.swift
Labels: pr:other

#5286 Remove CustomerCenterConfigDataAPI from API Tests
  Tests/APITesters/AllAPITests/AllAPITests.xcodeproj/project.pbxproj
  Tests/APITesters/AllAPITests/SwiftAPITester/CustomerCenterConfigDataAPI.swift
Labels: pr:other

#5260 Refactor PurchaseHistory to use PurchaseInformation
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation+Mock.swift
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift
  RevenueCatUI/CustomerCenter/Extensions/PurchaseInformation+Creation.swift
  RevenueCatUI/CustomerCenter/Utilities/CustomerCenterStoreKitUtilities.swift
  RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/PurchaseHistory/PurchaseDetailItem.swift
  RevenueCatUI/CustomerCenter/ViewModels/PurchaseHistory/PurchaseDetailViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/PurchaseHistory/PurchaseHistoryViewModel.swift
  RevenueCatUI/CustomerCenter/ViewModels/PurchaseHistory/PurchaseInfo.swift
  RevenueCatUI/CustomerCenter/ViewModels/PurchaseHistory/PurchaseInformation+History.swift
  RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
  RevenueCatUI/CustomerCenter/Views/PurchaseCardView.swift
  RevenueCatUI/CustomerCenter/Views/PurchaseHistory/PurchaseDetailView.swift
  RevenueCatUI/CustomerCenter/Views/PurchaseHistory/PurchaseHistoryView.swift
  RevenueCatUI/CustomerCenter/Views/PurchaseHistory/PurchaseLinkView.swift
  RevenueCatUI/CustomerCenter/Views/RelevantPurchasesListView.swift
  RevenueCatUI/CustomerCenter/Views/RestorePurchasesAlert.swift
  RevenueCatUI/CustomerCenter/Views/SubscriptionDetailView.swift
  Sources/CustomerCenter/CustomerCenterConfigData.swift
  Tests/RevenueCatUITests/CustomerCenter/BaseManageSubscriptionViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/CustomerCenterViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/SubscriptionDetailViewModelTests.swift
Labels: pr:feat, feat:Customer Center

#5273 Add tests for PurchaseInformationView.Badge + rc promo
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift
  RevenueCatUI/CustomerCenter/Views/PurchaseCardView.swift
  RevenueCatUI/CustomerCenter/Views/PurchaseHistory/PurchaseHistoryView.swift
  Sources/CustomerCenter/CustomerCenterConfigData.swift
  Tests/RevenueCatUITests/CustomerCenter/PurchaseCardViewBadgeTests.swift
Labels: pr:fix, feat:Customer Center

#5287 Delete Examples folder from carthage checkout
  Tests/InstallationTests/CarthageInstallation/fastlane/Fastfile
  Tests/InstallationTests/CarthageInstallation/fastlane/README.md
Labels: pr:other

#5274 Use minimal permissions for installation tests
  .circleci/config.yml
Labels: pr:other

#5297 Add missing `@_spi` to import in backend tests
  Tests/BackendIntegrationTests/EventsManagerIntegrationTests.swift
Labels: pr:other

#5275 Use `card_store_promotional` for RC Promos in card & history
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift
  RevenueCatUI/CustomerCenter/Extensions/Store+Localization.swift
  RevenueCatUI/CustomerCenter/ViewModels/PurchaseHistory/PurchaseInformation+History.swift
  RevenueCatUI/CustomerCenter/Views/PurchaseCardView.swift
  Sources/CustomerCenter/CustomerCenterConfigData.swift
Labels: pr:feat, feat:Customer Center

#5298 Fix index and mgiration guides docs not being updated
  fastlane/Fastfile
Labels: pr:other

#5291 [Paywalls] Update ImageComponent max width after initial layout if it changes.
  RevenueCatUI/Templates/V2/Components/Image/ImageComponentView.swift
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#5309 Fix paywall locale receiving UN M.49 standard localization
  RevenueCatUI/Templates/V2/Localizations/LocaleFinder.swift
  Tests/RevenueCatUITests/PaywallsV2/LocaleFinderTests.swift
Labels: pr:fix, feat:PaywallV2

#5324 Add logs to VirtualCurrencyManager
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Logging/Strings/Strings.swift
  Sources/Logging/Strings/VirtualCurrencyStrings.swift
  Sources/Virtual Currencies/VirtualCurrencyManager.swift
  Tests/UnitTests/Virtual Currencies/VirtualCurrencyManagerTests.swift
Labels: pr:other

#5322 Add Intro Eligibility Functions to CEC Mode
  Examples/testCustomEntitlementsComputation/testCustomEntitlementsComputation/ContentView.swift
  Sources/Misc/Concurrency/Purchases+async.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/APITesters/AllAPITests/CustomEntitlementComputationSwiftAPITester/PurchasesAPI.swift
Labels: pr:other

#5333 New issue template form and issue monitoring job
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/issue-notifications.yml
Labels: pr:other

#5336 Bump ack action to v11
  .github/workflows/issue-notifications.yml
Labels: pr:other

#5293 Use NewErrorUtils instead of RevenueCat.ErrorUtils
  Sources/Purchasing/Purchases/Purchases.swift
Labels: pr:other

#5329 Add smoother loading animation to SubscriptionDetailView
  RevenueCatUI/CustomerCenter/Views/SubscriptionDetailView.swift
Labels: pr:feat, feat:Customer Center

#5311 Fix broken Customer Center strings
  Sources/CustomerCenter/CustomerCenterConfigData.swift
Labels: pr:fix, pr:RevenueCatUI, feat:Customer Center

#5288 Preferred locale override
  RevenueCat.xcodeproj/project.pbxproj
  Sources/Misc/Locale/PreferredLocalesProvider.swift
  Sources/Misc/SystemInfo.swift
  Sources/Networking/HTTPClient/HTTPClient.swift
  Sources/Purchasing/Configuration.swift
  Sources/Purchasing/Purchases/Purchases.swift
  Tests/StoreKitUnitTests/LocalReceiptParserStoreKitTests.swift
  Tests/StoreKitUnitTests/StorefrontTests.swift
  Tests/UnitTests/Identity/CustomerInfoManagerUIPreviewModeTests.swift
  Tests/UnitTests/Identity/IdentityManagerTests.swift
  Tests/UnitTests/Misc/SystemInfoTests.swift
  Tests/UnitTests/Mocks/MockBackend.swift
  Tests/UnitTests/Mocks/MockIdentityManager.swift
  Tests/UnitTests/Mocks/MockSystemInfo.swift
  Tests/UnitTests/Mocks/PreferredLocalesProvider+Mock.swift
  Tests/UnitTests/Networking/Backend/BackendGetCustomerCenterConfigTests.swift
  Tests/UnitTests/Networking/Backend/BaseBackendTest.swift
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerCenterConfigTests/iOS13-testGetCustomerCenterConfigPassesLocalesWithOverride.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerCenterConfigTests/iOS14-testGetCustomerCenterConfigPassesLocalesWithOverride.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerCenterConfigTests/iOS15-testGetCustomerCenterConfigPassesLocalesWithOverride.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerCenterConfigTests/iOS16-testGetCustomerCenterConfigPassesLocalesWithOverride.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerCenterConfigTests/iOS17-testGetCustomerCenterConfigPassesLocalesWithOverride.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerCenterConfigTests/iOS18-testGetCustomerCenterConfigPassesLocalesWithOverride.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerCenterConfigTests/macOS-testGetCustomerCenterConfigPassesLocalesWithOverride.1.json
  Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerCenterConfigTests/watchOS-testGetCustomerCenterConfigPassesLocalesWithOverride.1.json
  Tests/UnitTests/Networking/HTTPClientTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift
  Tests/UnitTests/Purchasing/Purchases/PurchasesSyncPurchasesTests.swift
  Tests/UnitTests/Purchasing/ReceiptFetcherTests.swift
  Tests/UnitTests/Purchasing/StoreKitAbstractions/StoreKitWorkaroundsTests.swift
  Tests/UnitTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift
Labels: pr:other
