Repository RevenueCat/purchases-ios, pull requests merged in 2025-08, with the labels that each got.

#5440 Delete .swiftpm scheme folder to avoid scheme pollution
  .gitignore
  RevenueCat.xcworkspace/xcshareddata/xcschemes/ReceiptParser.xcscheme
  RevenueCat.xcworkspace/xcshareddata/xcschemes/RevenueCat_CustomEntitlementComputation.xcscheme
Labels: pr:other

#5444 Fix previews of paywall components not using Mac Catalyst button styling applied at top-level of Paywalls V2
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/Templates/V2/Components/Button/BottomSheetView.swift
  RevenueCatUI/Templates/V2/Components/Button/ButtonComponentView.swift
  RevenueCatUI/Templates/V2/Components/Carousel/CarouselComponentView.swift
  RevenueCatUI/Templates/V2/Components/Icon/IconComponentView.swift
  RevenueCatUI/Templates/V2/Components/Image/ImageComponentView.swift
  RevenueCatUI/Templates/V2/Components/Packages/Package/PackageComponentView.swift
  RevenueCatUI/Templates/V2/Components/Packages/PurchaseButton/PurchaseButtonComponentView.swift
  RevenueCatUI/Templates/V2/Components/Stack/StackComponentView.swift
  RevenueCatUI/Templates/V2/Components/Tabs/TabControlToggleComponentView.swift
  RevenueCatUI/Templates/V2/Components/Tabs/TabsComponentView.swift
  RevenueCatUI/Templates/V2/Components/Text/TextComponentView.swift
  RevenueCatUI/Templates/V2/Components/Timeline/TimelineComponentView.swift
  RevenueCatUI/Templates/V2/PaywallsV2View.swift
  RevenueCatUI/Templates/V2/Previews/PreviewMock.swift
  RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/ButtonWithFooterPreview.swift
  RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/FallbackComponentPreview.swift
  RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/FamilySharingTogglePreview.swift
  RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/MultiTierPreview.swift
  RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/PurchaseButtonInPackagePreview.swift
  RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/Template1Preview.swift
  RevenueCatUI/Templates/V2/ViewHelpers/BadgeModifier.swift
  RevenueCatUI/Templates/V2/ViewHelpers/FixMacButtonsModifier.swift
Labels: pr:other

#5453 Crash on release when using a Test Store API key
  Sources/Purchasing/Configuration.swift
Labels: pr:other

#5466 Show account id only debug for customer center
  RevenueCatUI/CustomerCenter/Views/ScrollViewSection.swift
Labels: pr:fix, pr:RevenueCatUI, feat:Customer Center

#5467 Add private CardStyleModifier
  RevenueCatUI/CustomerCenter/Views/ScrollViewSection.swift
Labels: pr:other

#5468 fix non-renewable appstore PATHs for customer center
  RevenueCatUI/CustomerCenter/Actions/CustomerCenterConfigData.HelpPath+PurchaseInformation.swift
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation+Mock.swift
  RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift
  RevenueCatUI/CustomerCenter/Data/Transaction.swift
  Tests/RevenueCatUITests/CustomerCenter/BaseManageSubscriptionViewModelTests.swift
  Tests/RevenueCatUITests/CustomerCenter/PurchaseInformationTests.swift
  Tests/RevenueCatUITests/Mocks/MockTransaction.swift
Labels: pr:fix, feat:Customer Center

#5485 Don't show subscriptions title if there are no subscriptions
  RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
  RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
  RevenueCatUI/CustomerCenter/Views/RelevantPurchasesListView.swift
  RevenueCatUI/Data/VirtualCurrenciesFixtures.swift
  Tests/RevenueCatUITests/CustomerCenter/CustomerCenterViewModelTests.swift
Labels: pr:fix, pr:RevenueCatUI, feat:Customer Center

#5491 Added APIs for hybrid SDKs to set presentedOfferingContext
  RevenueCat.xcodeproj/project.pbxproj
  RevenueCatUI/Data/PaywallViewConfiguration.swift
  RevenueCatUI/PaywallView.swift
  RevenueCatUI/UIKit/PaywallFooterViewController.swift
  RevenueCatUI/UIKit/PaywallViewController.swift
  Sources/Purchasing/Offering.swift
  Tests/APITesters/AllAPITests/RevenueCatUISwiftAPITester/PaywallViewControllerAPI.swift
  Tests/StoreKitUnitTests/OfferingTests.swift
Labels: pr:RevenueCatUI, pr:other, feat:PaywallV2

#5493 Fix the tests and implicit returns that broke our CI on main
  Sources/Caching/FileRepository.swift
  Sources/Caching/KeyedDeferredValueStore.swift
  Sources/Caching/LargeItemCacheType.swift
  Sources/Logging/Strings/FileRepositoryStrings.swift
  Tests/UnitTests/Caching/FileRepositoryTests.swift
  Tests/UnitTests/Mocks/MockSimpleNetworkService.swift
Labels: pr:other

#5501 Add button_text to ScreenOffering
  RevenueCatUI/CustomerCenter/Views/NoSubscriptionsCardView.swift
  Sources/CustomerCenter/CustomerCenterConfigData.swift
  Sources/Networking/Responses/CustomerCenterConfigResponse.swift
Labels: pr:feat, pr:RevenueCatUI, feat:Customer Center

#5505 Fix backend integration tests
  Sources/Purchasing/Purchases/Purchases.swift
Labels: pr:other
